### ISSUE TITLE
1.18.1 support?

### ISSUE THREAD

**Issue by lilnasxlover** [jellysquid3/Sodium#1042]
This is necessary as 1.18.1 fixes a security vulnerability that all versions before and including 1.18 had.

**Comment by PweSol** [comment]
sodium-fabric-mc1.18-0.4.0-alpha5+build.9 and all bleeding-edge builds for 1.18.1 work on 1.18.1. You most likely have a 1.18 or 1.18.1 mod that doesn't work with Sodium on 1.18.1.

I run into the same issue, trying to figure out right now which mod does it.

**Comment by PweSol** [comment]
None of the 1.18.1 bleeding-edge builds work with Iris 1.1.3 for Minecraft 1.18.1, as they crash with the following:
```
Description: Unexpected error

java.lang.NullPointerException: Cannot read field "field_3911" because "this.field_4015.field_1724" is null
	at net.minecraft.class_757.method_3188(class_757.java:1004)
	at net.minecraft.class_757.method_3192(class_757.java:811)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by jellysquid3** [comment]
The Minecraft launcher includes patches for the aforementioned security issue for versions since MC 1.12, to my knowledge. The current MC 1.18 builds should work fine on MC 1.18.1 as there weren't any internal differences between them that were relevant to Sodium.

**Comment by jellysquid3** [comment]
Either way, we'll publish an updated version later today.

**Comment by mlindner** [comment]
I first tried using the 1.18.1 alpha Sodium today and had to disable it as the performance is worse than unmodded minecraft with a 60 fps locked framerate. It causes significant hitches whenever new chunks load as compared to unmodded minecraft.

**Comment by RockStone-God** [comment]
hey, 
I currently use sodium 1.16.1 and it works just fine. But when I use any sodium version of 1.17+ it opens minecraft but does not finish loading up the screen and crashes on load screen. Any idea why?

**Comment by Pectacular** [comment]
Can you add the 1.18.1 tag in Curseforge so that I can add Sodium to my Curseforge instance?

**Comment by jellysquid3** [comment]
The current alpha release of Sodium for MC 1.18 works fine in MC 1.18.1.

We are working on other things in the midterm, hence the reason for the slow update to the (honestly minor) version of Minecraft. The only discrepancy that should exist is with the fog shape, which hopefully shouldn't be too significant for players right now.

I've updated CurseForge to reflect that the older build works fine in MC 1.18.1
