### ISSUE TITLE
game crashing after x minutes

### ISSUE THREAD

**Issue by snnwer** [jellysquid3/Sodium#1053]
### Version information

mc1.18-0.4.0-alpha5+build.9

### Reproduction Steps

1. spend some time doing something [in my case flying with a hacked client lol]
2. light rendering fails and you crash

### Crash Report file

`[23:34:24] [Render thread/FATAL]: Unreported exception thrown!
java.lang.IllegalStateException: Tried to mark light data as ready for chunk [-23, -57] but it hasn't been loaded yet
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkTracker.onLightDataAdded(ChunkTracker.java:92) ~[sodium-fabric-mc1.18-0.4.0-alpha5build.9.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.onChunkLightAdded(SodiumWorldRenderer.java:304) ~[sodium-fabric-mc1.18-0.4.0-alpha5build.9.jar:?]
	at net.minecraft.class_638.handler$bhg000$postLightUpdate(class_638.java:3078) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_39849(class_638.java:530) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_38543(class_634.java:2198) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_38545(class_634.java:2183) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_38534(class_638.java:142) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1208) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1031) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:811) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1117) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602) [fabric-loader-0.12.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.11.jar:?]`

### Additional information

mods
![image](https://user-images.githubusercontent.com/75314624/145869730-a623f28e-729b-49ec-8e2b-c86b96bc13ed.png)

**Comment by snnwer** [comment]
nevermind, #1016
