### ISSUE TITLE
Crash when entering a Nether Portal in a busy-ish area

### ISSUE THREAD

**Issue by rybak** [jellysquid3/Sodium#1071]
### Version information

- Sodium mc1.18-0.4.0-alpha5
- Minecraft 1.18.0 and 1.18.1 (as far as can tell, the only differences in 1.18.1 client are a network-related bugfix and the Log4Shell vulnerability fix).
- The crash was observed on several different 1.18 server configurations:
  - maybe on a 1.18.0 Vanilla server (didn't keep track of crashes at the time, sorry).
  - definitely on a 1.18.0 server with Lithium (some version earlier _before_ mc1.18.1-0.7.6) installed
  - definitely on a 1.18.1 server with Lithium (mc1.18.1-0.7.6) and StarLight (don't have access to version info at the moment) installed

### Reproduction Steps

1. Enter Nether Portal to a busy-ish location near spawn, but not in the spawn chunks.

Happens more often when going Nether → Overworld, but similar exception with similar error message also observed once when going Overworld → Nether.

Not observed in any other Nether Portals, including a portal inside spawn chunks.

### Crash Report file

```
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 20/12/2021, 21:14
Description: Unexpected error

java.lang.IllegalStateException: Tried to mark light data as ready for chunk [19, -10] but it hasn't been loaded yet
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkTracker.onLightDataAdded(ChunkTracker.java:92)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.onChunkLightAdded(SodiumWorldRenderer.java:304)
	at net.minecraft.class_638.handler$zcp000$postLightUpdate(class_638.java:1578)
	at net.minecraft.class_638.method_39849(class_638.java:530)
	at net.minecraft.class_634.method_38546(class_634.java:711)
	at net.minecraft.class_638.method_38534(class_638.java:142)
	at net.minecraft.class_761.method_22710(class_761.java:1208)
	at net.minecraft.class_757.method_3188(class_757.java:1031)
	at net.minecraft.class_757.method_3192(class_757.java:811)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkTracker.onLightDataAdded(ChunkTracker.java:92)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.onChunkLightAdded(SodiumWorldRenderer.java:304)
	at net.minecraft.class_638.handler$zcp000$postLightUpdate(class_638.java:1578)
	at net.minecraft.class_638.method_39849(class_638.java:530)
	at net.minecraft.class_634.method_38546(class_634.java:711)
	at net.minecraft.class_638.method_38534(class_638.java:142)
	at net.minecraft.class_761.method_22710(class_761.java:1208)
	at net.minecraft.class_757.method_3188(class_757.java:1031)

-- Affected level --
Details:
	All players: 2 total; [class_746['andrybak'/2465923, l='ClientLevel', x=62.03, y=63.00, z=239.50], class_745['Botimuz'/2519411, l='ClientLevel', x=113.40, y=63.00, z=222.42]]
	Chunk stats: 4096, 2066
	Level dimension: minecraft:overworld
	Level spawn location: World: (41,63,-1), Section: (at 9,15,15 in 2,3,-1; chunk contains blocks 32,-64,-16 to 47,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 26966523 game time, 38013781 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, VanillaTweaks_bundle_v2.zip, VanillaTweaks_iron_bars_fix.zip

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (amd64) version 5.11.0-41-generic
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 302813632 bytes (288 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 1.60
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: UHD Graphics 620
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x5917
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 12936.63
	Virtual memory used (MB): 8393.82
	Swap memory total (MB): 9011.20
	Swap memory used (MB): 1781.85
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.12.12-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD ICELAND (DRM 3.40.0, 5.11.0-41-generic, LLVM 12.0.0) GL version 4.6 (Core Profile) Mesa 21.0.3, AMD
	Window size: 1920x1051
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods, file/VanillaTweaks_bundle_v2.zip, file/VanillaTweaks_iron_bars_fix.zip
	Current Language: English (United Kingdom)
	CPU: 8x Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
```

### Additional information

- Unfortunately, I have only crash reports from a private server with no world download available.
- Thank you for maintaining this mod. The FPS boost is amazing.

**Comment by rybak** [comment]
Here are all the crash reports with the same error message: [crash-reports.zip](https://github.com/CaffeineMC/sodium-fabric/files/7747792/crash-reports.zip). As far as I can tell, ~~most~~ all of them share the same stacktrace, with slight differences between 1.18.0 client and 1.18.1 client.

**Comment by silversquirl** [comment]
Duplicate of #1016
