### ISSUE TITLE
Render thread - when using world edit + resource pack

### ISSUE THREAD

**Issue by Menotok** [jellysquid3/Sodium#1090]
//Getting this error every so often when using world edit. Not only that but when using a resourcepack in the 1.17.1 version I get really inconsistent chunk loading issues (Screenshots attached below).

17:28:46.165
net.minecraft.class_310
Render thread
Unreported exception thrown!
java.util.concurrent.CompletionException: java.lang.ArrayIndexOutOfBoundsException
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:412)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2114)
	at me.jellysquid.mods.sodium.common.util.collections.WorkStealingFutureDrain.findNext(WorkStealingFutureDrain.java:47)
	at me.jellysquid.mods.sodium.common.util.collections.WorkStealingFutureDrain.hasNext(WorkStealingFutureDrain.java:28)
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.setupUploadBatches(RenderRegionManager.java:123)
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.upload(RenderRegionManager.java:59)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:336)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:200)
	at net.minecraft.class_761.method_3273(class_761.java:4845)
	at net.minecraft.class_761.method_22710(class_761.java:1142)
	at net.minecraft.class_757.method_3188(class_757.java:1026)
	at net.minecraft.class_757.method_3192(class_757.java:810)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ArrayIndexOutOfBoundsException
17:28:50.542
monitor
Process Monitor
Process crashed with exit code -1

With resourcepack
![2021-12-30_17 33 38](https://user-images.githubusercontent.com/1346347/147770642-d80bca5e-9db7-4c8f-9bfb-9048a956a48f.png)

Without resourcepack
![2021-12-30_17 38 31](https://user-images.githubusercontent.com/1346347/147771006-088bec90-6999-4fca-8813-4dd7152f884c.png)

**Comment by jellysquid3** [comment]
You have not followed the issue template, and your issue will be closed as invalid as a result. We need a list of mod versions used, the **full** client log file, and information about the resource pack being used.

Please either open a new issue with all this information, or update this issue and ask for it to be re-opened.
