### ISSUE TITLE
crash when loading a world

### ISSUE THREAD

**Issue by EGOIST1372** [jellysquid3/Sodium#1206]
### Version information

Sodium 0.4.1 build.15

### Reproduction Steps

I had visual overhaul mod alongside sodium 1.18.1 alpha6 and after I updated to 1.18.2 with new sodium 0.4.1 build15 and loaded the test world that I have it crashed

### Crash Report file

Sodium 0.4.1+build.15
crash report:

Description: Rendering Block Entity

java.lang.NoSuchFieldError: field_23212
	at eu.midnightdust.visualoverhaul.block.renderer.FurnaceBlockEntityRenderer.render(FurnaceBlockEntityRenderer.java:57)
	at eu.midnightdust.visualoverhaul.block.renderer.FurnaceBlockEntityRenderer.method_3569(FurnaceBlockEntityRenderer.java:26)
	at net.minecraft.class_824.method_23079(class_824.java:84)
	at net.minecraft.class_824.method_23081(class_824.java:73)
	at net.minecraft.class_824.method_3554(class_824.java:98)
	at net.minecraft.class_824.method_3555(class_824.java:73)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:281)
	at net.minecraft.class_761.handler$bjl000$onRenderTileEntities(class_761.java:10045)
	at net.minecraft.class_761.method_22710(class_761.java:1359)
	at net.minecraft.class_757.method_3188(class_757.java:1034)
	at net.minecraft.class_757.method_3192(class_757.java:813)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at eu.midnightdust.visualoverhaul.block.renderer.FurnaceBlockEntityRenderer.render(FurnaceBlockEntityRenderer.java:57)
	at eu.midnightdust.visualoverhaul.block.renderer.FurnaceBlockEntityRenderer.method_3569(FurnaceBlockEntityRenderer.java:26)
	at net.minecraft.class_824.method_23079(class_824.java:84)
	at net.minecraft.class_824.method_23081(class_824.java:73)
	at net.minecraft.class_824.method_3554(class_824.java:98)
	at net.minecraft.class_824.method_3555(class_824.java:73)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:281)
	at net.minecraft.class_761.handler$bjl000$onRenderTileEntities(class_761.java:10045)
	at net.minecraft.class_761.method_22710(class_761.java:1359)
	at net.minecraft.class_757.method_3188(class_757.java:1034)

-- Block Entity Details --
Details:
	Name: minecraft:furnace // net.minecraft.class_3866
	Block: Block{minecraft:furnace}[facing=south,lit=false]
	Block location: World: (76,22,-88), Section: (at 12,6,8 in 4,1,-6; chunk contains blocks 64,-64,-96 to 79,319,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Block: Block{minecraft:furnace}[facing=south,lit=false]
	Block location: World: (76,22,-88), Section: (at 12,6,8 in 4,1,-6; chunk contains blocks 64,-64,-96 to 79,319,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
Stacktrace:
	at net.minecraft.class_824.method_3554(class_824.java:98)
	at net.minecraft.class_824.method_3555(class_824.java:73)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:281)
	at net.minecraft.class_761.handler$bjl000$onRenderTileEntities(class_761.java:10045)
	at net.minecraft.class_761.method_22710(class_761.java:1359)
	at net.minecraft.class_757.method_3188(class_757.java:1034)
	at net.minecraft.class_757.method_3192(class_757.java:813)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['EGOIST23'/119, l='ClientLevel', x=88.00, y=24.00, z=-92.92]]
	Chunk stats: 4096, 849
	Level dimension: minecraft:overworld
	Level spawn location: World: (144,64,-192), Section: (at 0,0,0 in 9,4,-12; chunk contains blocks 144,-64,-192 to 159,319,-177), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 578421 game time, 70519 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Black Icons, VanillaTweaks_1.18.zip, visualoverhaul/coloredwaterbucket, Better+chickens+V1.1+-+Mrblueyeti.zip, Better+sheep+-+Mrblueyeti.zip, Better_Dogs-Shiba_Inu.zip, Butterflies+-+Mrblueyeti.zip, loadmyresources.hiddenpack

	Fabric Mods: 
		ambientenvironment: Ambient Environment 7.0+18
		architectury: Architectury 4.0.29
		armorchroma: Armor Chroma 1.2.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		biomeinfo: BiomeInfo 1.18.2-10
		camerautils: Camera Utils 1.18.2-1.0.0
		chalk: Chalk 1.2.2
		chat-up: Chat Up! 2.0
		cleanview: CleanView 1.18.2-v1-fabric
		cloth-api: Cloth API 3.2.64
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 3.2.64
		cloth-common-events-v1: Cloth Common Events v1 3.2.64
		cloth-config: Cloth Config v6 6.2.57
		cloth-datagen-api-v1: Cloth Datagen v1 3.2.64
		cloth-scissors-api-v1: Cloth Scissors API v1 3.2.64
		cloth-utils-v1: Cloth Utils v1 3.2.64
		clumps: Clumps 8.0.0+6
		controlling: Controlling For Fabric 9.0+16
		drippyloadingscreen: Drippy Loading Screen 1.5.1
		fabric: Fabric API 0.47.8+1.18.2
		fabric-api-base: Fabric API Base 0.4.3+d7c144a8d2
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.6+d7c144a8d2
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.1+2873dd57d2
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.11+3ac43d95d2
		fabric-command-api-v1: Fabric Command API (v1) 1.1.8+d7c144a8d2
		fabric-commands-v0: Fabric Commands (v0) 0.2.7+b4f4f6cdd2
		fabric-containers-v0: Fabric Containers (v0) 0.1.20+d7c144a8d2
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.0+d82b9392d2
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.10+3ac43d95d2
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.16+25407454d2
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.7+d7c144a8d2
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.18+d7c144a8d2
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.12+d7c144a8d2
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.12+d7c144a8d2
		fabric-item-api-v1: Fabric Item API (v1) 1.3.2+691a79b5d2
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.8+3ac43d95d2
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.11+54e5b2ecd2
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.9+b4f4f6cdd2
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.1+25407454d2
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.10+d7c144a8d2
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.0.2+d1027f7dd2
		fabric-models-v0: Fabric Models (v0) 0.3.5+d7c144a8d2
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.20+d882b915d2
		fabric-networking-v0: Fabric Networking (v0) 0.3.7+b4f4f6cdd2
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.0.1+d882b915d2
		fabric-particles-v1: Fabric Particles (v1) 0.2.11+526dc1acd2
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.5+55dca1a4d2
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.12+d882b915d2
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.16+d8c7b9aed2
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cdd2
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.6+d7c144a8d2
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.1+54e5b2ecd2
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cdd2
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+54e5b2ecd2
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.1+d1027f7dd2
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.16+55dca1a4d2
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.9+d882b915d2
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.13+d7c144a8d2
		fabric-textures-v0: Fabric Textures (v0) 1.0.11+3ac43d95d2
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.12+d882b915d2
		fabricloader: Fabric Loader 0.13.3
		fallingleaves: Falling Leaves 1.10.0+1.18.2
		fancymenu: FancyMenu 2.6.3
		glassdoor: Glass Doors 2.1.0+1.18
		indium: Indium 1.0.2+mc1.18.2
		iris: Iris 1.2.1-rc2-0cc372f0-dirty
		java: OpenJDK 64-Bit Server VM 17
		konkrete: Konkrete 1.3.3
		lazydfu: LazyDFU 0.1.2
		lithium: Lithium 0.7.9
		loadmyresources: Load My Resources 1.0.1
		microdurability: microDurability 0.3.2+1.18.1
		midnightlib: MidnightLib 0.3.1
		minecraft: Minecraft 1.18.2
		modmenu: Mod Menu 3.1.0
		org_anarres_jcpp: jcpp 1.4.14
		org_joml_joml: joml 1.10.2
		sodium: Sodium 0.4.1+build.15
		sound_physics_remastered: Sound Physics Remastered 1.18.2-1.0.4
		umollu_ash: ASH - Another Simple HUD 1.1.16
		visualoverhaul: VisualOverhaul 4.0.0
		voicechat: Simple Voice Chat 1.18.2-2.2.26
		wi_zoom: WI Zoom 1.3-MC1.18.2
		windchimes: Windchimes 1.2.0
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.13.3-1.18.2

**Comment by jellysquid3** [comment]
You have out-of-date mods. This is not a problem with Sodium. See if Visual Overhaul has any updates, otherwise wait patiently for an update or downgrade to the previous version of Minecraft.

**Comment by EGOIST1372** [comment]
but visual overhaul is already updated and work with 1.18.2 as it says on curseforge
![image](https://user-images.githubusercontent.com/86555131/156654185-068f2bea-b508-424e-81f4-254bd33208e4.png)

**Comment by EGOIST1372** [comment]
it seems it got [fixed](https://github.com/TeamMidnightDust/VisualOverhaul/issues/29) even tho it had 1.18.2 tag in curseforge it wasn't compatible with 1.18.2 
sorry for inconvenient
