### ISSUE TITLE
Tried to mark light data as ready for chunk but it hasn't been loaded yet

### ISSUE THREAD

**Issue by cardanawandra** [jellysquid3/Sodium#1223]
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15

### Reproduction Steps

1. use fartherviewdistance plugin on server
2. render more than original view distance
3. wait for it, or just play, it will crash suddenly

### Crash Report file

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 3/11/22, 10:07 PM
Description: Unexpected error

java.lang.IllegalStateException: Tried to mark light data as ready for chunk [-13, -164] but it hasn't been loaded yet
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkTracker.onLightDataAdded(ChunkTracker.java:92)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.onChunkLightAdded(SodiumWorldRenderer.java:305)
	at net.minecraft.class_638.handler$zkh000$postLightUpdate(class_638.java:2067)
	at net.minecraft.class_638.method_39849(class_638.java:524)
	at net.minecraft.class_634.method_38546(class_634.java:706)
	at net.minecraft.class_638.method_38534(class_638.java:141)
	at net.minecraft.class_761.method_22710(class_761.java:1190)
	at net.minecraft.class_757.method_3188(class_757.java:1034)
	at net.minecraft.class_757.method_3192(class_757.java:813)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkTracker.onLightDataAdded(ChunkTracker.java:92)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.onChunkLightAdded(SodiumWorldRenderer.java:305)
	at net.minecraft.class_638.handler$zkh000$postLightUpdate(class_638.java:2067)
	at net.minecraft.class_638.method_39849(class_638.java:524)
	at net.minecraft.class_634.method_38546(class_634.java:706)
	at net.minecraft.class_638.method_38534(class_638.java:141)
	at net.minecraft.class_761.method_22710(class_761.java:1190)
	at net.minecraft.class_757.method_3188(class_757.java:1034)

-- Affected level --
Details:
	All players: 1 total; [class_746['MinerXHunter'/1252128, l='ClientLevel', x=-16.43, y=79.00, z=-2613.52]]
	Chunk stats: 1024, 420
	Level dimension: minecraft:overworld
	Level spawn location: World: (-2596,67,-374), Section: (at 12,3,10 in -163,4,-24; chunk contains blocks -2608,-64,-384 to -2593,319,-369), Region: (-6,-1; contains chunks -192,-32 to -161,-1, blocks -3072,-64,-512 to -2561,319,-1)
	Level time: 18502 game time, 36725 day time
	Server brand: 4G4C4S (Velocity)
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 143340360 bytes (136 MiB) / 1073741824 bytes (1024 MiB) up to 1073741824 bytes (1024 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 12
	Microarchitecture: whiskey Lake
	Frequency (GHz): 1.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics 620
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x3ea0
	Graphics card #0 versionInfo: DriverVersion=27.20.100.8853
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 15502.24
	Virtual memory used (MB): 11733.25
	Swap memory total (MB): 7424.00
	Swap memory used (MB): 1559.13
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmn128M -Xmx1024M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: Fabric 1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics 620 GL version 3.2.0 - Build 27.20.100.8853, Intel
	Window size: 1366x705
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz

**Comment by Lolothepro** [comment]
#1016
