### ISSUE TITLE
Game crash after joining the world and trying to go to "video setting"

### ISSUE THREAD

**Issue by skbMoon** [jellysquid3/Sodium#1266]
### Version information

1.16.5

### Reproduction Steps

the game crashes in two cases
Case A:When clicking the "video setting" button ---it shows"saving world" and the game crashed     .Message:The game crashed whilst mouseclicked event handler
Error: java.lang.ExceptionInInitializerError
Case B:joining any minecraft world or creating a new world---when it comes to 100%and joining the world,the game shows"saving world"and crashed.   Message:The game crashed whilst unexpected error
Error: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

when i removed sodium from the 'mods' folder,the game didn't crash in these cases.

### Crash Report file
---- Minecraft Crash Report ---- ***********************************************(Case A)*********************************************
// Don't be sad, have a hug! <3

Time: 2022/4/12 下午 10:28
Description: mouseClicked event handler

java.lang.ExceptionInInitializerError
	at me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI.<init>(SodiumOptionsGUI.java:52)
	at net.minecraft.class_429.handler$zbb000$open(class_429.java:523)
	at net.minecraft.class_429.method_19828(class_429.java)
	at net.minecraft.class_429$$Lambda$3024/815133163.onPress(Unknown Source)
	at net.minecraft.class_4185.method_25306(class_4185.java:33)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:149)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:92)
	at net.minecraft.class_312$$Lambda$3014/1968773395.run(Unknown Source)
	at net.minecraft.class_437.method_25412(class_437.java:435)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_312$$Lambda$3013/352926996.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at net.minecraft.class_312$$Lambda$2365/1178584054.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:127)
	at net.minecraft.class_310.method_1523(class_310.java:1071)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:825)
	at me.jellysquid.mods.sodium.client.gui.SodiumGameOptions.load(SodiumGameOptions.java:108)
	at me.jellysquid.mods.sodium.client.SodiumClientMod.loadConfig(SodiumClientMod.java:47)
	at me.jellysquid.mods.sodium.client.SodiumClientMod.options(SodiumClientMod.java:32)
	at me.jellysquid.mods.sodium.client.gui.options.storage.SodiumOptionsStorage.<init>(SodiumOptionsStorage.java:12)
	at me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages.<clinit>(SodiumGameOptionPages.java:26)
	... 31 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
	... 38 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI.<init>(SodiumOptionsGUI.java:52)
	at net.minecraft.class_429.handler$zbb000$open(class_429.java:523)
	at net.minecraft.class_429.method_19828(class_429.java)
	at net.minecraft.class_429$$Lambda$3024/815133163.onPress(Unknown Source)
	at net.minecraft.class_4185.method_25306(class_4185.java:33)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:149)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:92)
	at net.minecraft.class_312$$Lambda$3014/1968773395.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_429
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:435)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_312$$Lambda$3013/352926996.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at net.minecraft.class_312$$Lambda$2365/1178584054.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:127)
	at net.minecraft.class_310.method_1523(class_310.java:1071)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1473058472 bytes (1404 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.13.3-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon HD 7660D GL version 4.5.13399 Compatibility Profile Context 15.200.1062.0, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla
	Current Language: 繁體中文 (台灣)
	CPU: 4x AMD A10-5800K APU with Radeon(tm) HD Graphics 

---- Minecraft Crash Report ---- ***********************************************(Case B)*********************************************
// You should try our sister game, Minceraft!

Time: 2022/4/12 下午 10:33
Description: Unexpected error

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:825)
	at me.jellysquid.mods.sodium.client.gui.SodiumGameOptions.load(SodiumGameOptions.java:108)
	at me.jellysquid.mods.sodium.client.SodiumClientMod.loadConfig(SodiumClientMod.java:47)
	at me.jellysquid.mods.sodium.client.SodiumClientMod.options(SodiumClientMod.java:32)
	at net.minecraft.class_1058.method_4597(class_1058.java:545)
	at net.minecraft.class_1059.method_4612(class_1059.java:253)
	at net.minecraft.class_1059.method_4622(class_1059.java:270)
	at net.minecraft.class_1060.method_4622(class_1060.java:150)
	at net.minecraft.class_310.method_1574(class_310.java:1508)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
	... 20 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:825)
	at me.jellysquid.mods.sodium.client.gui.SodiumGameOptions.load(SodiumGameOptions.java:108)
	at me.jellysquid.mods.sodium.client.SodiumClientMod.loadConfig(SodiumClientMod.java:47)
	at me.jellysquid.mods.sodium.client.SodiumClientMod.options(SodiumClientMod.java:32)
	at net.minecraft.class_1058.method_4597(class_1058.java:545)
	at net.minecraft.class_1059.method_4612(class_1059.java:253)
	at net.minecraft.class_1059.method_4622(class_1059.java:270)
	at net.minecraft.class_1060.method_4622(class_1060.java:150)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: Client Chunk Cache: 1024, 455
	Level dimension: minecraft:overworld
	Level spawn location: World: (98,63,-59), Chunk: (at 2,3,5 in 6,-4; contains blocks 96,0,-64 to 111,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 339 game time, 339 day time
	Server brand: ~~ERROR~~ NullPointerException: null
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1391839456 bytes (1327 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.13.3-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon HD 7660D GL version 4.5.13399 Compatibility Profile Context 15.200.1062.0, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla
	Current Language: 繁體中文 (台灣)
	CPU: 4x AMD A10-5800K APU with Radeon(tm) HD Graphics 
### Additional information

I just ran into this problem recently, it didn't happen before

**Comment by skbMoon** [comment]
surprisingly i solved it.i just launch the game on version 1.17.1 and click the "restore defaults" button.Then launch the game on version 1.16.5 and 1.17.1 alternatively.

**Comment by jellysquid3** [comment]
Your config file had become corrupted, and newer versions of the mod now detect this issue and offer to correct it for you.

In the future, you can resolve this issue by deleting the `.minecraft/config/sodium-options.json` file to have Sodium restore the defaults on next game launch.

**Comment by Hassan8937** [comment]
I get error When I entered the world error 6
