### ISSUE TITLE
Uncaught exception in theard "main"

### ISSUE THREAD

**Issue by Cimikate** [jellysquid3/Sodium#1290]
### Version information

mc1.18.2-0.4.1+build.15

### Reproduction Steps

1. open the TLauncher
2. run the game
3. wait
4. and crash

### Crash Report file

Uncaught exception in thread "main"
java.lang.RuntimeException: Error creating Mixin config fabric-rendering-data-attachment-v1.mixins.json for mod fabric-rendering-data-attachment-v1
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:95)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:153)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config fabric-rendering-data-attachment-v1.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:93)
	... 3 more
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_16 could not be set. Level is not supported by the active JRE or ASM version (Java 1.8, ASM 9.3 (ASM10_EXPERIMENTAL))
	at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1570)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 6 more

### Additional information

im using minecraft version 1.16.5

**Comment by jellysquid3** [comment]
TLauncher is not supported.
