### ISSUE TITLE
I don't know how to interprete the crash but...

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#1314]
### Version information

mc1.18.2-0.4.1+build.15

### Reproduction Steps

It happened while I was heading to a ender boat (I have the nullscapes datapack installed)

The following report was provided by NotEnoughCrashes (i dont know if it has a different way of reporting crashes so i prefer saying it)

### Crash Report file

---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 25/05/2022 19:26
Description: Rendering Block Entity

java.lang.NoSuchMethodError: 'double net.minecraft.class_2338.method_10268(double, double, double, boolean)'
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22)
	at net.minecraft.client.render.block.entity.SkullBlockEntityRenderer.handler$bif000$render(SkullBlockEntityRenderer:536)
	at net.minecraft.client.render.block.entity.SkullBlockEntityRenderer.render(SkullBlockEntityRenderer)
	at net.minecraft.client.render.block.entity.SkullBlockEntityRenderer.render(SkullBlockEntityRenderer:32)
	at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.render(BlockEntityRenderDispatcher:84)
	at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.method_23081(BlockEntityRenderDispatcher:73)
	at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.runReported(BlockEntityRenderDispatcher:98)
	at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.render(BlockEntityRenderDispatcher:73)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:281)
	at net.minecraft.client.render.WorldRenderer.handler$bjd000$onRenderTileEntities(WorldRenderer:6545)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1359)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1034)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:813)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1122)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737)
	at net.minecraft.client.main.Main.main(Main:236)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_836.handler$bif000$render(class_836.java:536)
	at net.minecraft.class_836.method_3577(class_836.java)
	at net.minecraft.class_836.method_3569(class_836.java:32)
	at net.minecraft.class_824.method_23079(class_824.java:84)
	at net.minecraft.class_824.method_23081(class_824.java:73)
	at net.minecraft.class_824.method_3554(class_824.java:98)
	at net.minecraft.class_824.method_3555(class_824.java:73)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:281)
	at net.minecraft.class_761.handler$bjd000$onRenderTileEntities(class_761.java:6545)
	at net.minecraft.class_761.method_22710(class_761.java:1359)
	at net.minecraft.class_757.method_3188(class_757.java:1034)

-- Block Entity Details --
Details:
	Name: minecraft:skull // net.minecraft.class_2631
	Block: Block{minecraft:dragon_wall_head}[facing=north]
	Block location: World: (-1523,321,-299), Section: (at 13,1,5 in -96,20,-19; chunk contains blocks -1536,0,-304 to -1521,383,-289), Region: (-3,-1; contains chunks -96,-32 to -65,-1, blocks -1536,0,-512 to -1025,383,-1)
	Block: Block{minecraft:dragon_wall_head}[facing=north]
	Block location: World: (-1523,321,-299), Section: (at 13,1,5 in -96,20,-19; chunk contains blocks -1536,0,-304 to -1521,383,-289), Region: (-3,-1; contains chunks -96,-32 to -65,-1, blocks -1536,0,-512 to -1025,383,-1)
	Block Entity NBT: {}
Stacktrace:
	at net.minecraft.class_824.method_3554(class_824.java:98)
	at net.minecraft.class_824.method_3555(class_824.java:73)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:281)
	at net.minecraft.class_761.handler$bjd000$onRenderTileEntities(class_761.java:6545)
	at net.minecraft.class_761.method_22710(class_761.java:1359)
	at net.minecraft.class_757.method_3188(class_757.java:1034)
	at net.minecraft.class_757.method_3192(class_757.java:813)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Tweeprine'/126, l='ClientLevel', x=-1512.54, y=260.00, z=-280.30]]
	Chunk stats: 16384, 361
	Level dimension: minecraft:the_end
	Level spawn location: World: (0,117,0), Section: (at 0,5,0 in 0,7,0; chunk contains blocks 0,0,0 to 15,383,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,383,511)
	Level time: 1915882 game time, 239817 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, 1.17 sama faithful 1.9.zip, CCLevels++[1.17.x].zip, VanillaTweaks_r673043.zip, dArk+GUI.zip, piglin-chan.zip, §e§l§k.zip+§6§lRe-Archery+§e§l§k.zip, xali's+Potions+v1.0.zip, sconces.zip, rail_fix1.1.zip, 04am-s-axolotls-remastered.zip, frosted-elytra-by-eveee-cx-e2700.zip, absolutegraces-celestial-tools-by-eveee-cx.zip, §aBeds-Reimagined§8-[v1].zip, armorchroma/alternative-icons, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 780741312 bytes (744 MiB) / 1644167168 bytes (1568 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9300HF CPU @ 2.40GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2,40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1050
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 3072,00
	Graphics card #0 deviceId: 0x1c91
	Graphics card #0 versionInfo: DriverVersion=27.21.14.5749
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 2,40
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 18864,24
	Virtual memory used (MB): 13918,26
	Swap memory total (MB): 10752,00
	Swap memory used (MB): 1417,09
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin 2.3.0+mc1.18.1
		architectury: Architectury 4.0.27
		armorchroma: Armor Chroma 1.2.0
		autoswitch: AutoSwitch 4.0.3
		autoswitch-api: AutoSwitch API 1.1.0
		balm-fabric: Balm 3.0.0+0
		betterf3: BetterF3 1.2.4
		boostedbrightness: Boosted Brightness 2.1.1
		borderlessmining: Borderless Mining 1.1.1+1.18
		chat_heads: Chat Heads 0.6.0
		clienttweaks: Client Tweaks 7.1.0
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		dynamicfps: Dynamic FPS 2.1.0
		ecs: Elytra/Chestplate Swapper 1.2.0-MC1.18
		fabric: Fabric API 0.51.1+1.18.2
		fabric-api-base: Fabric API Base 0.4.4+d7c144a860
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.0+2373a54560
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.4+7b0f312660
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
		fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
		fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.3+d82b939260
		fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.11+3ac43d9560
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.17+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.14+d7c144a860
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.4.0+4457765560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.11+91896a4960
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.3+2d83e92c60
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.0+81ea5b3c60
		fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.0+fe4ddef060
		fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.0+7faf0d8860
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.18+2de5574560
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.0+1f6558e860
		fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.0+2373a54560
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+bd8a4a1860
		fabricloader: Fabric Loader 0.13.3
		farsight: Farsight Mod 1.18-1.7
		fpsreducer: FPS Reducer 1.18.2-2.0
		inventoryhud: Inventory HUD + 3.4.2
		inventoryprofilesnext: Inventory Profiles Next 1.3.1
		invmove: InvMove 1.18-0.1.1
		java: OpenJDK 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lazydfu: LazyDFU 0.1.2
		lightoverlay: Light Overlay 6.0.5
		lithium: Lithium 0.7.9
		minecraft: Minecraft 1.18.2
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 3.0.1
		mousetweaks: Mouse Tweaks 2.22
		notenoughcrashes: Not Enough Crashes 4.1.6+1.18.2
		org_aeonbits_owner_owner: owner 1.0.12
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_joml_joml: joml 1.10.2
		phosphor: Phosphor 0.8.1
		pride: Pride Lib 1.1.0+1.17
		shulkerboxtooltip: Shulker Box Tooltip 3.0.5+1.18
		skinlayers: 3d Skin Layers 1.4.0
		sodium: Sodium 0.4.1+build.15
		sound_physics_remastered: Sound Physics Remastered 1.18.2-1.0.5
		spruceui: SpruceUI 3.3.0+1.17
		torohealth: ToroHealth Damage Indicators 1.18-fabric-2
		waterdripsound: Drip Sounds 1.18-0.3.0
		wi_zoom: WI Zoom 1.3-MC1.18.1
	Launched Version: fabric-loader-0.13.3-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1050/PCIe/SSE2 GL version 3.2.0 NVIDIA 457.49, NVIDIA Corporation
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, file/1.17 sama faithful 1.9.zip (incompatible), file/CCLevels++[1.17.x].zip (incompatible), file/VanillaTweaks_r673043.zip, file/dArk+GUI.zip (incompatible), file/piglin-chan.zip (incompatible), file/§e§l§k.zip+§6§lRe-Archery+§e§l§k.zip (incompatible), file/xali's+Potions+v1.0.zip (incompatible), file/sconces.zip (incompatible), file/rail_fix1.1.zip (incompatible), file/04am-s-axolotls-remastered.zip (incompatible), file/frosted-elytra-by-eveee-cx-e2700.zip (incompatible), file/absolutegraces-celestial-tools-by-eveee-cx.zip (incompatible), file/§aBeds-Reimagined§8-[v1].zip (incompatible), armorchroma/alternative-icons, Fabric Mods
	Current Language: English (United Kingdom)
	CPU: 8x Intel(R) Core(TM) i5-9300HF CPU @ 2.40GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Tweeprine'/126, l='ServerLevel[1.18surv(nether+end ampli)]', x=-1512.54, y=260.00, z=-280.30]]
	Data Packs: vanilla, Fabric Mods, file/amplified-nether-1-18.zip, file/nullscape-v1-1-1.zip
	World Generation: Experimental
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Sodium (sodium)

### Additional information

It also suspected Iris Shaders to be part of the problem. I had tried to launch the game with both these mods but disabling the shaders and it worked for an extra few seconds (before crashing again due to Sodium. It did not work after I removed Iris.)

**Comment by Lolothepro** [comment]
#1288
