### ISSUE TITLE
RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium'!

### ISSUE THREAD

**Issue by SakeWasTaken** [jellysquid3/Sodium#1332]
### Version information

Sodium mc1.18.2-0.4.1

### Reproduction Steps

1. Install the latest version of Fabric for Minecraft 1.18.2 correctly.
2. Put the sodium file in the _mods_ folder inside _.minecraft_ folder.
3. Start Minecraft using the fabric 1.18 instance.
4. Enjoy.

### Crash Report file

A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium'!
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:164)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	... 2 more
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'preLaunch' provided by 'sodium'
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of me.jellysquid.mods.sodium.client.SodiumPreLaunch failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:418)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:322)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	... 5 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [fabric-resource-loader-v0.mixins.json:ResourceMixin from mod fabric-resource-loader-v0] from phase [DEFAULT] in config [fabric-resource-loader-v0.mixins.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:585)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:413)
	... 14 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Mixin target type mismatch: net.minecraft.class_3298 is an interface in org.spongepowered.asm.mixin.transformer.MixinInfo$SubType$Standard@de88ac6
	at org.spongepowered.asm.mixin.transformer.MixinInfo$SubType.validateTarget(MixinInfo.java:553)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTargetClass(MixinInfo.java:1027)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:1008)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.parseTargets(MixinInfo.java:896)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:869)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540)
	... 20 more

### Additional information

I have the same (or alike]) issue with Minecraft 1.17.2.  I already have checked the versions of Minecraft, Fabric, Sodium and Java, all are up to date. I also tried putting the latest version of _Fabric Api_ inside the mods folder but it won't work either.

**Comment by cupiditys** [comment]
i have the same problem, optifine works fine but sodium insta-crashes

**Comment by burgerindividual** [comment]
Could you try updating Fabric API?

**Comment by Brendan-epicness** [comment]
i think if you launch the game successfully once it will work after that, i got that same error but with a bunch of different mods (essential client, cull less leaves, including sodium) but i disabled every one of them that gave me that preLaunch error, and once the game successfully opened, I closed it and was able to launch it with those same mods that were causing issues successfully.
I was adding mods onto a multiMC instance, so the instance had never been opened beforehand.

**Comment by MinecraftModFixer** [comment]
> i think if you launch the game successfully once it will work after that, i got that same error but with a bunch of different mods (essential client, cull less leaves, including sodium) but i disabled every one of them that gave me that preLaunch error, and once the game successfully opened, I closed it and was able to launch it with those same mods that were causing issues successfully. I was adding mods onto a multiMC instance, so the instance had never been opened beforehand.

Idk tried nothig works...

**Comment by insanikx** [comment]
ві еблані? нормально обясніте

**Comment by Mxlanch0lia** [comment]
I found solution. Take attention to your minecraft folder's name. For example I have used MultiMC and named my instance with 
cyrillic symbols. When I rename this folders with just numbers it successful fixed this problem. So, you need to use only Romanic symbols to name your minecraft folders. **My english is not perfect if you didn't understand something just ask**

**Comment by Felix14-v2** [comment]
> For example I have used MultiMC and named my instance with
> cyrillic symbols. When I rename this folders with just numbers it successful fixed this problem

Weird, I use Modrinth App and I have some instances with Cyrillic folder names. Sodium works just fine, and I've never experienced any crashes.

**Comment by Mxlanch0lia** [comment]
May be I just have a luck. When I get this crash issue I have noticed 1 thing, crash report had some file path and there was a directory named "??????" I've checked this file and it was named in Russian then I renamed it with English and Minecraft started without any issues
