### ISSUE TITLE
v0.4.1+replaymod.rev.23e83a1 

### ISSUE THREAD

**Issue by showierdata9978** [jellysquid3/Sodium#1337]
### Version information

v0.4.1+replaymod.rev.23e83a1 IllegalStateException

### Reproduction Steps

I do not know honestly,

but mainly when I die 

### Crash Report file

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 6/16/22, 10:30 PM
Description: Unexpected error

java.lang.IllegalStateException: Tried to mark light data as ready for chunk [405, 290] but it hasn't been loaded yet
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkTracker.onLightDataAdded(ChunkTracker.java:92)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.onChunkLightAdded(SodiumWorldRenderer.java:305)
	at net.minecraft.class_638.handler$bgk000$postLightUpdate(class_638.java:2567)
	at net.minecraft.class_638.method_39849(class_638.java:524)
	at net.minecraft.class_634.method_38543(class_634.java:2205)
	at net.minecraft.class_634.method_38547(class_634.java:667)
	at net.minecraft.class_638.method_38534(class_638.java:141)
	at net.minecraft.class_761.method_22710(class_761.java:1190)
	at net.minecraft.class_757.method_3188(class_757.java:1034)
	at net.minecraft.class_757.method_3192(class_757.java:813)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkTracker.onLightDataAdded(ChunkTracker.java:92)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.onChunkLightAdded(SodiumWorldRenderer.java:305)
	at net.minecraft.class_638.handler$bgk000$postLightUpdate(class_638.java:2567)
	at net.minecraft.class_638.method_39849(class_638.java:524)
	at net.minecraft.class_634.method_38543(class_634.java:2205)
	at net.minecraft.class_634.method_38547(class_634.java:667)
	at net.minecraft.class_638.method_38534(class_638.java:141)
	at net.minecraft.class_761.method_22710(class_761.java:1190)
	at net.minecraft.class_757.method_3188(class_757.java:1034)

-- Affected level --
Details:
	All players: 51 total; [class_746['ShowierData9978'/86275, l='ClientLevel', x=6304.30, y=13.00, z=4653.55], class_745['CIT-00e752204e5b'/66, l='ClientLevel', x=6320.50, y=12.00, z=4663.50], class_745['Elusive_Jam'/84595, l='ClientLevel', x=6336.38, y=12.50, z=4631.26], class_745['§6§lJob Office'/36, l='ClientLevel', x=6292.50, y=12.00, z=4655.50], class_745['VN_iMinh'/83313, l='ClientLevel', x=6347.81, y=12.00, z=4647.00], class_745['SnorlaxIzDaBEST'/91748, l='ClientLevel', x=6338.36, y=12.00, z=4651.13], class_745['ItzMapleGuy0317'/85714, l='ClientLevel', x=6313.71, y=12.00, z=4653.53], class_745['glass shard'/72, l='ClientLevel', x=6320.50, y=12.00, z=4636.50], class_745['DINOBOY50'/83210, l='ClientLevel', x=6326.50, y=12.00, z=4671.50], class_745['HollandHallWhy'/91050, l='ClientLevel', x=6328.08, y=12.00, z=4626.47], class_745['file + nails'/75, l='ClientLevel', x=6344.50, y=12.00, z=4660.50], class_745['§9§lSniper'/92302, l='ClientLevel', x=6305.50, y=19.50, z=4680.50], class_745['kwten'/87803, l='ClientLevel', x=6340.03, y=12.00, z=4671.41], class_745['Cheems_soldier'/91573, l='ClientLevel', x=6292.79, y=12.06, z=4653.29], class_745['cloak'/63, l='ClientLevel', x=6319.50, y=16.00, z=4618.50], class_745['EndViolence'/91184, l='ClientLevel', x=6326.50, y=22.00, z=4665.50], class_745['Ianhola3'/92091, l='ClientLevel', x=6337.12, y=12.00, z=4652.97], class_745['janitor'/6, l='ClientLevel', x=6321.50, y=12.00, z=4632.50], class_745['Anseyyyyy'/89662, l='ClientLevel', x=6326.50, y=12.00, z=4665.50], class_745['HamyTHamster'/91022, l='ClientLevel', x=6340.89, y=12.50, z=4625.96], class_745['§6§lKitchen Lady'/18, l='ClientLevel', x=6315.50, y=12.00, z=4637.50], class_745['zero10616'/92491, l='ClientLevel', x=6292.49, y=12.06, z=4653.23], class_745['metal + razor'/51, l='ClientLevel', x=6304.50, y=17.00, z=4663.50], class_745['NerfComic'/92232, l='ClientLevel', x=6329.86, y=25.00, z=4663.92], class_745['Shikukute'/86357, l='ClientLevel', x=6304.55, y=12.25, z=4658.46], class_745['firebridge210'/91306, l='ClientLevel', x=6310.33, y=12.00, z=4661.70], class_745['Tylerbank21'/92230, l='ClientLevel', x=6301.49, y=12.13, z=4662.58], class_745['3R4043XE'/88536, l='ClientLevel', x=6323.62, y=12.56, z=4648.26], class_745['corruptguard'/78, l='ClientLevel', x=6316.50, y=19.00, z=4693.50], class_745['SacredCodes'/90904, l='ClientLevel', x=6326.34, y=22.00, z=4677.66], class_745['Pufferdent'/92124, l='ClientLevel', x=6332.04, y=12.06, z=4671.50], class_745['Percohcet'/91408, l='ClientLevel', x=6335.63, y=12.00, z=4653.20], class_745['§9§lArmoury'/15, l='ClientLevel', x=6321.13, y=12.50, z=4697.99], class_745['OneEquation459'/84979, l='ClientLevel', x=6301.49, y=12.00, z=4658.43], class_745['HzDemolisher'/90517, l='ClientLevel', x=6336.39, y=12.00, z=4677.49], class_745['CheesePerson450'/92355, l='ClientLevel', x=6326.50, y=12.00, z=4665.50], class_745['Eevee76'/91100, l='ClientLevel', x=6291.14, y=12.00, z=4649.83], class_745['oFelix_'/88098, l='ClientLevel', x=6334.66, y=24.18, z=4671.32], class_745['spoon'/9, l='ClientLevel', x=6309.50, y=12.50, z=4622.50], class_745['H4rveyClapedU'/89681, l='ClientLevel', x=6336.78, y=12.00, z=4654.67], class_745['gigbot92'/90457, l='ClientLevel', x=6333.79, y=23.11, z=4678.50], class_745['Mooshroo'/79110, l='ClientLevel', x=6328.30, y=12.00, z=4670.73], class_745['tape'/57, l='ClientLevel', x=6320.50, y=12.00, z=4660.50], class_745['CIT-aae25de54c33'/60, l='ClientLevel', x=6344.50, y=12.00, z=4636.50], class_745['shank'/12, l='ClientLevel', x=6328.50, y=13.00, z=4632.50], class_745['Arayzia'/87806, l='ClientLevel', x=6333.03, y=12.46, z=4656.22], class_745['akascyth_'/89745, l='ClientLevel', x=6348.67, y=12.00, z=4639.24], class_745['jjbros811'/92453, l='ClientLevel', x=6323.36, y=12.60, z=4646.60], class_745['wo_h'/89514, l='ClientLevel', x=6312.70, y=12.00, z=4661.15], class_745['brosk'/93, l='ClientLevel', x=6332.50, y=10.00, z=4671.52], class_745['smuggler'/81, l='ClientLevel', x=6312.50, y=12.00, z=4685.50]]
	Chunk stats: 1024, 356
	Level dimension: minecraft:overworld
	Level spawn location: World: (6326,12,4665), Section: (at 6,12,9 in 395,0,291; chunk contains blocks 6320,-64,4656 to 6335,319,4671), Region: (12,9; contains chunks 384,288 to 415,319, blocks 6144,-64,4608 to 6655,319,5119)
	Level time: 23885 game time, 78720884 day time
	Server brand: Paper (Velocity)
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 565732680 bytes (539 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 12
	Microarchitecture: unknown
	Frequency (GHz): 1.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics 620
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x3ea0
	Graphics card #0 versionInfo: DriverVersion=26.20.100.7985
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 18523.25
	Virtual memory used (MB): 15029.68
	Swap memory total (MB): 10517.51
	Swap memory used (MB): 2452.75
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		betterf3: BetterF3 1.2.5
			cloth-config: Cloth Config v6 6.2.62
				cloth-basic-math: cloth-basic-math 0.6.1
		codeutilities: Codeutilities 62
			javax_websocket_javax_websocket-api: javax.websocket-api 1.1
			org_java-websocket_java-websocket: Java-WebSocket 1.5.2
		fabric: Fabric API 0.56.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.4+7b0f312660
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.22+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.0+6f01bfd860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.0+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.19+ffb2c71e60
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.18+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.1+6c4e5d0960
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.13+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.0.0+e747827960
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.0+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.3+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.22+e6b169eb60
			fabric-networking-v0: Fabric Networking (v0) 0.3.9+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.2+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.9+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.0+7faf0d8860
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.1+e747827960
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.1+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabricloader: Fabric Loader 0.14.7
		iris: Iris 1.2.5
			org_anarres_jcpp: jcpp 1.4.14
		java: OpenJDK 64-Bit Server VM 17
		lithium: Lithium 0.7.10
		minecraft: Minecraft 1.18.2
		modmenu: Mod Menu 3.2.2
		phosphor: Phosphor 0.8.1
		raised: Raised 1.1.1
		sodium: Sodium 0.4.1+replaymod.rev.23e83a1
			org_joml_joml: joml 1.10.2
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.14.7-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics 620 GL version 3.2.0 - Build 26.20.100.7985, Intel
	Window size: 1366x705
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz

**Comment by showierdata9978** [comment]
duped
 it

**Comment by showierdata9978** [comment]
#1016
