### ISSUE TITLE
java.lang.IllegalStateException: Tried to mark light data as ready for chunk [-11, 4] but it hasn't been loaded yet

### ISSUE THREAD

**Issue by wifi-left** [jellysquid3/Sodium#1383]
### Version information

sodium-fabric-mc1.19-0.4.2+build.16

### Expected Behavior

continue working.

### Actual Behavior

error and crash:
```
[20:37:37] [Render thread/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[20:37:37] [Render thread/ERROR]: Unreported exception thrown!
java.lang.IllegalStateException: Tried to mark light data as ready for chunk [-11, 4] but it hasn't been loaded yet
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkTracker.onLightDataAdded(ChunkTracker.java:92) ~[sodium-fabric-mc1.19-0.4.2+build.16.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.onChunkLightAdded(SodiumWorldRenderer.java:305) ~[sodium-fabric-mc1.19-0.4.2+build.16.jar:?]
	at net.minecraft.class_638.handler$bph000$postLightUpdate(class_638.java:2609) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_39849(class_638.java:574) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_38546(class_634.java:735) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_38534(class_638.java:191) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1194) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1039) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:816) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1143) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:734) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
[20:37:37] [Render thread/INFO]: Stopping worker threads
```

### Reproduction Steps

1. start the game
2. join a multiplayer game
3. play for some time
4. /gamemode spectator
5. Use the spectator tool to teleport to a far away player
6. Crash with error `java.lang.IllegalStateException: Tried to mark light data as ready for chunk [x, y] but it hasn't been loaded yet`

### Java version

Java 17

### CPU

Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz   3.20 GHz

### GPU

GeForce GTX 960

### Additional information

Mods:
```
2022/06/09  16:45         1,126,255 cloth-config-7.0.72-fabric.jar
2022/07/01  21:20         1,491,691 fabric-api-0.57.0+1.19.jar
2022/06/19  13:05         1,473,555 fabric-carpet-1.19-1.4.79+v220607.jar
2022/07/02  18:08            45,967 Gamma-Utils-1.6.9-mc1.19.jar
2022/06/09  11:21         1,561,033 iris-mc1.19-1.2.5.jar
2022/06/18  09:02           475,670 lithium-fabric-mc1.19-0.8.0.jar
2022/06/09  11:21           120,013 logical_zoom-0.0.15.jar
2022/06/09  11:21           303,533 modmenu-4.0.0.jar
2022/06/09  16:45            88,018 phosphor-fabric-mc1.19.x-0.8.1.jar
2022/06/09  11:21            40,585 reeses_sodium_options-1.4.3+mc1.19-build.43.jar
2022/06/09  16:45           205,805 sodium-extra-0.4.5+mc1.19-build.43.jar
2022/06/09  08:39         1,364,166 sodium-fabric-mc1.19-0.4.2+build.16.jar
2022/06/09  11:22           951,347 ViaBackwards-4.3.0.jar
2022/07/08  12:15         5,773,107 viafabric-0.4.7+9-main.jar
2022/06/09  10:32           458,005 ViaRewind-2.0.3-SNAPSHOT.jar
2022/06/19  20:38           804,237 voxelmap-1.19-1.11.7.jar
2022/07/02  18:10         4,408,264 worldedit-fabric-mc1.19-7.2.11-SNAPSHOT-dist.jar
2022/05/22  01:01           494,081 WorldEditCUI-1.19-pre1+02-SNAPSHOT.jar
```
TIP: I have ViaVersion disabled.

**Comment by wifi-left** [comment]
Similar to #1016

**Comment by Checkmate128** [comment]
I have this problem on multiplayer servers. Whenever I die and teleport back to spawn, the same type of error occurs. This is on Sodium mc1.18.2 v0.4.1 build 15.
