### ISSUE TITLE
Falling Gravel Causes the Game to Crash. 

### ISSUE THREAD

**Issue by UnintendedSheep** [jellysquid3/Sodium#1459]
### Version information

sodium-fabric-mc1.19-0.4.2

### Reproduction Steps

1. Load a world
2. Find naturally generated Gravel (Possibly happens with other Gravity based blocks) 
3. break a block under it, the game will likely crash. 

### Crash Report file

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 9/22/22, 5:51 PM
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:19)
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.<init>(CTMBakedModel.java:70)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18)
	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16)
	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10)
	at net.minecraft.class_901.handler$zoe000$beforeRenderModel(class_901.java:518)
	at net.minecraft.class_901.method_3965(class_901.java:45)
	at net.minecraft.class_901.method_3936(class_901.java:17)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1567)
	at net.minecraft.class_761.method_22710(class_761.java:1315)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:19)
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.<init>(CTMBakedModel.java:70)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18)
	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16)
	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10)
	at net.minecraft.class_901.handler$zoe000$beforeRenderModel(class_901.java:518)
	at net.minecraft.class_901.method_3965(class_901.java:45)
	at net.minecraft.class_901.method_3936(class_901.java:17)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1567)
	at net.minecraft.class_761.method_22710(class_761.java:1315)
	at net.minecraft.class_757.method_3188(class_757.java:1039)

-- Entity being rendered --
Details:
	Entity Type: minecraft:falling_block (net.minecraft.class_1540)
	Entity ID: 729
	Entity Name: Falling Block
	Entity's Exact location: 35.50, 65.96, 282.50
	Entity's Block location: World: (35,65,282), Section: (at 3,1,10 in 2,4,17; chunk contains blocks 32,-64,272 to 47,319,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, -0.04, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
	Immitating BlockState: Block{minecraft:gravel}
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1567)
	at net.minecraft.class_761.method_22710(class_761.java:1315)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_901@46a3f2f0
	Location: 1.14,-1.18,3.26 - World: (1,-2,3), Section: (at 1,14,3 in 0,-1,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Rotation: 0.0
	Delta: 0.4999982
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1567)
	at net.minecraft.class_761.method_22710(class_761.java:1315)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['UnintendedSheep'/191, l='ClientLevel', x=34.35, y=65.54, z=279.26]]
	Chunk stats: 4096, 921
	Level dimension: minecraft:overworld
	Level spawn location: World: (-16,71,304), Section: (at 0,7,0 in -1,4,19; chunk contains blocks -16,-64,304 to -1,319,319), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 3978 game time, 3978 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_1514(class_310.java:753)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, charmonium/journeyman, Modified Sweet Berry Bush Model, illuminations/pixelaccurate, continuity/default, continuity/glass_pane_culling_fix

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 995407304 bytes (949 MiB) / 3254779904 bytes (3104 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
	Identifier: Intel64 Family 6 Model 141 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3050 Ti Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x25a0
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1659
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9a60
	Graphics card #1 versionInfo: DriverVersion=30.0.101.1631
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 18493.21
	Virtual memory used (MB): 15663.21
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 144.56
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		ambientenvironment: Ambient Environment 8.0+1
		amethystequipment: Amethyst Equipment 1.0.5
		architectury: Architectury 5.12.45
		artifacts: Artifacts 7.1.1+fabric
			com_github_llamalad7_mixinextras: MixinExtras 0.0.11
			expandability: ExpandAbility 6.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		awesomedungeon: Awesome dungeon 3.0.0
		awesomedungeonend: Awesome dungeon the end 3.0.0
		awesomedungeonnether: Awesome dungeon nether 3.0.0
		awesomedungeonocean: Awesome dungeon edition ocean 3.0.0
		balm-fabric: Balm 4.5.2+0
		basicshields: Basic Shields [Fabric] 1.4.0-pre2-1.19.2
			crowdin-translate: CrowdinTranslate 1.4+1.19
		bookshelf: Bookshelf 14.2.10
		charm: Charm 4.2.2
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		charmonium: Charmonium 4.1.0
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+7
		comforts: Comforts 6.0.1+1.19.2
			cardinal-components-base: Cardinal Components API (base) 5.0.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.1
			spectrelib: SpectreLib 0.10.0+1.19
				com_electronwill_night-config_core: core 3.6.5
				com_electronwill_night-config_toml: toml 3.6.5
		continuity: Continuity 2.0.1+1.19
		croptopia: Croptopia 2.0.7
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		dehydration: Dehydration 1.2.9
		dungeons_arise: When Dungeons Arise 2.1.51
		ecologics: Ecologics 2.1.8.1
		effective: Effective 1.3
		enchdesc: EnchantmentDescriptions 11.1.9
		environmentz: EnvironmentZ 1.2.3
		exlinecopperequipment: Copper Equipment 2.1.1
		expandeddelight: Expanded Delight 0.2.2
		fabric: Fabric API 0.58.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.28+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.1+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.2+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.26+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.5+35a03c43a9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.26+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.1+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.11+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.1.0+442de8b8a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.15+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.8+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.18+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.10+5187d39fa9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.6+5f1a85e0a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.7+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabricloader: Fabric Loader 0.14.9
		fabricshieldlib: Fabric Shield Lib 1.6.0-1.19
			mm: Manningham Mills 2.3
		fallingleaves: Falling Leaves 1.12.2+1.19.2
		farmersdelight: Farmer's Delight 1.19-1.3.3
		geckolib3: Geckolib 3.1.6
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		illuminations: Illuminations 1.10.8
		inmis: Inmis 2.7.0-1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		iris: Iris 1.2.6
			org_anarres_jcpp: jcpp 1.4.14
		ironchests: Iron Chests: Restocked 3.0.2
		jade: Jade 7.7.1
		jamlib: JamLib 0.4.4
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 11.1.1.239
		jeresources: Just Enough Resources 1.0.0.176
		libraryferret: Library ferret 3.0.0
		lod: Distant Horizons 1.6.7a
		mcda: MC Dungeons Armors 2.2.0
		mcdar: MC Dungeons Artifacts 1.5.2-1.19
		mcdw: MC Dungeons Weapons 5.0.4-1.19
			enchant_giver: Enchant Giver 1.3.0
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		mcsa: MC Story Mode Armors 3.1.2+1.19
		midnightlib: MidnightLib 0.6.1
		minecraft: Minecraft 1.19
		modmenu: Mod Menu 4.0.4
		moreberries: More Berries 1.5.1
		morevillagers: More Villagers 4.0.2
		naturescompass: Nature's Compass 1.19-2.0.4-fabric
		northerncompass: NorthernCompass 1.19-1.0.11
		nyfsquiver: Nyf's Quivers Fabric-0.5.0-1.19-rc2
		phosphor: Phosphor 0.8.1
		probablychests: Probably Chests 0.5.4-1.19.1
		repurposed_structures: Repurposed Structures 6.1.1+1.19
		rightclickharvest: Right Click Harvest 3.0.1
		seasons: Fabric Seasons 1.4-BETA+1.19
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		splatus_ultris: Ultris: Boss Expansion 5.6.4
		t_and_t: Towns and Towers - Structure Add-on 1.8.2
		terralith: Terralith 2.3
		trinkets: Trinkets 3.4.0
		wardentools: Warden Tools 1.6.1
		waystones: Waystones 11.1.0
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.14.9-1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3050 Ti Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 516.59, NVIDIA Corporation
	Window size: 1024x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, charmonium/journeyman, Modified Sweet Berry Bush Model, illuminations/pixelaccurate, continuity/default, continuity/glass_pane_culling_fix
	Current Language: English (US)
	CPU: 16x 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['UnintendedSheep'/191, l='ServerLevel[New World]', x=34.35, y=65.54, z=279.26]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental

### Additional information

I do have about 60+ other mods running, I have 3 mods that crash the game: Map Atlases, Iris Shaders and Sodium. Map Atlases was disabled during my crash, and Iris needs Sodium to run. I've disabled Iris Shaders in a previous test and kept Sodium enabled, during that test I found that Sodium was the cause of the crash.

**Comment by bytzo** [comment]
This crash appears to be the same as #1407. As noted in https://github.com/CaffeineMC/sodium-fabric/issues/1407#issuecomment-1200457490, you will need to install the [Indium](https://modrinth.com/mod/indium) mod when using Sodium and Continuity together.

**Comment by happy0catte** [comment]
> This crash appears to be the same as #1407. As noted in [#1407 (comment)](https://github.com/CaffeineMC/sodium-fabric/issues/1407#issuecomment-1200457490), you will need to install the [Indium](https://modrinth.com/mod/indium) mod when using Sodium and Continuity together.

is there any way to fix it

**Comment by Fnige** [comment]
> is there any way to fix it

... By installing indium (https://modrinth.com/mod/indium)

**Comment by user578344** [comment]
> > is there any way to fix it
> 
> ... By installing indium (https://modrinth.com/mod/indium)

Hi, when I install indium, my game crash whenever I join a game, can you help me please

**Comment by MeeniMc** [comment]
User support happens on discord, not on the bug tracker. 
https://discord.com/channels/602796788608401408/1010831567607844955
