### ISSUE TITLE
1.18.2Memory leak then crash

### ISSUE THREAD

**Issue by 5ur3z** [jellysquid3/Sodium#1520]
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15

### Reproduction Steps

1.join a server
2.play for sometime
3.crashed with memory leak

### Crash Report file

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/10087729/latest.log)

[00:55:15] [Render thread/ERROR]: Out of memory
java.lang.OutOfMemoryError: null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4) ~[?:?]
	at org.lwjgl.system.MemoryUtil.nmemReallocChecked(MemoryUtil.java:484) ~[lwjgl-3.2.2.jar:?]
	at org.lwjgl.system.MemoryUtil.memRealloc(MemoryUtil.java:517) ~[lwjgl-3.2.2.jar:?]
	at me.jellysquid.mods.sodium.client.model.vertex.buffer.VertexBufferBuilder.setBufferSize(VertexBufferBuilder.java:36) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.client.model.vertex.buffer.VertexBufferBuilder.start(VertexBufferBuilder.java:88) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuildBuffers.init(ChunkBuildBuffers.java:62) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:55) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.processJob(ChunkBuilder.java:273) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.stealTask(ChunkBuilder.java:233) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.common.util.collections.WorkStealingFutureDrain.findNext(WorkStealingFutureDrain.java:54) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.common.util.collections.WorkStealingFutureDrain.hasNext(WorkStealingFutureDrain.java:28) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.setupUploadBatches(RenderRegionManager.java:123) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.upload(RenderRegionManager.java:59) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:334) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:312) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:197) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at net.minecraft.client.render.WorldRenderer.setupTerrain(WorldRenderer:18485) ~[?:?]
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1235) ~[?:?]
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1034) ~[?:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:813) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1122) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.10.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) [JavaWrapper.jar:?]
[00:55:45] [Render thread/INFO]: Saved 'betterstats' config.

**Comment by 5ur3z** [comment]
Details:
It reapeat this for many times then memory leak and craash
[00:18:12] [Render thread/ERROR]: ########## GL ERROR ##########
[00:18:12] [Render thread/ERROR]: @ Pre render
[00:18:12] [Render thread/ERROR]: 65539: Invalid mouse button 99
[00:18:12] [Render thread/INFO]: [STDERR]: java.lang.RuntimeException
[00:18:12] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.redirect$zgb000$defaultErrorCallback(class_1041.java:589)
[00:18:12] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_4482(class_1041.java:222)
[00:18:12] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
[00:18:12] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokePI(Native Method)
[00:18:12] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwGetMouseButton(GLFW.java:3435)
[00:18:12] [Render thread/INFO]: [STDERR]: 	at fi.dy.masa.malilib.hotkeys.KeybindMulti.isKeyDown(KeybindMulti.java:430)
[00:18:12] [Render thread/INFO]: [STDERR]: 	at fi.dy.masa.malilib.hotkeys.KeybindMulti.reCheckPressedKeys(KeybindMulti.java:474)
[00:18:12] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.handler$dbj000$onPostKeyboardInput(class_310.java:18967)
[00:18:12] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1574(class_310.java:1817)
[00:18:12] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1091)
[00:18:12] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:737)
[00:18:12] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:236)
[00:18:12] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[00:18:12] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[00:18:12] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[00:18:12] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:18:12] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[00:18:12] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:18:12] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[00:18:12] [Render thread/INFO]: [STDERR]: 	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
[00:18:12] [Render thread/INFO]: [STDERR]: 	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

**Comment by 5ur3z** [comment]
[hs_err_pid53820.log](https://github.com/CaffeineMC/sodium-fabric/files/10087786/hs_err_pid53820.log)
[hs_err_pid48144.log](https://github.com/CaffeineMC/sodium-fabric/files/10087788/hs_err_pid48144.log)
[hs_err_pid53820.log](https://github.com/CaffeineMC/sodium-fabric/files/10087789/hs_err_pid53820.log)

**Comment by Timolino456** [comment]
Please don't use Not Enough Crashes, it's known to cause problems, often blaming Sodium or Iris for things that aren't the actual crash cause (which is why Iris 1.4.3 and onward will show a warning screen when having it installed).
Try again without Not Enough Crashes and report back if anything changes and if yes, post a new log.

**Comment by Pultex** [comment]
good the team might be working on 1.18.2 still

sodium has a problem with botania render of all things in it
crashes randomly when it happens again and it will
will try to post the crash log
strange thing is the crashes happen with things that are listed in the crash log are NOT active
Like the effect from the botania monical you do not have to have it ACTIVE for sodium to crash the server from its rendered effect

**Comment by 5ur3z** [comment]
I have deleted Not Enough Crashes mod，but it still crashes，see the latest issue #1568

**Comment by piuvas** [comment]
you created a new issue and then closed it. is the issue fixed?

**Comment by jellysquid3** [comment]
Not an issue with Sodium. You have some kind of overlay software which is interfering with Minecraft.
