### ISSUE TITLE
Sodium 0.4.8 crashing on 1.19.3

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#1562]
### Version information

sodium-fabric-mc1.19.3-0.4.8+build.22

### Reproduction Steps

1. Install it
2. Enter any world

### Crash Report file

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2023-01-05 00:03:27
Description: Unexpected error

java.lang.IllegalArgumentException: Texture width must be power-of-two
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:158)
	at me.jellysquid.mods.sodium.client.render.CloudRenderer$CloudEdges.<init>(CloudRenderer.java:349)
	at me.jellysquid.mods.sodium.client.render.CloudRenderer.createCloudEdges(CloudRenderer.java:337)
	at me.jellysquid.mods.sodium.client.render.CloudRenderer.reloadTextures(CloudRenderer.java:298)
	at me.jellysquid.mods.sodium.client.render.CloudRenderer.<init>(CloudRenderer.java:61)
	at net.minecraft.class_761.method_3259(class_761.java:6446)
	at net.minecraft.class_761.method_22710(class_761.java:1521)
	at net.minecraft.class_757.method_3188(class_757.java:1085)
	at net.minecraft.class_757.method_3192(class_757.java:864)
	at net.minecraft.class_310.method_1523(class_310.java:1193)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:158)
	at me.jellysquid.mods.sodium.client.render.CloudRenderer$CloudEdges.<init>(CloudRenderer.java:349)
	at me.jellysquid.mods.sodium.client.render.CloudRenderer.createCloudEdges(CloudRenderer.java:337)
	at me.jellysquid.mods.sodium.client.render.CloudRenderer.reloadTextures(CloudRenderer.java:298)
	at me.jellysquid.mods.sodium.client.render.CloudRenderer.<init>(CloudRenderer.java:61)
	at net.minecraft.class_761.method_3259(class_761.java:6446)
	at net.minecraft.class_761.method_22710(class_761.java:1521)
	at net.minecraft.class_757.method_3188(class_757.java:1085)

-- Affected level --
Details:
	All players: 1 total; [class_746['Gamez_Plays'/242, l='ClientLevel', x=206.96, y=120.23, z=-180.27]]
	Chunk stats: 1024, 464
	Level dimension: minecraft:overworld
	Level spawn location: World: (211,63,-202), Section: (at 3,15,6 in 13,3,-13; chunk contains blocks 208,-64,-208 to 223,319,-193), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 881500 game time, 1000 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2390)
	at net.minecraft.class_310.method_1514(class_310.java:805)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods, file/Gamez_Plays's Faithful 32x

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 2477622648 bytes (2362 MiB) / 4097835008 bytes (3908 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 12
	Microarchitecture: Whiskey Lake
	Frequency (GHz): 1.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics 620
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x3ea0
	Graphics card #0 versionInfo: DriverVersion=27.20.100.9664
	Graphics card #1 name: Radeon (TM) 520
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x6665
	Graphics card #1 versionInfo: DriverVersion=26.20.15026.1
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 16135.63
	Virtual memory used (MB): 12135.84
	Swap memory total (MB): 8067.81
	Swap memory used (MB): 971.37
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms8192m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m
	Launched Version: 1.19.3
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Radeon (TM) 520 GL version 3.2.13587 Core Profile Forward-Compatible Context 19.50.26 26.20.15026.1, ATI Technologies Inc.
	Window size: 1366x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, fabric, file/Gamez_Plays's Faithful 32x
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Gamez_Plays'/242, l='ServerLevel[FPS Test]', x=206.96, y=120.23, z=-180.27]]
	Data Packs: vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable

### Additional information

I dont have NVIDIA driver, I tested with 0.4.7 it crashed, on 0.4.6 was fine.

**Comment by jellysquid3** [comment]
You have a broken resource pack. The cloud texture in it must be a size which is a power-of-two (2, 4, 8, 16, 32, 64, 128, 256, 512, etc..).
