### ISSUE TITLE
Sodium crashes when opening video settings or creating a new world.

### ISSUE THREAD

**Issue by Xatzis731** [jellysquid3/Sodium#1598]
### Version information

sodium-fabric-mc1.19.2-0.4.4+build.18

### Reproduction Steps

After opening minecraft normally through the original launcher and then when I either try to navigate over the video settings or create a world my game instantly crashes. I've had this issue in the past but it was somehow solved by itself. I've tried deleting the sodium config file and the config folder as a whole, changing the mod version, but still nothing. Any sort of solution would be much appreciated.

### Crash Report file

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2023-02-02 15:07:50
Description: mouseClicked event handler

java.lang.IncompatibleClassChangeError: Class net.minecraft.class_2588 does not implement the requested interface net.minecraft.class_2561
	at me.jellysquid.mods.sodium.client.gui.options.OptionImpl.handler$zej000$init(OptionImpl.java:540)
	at me.jellysquid.mods.sodium.client.gui.options.OptionImpl.<init>(OptionImpl.java:52)
	at me.jellysquid.mods.sodium.client.gui.options.OptionImpl$Builder.build(OptionImpl.java:200)
	at me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages.localvar$zkg000$addLeavesCulling(SodiumGameOptionPages.java:530)
	at me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages.performance(SodiumGameOptionPages.java:308)
	at me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI.<init>(SodiumOptionsGUI.java:50)
	at net.minecraft.class_429.handler$cbj000$open(class_429.java:523)
	at net.minecraft.class_429.method_19828(class_429.java)
	at net.minecraft.class_4185.method_25306(class_4185.java:43)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1208)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.gui.options.OptionImpl.handler$zej000$init(OptionImpl.java:540)
	at me.jellysquid.mods.sodium.client.gui.options.OptionImpl.<init>(OptionImpl.java:52)
	at me.jellysquid.mods.sodium.client.gui.options.OptionImpl$Builder.build(OptionImpl.java:200)
	at me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages.localvar$zkg000$addLeavesCulling(SodiumGameOptionPages.java:530)
	at me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages.performance(SodiumGameOptionPages.java:308)
	at me.jellysquid.mods.sodium.client.gui.SodiumOptionsGUI.<init>(SodiumOptionsGUI.java:50)
	at net.minecraft.class_429.handler$cbj000$open(class_429.java:523)
	at net.minecraft.class_429.method_19828(class_429.java)
	at net.minecraft.class_4185.method_25306(class_4185.java:43)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_429
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1208)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, §l§6No §4Fire §6Overlay
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2348)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 606865984 bytes (578 MiB) / 905969664 bytes (864 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1b81
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2756
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 18765.42
	Virtual memory used (MB): 9488.98
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 19.19
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 6.4.61
		armor_hud: BerdinskiyBear's ArmorHUD 0.3.7
		autoreconnect: AutoReconnect 2.1.0-beta
		betterhurtcam: BetterHurtCam 1.2.0+mc1.19
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		boostedbrightness: Boosted Brightness 2.1.2
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.9.5
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.9.5
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.9.5
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.9.5
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.9.5
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.9.5
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.9.5
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.9.5
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.9.5
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.9.5
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.9.5
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.9.5
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.9.5
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.9.5
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.9.5
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.9.5
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.9.5
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.9.5
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.9.5
			c2me-threading-scheduling: Concurrent Chunk Management Engine (Threading/Scheduling) 0.2.0+alpha.9.5
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.9.5
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		capes: Capes 1.4.5+1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 2.0.1+1.19
		cull-less-leaves: Cull Less Leaves 1.0.1
		custom_hud: CustomHud 2.1.0+1.19
		debugify: Debugify 2.8.0
			com_github_llamalad7_mixinextras: mixinextras 0.1.0
		enhancedblockentities: Enhanced Block Entities 0.7.2+1.19.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			spruceui: SpruceUI 4.0.0+1.19
		fabric-api: Fabric API 0.72.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.14+6e0787e690
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.13+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.0+82db024a90
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.23+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.4+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.15+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.0+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.32+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.40+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.0+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.1+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.6+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.34+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.3+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.33+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.33+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.3+9785ec3590
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.37+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.3+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.11+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.14+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.6+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.22+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.20+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.10+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.27+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.5+9785ec3590
			fabric-particles-v1: Fabric Particles (v1) 1.0.13+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.0+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.31+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.0+2e5408b590
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.7.0+2e5408b590
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.23+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.18+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.10+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.26+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.0+08b73de490
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.3+251d254a90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.31+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.6+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.23+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.5+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.9.0+kotlin.1.8.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.13
		healthindicators: PlayerHealthIndicators 1.0.1
		inventoryhud: Inventory HUD + 3.4.2
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.10.4
		logical_zoom: Logical Zoom 0.0.17
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.1.0
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		sodiumfix: Sodium Temporary Fix 1.0.2
		starlight: Starlight 1.1.1+fabric.ae22326
		ukulib: ukulib 0.2.0+1.18.2
	Launched Version: fabric-loader-0.14.13-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1070/PCIe/SSE2 GL version 3.2.0 NVIDIA 527.56, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods, file/§l§6No §4Fire §6Overlay (incompatible)
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor

**Comment by pajicadvance** [comment]
Try updating the "Cull Less Leaves" mod. And make sure you're using Sodium 0.4.4, since you're using 0.4.2 according to the log.

**Comment by Xatzis731** [comment]
That sorted everything out. Thanks a lot!
