### ISSUE TITLE
Any Minecraft version with sodium installed crashes when I load a world

### ISSUE THREAD

**Issue by Wyzebb** [jellysquid3/Sodium#1605]
MultiMC version: 0.7.0-3714

Launched instance in online mode

authserver.mojang.com resolves to:
    [18.165.226.41, 18.165.226.61, 18.165.226.58, 18.165.226.43]

session.minecraft.net resolves to:
    [34.197.32.8, 100.24.172.95, 35.153.153.200]

textures.minecraft.net resolves to:
    [13.107.237.64, 13.107.238.64]

api.mojang.com resolves to:
    [18.172.153.32, 18.172.153.63, 18.172.153.104, 18.172.153.35]

Minecraft folder is:
C:/Program Files/MultiMC/instances/1.16.1/.minecraft

Java path is:
C:/Program Files/Eclipse Adoptium/jdk-19.0.2.7-hotspot/bin/javaw.exe

Checking Java version...
Java is version 19.0.2, using 64-bit architecture, from Eclipse Adoptium.

Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  C:/Program Files/MultiMC/instances/1.16.1/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Program Files/MultiMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/Program Files/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Program Files/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Program Files/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Program Files/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  C:/Program Files/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Program Files/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Program Files/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Program Files/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Program Files/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Program Files/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Program Files/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Program Files/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Program Files/MultiMC/libraries/com/mojang/datafixerupper/3.0.25/datafixerupper-3.0.25.jar
  C:/Program Files/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Program Files/MultiMC/libraries/com/mojang/authlib/1.6.25/authlib-1.6.25.jar
  C:/Program Files/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Program Files/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Program Files/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Program Files/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Program Files/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Program Files/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/Program Files/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/Program Files/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Program Files/MultiMC/libraries/net/fabricmc/intermediary/1.16.1/intermediary-1.16.1.jar
  C:/Program Files/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  C:/Program Files/MultiMC/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar
  C:/Program Files/MultiMC/libraries/net/fabricmc/tiny-remapper/0.8.2/tiny-remapper-0.8.2.jar
  C:/Program Files/MultiMC/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  C:/Program Files/MultiMC/libraries/org/ow2/asm/asm/9.4/asm-9.4.jar
  C:/Program Files/MultiMC/libraries/org/ow2/asm/asm-analysis/9.4/asm-analysis-9.4.jar
  C:/Program Files/MultiMC/libraries/org/ow2/asm/asm-commons/9.4/asm-commons-9.4.jar
  C:/Program Files/MultiMC/libraries/org/ow2/asm/asm-tree/9.4/asm-tree-9.4.jar
  C:/Program Files/MultiMC/libraries/org/ow2/asm/asm-util/9.4/asm-util-9.4.jar
  C:/Program Files/MultiMC/libraries/net/fabricmc/fabric-loader/0.14.13/fabric-loader-0.14.13.jar
  C:/Program Files/MultiMC/libraries/com/mojang/minecraft/1.16.1/minecraft-1.16.1-client.jar

Native libraries:
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Program Files/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] antiresourcereload-1.16.1-1.0.0.jar
  [✔️] atum-1.1.3+1.16.1.jar
  [✔️] fast-reset-1.16.1-v1.4.1.jar
  [✔️] forceport-1.1.0.jar
  [✔️] lazydfu-0.1.2.jar
  [✔️] lazystronghold-1.1.3+1.16.1.jar
  [✔️] lithium-1.16.1-backport-fabric-0.6.6.jar
  [✔️] serverSideRNG-6.0.0.jar
  [✔️] sodium-1.16.1-v1.jar
  [✔️] SpeedRunIGT-13.2+1.16.1.jar
  [✔️] starlight-fabric-1.0.0-RC2-1.16.x.jar
  [✔️] voyager-1.0.0.jar

Params:
  --username  --version 1.16.1 --gameDir C:/Program Files/MultiMC/instances/1.16.1/.minecraft --assetsDir C:/Program Files/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms204m, -Xmx2048m, -Duser.language=en]

Minecraft process ID: 5700

Using onesix launcher.

[19:06:09] [main/INFO]: Loading Minecraft 1.16.1 with Fabric Loader 0.14.13
[19:06:10] [ForkJoinPool-1-worker-2/WARN]: Mod starlight uses the version fabric-1.0.0-RC2-82ae5ca which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[19:06:10] [ForkJoinPool-1-worker-1/WARN]: Mod sodium uses the version v1 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'v1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[19:06:10] [main/INFO]: Loading 15 mods:
	- antiresourcereload 1.0.0
	- atum 1.1.3+1.16.1
	- fabricloader 0.14.13
	- fast_reset 1.4.1
	- forceport 1.1.0
	- java 19
	- lazydfu 0.1.2
	- lazystronghold 1.1.3
	- lithium 0.6.6
	- minecraft 1.16.1
	- serversiderng 6.0.0
	- sodium v1
	- speedrunigt 13.2+1.16.1
	- starlight fabric-1.0.0-RC2-82ae5ca
	- voyager 1.0.0
[19:06:10] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Program%20Files/MultiMC/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[19:06:11] [main/INFO]: Loaded configuration file for Lithium: 79 options available, 0 override(s) found
[19:06:11] [main/INFO]: Loaded configuration file for Sodium: 24 options available, 0 override(s) found
[19:06:29] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[19:06:29] [Render thread/INFO]: Setting user: Wyzebb
[19:06:29] [Render thread/INFO]: [AntiResourceReload] Initializing.
[19:06:29] [Render thread/INFO]: Narrator library for x64 successfully loaded
[19:06:29] [Render thread/INFO]: Initializing
[19:06:29] [Render thread/INFO]: [STDOUT]: Using Fast Reset
[19:06:29] [Render thread/INFO]: [Force Port Mod] Initializing
[19:06:30] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[19:06:31] [Render thread/INFO]: [STDERR]: [LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers.
[19:06:36] [Render thread/INFO]: Reloading ResourceManager: Default
[19:06:42] [Render thread/INFO]: OpenAL initialized.
[19:06:42] [Render thread/INFO]: Sound engine started
[19:06:43] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[19:06:43] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[19:06:43] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[19:06:43] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[19:06:43] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[19:06:43] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[19:06:43] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[19:06:45] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[19:06:45] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[19:06:45] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[19:07:40] [Render thread/INFO]: [AntiResourceReload] Using data-packs, reloading.
[19:07:40] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[19:07:40] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[19:07:40] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[19:07:40] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[19:07:40] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[19:07:40] [Render thread/INFO]: Reloading ResourceManager: Default, UI
[19:07:41] [Render thread/INFO]: Loaded 7 recipes
[19:07:42] [Render thread/INFO]: Loaded 927 advancements
[19:07:43] [Render thread/FATAL]: Reported exception thrown!
net.minecraft.class_148: Starting integrated server
	at net.minecraft.class_437.method_25412(class_437.java:436) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:92) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:162) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:162) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:308) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1041) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:654) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.13.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.concurrent.CompletableFuture.get()" because "me.wurgo.antiresourcereload.AntiResourceReload.cache" is null
	at net.minecraft.class_310.redirect$zza000$antiresourcereload_skipLoad(class_310.java:2831) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_29610(class_310.java:1788) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_29606(class_310.java:1698) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:408) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:319) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:256) ~[client-intermediary.jar:?]
	at net.minecraft.class_350.method_25402(class_350.java:331) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:92) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:431) ~[client-intermediary.jar:?]
	... 21 more
---- Minecraft Crash Report ----
// My bad.

Time: 08/02/2023, 19:07
Description: Starting integrated server

java.lang.NullPointerException: Cannot invoke "java.util.concurrent.CompletableFuture.get()" because "me.wurgo.antiresourcereload.AntiResourceReload.cache" is null
	at net.minecraft.class_310.redirect$zza000$antiresourcereload_skipLoad(class_310.java:2831)
	at net.minecraft.class_310.method_29610(class_310.java:1788)
	at net.minecraft.class_310.method_29606(class_310.java:1698)
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:408)
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:319)
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:256)
	at net.minecraft.class_350.method_25402(class_350.java:331)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:92)
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102)
	at net.minecraft.class_1041.method_15998(class_1041.java:308)
	at net.minecraft.class_310.method_1523(class_310.java:1041)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_310.redirect$zza000$antiresourcereload_skipLoad(class_310.java:2831)

-- Starting integrated server --
Details:
	Level ID: Portal Practice v2
	Level Name: Portal Practice v2
Stacktrace:
	at net.minecraft.class_310.method_29610(class_310.java:1788)
	at net.minecraft.class_310.method_29606(class_310.java:1698)
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:408)
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:319)
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:256)
	at net.minecraft.class_350.method_25402(class_350.java:331)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:92)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_526
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102)
	at net.minecraft.class_1041.method_15998(class_1041.java:308)
	at net.minecraft.class_310.method_1523(class_310.java:1041)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 19.0.2, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 186751632 bytes (178 MB) / 458227712 bytes (437 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms204m -Xmx2048m
	Launched Version: 1.16.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon(TM) Graphics GL version 4.6.13596 Compatibility Profile Context 20.10.21.01 27.20.1021.1002, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx 
#@!@# Game crashed! Crash report saved to: #@!@# C:\Program Files\MultiMC\instances\1.16.1\.minecraft\crash-reports\crash-2023-02-08_19.07.43-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1 (0xffffffffffffffff).

**Comment by Wyzebb** [comment]
Any version of Minecraft without sodium works just fine.

**Comment by Wyzebb** [comment]
I have fixed the issue - cull leaves and AntiResourceReload are incompatible.
