### ISSUE TITLE
Crash when trying to load world

### ISSUE THREAD

**Issue by Chris6ix** [jellysquid3/Sodium#1647]
### Version information

sodium-fabric-mc1.19.3-0.4.9+build.23

### Expected Behavior

No crash

### Actual Behavior

Crashes with the following error as soon as it tries to load the world:

java.lang.NoClassDefFoundError: me/jellysquid/mods/sodium/client/model/vertex/type/VertexType
	at net.minecraft.class_702.handler$bpo001$render(class_702.java:4638)
	at net.minecraft.class_702.method_3049(class_702.java)
	at net.minecraft.class_761.redirect$bbg000$iris$renderTranslucentAfterDeferred(class_761.java:8473)
	at net.minecraft.class_761.method_22710(class_761.java:1502)
	at net.minecraft.class_757.method_3188(class_757.java:1085)
	at net.minecraft.class_757.method_3192(class_757.java:864)
	at net.minecraft.class_310.method_1523(class_310.java:1193)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: me.jellysquid.mods.sodium.client.model.vertex.type.VertexType
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 13 more

### Reproduction Steps

Load a singleplayer world or join a server

### Java version

Java 17.0.6+9-LTS-190

### CPU

AMD Ryzen 5 5600X

### GPU

AMD RX 7900 XT

### Additional information

Full crash log: [crash-2023-03-02_05.07.32-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/10867428/crash-2023-03-02_05.07.32-client.txt)

**Comment by papamaionise** [comment]
Same issue sodium makes minecraft crash on joining any world sometimes it renders a frame with invisible blocks and visible entities then freezes the game other times it just freezes even before that

 yeah I have tried changing settings removing all other mods reinstalling minecraft and many recommended fixes like disabling some stuff in advance settings

Sodium For 1.18.2 works flawlessly No problems at all even when using many other mods alongside

I have an old AMD gpu with modded drivers 14 gigs of ram and a 4th gen intel i3 processor

I just started using sodium for the first time and this happend :/

**Comment by Lolothepro** [comment]
update physicsmod

**Comment by papamaionise** [comment]
@Lolothepro  Not using physics mod its just Na

**Comment by Chris6ix** [comment]
> update physicsmod

Updating PhysicsMod actually fixed it...thanks!
Should I leave this open for @papamaionise's issue (The same issue but apparently without even using PhysicsMod), or should he open a new issue for that?

**Comment by Lolothepro** [comment]
You can close here
