### ISSUE TITLE
Fabric Minecraft crashes because of Sodium

### ISSUE THREAD

**Issue by KickOnTwitch** [jellysquid3/Sodium#1652]
### Version information

Minecraft version: 1.19.3; Fabric - 0.14.17

### Reproduction Steps

1. Start the game
2. The game crashes

### Crash Report file

[19:46:27] [main/INFO]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.17
[19:46:28] [main/INFO]: Loading 149 mods:
	- ae2 13.0.6-beta
	   |-- noindium 1.1.0+1.19
	   \-- team_reborn_energy 2.0.0-beta1
	- ambientsounds 5.2.17
	- appleskin 2.4.2+mc1.19.3
	   \-- cloth-config 9.0.94
	        \-- cloth-basic-math 0.6.1
	- architectury 7.1.70
	- bclib 2.2.4
	- betteradvancements 0.3.1.149
	- betterend 3.1.2
	- betterf3 5.1.0
	   \-- cloth-config 9.0.94
	        \-- cloth-basic-math 0.6.1
	- betternether 8.1.3
	- blur 2.6.1
	   |-- midnightlib 1.1.0
	   \-- satin 1.10.0
	- bookshelf 17.0.3
	- cardinal-components 5.1.0
	   |-- cardinal-components-base 5.1.0
	   |-- cardinal-components-block 5.1.0
	   |-- cardinal-components-chunk 5.1.0
	   |-- cardinal-components-entity 5.1.0
	   |-- cardinal-components-item 5.1.0
	   |-- cardinal-components-level 5.1.0
	   |-- cardinal-components-scoreboard 5.1.0
	   \-- cardinal-components-world 5.1.0
	- carryon 2.0.4.15
	   \-- com_github_llamalad7_mixinextras 0.2.0-beta.1
	- clickadv 3.0
	- clickthrough 1.19.3-fabric0.68.1-0.4
	   |-- crowdin-translate 1.4+1.19.3
	   \-- gbfabrictools 1.3.4+1.19.3
	- comforts 6.1.1+1.19.3
	   |-- cardinal-components-base 5.1.0
	   |-- cardinal-components-entity 5.1.0
	   \-- spectrelib 0.12.1+1.19.2
	        |-- com_electronwill_night-config_core 3.6.5
	        \-- com_electronwill_night-config_toml 3.6.5
	- controlling 10.0+9
	- creativecore 2.10.4
	   \-- net_minecraftforge_eventbus 6.0.4
	- darkpaintings 14.0.2
	- ecologics 2.1.12
	   \-- cloth-config 9.0.94
	        \-- cloth-basic-math 0.6.1
	- fabric-api 0.75.1+1.19.3
	   |-- fabric-api-base 0.4.21+70be179c85
	   |-- fabric-api-lookup-api-v1 1.6.20+49abcf7e85
	   |-- fabric-biome-api-v1 12.1.1+b5d379b085
	   |-- fabric-block-api-v1 1.0.5+e022e5d185
	   |-- fabric-blockrenderlayer-v1 1.1.31+928d44d585
	   |-- fabric-client-tags-api-v1 1.0.12+1134c5b885
	   |-- fabric-command-api-v1 1.2.22+f71b366f85
	   |-- fabric-command-api-v2 2.2.1+3fc4752e85
	   |-- fabric-commands-v0 0.2.39+df3654b385
	   |-- fabric-containers-v0 0.1.47+df3654b385
	   |-- fabric-content-registries-v0 3.5.1+1d37d50285
	   |-- fabric-convention-tags-v1 1.2.2+8e4e694f85
	   |-- fabric-crash-report-info-v1 0.2.14+aeb40ebe85
	   |-- fabric-data-generation-api-v1 11.3.1+40dc7a9485
	   |-- fabric-dimensions-v1 2.1.42+00a2eb1085
	   |-- fabric-entity-events-v1 1.5.7+b83334a085
	   |-- fabric-events-interaction-v0 0.4.40+3baeb27a85
	   |-- fabric-events-lifecycle-v0 0.2.44+df3654b385
	   |-- fabric-game-rule-api-v1 1.0.30+99f9db8085
	   |-- fabric-item-api-v1 2.1.10+312c329485
	   |-- fabric-item-group-api-v1 2.1.12+1134c5b885
	   |-- fabric-key-binding-api-v1 1.0.31+bc01e09785
	   |-- fabric-keybindings-v0 0.2.29+df3654b385
	   |-- fabric-lifecycle-events-v1 2.2.10+23a79c8a85
	   |-- fabric-loot-api-v2 1.1.20+75e9821185
	   |-- fabric-loot-tables-v1 1.1.24+9e7660c685
	   |-- fabric-message-api-v1 5.1.0+c85585f885
	   |-- fabric-mining-level-api-v1 2.1.31+49abcf7e85
	   |-- fabric-models-v0 0.3.27+11ba9c3b85
	   |-- fabric-networking-api-v1 1.2.17+4017a8cb85
	   |-- fabric-networking-v0 0.3.34+df3654b385
	   |-- fabric-object-builder-api-v1 5.4.1+eb2a3ba985
	   |-- fabric-particles-v1 1.0.20+f1e4495b85
	   |-- fabric-recipe-api-v1 1.0.1+5176f73d85
	   |-- fabric-registry-sync-v0 2.1.0+f7b4d36485
	   |-- fabric-renderer-api-v1 2.2.2+3a95925a85
	   |-- fabric-renderer-indigo 0.8.0+3a95925a85
	   |-- fabric-renderer-registries-v1 3.2.30+df3654b385
	   |-- fabric-rendering-data-attachment-v1 0.3.25+afca2f3e85
	   |-- fabric-rendering-fluids-v1 3.0.18+f1e4495b85
	   |-- fabric-rendering-v0 1.1.33+df3654b385
	   |-- fabric-rendering-v1 1.12.1+eb2a3ba985
	   |-- fabric-resource-conditions-api-v1 2.3.0+e63306e085
	   |-- fabric-resource-loader-v0 0.10.5+a91e48b785
	   |-- fabric-screen-api-v1 1.0.41+f1e4495b85
	   |-- fabric-screen-handler-api-v1 1.3.13+99f9db8085
	   |-- fabric-sound-api-v1 1.0.8+75e9821185
	   |-- fabric-transfer-api-v1 2.1.15+ccd377ba85
	   \-- fabric-transitive-access-wideners-v1 2.3.1+40dc7a9485
	- fabric-language-kotlin 1.9.1+kotlin.1.8.10
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.10
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.19.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1
	- fabricloader 0.14.17
	- friendsandfoes 1.7.5
	- inventorysorter 1.8.10-1.19.3
	   \-- kyrptconfig 1.5.1-1.19.3
	- java 17
	- jei 12.3.0.18
	- lambdynlights 2.2.0+1.19.3
	   |-- pride 1.2.0+1.19.3
	   \-- spruceui 4.1.0+1.19.3
	- mcwbridges 2.0.6
	- mcwdoors 1.0.8
	- mcwfences 1.0.7
	- mcwlights 1.0.5
	- mcwpaintings 1.0.4
	- mcwpaths 1.0.2
	- mcwroofs 2.2.2
	- mcwtrpdoors 1.0.8
	- mcwwindows 2.1.2
	- minecraft 1.19.3
	- modmenu 5.0.2
	- mousetweaks 2.24
	- naturescompass 1.19.3-2.1.1-fabric
	- phosphor 0.8.1
	- presencefootsteps 1.7.1
	   \-- kirin 1.13.2
	- puzzle 1.4.2-1.19.3
	   |-- midnightlib 1.1.0
	   |-- puzzle-base 1.4.2-1.19.3
	   |-- puzzle-gui 1.4.2-1.19.3
	   |-- puzzle-models 1.4.2-1.19.3
	   \-- puzzle-splashscreen 1.4.2-1.19.3
	- runelic 15.0.1
	- skinlayers 1.5.2-mc1.19.3
	- sodium 0.4.9+build.23
	- sound_physics_remastered 1.19.3-1.1.0
	- structory 1.0.1
	- terrablender 2.1.0.134
	- terralith 2.3
	- the_bumblezone 6.6.13+1.19.3-fabric
	   |-- cardinal-components-base 5.1.0
	   |-- cardinal-components-entity 5.1.0
	   \-- fake-player-api 0.5.0
	- toms_storage 1.5.1
	   \-- cloth-config 9.0.94
	        \-- cloth-basic-math 0.6.1
	- villagernames 4.5.0
	   |-- cardinal-components-base 5.1.0
	   |-- cardinal-components-level 5.1.0
	   \-- cloth-config 9.0.94
	        \-- cloth-basic-math 0.6.1
	- visuality 0.6.1
	- waterdripsound 1.19-0.3.1
	- xaerominimap 23.2.0
	- xaeroworldmap 1.29.1
	- yet-another-config-lib 2.2.0
[19:46:28] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/kickd/curseforge/minecraft/Install/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[19:46:28] [main/INFO]: Compatibility level set to JAVA_11
[19:46:28] [main/INFO]: Compatibility level set to JAVA_17
[19:46:29] [main/WARN]: [Satin] Sodium is present, custom block renders may not work
[19:46:29] [main/INFO]: Loaded configuration file for Sodium: 33 options available, 0 override(s) found
[19:46:29] [main/WARN]: Error loading class: net/dorianpb/cem/internal/config/CemConfig (java.lang.ClassNotFoundException: net/dorianpb/cem/internal/config/CemConfig)
[19:46:29] [main/WARN]: @Mixin target net.dorianpb.cem.internal.config.CemConfig was not found puzzle-gui.mixins.json:CemConfigAccessor from mod puzzle-gui
[19:46:29] [main/WARN]: Error loading class: org/jetbrains/annotations/ApiStatus$Internal (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$Internal)
[19:46:36] [main/INFO]: Building optimized datafixer
[19:46:40] [main/INFO]: [bclib] Added Config betternether.main to auto sync (file hash)
[19:46:40] [main/INFO]: [bclib] Added Config betternether.generator to auto sync (file hash)
[19:46:40] [main/INFO]: [bclib] Added Config betternether.blocks to auto sync (file hash)
[19:46:40] [main/INFO]: [bclib] Added Config betternether.items to auto sync (file hash)
[19:46:40] [main/INFO]: [bclib] Added Config betternether.biomes to auto sync (file hash)
[19:46:40] [main/INFO]: [bclib] Added Config betternether.mobs to auto sync (file hash)
[19:46:40] [main/INFO]: [bclib] Added Config betternether.recipes to auto sync (file hash)
[19:46:41] [main/INFO]: [bclib] Added Config bclib.generator to auto sync (file hash)
[19:46:41] [main/INFO]: [bclib] Added Config bclib.main to auto sync (content diff)
[19:46:41] [main/INFO]: [bclib] Added Config bclib.recipes to auto sync (file hash)
[19:46:41] [main/INFO]: [bclib] Added Config bclib.biomes to auto sync (file hash)
[19:46:42] [Render thread/INFO]: Launching a new process to probe the system configuration!
[19:46:43] [Render thread/INFO]: OpenGL Vendor: NVIDIA Corporation
[19:46:43] [Render thread/INFO]: OpenGL Renderer: NVIDIA GeForce RTX 2070/PCIe/SSE2
[19:46:43] [Render thread/INFO]: OpenGL Version: 3.3.0 NVIDIA 531.18
[19:46:43] [Render thread/WARN]: Enabling workaround for NVIDIA graphics drivers on Windows (issue #1486)
[19:46:43] [Render thread/WARN]: One or more workarounds were enabled to prevent crashes or other issues on your system. You may need to update your graphics drivers.
[19:46:44] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[19:46:45] [Render thread/INFO]: Setting user: KickOnTwitch
[19:46:45] [Render thread/INFO]: [bclib] Added Config betterend.entities to auto sync (file hash)
[19:46:45] [Render thread/INFO]: [bclib] Added Config betterend.blocks to auto sync (file hash)
[19:46:45] [Render thread/INFO]: [bclib] Added Config betterend.items to auto sync (file hash)
[19:46:45] [Render thread/INFO]: [bclib] Added Config betterend.biomes to auto sync (file hash)
[19:46:45] [Render thread/INFO]: [bclib] Added Config betterend.recipes to auto sync (file hash)
[19:46:45] [Render thread/INFO]: [bclib] Added Config betterend.enchantments to auto sync (file hash)
[19:47:02] [Render thread/INFO]: [betternether] =^..^=    BetterNether for 1.19    =^..^=
[19:47:02] [Render thread/INFO]: Fixing MC-151457. Crafting remainder for minecraft:pufferfish_bucket is now minecraft:bucket.
[19:47:02] [Render thread/INFO]: Fixing MC-151457. Crafting remainder for minecraft:salmon_bucket is now minecraft:bucket.
[19:47:02] [Render thread/INFO]: Fixing MC-151457. Crafting remainder for minecraft:cod_bucket is now minecraft:bucket.
[19:47:02] [Render thread/INFO]: Fixing MC-151457. Crafting remainder for minecraft:tropical_fish_bucket is now minecraft:bucket.
[19:47:02] [Render thread/INFO]: Fixing MC-151457. Crafting remainder for minecraft:axolotl_bucket is now minecraft:bucket.
[19:47:02] [Render thread/INFO]: Fixing MC-151457. Crafting remainder for minecraft:powder_snow_bucket is now minecraft:bucket.
[19:47:02] [Render thread/INFO]: Fixing MC-151457. Crafting remainder for minecraft:tadpole_bucket is now minecraft:bucket.
[19:47:02] [Render thread/INFO]: clickadv mod initialized
[19:47:11] [Render thread/INFO]: Reloading reverb parameters
[19:47:11] [Render thread/WARN]: Sound event ecologics:entity.camel.ambient not found
[19:47:11] [Render thread/WARN]: Sound event ecologics:entity.camel.death not found
[19:47:11] [Render thread/WARN]: Sound event ecologics:entity.coconut_crab.ambient not found
[19:47:11] [Render thread/WARN]: Sound event ecologics:entity.camel.step not found
[19:47:11] [Render thread/WARN]: Sound event ecologics:block.thin_ice.crack not found
[19:47:11] [Render thread/WARN]: Sound event ecologics:entity.camel.angry not found
[19:47:11] [Render thread/WARN]: Sound event ecologics:entity.coconut_crab.hurt not found
[19:47:11] [Render thread/WARN]: Sound event ecologics:entity.squirrel.hurt not found
[19:47:11] [Render thread/WARN]: Sound event ecologics:block.coconut.smash not found
[19:47:11] [Render thread/WARN]: Sound event ecologics:entity.camel.eat not found
[19:47:11] [Render thread/WARN]: Sound event ecologics:entity.penguin.death not found
[19:47:11] [Render thread/WARN]: Sound event ecologics:entity.camel.chest not found
[19:47:11] [Render thread/WARN]: Sound event ecologics:music_disc.coconut not found
[19:47:11] [Render thread/WARN]: Sound event ecologics:entity.penguin.hurt not found
[19:47:11] [Render thread/WARN]: Sound event ecologics:entity.camel.hurt not found
[19:47:11] [Render thread/WARN]: Sound event ecologics:entity.coconut_crab.death not found
[19:47:11] [Render thread/WARN]: Sound event ecologics:entity.squirrel.ambient not found
[19:47:11] [Render thread/WARN]: Sound event ecologics:entity.penguin.ambient not found
[19:47:11] [Render thread/WARN]: Sound event ecologics:entity.squirrel.death not found
[19:47:13] [Render thread/INFO]: Config loaded
[19:47:13] [Render thread/INFO]: Tom's Storage Setup starting
[19:47:15] [Render thread/WARN]: Unable to find class com.simibubi.create.foundation.ponder.PonderWorld. Integration with PonderJS disabled.
[19:47:15] [Render thread/WARN]: Static binding violation: PRIVATE @Overwrite method method_23182 in sodium.mixins.json:features.item.MixinItemRenderer from mod sodium cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
[19:47:15] [Render thread/ERROR]: Specified invalid page id in system property guideDev.ae2guide.startupPage
[19:47:15] [Render thread/INFO]: Registering S2C receiver with id architectury:spawn_entity_packet
[19:47:16] [Thread-6/INFO]: [bclib] Received Version Info for minecraft=1.19.3, loader=fabric
[19:47:16] [Thread-6/INFO]: [bclib]  - bclib:2.2.4
[19:47:16] [Thread-6/INFO]: [bclib]  - betterend:3.1.2
[19:47:16] [Thread-6/INFO]: [bclib]  - betternether:8.1.3
[19:47:16] [Render thread/INFO]: Loaded
[19:47:16] [Render thread/ERROR]: java.io.FileNotFoundException: C:\Users\kickd\curseforge\minecraft\Instances\Streampack\config\betteradvancements.json (Das System kann die angegebene Datei nicht finden)
[19:47:16] [Render thread/INFO]: [BetterF3] Loading...
[19:47:16] [Render thread/INFO]: [BetterF3] All done!
[19:47:16] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[19:47:16] [Worker-Bootstrap-6/INFO]: 4445 Datafixer optimizations took 40786 milliseconds
[19:47:17] [Render thread/INFO]: Sending ConfigManager...
[19:47:17] [Render thread/INFO]: Sending ConfigManager took 3.765 ms
[19:47:17] [Render thread/INFO]: [LambDynLights] Initializing LambDynamicLights...
[19:47:17] [Render thread/INFO]: [LambDynLights] Configuration loaded.
[19:47:17] [Render thread/WARN]: Using Cloth Config GUI
[19:47:17] [Render thread/INFO]: [STDOUT]: [Mouse Tweaks] Main.initialize()
[19:47:17] [Render thread/INFO]: [STDOUT]: [Mouse Tweaks] Initialized.
[19:47:17] [Render thread/INFO]: Trying to read config file...
[19:47:17] [Render thread/INFO]: A config file was found, loading it..
[19:47:17] [Render thread/INFO]: Successfully loaded config file.
[19:47:17] [Render thread/INFO]: Loading Xaero's Minimap - Stage 1/2
[19:47:18] [Render thread/INFO]: Loading Xaero's World Map - Stage 1/2
[19:47:20] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[19:47:21] [Render thread/INFO]: [STDOUT]: bumblezone: register particles
[19:47:21] [Render thread/INFO]: Narrator library for x64 successfully loaded
[19:47:21] [Render thread/INFO]: Reloading ResourceManager: vanilla, Fabric Mods (Applied Energistics 2, Ambient Sounds (Fabric), AppleSkin, BCLib, Better Advancements, Better End, BetterF3, Better Nether, Blur (Fabric), Bookshelf, Cardinal Components API, Cardinal Components API (base), Cardinal Components API (blocks), Cardinal Components API (chunks), Cardinal Components API (entities), Cardinal Components API (items), Cardinal Components API (world saves), Cardinal Components API (scoreboard), Cardinal Components API (worlds), Carry On, Clickable Advancements Mod, ClickThrough, Cloth Config v9, Comforts, Controlling For Fabric, CreativeCore (Fabric), DarkPaintings, Ecologics, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric Block API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Client Tags, Fabric Command API (v1), Fabric Command API (v2), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Data Generation API (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Group API (v1), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Language Kotlin, Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Loot Tables (v1), Fabric Message API (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Recipe API (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Sound API (v1), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, Fake Player API, Friends&Foes, GBfabrictools, Inventory Sorter, Just Enough Items, Kyrpt Config, LambDynamicLights, Macaw's Bridges, Macaw's Doors, Macaw's Fences and Walls, Macaw's Lights and Lamps, Macaw's Paintings, Macaw's Paths and Pavings, Macaw's Roofs, Macaw's Trapdoors, Macaw's Windows, MidnightLib, Mod Menu, Nature's Compass, No Indium?, Phosphor, Presence Footsteps, Pride Lib, Puzzle, Puzzle Base, Puzzle GUI, Puzzle Models, Puzzle Splash Screen, Runelic, Satin, 3d Skin Layers, Sodium, Sound Physics Remastered, SpruceUI, Energy, TerraBlender, The Bumblezone - Fabric, Tom's Simple Storage Mod, Villager Names, Visuality, Drip Sounds, Xaero's Minimap, Xaero's World Map, YetAnotherConfigLib)
[19:47:22] [Worker-Main-22/ERROR]: Invalid path in mod resource-pack fabric:ae2: ae2:ae2guide/website/assets/large/VibrantQuartzGlassAni.gif, ignoring
[19:47:22] [Worker-Main-16/ERROR]: Invalid path in mod resource-pack fabric:betterend: betterend:textures/item/thermal fungus.png, ignoring
[19:47:22] [Render thread/ERROR]: Unhandled game exception
java.lang.NoSuchMethodError: 'void net.minecraft.class_4185.<init>(int, int, int, int, net.minecraft.class_2561, net.minecraft.class_4185$class_4241)'
	at me.luligabi.noindium.NoIndiumWarningScreen.method_41160(NoIndiumWarningScreen.java:30) ~[noindium-1.1.0+1.19-551f02e6b5221299.jar:?]
	at me.luligabi.noindium.NoIndiumWarningScreen.method_25426(NoIndiumWarningScreen.java:62) ~[noindium-1.1.0+1.19-551f02e6b5221299.jar:?]
	at net.minecraft.class_437.method_41843(class_437.java:392) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:383) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1049) ~[client-intermediary.jar:?]
	at me.luligabi.noindium.NoIndium.lambda$onInitializeClient$0(NoIndium.java:26) ~[noindium-1.1.0+1.19-551f02e6b5221299.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents.lambda$static$0(ClientLifecycleEvents.java:35) ~[fabric-lifecycle-events-v1-2.2.1+23a79c8a85-8ce42a4ec43c8c0d.jar:?]
	at net.minecraft.class_310.handler$bem001$fabric-lifecycle-events-v1$onStart(class_310.java:10507) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:760) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) ~[fabric-loader-0.14.17-1.19.3.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[fabric-loader-0.14.17-1.19.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.17.jar:?]
[19:47:22] [Render thread/INFO]: Stopping!
[19:47:22] [Render thread/WARN]: Mixin bclib.mixins.client.json:SignEditScreenMixin from mod bclib has multiple constructors, (Lnet/minecraft/class_2625;Z)V was selected
[19:47:22] [Render thread/INFO]: Loading Xaero's World Map - Stage 2/2
[19:47:22] [Render thread/INFO]: New world map region cache hash code: 154799326
[19:47:22] [Render thread/INFO]: Xaero's WorldMap Mod: Xaero's minimap found!
[19:47:22] [Render thread/INFO]: No Optifine!
[19:47:22] [Render thread/INFO]: Xaero's World Map: No Vivecraft!

### Additional information

I already found out that Sodium is the reason for my game to crash because disabling it fixes my problem.

**Comment by TheUnknownCod3r** [comment]
Its also likely that Sodium isn't the issue, your crash is related to me.luligabi.noindium.NoIndiumWarningScreen.method_41160, which is probably being called cause you don't have Indium installed, but are calling functions with the Rendering Engine. Try adding Indium to the modlist and trying again. If you still have issues, post the updated Log.

EDIT: No Indium is a mod, but still, you should install Indium anyway, and remove this one. Your error is directly related to NoIndium, not Sodium.

EDIT 2: For clarification, NoIndium? is a mod that alerts you if you don't have Indium installed, and asks you to install it. So Install Indium, remove NoIndium? and your issue will be fixed.

 

> I already found out that Sodium is the reason for my game to crash because disabling it fixes my problem.

Removing Sodium removes all references it adds, including references to Indium Functions. Removing Sodium will fix the issue due to Indium no longer being required, thats all. Sodium was never your issue.

**Comment by KickOnTwitch** [comment]
> Its also likely that Sodium isn't the issue, your crash is related to me.luligabi.noindium.NoIndiumWarningScreen.method_41160, which is probably being called cause you don't have Indium installed, but are calling functions with the Rendering Engine. Try adding Indium to the modlist and trying again. If you still have issues, post the updated Log.
> 
> EDIT: No Indium is a mod, but still, you should install Indium anyway, and remove this one. Your error is directly related to NoIndium, not Sodium.
> 
> EDIT 2: For clarification, NoIndium? is a mod that alerts you if you don't have Indium installed, and asks you to install it. So Install Indium, remove NoIndium? and your issue will be fixed.
> 
> > I already found out that Sodium is the reason for my game to crash because disabling it fixes my problem.
> 
> Removing Sodium removes all references it adds, including references to Indium Functions. Removing Sodium will fix the issue due to Indium no longer being required, thats all. Sodium was never your issue.

Installing Indium actually fixed my problem, thank you very much :)

**Comment by TheUnknownCod3r** [comment]
No worries, sorry I went a bit overboard in my comment explaining it XD. Glad to help
