### ISSUE TITLE
game crashes

### ISSUE THREAD

**Issue by joeyreg** [jellysquid3/Sodium#1673]
### Version information

mc1.19.4

### Reproduction Steps

the game crashes

### Crash Report file

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Sodium' (sodium) 0.4.10+build.24 with version 0.4.10 or later that is compatible with:
		 - optifabric 1.13.24
Unmet dependency listing:
	 - Mod 'Sodium' (sodium) 0.4.10+build.24 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.24!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by ThatMG393** [comment]
Remove `OptiFabric`

**Comment by LucilleTea** [comment]
Mod 'Sodium' (sodium) 0.4.10+build.24 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.24!

you cannot use sodium and optifine together, at all.
