### ISSUE TITLE
Error 1

### ISSUE THREAD

**Issue by ItzYorki** [jellysquid3/Sodium#1682]
### Version information

fabric-loader-0.14.19-1.19.4

### Reproduction Steps

Open Minecraft and it crashes immediately before mojang screen loads

### Crash Report file
16:55:20.968
launcher
main
Using default game log configuration client-1.12.xml (outputs XML)
16:55:37.340
FabricLoader/GameProvider
main
Loading Minecraft 1.19.4 with Fabric Loader 0.14.19
16:55:38.426
FabricLoader/Metadata
ForkJoinPool-1-worker-4
Mod com_github_jctools_jctools_jctools-core uses the version v4.0.1 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'v4'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
16:55:38.998
FabricLoader/Metadata
ForkJoinPool-1-worker-4
The mod "moreculling" contains invalid entries in its mod json:
- Unsupported root entry "embedded" at line 35 column 13
16:55:39.932
FabricLoader/Resolution
main
Warnings were found!
 - Mod 'OptiGUI' (optigui) 2.0.0-beta.3 recommends any version of knowmyname, which is missing!
	 - You should install any version of knowmyname for the optimal experience.
16:55:39.938
FabricLoader
main
Loading 128 mods:
	- animatica 0.5+1.19
	- antighost 1.19.3-fabric0.68.1-1.1.5
	   \-- crowdin-translate 1.4+1.19.3
	- bettermounthud 1.2.1
	- borderlessmining 1.1.7+1.19.4
	- capes 1.5.2+1.19.3
	- citresewn 1.1.3+1.19.4
	   \-- citresewn-defaults 1.1.3+1.19.4
	- cloth-config 10.0.96
	   \-- cloth-basic-math 0.6.1
	- continuity 3.0.0-beta.2+1.19.3
	- debugify 1.19.4+1.0
	- dynamicfps 2.2.0
	   \-- com_moandjiezana_toml_toml4j 0.7.2
	- entity_model_features 0.2.4
	- entity_texture_features 4.3.5
	   \-- org_apache_httpcomponents_httpmime 4.5.10
	- entityculling 1.6.2-mc1.19.4
	- fabric-api 0.76.0+1.19.4
	   |-- fabric-api-base 0.4.23+9ff28bcef4
	   |-- fabric-api-lookup-api-v1 1.6.24+49abcf7ef4
	   |-- fabric-biome-api-v1 13.0.6+348a9c64f4
	   |-- fabric-block-api-v1 1.0.5+e022e5d1f4
	   |-- fabric-blockrenderlayer-v1 1.1.33+c2e6f674f4
	   |-- fabric-client-tags-api-v1 1.0.14+1134c5b8f4
	   |-- fabric-command-api-v1 1.2.25+f71b366ff4
	   |-- fabric-command-api-v2 2.2.4+ae0966baf4
	   |-- fabric-commands-v0 0.2.42+df3654b3f4
	   |-- fabric-containers-v0 0.1.52+df3654b3f4
	   |-- fabric-content-registries-v0 3.5.7+ae0966baf4
	   |-- fabric-convention-tags-v1 1.4.0+9a7c5daaf4
	   |-- fabric-crash-report-info-v1 0.2.14+aeb40ebef4
	   |-- fabric-data-generation-api-v1 11.3.5+5da15ca1f4
	   |-- fabric-dimensions-v1 2.1.44+7f87f8faf4
	   |-- fabric-entity-events-v1 1.5.12+e45f7c65f4
	   |-- fabric-events-interaction-v0 0.4.42+a1ccd7bff4
	   |-- fabric-events-lifecycle-v0 0.2.51+df3654b3f4
	   |-- fabric-game-rule-api-v1 1.0.32+a1ccd7bff4
	   |-- fabric-item-api-v1 2.1.16+09a3510cf4
	   |-- fabric-item-group-api-v1 3.0.3+043f9acff4
	   |-- fabric-key-binding-api-v1 1.0.32+c477957ef4
	   |-- fabric-keybindings-v0 0.2.30+df3654b3f4
	   |-- fabric-lifecycle-events-v1 2.2.14+5da15ca1f4
	   |-- fabric-loot-api-v2 1.1.25+75e98211f4
	   |-- fabric-loot-tables-v1 1.1.29+9e7660c6f4
	   |-- fabric-message-api-v1 5.1.0+1ee8be40f4
	   |-- fabric-mining-level-api-v1 2.1.37+49abcf7ef4
	   |-- fabric-models-v0 0.3.29+11ba9c3bf4
	   |-- fabric-networking-api-v1 1.2.22+ca5f59aaf4
	   |-- fabric-networking-v0 0.3.39+df3654b3f4
	   |-- fabric-object-builder-api-v1 7.0.1+63b515f4f4
	   |-- fabric-particles-v1 1.0.22+f1e4495bf4
	   |-- fabric-recipe-api-v1 1.0.6+a1ccd7bff4
	   |-- fabric-registry-sync-v0 2.1.2+a383ab97f4
	   |-- fabric-renderer-api-v1 2.2.4+81e8c576f4
	   |-- fabric-renderer-indigo 1.1.0+81e8c576f4
	   |-- fabric-renderer-registries-v1 3.2.37+df3654b3f4
	   |-- fabric-rendering-data-attachment-v1 0.3.27+afca2f3ef4
	   |-- fabric-rendering-fluids-v1 3.0.20+f1e4495bf4
	   |-- fabric-rendering-v0 1.1.40+df3654b3f4
	   |-- fabric-rendering-v1 2.1.0+8f878217f4
	   |-- fabric-resource-conditions-api-v1 2.3.0+e6c7d4eef4
	   |-- fabric-resource-loader-v0 0.11.0+938a1d56f4
	   |-- fabric-screen-api-v1 1.0.44+8c25edb4f4
	   |-- fabric-screen-handler-api-v1 1.3.18+5da15ca1f4
	   |-- fabric-sound-api-v1 1.0.8+75e98211f4
	   |-- fabric-transfer-api-v1 3.0.1+9003cbe9f4
	   \-- fabric-transitive-access-wideners-v1 3.0.2+63b515f4f4
	- fabric-language-kotlin 1.9.3+kotlin.1.8.20
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.20
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.0
	- fabricloader 0.14.19
	- fabricskyboxes 0.6.5+mc1.19.4
	- fabrishot 1.9.1
	- farsight 1.19-3.4
	   \-- com_github_jctools_jctools_jctools-core v4.0.1
	- fastquit 2.1.0+1.19.3
	- ferritecore 5.2.0
	- fsb-interop 1.2.0+mc1.19.4-build.31
	- immediatelyfast 1.1.11
	   \-- net_lenni0451_reflect 1.1.0
	- isxander-main-menu-credits 1.1.1
	- java 17
	- lambdynlights 2.3.0+1.19.4
	   |-- pride 1.2.0+1.19.4
	   \-- spruceui 4.2.0+1.19.4
	- languagereload 1.5.5+1.19.4
	- lithium 0.11.1
	- memoryleakfix 1.0.0
	   \-- com_github_llamalad7_mixinextras 0.2.0-beta.6
	- midnightcontrols 1.8.1+1.19.4
	   |-- midnightlib 1.2.1
	   |-- org_aperlambda_lambdajcommon 1.8.1
	   \-- spruceui 4.2.0+1.19.4
	- minecraft 1.19.4
	- mixintrace 1.1.1+1.17
	- modelfix 1.10
	- modmenu 6.1.0-rc.4
	   |-- fabric-api-base 0.4.23+9ff28bcef4
	   |-- fabric-key-binding-api-v1 1.0.32+c477957ef4
	   |-- fabric-lifecycle-events-v1 2.2.14+5da15ca1f4
	   |-- fabric-resource-loader-v0 0.11.0+938a1d56f4
	   \-- fabric-screen-api-v1 1.0.44+8c25edb4f4
	- morechathistory 1.1.1
	- moreculling 1.19.4-0.17.0
	   \-- conditional-mixin 0.3.2
	- nofade 1.18-2.0.1
	- optigui 2.0.0-beta.3
	   |-- optiglue 2.0.0-beta.3-mc.1.19.4
	   \-- org_apache_commons_commons-text 1.10.0
	- puzzle 1.5.0+1.19.4
	   |-- midnightlib 1.2.1
	   |-- puzzle-base 1.5.0+1.19.4
	   |-- puzzle-gui 1.5.0+1.19.4
	   |-- puzzle-models 1.5.0+1.19.4
	   \-- puzzle-splashscreen 1.5.0+1.19.4
	- sodium 0.4.9+build.23
	- starlight 1.1.1+fabric.ae22326
	- yet-another-config-lib 2.3.1
	- yosbr 0.1.1
	- zoomify 2.9.2
	   |-- com_akuleshov7_ktoml-core-jvm 0.3.0
	   |-- dev_isxander_settxi_settxi-core 2.10.6
	   |-- dev_isxander_settxi_settxi-gui 2.10.6
	   |-- dev_isxander_settxi_settxi-kotlinx-serialization 2.10.6
	   \-- settxi-gui-yacl 2.10.6
16:55:51.145
FabricLoader/Mixin
main
SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/HOME/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
16:57:04.079
Sodium
Render thread
OpenGL Version: 3.3.0 - Build 10.18.10.4358
16:57:05.616
FabricLoader
Render thread
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_310 failed
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:464)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_310 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.client.main.Main.main(Main.java:207)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 8 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector overrideWindowTitle(Lnet/minecraft/class_6489;)Ljava/lang/String; in sodium.mixins.json:workarounds.issue1486.MixinMinecraftClient from mod sodium failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap mixins.sodium.refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 11 more
16:57:06.239
launcher
main

16:57:06.239
monitor
Process Monitor
Process crashed with exit code 1

### Additional information

Crash with Sodium version 0.4.9
Pack mod: Fabulously Optimized

**Comment by Toxic-Cookie** [comment]
I literally only have iris, sodium, lithium, and phosphor installed for 1.19.4 and it immediately crashes with exit code 1. Attached my log.
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/11155746/latest.log)

Edit: I somehow managed to get an out of date version thanks to curse being cursed. Get this one to fix it instantly: https://www.curseforge.com/minecraft/mc-mods/sodium/download/4437119

**Comment by pajicadvance** [comment]
You are using Sodium 0.4.9 for MC 1.19.3 in MC 1.19.4. Use a Sodium version for MC 1.19.4 instead.
