### ISSUE TITLE
Game crashes while joining a server/world [Android]

### ISSUE THREAD

**Issue by Enderteck** [jellysquid3/Sodium#1692]
### Version information

Sodium 0.4.9 Release mc1.19.3-0.4.9

### Reproduction Steps

Use Pojav launcher on Android with fabric, fabric api and sodium.
Launch the game and join a world or server
The game will crash at the end of the loading with the error code -1

### Crash Report file

---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 2023-04-11 01:02:35
Description: Unexpected error

java.lang.RuntimeException: Shader compilation failed, see log for details
	at me.jellysquid.mods.sodium.client.gl.shader.GlShader.<init>(GlShader.java:34)
	at me.jellysquid.mods.sodium.client.gl.shader.ShaderLoader.loadShader(ShaderLoader.java:22)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.createShader(ShaderChunkRenderer.java:47)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.compileProgram(ShaderChunkRenderer.java:38)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java:72)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:66)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:289)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:215)
	at net.minecraft.class_761.method_3251(class_761.java:4512)
	at net.minecraft.class_761.method_22710(class_761.java:1246)
	at net.minecraft.class_757.method_3188(class_757.java:1085)
	at net.minecraft.class_757.method_3192(class_757.java:864)
	at net.minecraft.class_310.method_1523(class_310.java:1193)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.gl.shader.GlShader.<init>(GlShader.java:34)
	at me.jellysquid.mods.sodium.client.gl.shader.ShaderLoader.loadShader(ShaderLoader.java:22)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.createShader(ShaderChunkRenderer.java:47)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.compileProgram(ShaderChunkRenderer.java:38)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java:72)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:66)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:289)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:215)
	at net.minecraft.class_761.method_3251(class_761.java:4512)
	at net.minecraft.class_761.method_22710(class_761.java:1246)
	at net.minecraft.class_757.method_3188(class_757.java:1085)

-- Affected level --
Details:
	All players: 64 total; [class_746['Enderteck'/1304712, l='ClientLevel', x=-38.18, y=72.00, z=-0.13], class_745['GoblinGamer72'/1294346, l='ClientLevel', x=-35.10, y=74.27, z=12.95], class_745['maningreen12'/1298892, l='ClientLevel', x=-37.47, y=72.00, z=0.78], class_745['Kaemei'/1300057, l='ClientLevel', x=-43.84, y=72.00, z=7.29], class_745['unafraidosd'/1300629, l='ClientLevel', x=-37.02, y=72.00, z=0.89], class_745['MrMarcozis'/1301512, l='ClientLevel', x=-38.00, y=72.00, z=0.00], class_745['BodakYellowLVM'/1303492, l='ClientLevel', x=-25.21, y=68.82, z=-0.11], class_745['Gqtorade'/1304092, l='ClientLevel', x=-38.20, y=72.00, z=1.07], class_745['Peckalo'/1304102, l='ClientLevel', x=-37.68, y=72.00, z=0.82], class_745['jddabosssdogg1'/1304413, l='ClientLevel', x=-39.31, y=72.00, z=1.26], class_745['Tidal_topher'/1304595, l='ClientLevel', x=-34.70, y=71.00, z=-2.76], class_745['MindWorld'/1304597, l='ClientLevel', x=-35.93, y=72.00, z=3.06], class_745['CharlieChaos13'/1304609, l='ClientLevel', x=-38.34, y=72.00, z=1.39], class_745['Aoki_Ch'/1279760, l='ClientLevel', x=-28.58, y=68.00, z=13.69], class_745['DR_SKELETONI'/1296343, l='ClientLevel', x=-30.41, y=67.00, z=5.29], class_745['GoldenDeer111'/1296440, l='ClientLevel', x=-22.68, y=67.00, z=4.48], class_745['bird_w'/1297557, l='ClientLevel', x=-23.28, y=72.00, z=6.06], class_745['egoz'/1299858, l='ClientLevel', x=-19.50, y=75.72, z=7.97], class_745['Lime_Concrete'/1301537, l='ClientLevel', x=-28.11, y=67.00, z=9.66], class_745['Eclipsegames0'/1300053, l='ClientLevel', x=-55.17, y=30.60, z=25.51], class_745['fruit105'/1289765, l='ClientLevel', x=-38.84, y=72.00, z=-1.25], class_745['3whyehwhy'/1300155, l='ClientLevel', x=-39.31, y=72.00, z=-1.05], class_745['M4r6Pl4yer'/1301400, l='ClientLevel', x=-37.80, y=72.00, z=-0.80], class_745['saekoo_'/1301918, l='ClientLevel', x=-36.94, y=72.00, z=-0.52], class_745['Mrbozz2808'/1302032, l='ClientLevel', x=-41.45, y=72.74, z=-19.60], class_745['_Amillie_'/1303767, l='ClientLevel', x=-36.97, y=72.00, z=-0.94], class_745['SearFlea'/1304599, l='ClientLevel', x=-26.63, y=70.67, z=1.97], class_745['eveam2013'/1281219, l='ClientLevel', x=-26.25, y=67.00, z=-4.28], class_745['Repoman1981'/1303778, l='ClientLevel', x=-20.78, y=68.60, z=-0.20], class_745['b77107fw1j'/61, l='ClientLevel', x=-24.50, y=67.00, z=-5.50], class_745['zBy_'/1292471, l='ClientLevel', x=-12.58, y=67.41, z=-13.84], class_745['AroXYT'/1297251, l='ClientLevel', x=-10.15, y=67.00, z=-2.91], class_745['KamyWamy132'/1297734, l='ClientLevel', x=-10.47, y=67.00, z=-5.97], class_745['Doggqo'/1303994, l='ClientLevel', x=-3.00, y=68.00, z=-8.05], class_745['ta01k1n02t'/10, l='ClientLevel', x=-2.50, y=68.00, z=-4.50], class_745['0q01s33tv7'/12, l='ClientLevel', x=-5.50, y=68.00, z=-12.50], class_745['m4k4o75112'/13, l='ClientLevel', x=-3.50, y=68.00, z=-8.50], class_745['cartermcnz'/1299856, l='ClientLevel', x=-13.84, y=67.00, z=0.45], class_745['Ant0n_'/1303762, l='ClientLevel', x=-12.77, y=67.00, z=0.42], class_745['8k2t7pbf9h'/11, l='ClientLevel', x=-2.50, y=68.00, z=5.50], class_745['nermstyle'/1274493, l='ClientLevel', x=-40.30, y=73.67, z=-33.45], class_745['PigtheBOB'/1291028, l='ClientLevel', x=-34.10, y=72.67, z=-26.69], class_745['BunnyGirlAnna'/1301520, l='ClientLevel', x=-0.80, y=69.14, z=-22.11], class_745['NightShxdow'/1302639, l='ClientLevel', x=13.79, y=86.47, z=0.69], class_745['8n7f2h09m4'/62, l='ClientLevel', x=11.50, y=69.00, z=21.50], class_745['Adhem_badour'/1304714, l='ClientLevel', x=-38.65, y=72.00, z=0.82], class_745['Castl0'/1303506, l='ClientLevel', x=-46.25, y=73.77, z=-39.48], class_745['MewMoDz57'/1303992, l='ClientLevel', x=-44.39, y=75.33, z=-40.46], class_745['ExcaliburRules'/1273800, l='ClientLevel', x=30.26, y=140.19, z=-59.13], class_745['asdlegit'/1302415, l='ClientLevel', x=28.64, y=72.98, z=14.95], class_745['Draza14'/1304719, l='ClientLevel', x=-37.61, y=72.00, z=0.35], class_745['melletjeman'/1288097, l='ClientLevel', x=-24.36, y=86.39, z=-84.52], class_745['z20e3u8476'/1, l='ClientLevel', x=2.00, y=67.00, z=-17.00], class_745['l21h1jf8n8'/2, l='ClientLevel', x=4.50, y=67.00, z=0.50], class_745['2f86i08az7'/3, l='ClientLevel', x=-3.50, y=68.00, z=9.50], class_745['483g10v89t'/5, l='ClientLevel', x=-5.50, y=68.00, z=13.50], class_745['n4j42h38b7'/7, l='ClientLevel', x=-17.50, y=67.00, z=7.50], class_745['74737y635y'/9, l='ClientLevel', x=17.00, y=69.00, z=0.00], class_745['Alihakami7'/1304813, l='ClientLevel', x=-39.15, y=72.00, z=-0.28], class_745['Tamrod'/1304818, l='ClientLevel', x=-39.19, y=72.00, z=0.84], class_745['yuhgranny123'/1304911, l='ClientLevel', x=-37.22, y=72.00, z=-0.65], class_745['BatYT'/1290921, l='ClientLevel', x=-2.53, y=67.90, z=12.06], class_745['AlexOnPc10'/1288958, l='ClientLevel', x=-12.61, y=67.65, z=-3.70], class_745['ajuaneena'/1305012, l='ClientLevel', x=-36.75, y=72.00, z=0.09]]
	Chunk stats: 16384, 169
	Level dimension: minecraft:overworld
	Level spawn location: World: (-39,72,-1), Section: (at 9,8,15 in -3,4,-1; chunk contains blocks -48,0,-16 to -33,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 41135473 game time, 10500 day time
	Server brand: Hypixel BungeeCord (1.3.18) <- vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2390)
	at net.minecraft.class_310.method_1514(class_310.java:805)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Linux (aarch64) version Android-13
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1334428672 bytes (1272 MiB) / 2118123520 bytes (2020 MiB) up to 2118123520 bytes (2020 MiB)
	CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	JVM Flags: 3 total; -Xms2020M -Xmx2020M -Xbootclasspath/a:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
	Launched Version: 1.19.3
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	Window size: 2562x1600
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: fabric
	Current Language: Français (France)
	CPU: <unknown>

### Additional information

Tried the sodium patcher mod and config files found on the Pojav Launcher wiki. Doesn't change anything.
https://pojavlauncherteam.github.io/

**Comment by silversquirl** [comment]
Sodium is explicitly not supported by PojavLauncher, as stated on this page: https://pojavlauncherteam.github.io/MODS-UNSUPPORTED.html

While they provide a patching tool that may work, it's not supported by us and YMMV

**Comment by CowSheep72** [comment]
You use the wrong renderer, use angle(but haven't tested in 1.19.3, but i know 1.19.2 works)
