### ISSUE TITLE
Sodium stuck at loading 25% 

### ISSUE THREAD

**Issue by Glqch404** [jellysquid3/Sodium#1694]
### Version information

sodium-fabric-mc1.19.4-0.4.10+build.24

### Reproduction Steps

I launch minecraft with sodium and it gets stuck at 25% loading and when i leave it for hours it doesnt load and it goes not responding, i know i have an old system but i get to play at 60fps flawlesly and it wasnt an issue for me before, i've seen other issues like mine and jelly said to update my drivers, i have an intel celeron proccessor with cpu n2840 2.16GHz and when i look for driver updates they are up to date, i also tried adding indium but nothing changed, please help me as i prefer to use sodium

### Crash Report file

[17:36:06] [main/INFO]: Loading Minecraft 1.19.4 with Fabric Loader 0.14.19
[17:36:07] [main/INFO]: Loading 8 mods:
	- fabricloader 0.14.19
	- java 17
	- minecraft 1.19.4
	- sodium 0.4.10+build.24
	   |-- fabric-api-base 0.4.23+9ff28bced8
	   |-- fabric-rendering-data-attachment-v1 0.3.27+afca2f3ed8
	   |-- fabric-rendering-fluids-v1 3.0.20+f1e4495bd8
	   \-- fabric-resource-loader-v0 0.10.9+711cde8ad8
[17:36:07] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/midoa/AppData/Roaming/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[17:36:08] [main/INFO]: Compatibility level set to JAVA_16
[17:36:08] [main/INFO]: Compatibility level set to JAVA_17
[17:36:09] [main/INFO]: Loaded configuration file for Sodium: 33 options available, 0 override(s) found
[17:36:57] [Datafixer Bootstrap/INFO]: 180 Datafixer optimizations took 13024 milliseconds
[17:36:57] [main/WARN]: Unrecognized user type: offline
[17:36:59] [Render thread/INFO]: Launching a new process to probe the system configuration!
[17:37:01] [Render thread/INFO]: OpenGL Vendor: Intel
[17:37:01] [Render thread/INFO]: OpenGL Renderer: Intel(R) HD Graphics
[17:37:01] [Render thread/INFO]: OpenGL Version: 3.3.0 - Build 10.18.10.4252
[17:37:03] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:37:06] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-3.18.38.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:156) ~[authlib-3.18.38.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:55) ~[authlib-3.18.38.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:161) ~[authlib-3.18.38.jar:?]
	at net.minecraft.class_310.method_31382(class_310.java:732) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:440) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:198) ~[minecraft-1.19.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.19.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:85) ~[authlib-3.18.38.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-3.18.38.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:129) ~[authlib-3.18.38.jar:?]
	... 11 more
[17:37:07] [Render thread/INFO]: Setting user: Glqch
[17:37:08] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[17:37:24] [Render thread/INFO]: Narrator library for x64 successfully loaded
[17:37:25] [Render thread/INFO]: Reloading ResourceManager: vanilla, Fabric Mods (Fabric API Base, Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Resource Loader (v0), Fabric Loader, Sodium)
[17:37:28] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id

**Comment by joythejoystick1** [comment]
also forgot to mention my intel driver  version is 10.18.10.4252

**Comment by Glqch404** [comment]
i fixed it by updating the driver
