### ISSUE TITLE
Sodium 0.4.11 incompatible with BedrockWaters

### ISSUE THREAD

**Issue by sternschnaube** [jellysquid3/Sodium#1718]
### Version information

sodium-fabric-mc1.19.4-0.4.11+build.26

### Reproduction Steps

Install BedrockWaters: https://modrinth.com/mod/bedrockwaters

### Crash Report file

Unhandled game exception
java.lang.RuntimeException: Mixin transformation of me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.FluidRenderer failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.findClass(MixinServiceKnot.java:96)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.audit(MixinProcessor.java:254)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.audit(MixinTransformer.java:171)
	at org.spongepowered.asm.mixin.MixinEnvironment.audit(MixinEnvironment.java:1425)
	at ca.fxco.memoryleakfix.fabric.MemoryLeakFixFabric.internalForceLoadAllMixinsAndClearSpongePoweredCache(MemoryLeakFixFabric.java:40)
	at ca.fxco.memoryleakfix.fabric.MemoryLeakFixFabric.forceLoadAllMixinsAndClearSpongePoweredCache(MemoryLeakFixFabric.java:32)
	at net.minecraft.class_310.handler$gie000$memoryleakfix$memoryLeakFix$loadAllMixinsClientSide(class_310.java:32000)
	at net.minecraft.class_310.method_1514(class_310.java)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 18 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for bedrockwaters.mixins.sodium.json:MixinFluidRenderer from mod bedrockwaters during activity: [Transform -> Method redirectMul(IFLme/jellysquid/mods/sodium/client/model/quad/ModelQuadView;Lnet/minecraft/class_1920;Lnet/minecraft/class_2338;)I -> INVOKESTATIC -> me/jellysquid/mods/sodium/client/util/color/ColorABGR::unpackRed:(I)I]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 21 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: me.jellysquid.mods.sodium.client.util.color.ColorABGR
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:786)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:772)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:738)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307)
	... 27 more
Caused by: java.lang.ClassNotFoundException: me.jellysquid.mods.sodium.client.util.color.ColorABGR
	... 31 more

### Additional information

Sodium 0.4.10 was working fine with BedrockWaters.

**Comment by 0-x-2-2** [comment]
The mod bedrock waters will need to be updated by the developer to support the latest version of Sodium. It hooks into the sodium internals.

**Comment by sternschnaube** [comment]
Thanks, I moved it to BedrockWaters.
