### ISSUE TITLE
When being in my world, it crashes for no reason

### ISSUE THREAD

**Issue by Ghosted-Alex** [jellysquid3/Sodium#1729]
### Version information

mc1.19.4-0.4.10+build.24

### Reproduction Steps

Just go into a world, after a few seconds, crash

### Crash Report file

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2023-05-04 20:20:40
Description: Unexpected error

java.lang.NoClassDefFoundError: net/caffeinemc/mods/sodium/api/vertex/buffer/VertexBufferWriter
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.diebuddies.physics.DummyMultiBufferSource.lambda$getBuffer$0(DummyMultiBufferSource.java:24)
	at java.base/java.util.Map.computeIfAbsent(Map.java:1054)
	at net.diebuddies.physics.DummyMultiBufferSource.getBuffer(DummyMultiBufferSource.java:24)
	at net.minecraft.class_922.method_4054(class_922.java:138)
	at net.minecraft.class_927.method_4072(class_927.java:45)
	at net.minecraft.class_927.method_3936(class_927.java:18)
	at net.diebuddies.physics.PhysicsMod.blockifyEntity(PhysicsMod.java:732)
	at net.minecraft.class_1309.handler$bgo000$physicsmod$onDeath(class_1309.java:7129)
	at net.minecraft.class_1309.method_6078(class_1309.java)
	at net.minecraft.class_1309.method_5711(class_1309.java:1778)
	at net.minecraft.class_1308.method_5711(class_1308.java:338)
	at net.minecraft.class_634.method_11148(class_634.java:1063)
	at net.minecraft.class_2663.method_11471(class_2663.java:33)
	at net.minecraft.class_2663.method_11054(class_2663.java:11)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1174)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.caffeinemc.mods.sodium.api.vertex.buffer.VertexBufferWriter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 33 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.diebuddies.physics.DummyMultiBufferSource.lambda$getBuffer$0(DummyMultiBufferSource.java:24)
	at java.base/java.util.Map.computeIfAbsent(Map.java:1054)
	at net.diebuddies.physics.DummyMultiBufferSource.getBuffer(DummyMultiBufferSource.java:24)
	at net.minecraft.class_922.method_4054(class_922.java:138)
	at net.minecraft.class_927.method_4072(class_927.java:45)
	at net.minecraft.class_927.method_3936(class_927.java:18)
	at net.diebuddies.physics.PhysicsMod.blockifyEntity(PhysicsMod.java:732)
	at net.minecraft.class_1309.handler$bgo000$physicsmod$onDeath(class_1309.java:7129)
	at net.minecraft.class_1309.method_6078(class_1309.java)
	at net.minecraft.class_1309.method_5711(class_1309.java:1778)
	at net.minecraft.class_1308.method_5711(class_1308.java:338)
	at net.minecraft.class_634.method_11148(class_634.java:1063)
	at net.minecraft.class_2663.method_11471(class_2663.java:33)
	at net.minecraft.class_2663.method_11054(class_2663.java:11)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)

-- Affected level --
Details:
	All players: 1 total; [class_746['Ghosted9558'/183, l='ClientLevel', x=161.62, y=72.00, z=236.57]]
	Chunk stats: 4096, 1021
	Level dimension: minecraft:overworld
	Level spawn location: World: (128,64,144), Section: (at 0,0,0 in 8,4,9; chunk contains blocks 128,-64,144 to 143,319,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 683072 game time, 97095 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:825)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods, file/Better GUI

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 958632800 bytes (914 MiB) / 3288334336 bytes (3136 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.21
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9bc4
	Graphics card #0 versionInfo: DriverVersion=30.0.101.1340
	Graphics card #1 name: NVIDIA GeForce RTX 3060 Laptop GPU
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x2520
	Graphics card #1 versionInfo: DriverVersion=31.0.15.3179
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.93
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.93
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 33580.87
	Virtual memory used (MB): 17887.28
	Swap memory total (MB): 17408.00
	Swap memory used (MB): 108.42
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		ambientsounds: Ambient Sounds (Fabric) 5.2.18
		architectury: Architectury 8.1.79
		cloth-config: Cloth Config v10 10.0.96
			cloth-basic-math: cloth-basic-math 0.6.1
		creativecore: CreativeCore (Fabric) 2.10.7
			net_minecraftforge_eventbus: eventbus 6.0.4
		fabric-api: Fabric API 0.79.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.24+9ff28bcef4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.25+49abcf7ef4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.7+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.6+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.34+c2e6f674f4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.15+1134c5b8f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.27+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.6+e719b857f4
			fabric-commands-v0: Fabric Commands (v0) 0.2.44+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.54+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.9+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.4.1+9a7c5daaf4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.15+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.4.0+6cebf059f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.45+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.13+e45f7c65f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.43+a1ccd7bff4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.52+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.33+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.17+09a3510cf4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.5+043f9acff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.33+c477957ef4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.31+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.15+5da15ca1f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.27+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.31+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.1+1ee8be40f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.39+49abcf7ef4
			fabric-models-v0: Fabric Models (v0) 0.3.30+11ba9c3bf4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.1+a6f3ccfaf4
			fabric-networking-v0: Fabric Networking (v0) 0.3.41+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.3+63b515f4f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.23+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.8+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.0+670e8ac6f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.5+81e8c576f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.1.1+81e8c576f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.38+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.28+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.21+f1e4495bf4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.41+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.1+8f878217f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.1+e6c7d4eef4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.2+1e1fb126f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.45+8c25edb4f4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.20+5da15ca1f4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.9+75e98211f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.1.1+da9bb835f4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.0.3+63b515f4f4
		fabric-language-kotlin: Fabric Language Kotlin 1.9.3+kotlin.1.8.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.0
		fabricloader: Fabric Loader 0.14.19
		healthindicators: PlayerHealthIndicators 1.1.0
		iris: Iris 1.6.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre12
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		libipn: libIPN 2.0.6
		litematica: Litematica 0.14.3
		logical_zoom: Logical Zoom 0.0.19
		malilib: MaLiLib 0.15.3
		minecraft: Minecraft 1.19.4
		modmenu: Mod Menu 6.2.1
		notenoughanimations: NotEnoughAnimations 1.6.3
		physicsmod: Physics Mod 2.12.4
		presencefootsteps: Presence Footsteps 1.8.0
			kirin: Kirin UI 1.14.0
		roughlyenoughitems: Roughly Enough Items 11.0.597
			error_notifier: Error Notifier 1.0.9
		sodium: Sodium 0.4.10+build.24
		sound_physics_remastered: Sound Physics Remastered 1.19.4-1.1.0
		worldedit: WorldEdit 7.2.14+6360-094b734
	Loaded Shaderpack: Complementery Reimagined
		Profile: Custom (+16 options changed by user)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.19-1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 531.79, NVIDIA Corporation
	Window size: 2560x1009
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, file/Better GUI
	Current Language: en_us
	CPU: 16x Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Ghosted9558'/183, l='ServerLevel[Survival]', x=161.62, y=72.00, z=236.57]]
	Data Packs: vanilla, update_1_20, bundle, fabric
	Enabled Feature Flags: minecraft:update_1_20, minecraft:bundle, minecraft:vanilla
	World Generation: Stable

**Comment by Poopooracoocoo** [comment]
Is physics mod up to date? I believe there's Physics Mod 2.12.4b available...

Edit: You'll need an older version of it for it to be compatible with Sodium 0.4.10

**Comment by Ghosted-Alex** [comment]
Let me see

**Comment by Ghosted-Alex** [comment]
I do have 2.12.4b installed
![image](https://user-images.githubusercontent.com/100062083/236690895-39081dbb-edf2-4687-a734-75c69ddd7cc3.png)

**Comment by jellysquid3** [comment]
This isn't an issue with Sodium. Another mod is depending on internals in Sodium, which changed in a recent update. You need to update any other mods installed. And if that doesn't fix it, narrow down specifically which mod is causing the incompatibility with Sodium, and contact the author of that mod for help.
