### ISSUE TITLE
Sodium Crashes on World Creation/Load (With Extra Mods Installed)

### ISSUE THREAD

**Issue by Gatornator** [jellysquid3/Sodium#1757]
### Version information

1.19.4 - Sodium 0.4.10

### Reproduction Steps

Load a world and it crashes

### Crash Report file

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2023-05-12 20:57:35
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5944.method_34583(String, Object)" because "$$2" is null
	at net.minecraft.class_291.method_34431(class_291.java:128)
	at net.minecraft.class_291.method_34427(class_291.java:121)
	at net.minecraft.class_286.method_43438(class_286.java:33)
	at net.minecraft.class_286.method_43433(class_286.java:26)
	at net.coderbot.batchedentityrendering.impl.BufferSegmentRenderer.drawInner(BufferSegmentRenderer.java:24)
	at net.coderbot.batchedentityrendering.impl.FullyBufferedMultiBufferSource.method_22993(FullyBufferedMultiBufferSource.java:141)
	at net.minecraft.class_761.handler$cfa000$iris$batchedentityrendering$beginTranslucents(class_761.java:4458)
	at net.minecraft.class_761.method_22710(class_761.java:1491)
	at net.minecraft.class_757.method_3188(class_757.java:1100)
	at net.minecraft.class_757.redirect$bna000$imm_ptl_core$redirectRenderingWorld(class_757.java:4730)
	at net.minecraft.class_757.method_3192(class_757.java:872)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_291.method_34431(class_291.java:128)
	at net.minecraft.class_291.method_34427(class_291.java:121)
	at net.minecraft.class_286.method_43438(class_286.java:33)
	at net.minecraft.class_286.method_43433(class_286.java:26)
	at net.coderbot.batchedentityrendering.impl.BufferSegmentRenderer.drawInner(BufferSegmentRenderer.java:24)
	at net.coderbot.batchedentityrendering.impl.FullyBufferedMultiBufferSource.method_22993(FullyBufferedMultiBufferSource.java:141)
	at net.minecraft.class_761.handler$cfa000$iris$batchedentityrendering$beginTranslucents(class_761.java:4458)
	at net.minecraft.class_761.method_22710(class_761.java:1491)
	at net.minecraft.class_757.method_3188(class_757.java:1100)
	at net.minecraft.class_757.redirect$bna000$imm_ptl_core$redirectRenderingWorld(class_757.java:4730)

-- Affected level --
Details:
	All players: 1 total; [class_746['Gatornator13'/193, l='ClientWorld minecraft:overworld', x=-9.50, y=69.00, z=56.50]]
	Chunk stats: Client Chunks (ImmPtl) 15
	Level dimension: minecraft:overworld
	Level spawn location: World: (-16,76,64), Section: (at 0,12,0 in -1,4,4; chunk contains blocks -16,-64,64 to -1,319,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 36 game time, 36 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:825)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: No
	Packs: vanilla, Fabric Mods, minecraft/physicsmod, visualoverhaul/rounddiscs, minecraft/supporteatinganimation, Default Connected Textures, Glass Pane Culling Fix, visualoverhaul/nobrewingbottles, file/Better-Leaves-7.2-1.19+.zip, visualoverhaul/fancyfurnace, file/FreshAnimations_v1.8.1.zip, file/Ore+Variants+v2.6.zip, file/xali's+Enchanted+Books+v0.12.0.zip, file/xali's+Potions+v1.0.zip, replaymod_lang
	Recovery: Yes
	Recovery reason: java.util.concurrent.CompletionException: java.lang.RuntimeException: could not reload shaders
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_4014.method_18365(class_4014.java:69)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1174)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: could not reload shaders
	at net.minecraft.class_757.method_34538(class_757.java:559)
	at net.minecraft.class_757$1.method_45777(class_757.java:437)
	at net.minecraft.class_757$1.method_18788(class_757.java:414)
	at net.minecraft.class_4080.method_18790(class_4080.java:13)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	... 12 more
Caused by: net.minecraft.class_2973: Invalid shaders/core/block.json: The validated expression is false
	at net.minecraft.class_2973.method_12856(class_2973.java:48)
	at net.minecraft.class_5944.<init>(class_5944.java:203)
	at net.minecraft.class_757.method_34538(class_757.java:499)
	... 16 more
Caused by: java.lang.IllegalArgumentException: The validated expression is false
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:183)
	at net.minecraft.class_281.handler$bob000$imm_ptl_core$onBeginCompileShaderInternal(class_281.java:540)
	at net.minecraft.class_281.method_34416(class_281.java)
	at net.minecraft.class_281.method_1283(class_281.java:51)
	at net.minecraft.class_5944.method_34579(class_5944.java:242)
	at net.minecraft.class_5944.<init>(class_5944.java:185)
	... 17 more

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1819418584 bytes (1735 MiB) / 4831838208 bytes (4608 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz
	Identifier: Intel64 Family 6 Model 167 Stepping 1
	Microarchitecture: Rocket Lake
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2484
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3179
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 16384.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.20
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 52056.04
	Virtual memory used (MB): 21409.57
	Swap memory total (MB): 3072.00
	Swap memory used (MB): 38.82
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		ambientsounds: Ambient Sounds (Fabric) 5.2.19
		amplified_nether: Amplified Nether 1.2.1a
		appleskin: AppleSkin 2.4.3+mc1.19.4
		bedbenefits: BedBenefits 11.0.1
		betterdeserttemples: YUNG's Better Desert Temples 1.19.4-Fabric-2.4.0
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.19.4-Fabric-3.4.0
		betterf3: BetterF3 6.0.1
		betterfortresses: YUNG's Better Nether Fortresses 1.19.4-Fabric-1.2.0
		bettermineshafts: YUNG's Better Mineshafts 1.19.4-Fabric-3.4.0
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.19.4-Fabric-2.3.0
		betterstrongholds: YUNG's Better Strongholds 1.19.4-Fabric-3.4.0
		betterwitchhuts: YUNG's Better Witch Huts 1.19.4-Fabric-2.3.0
		bookshelf: Bookshelf 18.0.2
		citresewn: CIT Resewn 1.1.3+1.19.4
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.19.4
		cloth-config: Cloth Config v10 10.0.96
			cloth-basic-math: cloth-basic-math 0.6.1
		connectiblechains: Connectible Chains 2.2.0+1.19.4
		continuity: Continuity 3.0.0-beta.2+1.19.3
		creativecore: CreativeCore (Fabric) 2.10.12
			net_minecraftforge_eventbus: eventbus 6.0.4
		cullleaves: Cull Leaves 3.0.3
		debugify: Debugify 1.19.4+2.2
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.6
		detailab: Detail Armor Bar 2.6.3+1.19.4-fabric
		do_a_barrel_roll: Do a Barrel Roll 2.7.3+1.19.4
			cardinal-components-base: Cardinal Components API (base) 5.1.0
			cardinal-components-entity: Cardinal Components API (entities) 5.1.0
			cicada: CICADA 0.4.0
		dropz: Dropz 2.2.0+1.19.4
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		eatinganimationid: Eating Animation 1.9.3
		enchdesc: EnchantmentDescriptions 15.0.1
		entity_model_features: Entity Model Features 0.2.9
		entity_texture_features: Entity Texture Features 4.4.4
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.2-mc1.19.4
		fabric-api: Fabric API 0.80.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.25+504944c8f4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.26+504944c8f4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.8+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.7+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.35+c2e6f674f4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.16+504944c8f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.28+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.7+504944c8f4
			fabric-commands-v0: Fabric Commands (v0) 0.2.45+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.55+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.10+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.4.2+9a7c5daaf4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.16+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.4.1+504944c8f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.46+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.14+504944c8f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.5.0+76ba65ebf4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.53+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.34+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.18+504944c8f4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.6+043f9acff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.34+504944c8f4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.32+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.16+504944c8f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.28+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.32+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.2+504944c8f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.40+49abcf7ef4
			fabric-models-v0: Fabric Models (v0) 0.3.31+504944c8f4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.2+504944c8f4
			fabric-networking-v0: Fabric Networking (v0) 0.3.42+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.4+504944c8f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.24+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.9+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.1+504944c8f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.6+504944c8f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.1.2+81e8c576f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.39+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.29+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.22+504944c8f4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.42+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.2+504944c8f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.2+e6c7d4eef4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.3+1e1fb126f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.46+504944c8f4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.21+504944c8f4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.10+504944c8f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.1.2+504944c8f4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.0.4+504944c8f4
		fabricloader: Fabric Loader 0.14.19
		fallingleaves: Falling Leaves 1.15.0+1.19.4
		firstperson: FirstpersonModel 2.2.3
		handcrafted: Handcrafted 2.2.0
		immersive_portals: Immersive Portals 2.6.9
			imm_ptl_core: Immersive Portals Core 2.6.9
			q_misc_util: QMiscUtil 2.6.9
		invmove: InvMove 0.8.3
		iris: Iris 1.6.3
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		jamlib: JamLib 0.6.0+1.19.4
		java: OpenJDK 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.3.0+1.19.4
			pride: Pride Lib 1.2.0+1.19.4
			spruceui: SpruceUI 4.2.0+1.19.4
		lithium: Lithium 0.11.1
		make_bubbles_pop: Make Bubbles Pop Mod 0.1.1-1.19.4
		midnightlib: MidnightLib 1.3.0
		minecraft: Minecraft 1.19.4
		modmenu: Mod Menu 6.2.2
		notenoughanimations: NotEnoughAnimations 1.6.3
		physicsmod: Physics Mod 2.12.4
		presencefootsteps: Presence Footsteps 1.8.0
			kirin: Kirin UI 1.14.0
		rayon: Rayon 1.7.1+1.19.4
			toolbox: Lazurite Toolbox 1.4.0+1.19.4
			transporter: Transporter 1.4.0+1.19.4
		realisticsleep: Realistic Sleep 1.7.0
		reeses-sodium-options: Reese's Sodium Options 1.5.0+mc1.19.4-build.72
		replaymod: Replay Mod 1.19.4-2.6.12
		resourcefullib: Resourceful Lib 1.3.1
			com_teamresourceful_yabn: yabn 1.0.2
		rightclickharvest: Right Click Harvest 3.1.1+1.19.4
		shulkerboxtooltip: Shulker Box Tooltip 3.2.5+1.19.4
		smoothboot: Smooth Boot 1.19.4-1.7.0
		smoothswapping: Smooth Swapping 0.9
		sodium: Sodium 0.4.10+build.24
		sodium-extra: Sodium Extra 0.4.18+mc1.19.4-build.100
			caffeineconfig: CaffeineConfig 1.1.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		sound_physics_remastered: Sound Physics Remastered 1.19.4-1.1.0
		travelerstitles: Traveler's Titles 1.19.4-Fabric-3.3.0
		visuality: Visuality 0.7.0
		visualoverhaul: VisualOverhaul 5.0.0
		yungsapi: YUNG's API 1.19.4-Fabric-3.10.1
			org_javassist_javassist: javassist 3.29.2-GA
		yungsbridges: YUNG's Bridges 1.19.4-Fabric-3.3.0
	Loaded Shaderpack: rethinking-voxels_beta12.zip (fallback)
		Profile: Custom (+1 option changed by user)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.19-1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3070/PCIe/SSE2 GL version 3.2.0 NVIDIA 531.79, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: en_us
	CPU: 16x 11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Gatornator13'/193, l='ServerWorld minecraft:overworld Minecraft+ Survival', x=-9.50, y=69.00, z=56.50]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable

### Additional information

No clue why this happens. It may be a mod conflict?

**Comment by PumpingThunder** [comment]
Having similar issue, just posted after you. Pray with me :(

**Comment by pajicadvance** [comment]
Start by disabling Immersive Portals and downgrading Physics Mod to 2.12.3 (or v152 for the Pro version). Post the new crash log if it crashes again.
