### ISSUE TITLE
Sodium shows up under the name Our server from the Author ps3wins4ever minecraft also crashes when trying to start

### ISSUE THREAD

**Issue by mrpyrocat** [jellysquid3/Sodium#1848]
### Version information

sodium-fabric-mc1.20-0.4.10+build.27

### Expected Behavior

I expected the game to start

### Actual Behavior

The game did not start and gave me back an error 1
and gave me the crash report:
[13:24:09] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.21
[13:24:09] [ForkJoinPool-1-worker-2/WARN]: Mod sodium uses the version ${version} which isn't compatible with Loader's extended semantic version format (Could not parse version number component '${version}'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[13:24:09] [main/WARN]: Mod resolution failed
[13:24:09] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE sodium-extra 0.4.20+mc1.20-build.103 {depends sodium @ [>=0.4.10]}, ROOT_FORCELOAD_SINGLE sodium-extra 0.4.20+mc1.20-build.103]
[13:24:09] [main/INFO]: Reason: [HARD_DEP sodium-extra 0.4.20+mc1.20-build.103 {depends sodium @ [>=0.4.10]}]
[13:24:09] [main/INFO]: Fix: add [], remove [], replace [[sodium ${version}] -> add:sodium 0.4.10 ([[0.4.10,?)])]
[13:24:09] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Sodium' (sodium) ${version} with version 0.4.10 or later.
Unmet dependency listing:
	 - Mod 'Sodium Extra' (sodium-extra) 0.4.20+mc1.20-build.103 requires version 0.4.10 or later of mod 'Sodium' (sodium), but only the wrong version is present: ${version}!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]

### Reproduction Steps

I Just started the game.

### Java version

Java 1.20.1 fabric 0.14.21

### CPU

AMD Ryzen 7 4700U

### GPU

AMD Radeon graphics

### Additional information

<img width="479" alt="image" src="https://github.com/CaffeineMC/sodium-fabric/assets/112426215/6d903bde-3888-46be-8483-024f0cb5f0a6">
<img width="513" alt="image" src="https://github.com/CaffeineMC/sodium-fabric/assets/112426215/7e6f2850-cadc-4f73-b35e-4bbe09e5aed8">
<img width="594" alt="image" src="https://github.com/CaffeineMC/sodium-fabric/assets/112426215/542e57eb-cbf7-42e0-bcce-474bd13eb630">
Lithium also does not show up when looking in the curseforge app, only when looking in the Files

**Comment by mrpyrocat** [comment]
when trying to run my modpack without Sodium, Sodium Extra and Reeses sodium options, this happens<img width="471" alt="image" src="https://github.com/CaffeineMC/sodium-fabric/assets/112426215/dca9f1e0-c25b-40a5-abbd-f8e5a17f55f9">

**Comment by pajicadvance** [comment]
The problem with the Curseforge app showing our mod as something else is known, and there is nothing we can do about it. The mod should still work as expected, even if the Curseforge app shows it improperly.

Your game is not launching because you have the Sodium `sources` jar next to the regular one. Remove `sodium-fabric-mc1.20-0.4.10+build.27-sources.jar` from the mods folder and it should launch.
