### ISSUE TITLE
Crash when start game

### ISSUE THREAD

**Issue by Makiru-M** [jellysquid3/Sodium#1850]
### Version information

sodium-fabric-mc1.20-0.4.10-build.27

### Reproduction Steps

Start the game and then it`s crashing

### Crash Report file

[02:42:15] [main/INFO]: Loading Minecraft 1.20 with Fabric Loader 0.14.21
[02:42:15] [ForkJoinPool-1-worker-4/WARN]: The mod "carpet-shadow" contains invalid entries in its mod json:
- Invalid entry in person "comment" at line 22 column 16
[02:42:15] [main/WARN]: Warnings were found!
 - Mod 'Debugify' (debugify) 1.20+1.1 recommends any 3.x version of yet-another-config-lib, which is missing!
	 - You should install any 3.x version of yet-another-config-lib for the optimal experience.
 - Mod 'Debugify' (debugify) 1.20+1.1 recommends any version of modmenu, which is missing!
	 - You should install any version of modmenu for the optimal experience.
[02:42:15] [main/INFO]: Loading 128 mods:
	- c2me 0.2.0+alpha.10.88
	   |-- c2me-base 0.2.0+alpha.10.88
	   |-- c2me-client-uncapvd 0.2.0+alpha.10.88
	   |-- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.10.88
	   |-- c2me-fixes-general-threading-issues 0.2.0+alpha.10.88
	   |-- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.10.88
	   |-- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.10.88
	   |-- c2me-notickvd 0.2.0+alpha.10.88
	   |-- c2me-opts-allocs 0.2.0+alpha.10.88
	   |-- c2me-opts-chunk-access 0.2.0+alpha.10.88
	   |-- c2me-opts-chunkio 0.2.0+alpha.10.88
	   |-- c2me-opts-math 0.2.0+alpha.10.88
	   |-- c2me-opts-scheduling 0.2.0+alpha.10.88
	   |-- c2me-opts-worldgen-general 0.2.0+alpha.10.88
	   |-- c2me-opts-worldgen-vanilla 0.2.0+alpha.10.88
	   |-- c2me-rewrites-chunk-serializer 0.2.0+alpha.10.88
	   |-- c2me-rewrites-chunkio 0.2.0+alpha.10.88
	   |-- c2me-server-utils 0.2.0+alpha.10.88
	   |-- c2me-threading-chunkio 0.2.0+alpha.10.88
	   |-- c2me-threading-lighting 0.2.0+alpha.10.88
	   |-- c2me-threading-worldgen 0.2.0+alpha.10.88
	   |-- com_electronwill_night-config_core 3.6.5
	   |-- com_electronwill_night-config_toml 3.6.5
	   |-- com_ibm_async_asyncutil 0.1.0
	   |-- net_objecthunter_exp4j 0.4.8
	   \-- org_threadly_threadly 7.0
	- carpet 1.4.112+v230608
	- carpet-fixes 1.20-1.15.2
	- carpet-shadow 1.10.0-MC1.20+
	- clickthrougharchitectury 1.0.3
	- cloth-config 11.0.99
	   \-- cloth-basic-math 0.6.1
	- debugify 1.20+1.1
	   \-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	- do_a_barrel_roll 3.0.1+1.20
	   \-- cicada 0.4.0
	- enhancedblockentities 0.9+1.20
	   |-- advanced_runtime_resource_pack 0.6.7
	   \-- spruceui 5.0.0+1.20
	- entityculling 1.6.2-mc1.20
	- fabric-api 0.83.0+1.20
	   |-- fabric-api-base 0.4.29+b04edc7a27
	   |-- fabric-api-lookup-api-v1 1.6.34+4d8536c927
	   |-- fabric-biome-api-v1 13.0.10+b3afc78b27
	   |-- fabric-block-api-v1 1.0.9+e022e5d127
	   |-- fabric-blockrenderlayer-v1 1.1.39+b3afc78b27
	   |-- fabric-client-tags-api-v1 1.0.20+b3afc78b27
	   |-- fabric-command-api-v1 1.2.32+f71b366f27
	   |-- fabric-command-api-v2 2.2.11+b3afc78b27
	   |-- fabric-commands-v0 0.2.49+df3654b327
	   |-- fabric-containers-v0 0.1.61+df3654b327
	   |-- fabric-content-registries-v0 4.0.7+b3afc78b27
	   |-- fabric-convention-tags-v1 1.5.3+b3afc78b27
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe27
	   |-- fabric-data-generation-api-v1 12.1.10+b3afc78b27
	   |-- fabric-dimensions-v1 2.1.51+b3afc78b27
	   |-- fabric-entity-events-v1 1.5.21+b3afc78b27
	   |-- fabric-events-interaction-v0 0.6.0+b3afc78b27
	   |-- fabric-events-lifecycle-v0 0.2.61+df3654b327
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a27
	   |-- fabric-item-api-v1 2.1.26+b3afc78b27
	   |-- fabric-item-group-api-v1 4.0.7+b3afc78b27
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da27
	   |-- fabric-keybindings-v0 0.2.34+df3654b327
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b27
	   |-- fabric-loot-api-v2 1.1.37+b3afc78b27
	   |-- fabric-loot-tables-v1 1.1.41+9e7660c627
	   |-- fabric-message-api-v1 5.1.6+b3afc78b27
	   |-- fabric-mining-level-api-v1 2.1.47+b3afc78b27
	   |-- fabric-models-v0 0.3.35+b3afc78b27
	   |-- fabric-networking-api-v1 1.3.8+b3afc78b27
	   |-- fabric-networking-v0 0.3.48+df3654b327
	   |-- fabric-object-builder-api-v1 11.0.6+b3afc78b27
	   |-- fabric-particles-v1 1.0.28+b3afc78b27
	   |-- fabric-recipe-api-v1 1.0.18+b3afc78b27
	   |-- fabric-registry-sync-v0 2.2.6+b3afc78b27
	   |-- fabric-renderer-api-v1 3.0.1+b3afc78b27
	   |-- fabric-renderer-indigo 1.3.1+b3afc78b27
	   |-- fabric-renderer-registries-v1 3.2.44+df3654b327
	   |-- fabric-rendering-data-attachment-v1 0.3.33+b3afc78b27
	   |-- fabric-rendering-fluids-v1 3.0.26+b3afc78b27
	   |-- fabric-rendering-v0 1.1.47+df3654b327
	   |-- fabric-rendering-v1 3.0.6+b3afc78b27
	   |-- fabric-resource-conditions-api-v1 2.3.4+b3afc78b27
	   |-- fabric-resource-loader-v0 0.11.7+f7923f6d27
	   |-- fabric-screen-api-v1 2.0.6+b3afc78b27
	   |-- fabric-screen-handler-api-v1 1.3.27+b3afc78b27
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b27
	   |-- fabric-transfer-api-v1 3.2.2+b3afc78b27
	   \-- fabric-transitive-access-wideners-v1 4.2.0+b3afc78b27
	- fabricloader 0.14.21
	- farsight 1.20.1-3.7
	   \-- org_jctools_jctools-core 4.0.1
	- ferritecore 6.0.0
	- inventorysorter 1.9.0-1.20
	   \-- kyrptconfig 1.5.6-1.20
	- iris 1.6.4
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- itemscroller 0.20.0
	- java 17
	- journeymap 5.9.8
	   \-- journeymap-api-fabric 1.20-1.9-fabric-SNAPSHOT
	- lazydfu 0.1.3
	- litematica 0.15.0
	- lithium 0.11.2
	- logical_zoom 0.0.20
	- malilib 0.16.0
	- memoryleakfix 1.1.1
	- minecraft 1.20
	- moreculling 1.20-0.18.1
	   \-- conditional-mixin 0.3.2
	- reeses-sodium-options 1.5.1+mc1.20-build.74
	- sodium 0.4.10+build.27
	   |-- fabric-api-base 0.4.29+b04edc7a27
	   |-- fabric-rendering-data-attachment-v1 0.3.33+b3afc78b27
	   |-- fabric-rendering-fluids-v1 3.0.26+b3afc78b27
	   \-- fabric-resource-loader-v0 0.11.7+f7923f6d27
	- sodium-extra 0.4.20+mc1.20-build.103
	   |-- caffeineconfig 1.1.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- starlight 1.1.2+fabric.dbc156f
	- voicechat 1.20-2.4.9
	   |-- fabric-api-base 0.4.29+b04edc7a27
	   |-- fabric-command-api-v2 2.2.11+b3afc78b27
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da27
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b27
	   |-- fabric-networking-api-v1 1.3.8+b3afc78b27
	   \-- fabric-resource-loader-v0 0.11.7+f7923f6d27
	- worldedit 7.2.15+6463-5ca4dff
	   |-- fabric-api-base 0.4.29+b04edc7a27
	   |-- fabric-command-api-v2 2.2.11+b3afc78b27
	   |-- fabric-events-interaction-v0 0.6.0+b3afc78b27
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b27
	   \-- fabric-networking-api-v1 1.3.8+b3afc78b27
	- yet_another_config_lib_v3 3.0.2+1.20
	   |-- com_twelvemonkeys_common_common-image 3.9.4
	   |-- com_twelvemonkeys_common_common-io 3.9.4
	   |-- com_twelvemonkeys_common_common-lang 3.9.4
	   |-- com_twelvemonkeys_imageio_imageio-core 3.9.4
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.9.4
	   \-- com_twelvemonkeys_imageio_imageio-webp 3.9.4
[02:42:15] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/RyZen/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[02:42:16] [main/INFO]: Compatibility level set to JAVA_16
[02:42:16] [main/INFO]: Compatibility level set to JAVA_17
[02:42:16] [main/INFO]: Initializing com.ishland.c2me.base.mixin
[02:42:16] [main/INFO]: Initializing com.ishland.c2me.client.uncapvd.mixin
[02:42:16] [main/INFO]: Initializing com.ishland.c2me.fixes.chunkio.threading_issues.mixin
[02:42:16] [main/INFO]: Initializing com.ishland.c2me.fixes.general.threading_issues.mixin
[02:42:16] [main/INFO]: Initializing com.ishland.c2me.fixes.worldgen.threading_issues.mixin
[02:42:16] [main/INFO]: Initializing com.ishland.c2me.fixes.worldgen.vanilla_bugs.mixin
[02:42:16] [main/INFO]: Initializing com.ishland.c2me.notickvd.mixin
[02:42:16] [main/INFO]: Initializing com.ishland.c2me.opts.allocs.mixin
[02:42:16] [main/INFO]: Initializing com.ishland.c2me.opts.chunk_access.mixin
[02:42:16] [main/INFO]: Initializing com.ishland.c2me.opts.chunkio.mixin
[02:42:16] [main/INFO]: Initializing com.ishland.c2me.opts.math.mixin
[02:42:16] [main/INFO]: Initializing com.ishland.c2me.opts.scheduling.mixin
[02:42:16] [main/INFO]: Initializing com.ishland.c2me.opts.worldgen.general.mixin
[02:42:16] [main/INFO]: Initializing com.ishland.c2me.opts.worldgen.vanilla.mixin
[02:42:16] [main/INFO]: Initializing com.ishland.c2me.rewrites.chunk_serializer.mixin
[02:42:16] [main/INFO]: Disabling com.ishland.c2me.rewrites.chunk_serializer.mixin
[02:42:16] [main/INFO]: Initializing com.ishland.c2me.rewrites.chunkio.mixin
[02:42:16] [main/INFO]: Initializing com.ishland.c2me.server.utils.mixin
[02:42:16] [main/INFO]: Initializing com.ishland.c2me.threading.chunkio.mixin
[02:42:16] [main/INFO]: Initializing com.ishland.c2me.threading.lighting.mixin
[02:42:16] [main/INFO]: Initializing com.ishland.c2me.threading.worldgen.mixin
[02:42:16] [main/INFO]: Preloading Debugify
[02:42:16] [main/INFO]: Loaded configuration file for Lithium: 115 options available, 3 override(s) found
[02:42:16] [main/INFO]: Loaded configuration file for Sodium: 33 options available, 3 override(s) found
[02:42:16] [main/INFO]: Loaded configuration file for Sodium Extra: 28 options available, 0 override(s) found
[02:42:16] [main/WARN]: Error loading class: net/caffeinemc/sodium/config/user/UserConfigCategories (java.lang.ClassNotFoundException: net/caffeinemc/sodium/config/user/UserConfigCategories)
[02:42:17] [main/WARN]: Force disabled MC-135971 because it's conflicting with: carpet
[02:42:17] [main/WARN]: Force disabled MC-121772 because it only applies to OS: MAC
[02:42:17] [main/WARN]: Force disabled MC-122477 because it only applies to OS: LINUX
[02:42:17] [main/WARN]: Force disabled MC-22882 because it only applies to OS: MAC
[02:42:17] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[02:42:17] [main/WARN]: Force-enabling mixin 'block.hopper.worldedit_compat.WorldChunkMixin' as rule 'mixin.block.hopper.worldedit_compat' (added by mods [lithium-fabric]) enables it
[02:42:17] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [c2me]) disables it and children
[02:42:17] [main/WARN]: Force-disabling mixin 'features.entity.fast_render.MixinCuboid' as rule 'mixin.features.entity.fast_render' (added by mods [iris]) disables it and children
[02:42:17] [main/WARN]: Force-disabling mixin 'features.entity.fast_render.MixinModelPart' as rule 'mixin.features.entity.fast_render' (added by mods [iris]) disables it and children
[02:42:17] [main/WARN]: Force-disabling mixin 'features.gui.font.MixinGlyphRenderer' as rule 'mixin.features.gui.font' (added by mods [iris]) disables it and children
[02:42:17] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[02:42:17] [main/WARN]: [carpet] detected, disabling UPDATE mixin com.sk89q.worldedit.fabric.mixin.MixinLevelChunkSetBlockHook
[02:42:17] [main/INFO]: [MemoryLeakFix] Will be applying 3 memory leak fixes!
[02:42:17] [main/INFO]: [MemoryLeakFix] Currently enabled memory leak fixes: [targetEntityLeak, biomeTemperatureLeak, hugeScreenshotLeak]
[02:42:17] [main/WARN]: Error loading class: net/caffeinemc/sodium/config/user/UserConfigCategories (java.lang.ClassNotFoundException: net/caffeinemc/sodium/config/user/UserConfigCategories)
[02:42:17] [main/WARN]: Error loading class: net/caffeinemc/sodium/config/user/UserConfigCategories (java.lang.ClassNotFoundException: net/caffeinemc/sodium/config/user/UserConfigCategories)
[02:42:17] [main/WARN]: Error loading class: org/jetbrains/annotations/ApiStatus$Internal (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$Internal)
[02:42:17] [main/INFO]: I used the json to destroy the json
[02:42:19] [main/WARN]: Failed to add PDH Counter: \Paging File(_Total)\% Usage, Error code: 0xC0000BB8
[02:42:19] [main/WARN]: Failed to add counter for PDH counter: \Paging File(_Total)\% Usage
[02:42:19] [main/WARN]: Disabling further attempts to query Paging File.
[02:42:20] [main/WARN]: COM exception: Invalid Query: SELECT PERCENTUSAGE FROM Win32_PerfRawData_PerfOS_PagingFile
[02:42:20] [main/WARN]: Method overwrite conflict for getLanguage in worldedit-fabric.mixins.json:MixinServerPlayer from mod worldedit, previously written by carpet.mixins.ServerPlayer_scarpetEventMixin. Skipping method.
[02:42:20] [main/WARN]: Method overwrite conflict for method_5800 in carpet-fixes.mixins.json:itemFixes.ItemEntity_lightningKillsDropsMixin from mod carpet-fixes, previously written by carpet.mixins.ItemEntityMixin. Skipping method.
[02:42:21] [main/WARN]: @Redirect conflict. Skipping debugify.mixins.json:basic.mc160095.CactusBlockMixin from mod debugify->@Redirect::replaceBlockState(Lnet/minecraft/class_4538;Lnet/minecraft/class_2338;)Lnet/minecraft/class_2680; with priority 1000, already redirected by carpet-fixes.mixins.json:blockFixes.CactusBlock_movingBlockMixin from mod carpet-fixes->@Redirect::getCorrectBlockStateIfMovingPiston(Lnet/minecraft/class_4538;Lnet/minecraft/class_2338;)Lnet/minecraft/class_2680; with priority 1000
[02:42:21] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2266 failed
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2266 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:166) ~[Optimased%201.20.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:166) ~[Optimased%201.20.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector replaceBlockState(Lnet/minecraft/class_4538;Lnet/minecraft/class_2338;)Lnet/minecraft/class_2680; in debugify.mixins.json:basic.mc160095.CactusBlockMixin from mod debugify failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap Debugify-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:166) ~[Optimased%201.20.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	... 2 more

**Comment by pajicadvance** [comment]
The mod "Debugify" is conflicting with some other mod. This has nothing to do with Sodium.
