### ISSUE TITLE
game crash upon opening a world

### ISSUE THREAD

**Issue by xzTWINzx** [jellysquid3/Sodium#1867]
### Version information

sodium-fabric-mc1.19.4-0.4.10+build.24

### Reproduction Steps

-Open the game.
-Open any world.

### Crash Report file

Description: Unexpected error

java.lang.NoClassDefFoundError: net/caffeinemc/mods/sodium/api/vertex/buffer/VertexBufferWriter
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_631.chunkPosChanged(class_631.java:1627)
	at net.minecraft.class_757.handler$dcg000$physicsmod$render(class_757.java:7211)
	at net.minecraft.class_757.method_3192(class_757.java)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.caffeinemc.mods.sodium.api.vertex.buffer.VertexBufferWriter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 17 more

### Additional information

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_631.chunkPosChanged(class_631.java:1627)
	at net.minecraft.class_757.handler$dcg000$physicsmod$render(class_757.java:7211)

-- Affected level --
Details:
	All players: 1 total; [class_746['xzTWINzx'/1, l='ClientLevel', x=4.50, y=65.00, z=47.50]]
	Chunk stats: 1024, 105
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,65,48), Section: (at 0,1,0 in 0,4,3; chunk contains blocks 0,-64,48 to 15,319,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 226 game time, 226 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:825)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, minecraft:supporteatinganimation, minecraft:physicsmod, file/FreshAnimations_v1.7_Add_S10.zip, file/FreshAnimations_v1.7_S10.zip, essential

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 816354112 bytes (778 MiB) / 2948595712 bytes (2812 MiB) up to 8422162432 bytes (8032 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 4.01
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1b81
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3141
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 23224.84
	Virtual memory used (MB): 16606.21
	Swap memory total (MB): 6912.00
	Swap memory used (MB): 146.35
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8032m -Xms256m
	Fabric Mods: 
		advancementinfo: AdvancementInfo 1.19.4-fabric0.76.0-1.3.1
		ambientsounds: Ambient Sounds (Fabric) 5.2.19
		animatica: Animatica 0.6+1.20
		architectury: Architectury 8.1.87
		bookshelf: Bookshelf 18.0.6
		borderlessmining: Borderless Mining 1.1.7+1.19.4
		cem: Custom Entity Models 0.7.3_S10_1.19.4
			completeconfig-base: completeconfig-base 2.3.1
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.3.1
		cloth-config: Cloth Config v10 10.0.96
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 10.0.0.4
		controlling: Controlling For Fabric 11.1.5
		creativecore: CreativeCore (Fabric) 2.10.12
			net_minecraftforge_eventbus: eventbus 6.0.4
		dashloader: DashLoader 5.0.0-beta.1+1.19.4
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_notalpha_taski: Taski 2.1.0
			dev_quantumfusion_hyphen: Hyphen 0.4.0-rc.3
		eatinganimationid: Eating Animation 1.9.3
		elementa: Elementa 590
		enchdesc: EnchantmentDescriptions 15.0.3
		entity_texture_features: Entity Texture Features 4.4.4
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.2-mc1.19.4
		essential: Essential 12933+deploy-staging+gf941de5ac
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.0.0
		exordium: Exordium 1.1.2-mc1.19.4
		fabric-api: Fabric API 0.84.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.27+1e9487d2f4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.28+504944c8f4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.9+10ce000ff4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.8+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.37+10ce000ff4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.18+10ce000ff4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.30+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.9+10ce000ff4
			fabric-commands-v0: Fabric Commands (v0) 0.2.47+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.57+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.12+10ce000ff4
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.2+10ce000ff4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.17+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.4.3+10ce000ff4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.48+10ce000ff4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.16+10ce000ff4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+10ce000ff4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.55+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.35+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.20+10ce000ff4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.8+10ce000ff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.35+504944c8f4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.33+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.18+10ce000ff4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.30+10ce000ff4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.34+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.4+10ce000ff4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.42+10ce000ff4
			fabric-models-v0: Fabric Models (v0) 0.3.33+10ce000ff4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.4+10ce000ff4
			fabric-networking-v0: Fabric Networking (v0) 0.3.44+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.6+10ce000ff4
			fabric-particles-v1: Fabric Particles (v1) 1.0.26+10ce000ff4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.11+10ce000ff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.3+10ce000ff4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.4.0+c6bbc80df4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.0+c6bbc80df4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.41+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.31+10ce000ff4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.24+10ce000ff4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.44+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.4+10ce000ff4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.3+10ce000ff4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.5+5ade3c38f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.48+10ce000ff4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.23+10ce000ff4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.11+10ce000ff4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.1+10ce000ff4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.2.0+10ce000ff4
		fabric-language-kotlin: Fabric Language Kotlin 1.8.2+kotlin.1.7.10
		fabricloader: Fabric Loader 0.14.21
		fallingleaves: Falling Leaves 1.15.1+1.20.1
		faster_entity_animations: FastAnim 1.6
		fastload: Fast Load 3.3.7
			conditional-mixin: conditional mixin 0.3.2
			fastload-119-0-1-2-compat: Fastload 1.19-0-1-2 Compatibility 3.3.7
			fastload-1193-compat: Fastload 1.19.3 Compatibility 3.3.7
			fastload-1194-compat: Fastload 1.19.4 Compat 3.3.7
			fastload_fapi_forward: Fastload Fabric-api Forwarding 1.0.1
		fastquit: FastQuit 2.1.0+1.19.3
		ferritecore: FerriteCore 5.2.0
		forgeconfigapiport: Forge Config API Port 6.0.2
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		immediatelyfast: ImmediatelyFast 1.1.15+1.19.4
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
			net_lenni0451_reflect: Reflect 1.1.0
		immersivemc: ImmersiveMC 1.3.3
		indium: Indium 1.0.18+mc1.19.4
		iris: Iris 1.6.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre12
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		jeed: Just Enough Effects Descriptions 1.19.4-2.1.4
		krypton: Krypton 0.2.2
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		languagereload: Language Reload 1.5.8+1.19.4
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.11.1
		memoryleakfix: Memory Leak Fix 1.0.0
		minecraft: Minecraft 1.19.4
		modelfix: Model Gap Fix 1.10
		modmenu: Mod Menu 6.2.3
		moreculling: More Culling 1.19.4-0.17.0
		org_jetbrains_annotations: annotations 13.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
		org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.2
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
		org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		perfectaccuracy: Perfect Accuracy 1.2-1.19
		physicsmod: Physics Mod 2.12.4
		presencefootsteps: Presence Footsteps 1.8.0
			kirin: Kirin UI 1.14.0
		reeses-sodium-options: Reese's Sodium Options 1.5.0+mc1.19.4-build.72
		searchables: Searchables 1.0.3
		snowundertrees: Snow Under Trees 1.1.0+1.19.4
			owo: oωo 0.10.3+1.19.4
				blue_endless_jankson: jankson 1.2.2
		sodium: Sodium 0.4.10+build.24
		sodium-extra: Sodium Extra 0.4.18+mc1.19.4-build.100
			caffeineconfig: CaffeineConfig 1.1.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		sound_physics_remastered: Sound Physics Remastered 1.19.4-1.1.1
		starlight: Starlight 1.1.1+fabric.ae22326
		travelerstitles: Traveler's Titles 1.19.4-Fabric-3.3.0
			org_reflections_reflections: reflections 0.10.2
		universalcraft: UniversalCraft 277
		vigilance: Vigilance 284
		vivecraft: Vivecraft 1.19.4-0.0.15
		yigd: You're in Grave Danger 1.6.0
		yungsapi: YUNG's API 1.19.4-Fabric-3.10.1
			org_javassist_javassist: javassist 3.29.2-GA
	Loaded Shaderpack: ComplementaryShaders_v4.7.1.zip
		Profile: Custom (+47 options changed by user)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.21-1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1070/PCIe/SSE2 GL version 3.2.0 NVIDIA 531.41, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, minecraft:supporteatinganimation, minecraft:physicsmod (incompatible), file/FreshAnimations_v1.7_Add_S10.zip (incompatible), file/FreshAnimations_v1.7_S10.zip (incompatible)
	Current Language: ru_ru
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['xzTWINzx'/1, l='ServerLevel[Новый мир]', x=4.50, y=65.00, z=47.50]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	
	My guess is that one of my mods I installed has caused the issue with sodium

**Comment by xzTWINzx** [comment]
i fix this. just change physics mod version from 153b to 152 (1.19.4). thx for all
