### ISSUE TITLE
[Fabric 1.20.1][CRASH] java.lang.NullPointerException

### ISSUE THREAD

**Issue by LokeYourC3PH** [jellysquid3/Sodium#1909]
### Bug Description

This issue occurs at random after having updated some mods recently, but it occurs mostly within my base in which there are many things that need to get rendered. The client crashes immediately to desktop (CTD) upon encountering something it has an issue with rendering.

### Reproduction Steps

This might be difficult to reproduce honestly, as I cannot tell what exactly/which block exactly is causing this.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12141872/latest.log)

### Crash Report

[crash-2023-07-24_13.50.56-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12141871/crash-2023-07-24_13.50.56-client.txt)

**Comment by hexadecimal233** [comment]
It seems it was caused by immersive portals, try removing the mod and see if the game continues to crash

**Comment by LokeYourC3PH** [comment]
As this is on a server, there's no way I can remove it, as I otherwise can't join to test this.

**Comment by hexadecimal233** [comment]
This is related to sign rendering, maybe placing a sign and see if the game crashes

and more possible mods here: enhancedblockentities, iris, supplementaries, moreculling

**Comment by LokeYourC3PH** [comment]
Alright, I will check those out in a local world and see if any of these cause it and report back to you, thank you :)

**Comment by LokeYourC3PH** [comment]
> This is related to sign rendering, maybe placing a sign and see if the game crashes
> 
> and more possible mods here: enhancedblockentities, iris, supplementaries, moreculling

Well so, it seems to be none of it. I placed a Globe from Supplementaries (which I have in my Multiplayer base), doesn't crash. I placed a sign and a Hazard Diamond Sign (as I figured it might be related), also nothing. I created an Immersive Portals portal, also nothing.

**Comment by zacky24685** [comment]
I encountered the same problem and solved it by removing enhancedblockentities.

**Comment by LokeYourC3PH** [comment]
> I encountered the same problem and solved it by removing enhancedblockentities.

Oh really? Let me try it myself later, thanks a lot for the tip!

**Comment by LokeYourC3PH** [comment]
> I encountered the same problem and solved it by removing enhancedblockentities.

Update: Nope, that wasn't it unfortunately. I disabled the mod, but the exact same issue seems to occur. I had an issue before that with "MoreCulling" caused by Indium, so I will try disabling that one now.

Update on my update: Nope, also not. Guess I gotta keep trying to disable as many client side optimization mods as I can without running into it. Bothersome...

**Comment by FlashyReese** [comment]
Aftering mapping the crashlog
```
---- Minecraft Crash Report ----
// You're mean.

Time: 2023-07-24 13:50:56
Description: Rendering Block Entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.client.util.SpriteIdentifier.getVertexConsumer(net.minecraft.client.render.VertexConsumerProvider, java.util.function.Function)" because "$$7" is null
	at net.minecraft.client.render.block.entity.SignBlockEntityRenderer.renderSign(SignBlockEntityRenderer.java:101)
	at net.minecraft.client.render.block.entity.SignBlockEntityRenderer.mixinextras$bridge$0$renderSign(SignBlockEntityRenderer.java)
	at net.minecraft.client.render.block.entity.SignBlockEntityRenderer.wrapOperation$kip000$terraform-wood-api-v1$setRenderedBlockEntity(SignBlockEntityRenderer.java:2035)
	at net.minecraft.client.render.block.entity.SignBlockEntityRenderer.render(SignBlockEntityRenderer.java:81)
	at net.minecraft.client.render.block.entity.SignBlockEntityRenderer.render(SignBlockEntityRenderer.java:66)
	at net.minecraft.client.render.block.entity.SignBlockEntityRenderer.render(SignBlockEntityRenderer.java:41)
	at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.render(BlockEntityRenderDispatcher.java:90)
	at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.method_23081(BlockEntityRenderDispatcher.java:79)
	at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.runReported(BlockEntityRenderDispatcher.java:104)
	at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.render(BlockEntityRenderDispatcher.java:79)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:275)
	at net.minecraft.client.render.WorldRenderer.handler$jom000$sodium$onRenderTileEntities(WorldRenderer.java:25367)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer.java:1372)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer.java:1110)
	at net.minecraft.client.render.GameRenderer.redirect$ekf000$imm_ptl_core$redirectRenderingWorld(GameRenderer.java:8242)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:880)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1219)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```
	
There are multiple points it could be, I suspect it could be one of TerraformersMC mods according to `at net.minecraft.client.render.block.entity.SignBlockEntityRenderer.wrapOperation$kip000$terraform-wood-api-v1$setRenderedBlockEntity(SignBlockEntityRenderer.java:2035)`

**Comment by LokeYourC3PH** [comment]
> Aftering mapping the crashlog
> 
> ```
> ---- Minecraft Crash Report ----
> // You're mean.
> 
> Time: 2023-07-24 13:50:56
> Description: Rendering Block Entity
> 
> java.lang.NullPointerException: Cannot invoke "net.minecraft.client.util.SpriteIdentifier.getVertexConsumer(net.minecraft.client.render.VertexConsumerProvider, java.util.function.Function)" because "$$7" is null
> 	at net.minecraft.client.render.block.entity.SignBlockEntityRenderer.renderSign(SignBlockEntityRenderer.java:101)
> 	at net.minecraft.client.render.block.entity.SignBlockEntityRenderer.mixinextras$bridge$0$renderSign(SignBlockEntityRenderer.java)
> 	at net.minecraft.client.render.block.entity.SignBlockEntityRenderer.wrapOperation$kip000$terraform-wood-api-v1$setRenderedBlockEntity(SignBlockEntityRenderer.java:2035)
> 	at net.minecraft.client.render.block.entity.SignBlockEntityRenderer.render(SignBlockEntityRenderer.java:81)
> 	at net.minecraft.client.render.block.entity.SignBlockEntityRenderer.render(SignBlockEntityRenderer.java:66)
> 	at net.minecraft.client.render.block.entity.SignBlockEntityRenderer.render(SignBlockEntityRenderer.java:41)
> 	at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.render(BlockEntityRenderDispatcher.java:90)
> 	at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.method_23081(BlockEntityRenderDispatcher.java:79)
> 	at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.runReported(BlockEntityRenderDispatcher.java:104)
> 	at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.render(BlockEntityRenderDispatcher.java:79)
> 	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:275)
> 	at net.minecraft.client.render.WorldRenderer.handler$jom000$sodium$onRenderTileEntities(WorldRenderer.java:25367)
> 	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer.java:1372)
> 	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer.java:1110)
> 	at net.minecraft.client.render.GameRenderer.redirect$ekf000$imm_ptl_core$redirectRenderingWorld(GameRenderer.java:8242)
> 	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:880)
> 	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1219)
> 	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802)
> 	at net.minecraft.client.main.Main.main(Main.java:250)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> ```
> 
> There are multiple points it could be, I suspect it could be one of TerraformersMC mods according to `at net.minecraft.client.render.block.entity.SignBlockEntityRenderer.wrapOperation$kip000$terraform-wood-api-v1$setRenderedBlockEntity(SignBlockEntityRenderer.java:2035)`

If that really is the case, it would be Cinderscapes (the only mod I have from them which adds blocks). That is odd however, as I do not recall any Cinderscapes block in my base. Besides, when I am in the Nether, surrounded by Cinderscapes blocks, I do not crash at all either.

EDIT: It also mentioned "renderSign", so I placed all signs (4) from Cinderscapes, but it does not cause the crash.

**Comment by LokeYourC3PH** [comment]
I have an update on this: Same crash, but slightly different output. It seems to be caused by some sort of TileEntity in particular? But I can't tell which one:

```
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_4730.method_24145(net.minecraft.class_4597, java.util.function.Function)" because "$$7" is null
	at net.minecraft.class_837.method_45800(class_837.java:101)
	at net.minecraft.class_837.mixinextras$bridge$0$method_45800(class_837.java)
	at net.minecraft.class_837.wrapOperation$klc000$terraform-wood-api-v1$setRenderedBlockEntity(class_837.java:2035)
	at net.minecraft.class_837.method_49920(class_837.java:81)
	at net.minecraft.class_837.method_23083(class_837.java:66)
	at net.minecraft.class_837.method_3569(class_837.java:41)
	at net.minecraft.class_824.method_23079(class_824.java:90)
	at net.minecraft.class_824.method_23081(class_824.java:79)
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_3555(class_824.java:79)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:275)
	at net.minecraft.class_761.handler$kam000$sodium$onRenderTileEntities(class_761.java:25867)
	at net.minecraft.class_761.method_22710(class_761.java:1372)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.redirect$emb000$imm_ptl_core$redirectRenderingWorld(class_757.java:8242)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

EDIT:
After lots of consideration, I think I have an idea which block it could be. I think it's [Entangled](https://modrinth.com/mod/entangled), which is the only thing in that corner that I could think of that might cause this. I use Entangled blocks all around the server, other people do as well, but in my base in particular in that corner, is only an [AE2 Storage System](https://modrinth.com/mod/ae2) with some import/export bus', a couple of [Ender Chests (those that can be coloured & privatized)](https://modrinth.com/mod/linked-storage), a [Tesseract](https://modrinth.com/mod/tesseract), and the Entangled blocks linked to several blocks around the area. And if I am right, then that would be catastrophic because removing it would break a lot on the server. I will take a backup of the map, and remove the mod, and then see what happens. If it stops crashing, I will report back here.

**Comment by LokeYourC3PH** [comment]
Update: It was the Entangled mod. Coincidentally, the developer had pushed an update to his mod for, in case, where an Entangled block causes a crash, it will instead not crash but output a warning. It didn't output a warning, but after updating the mod, the issue disappeared, which thus concludes this issue tracker.
