### ISSUE TITLE
Sodium crashes when I try loading into my world

### ISSUE THREAD

**Issue by W0lfve** [jellysquid3/Sodium#1985]
### Bug Description

I've been trying to install Sodium and Iris so I can play with shaders, all of my mods are up to date yet it repeatedly fails and I don't know why. These are the mods I use; 
![image](https://github.com/CaffeineMC/sodium-fabric/assets/44285510/49aa28c7-7a95-4948-9041-e9a08e0ec655)

### Reproduction Steps

1: Installed Sodium, Iris and Indium, all fabric
2: Loaded up Minecraft
3: Selected world
4: World says it's loading, then says saving and the game crashes.

### Log File

[2023-08-12-2.log.gz](https://github.com/CaffeineMC/sodium-fabric/files/12326043/2023-08-12-2.log.gz)

### Crash Report

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2023-08-12 01:23:58
Description: Unexpected error

java.lang.NoSuchMethodError: 'void me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.onChunkAdded(int, int)'
	at de.johni0702.minecraft.bobby.sodium.SodiumChunkStatusListenerImpl.onChunkAdded(SodiumChunkStatusListenerImpl.java:10)
	at net.minecraft.class_631.bobby_onFakeChunkAdded(class_631.java:2022)
	at net.minecraft.class_631.handler$zdo000$bobby$bobbyPostLoadRealChunk(class_631.java:597)
	at net.minecraft.class_631.method_16020(class_631.java:123)
	at net.minecraft.class_634.method_38539(class_634.java:773)
	at net.minecraft.class_634.method_11128(class_634.java:738)
	at net.minecraft.class_2672.method_11528(class_2672.java:45)
	at net.minecraft.class_2672.method_11054(class_2672.java:12)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1175)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at de.johni0702.minecraft.bobby.sodium.SodiumChunkStatusListenerImpl.onChunkAdded(SodiumChunkStatusListenerImpl.java:10)
	at net.minecraft.class_631.bobby_onFakeChunkAdded(class_631.java:2022)
	at net.minecraft.class_631.handler$zdo000$bobby$bobbyPostLoadRealChunk(class_631.java:597)
	at net.minecraft.class_631.method_16020(class_631.java:123)
	at net.minecraft.class_634.method_38539(class_634.java:773)
	at net.minecraft.class_634.method_11128(class_634.java:738)
	at net.minecraft.class_2672.method_11528(class_2672.java:45)
	at net.minecraft.class_2672.method_11054(class_2672.java:12)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)

-- Affected level --
Details:
	All players: 1 total; [class_746['W0lfve'/86, l='ClientLevel', x=0.83, y=-60.00, z=-15.70]]
	Chunk stats: 4096, 1
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 10313 game time, 10313 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, Supplementaries Generated Pack, file/Wolf's Adventure.zip, file/Vanilla Tweaks.zip, file/Wisteria Berries, file/Better Birch.zip, file/Better Apples - Sr Paulo.zip, file/Beds Reimagined.zip, file/Better Diamonds, file/Better Grass.zip, file/Better shears - Sr Paulo.zip, file/Better+Leaves+Add-on+V3.0-1.20.zip, file/Coloured Subtitles.zip, file/Golden Crown.zip, file/Crops n' Meats.zip, file/Magical biomes Ocean.zip, file/Lush Desert, minecraft:supporteatinganimation, file/Xali's Potions.zip, file/Xali's Enhanced Biomes.zip, file/Shield Corrections.zip, file/Softer Stones.zip, file/Star Orbs.zip, file/Totem of Undying - Botw Fairy.zip, file/Visible Glint.zip, file/Dynamic Surroundings Sounds Pack.zip, file/Trident of Poseidon, essential

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 956662824 bytes (912 MiB) / 3183476736 bytes (3036 MiB) up to 6845104128 bytes (6528 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3800X 8-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.90
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce GTX 1660
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2184
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3640
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 30155.49
	Virtual memory used (MB): 27125.39
	Swap memory total (MB): 13844.96
	Swap memory used (MB): 1056.42
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6528m -Xms256m
	Fabric Mods: 
		adorn: Adorn 5.0.0+1.20.1
		architectury: Architectury 9.1.12
		autofish: Autofish 1.0.0
		badpackets: Bad Packets 0.4.1
		bobby: Bobby 5.0.0
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		eatinganimationid: Eating Animation 1.9.4+1.20
		elementa: Elementa 590
		essential: Essential 13437+deploy-staging+gd2fc09762
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.0
		fabric-api: Fabric API 0.86.1+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.62+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.1+1e61dba177
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.52+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.9+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.49+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.19+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.1+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.1+9386d8a777
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.1+9172968c77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.34+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.28+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.8+kotlin.1.9.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.21.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.2
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.22
		fallingtree: FallingTree 4.3.0
		farmersdelight: Farmer's Delight 1.20.1-1.4.1
		farmersknives: Farmer's Knives 3.0.2
		fdjei: Just Enough Farmer's Recipes 1.0.1
		forgeconfigapiport: Forge Config API Port 8.0.0
		freecam: Freecam 1.2.1+1.20
		indium: Indium 1.0.23+mc1.20.1
		iris: Iris 1.6.5
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.2.0.25
		libipn: libIPN 3.0.2
		malilib: MaLiLib 0.16.1
		minecraft: Minecraft 1.20.1
		modmenu: Mod Menu 7.2.1
		moonlight: Moonlight 1.20-2.7.4
		notenoughanimations: NotEnoughAnimations 1.6.4
		org_jetbrains_annotations: annotations 13.0
		prism: Prism 1.0.5
		roughlyenoughitems: Roughly Enough Items 12.0.645
			error_notifier: Error Notifier 1.0.9
		sodium: Sodium 0.5.0
		supplementaries: Supplementaries 1.20-2.5.21
		universalcraft: UniversalCraft 277
		vigilance: Vigilance 284
		visuality: Visuality 0.7.0+1.20
		wthit: wthit 8.3.1
		xaerominimap: Xaero's Minimap 23.6.1
		xaeroworldmap: Xaero's World Map 1.32.0
	Loaded Shaderpack: ComplementaryReimagined_r2.3.zip
		Profile: HIGH (+0 options changed by user)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.22-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1660/PCIe/SSE2 GL version 3.2.0 NVIDIA 536.40, NVIDIA Corporation
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, Supplementaries Generated Pack, file/Wolf's Adventure.zip (incompatible), file/Vanilla Tweaks.zip, file/Wisteria Berries (incompatible), file/Better Birch.zip (incompatible), file/Better Apples - Sr Paulo.zip (incompatible), file/Beds Reimagined.zip (incompatible), file/Better Diamonds (incompatible), file/Better Grass.zip (incompatible), file/Better shears - Sr Paulo.zip (incompatible), file/Better+Leaves+Add-on+V3.0-1.20.zip, file/Coloured Subtitles.zip (incompatible), file/Golden Crown.zip (incompatible), file/Crops n' Meats.zip (incompatible), file/Magical biomes Ocean.zip (incompatible), file/Lush Desert (incompatible), minecraft:supporteatinganimation, file/Xali's Potions.zip (incompatible), file/Xali's Enhanced Biomes.zip (incompatible), file/Shield Corrections.zip (incompatible), file/Softer Stones.zip (incompatible), file/Star Orbs.zip (incompatible), file/Totem of Undying - Botw Fairy.zip (incompatible), file/Visible Glint.zip (incompatible), file/Dynamic Surroundings Sounds Pack.zip (incompatible), file/Trident of Poseidon (incompatible)
	Current Language: en_us
	CPU: 16x AMD Ryzen 7 3800X 8-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['W0lfve'/86, l='ServerLevel[Testing ❀]', x=0.83, y=-60.00, z=-15.70]]
	Data Packs: vanilla, fabric, Supplementaries Generated Pack
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable

**Comment by W0lfve** [comment]
Issue resolved, the mod causing the error was Bobby.
