### ISSUE TITLE
Incompatibility with PolyDungeons Mod (BufferBuilder Not Started)

### ISSUE THREAD

**Issue by allanf181** [jellysquid3/Sodium#209]
```
---- Minecraft Crash Report ----
// Don't do that.

Time: 2020-07-29 15:12:56 BRT
Description: Rendering Block Entity

java.lang.IllegalStateException: BufferBuilder not started
    at Not Enough Crashes deobfuscated stack trace.(1.16.1+build.21)
    at net.minecraft.client.render.BufferBuilder.getCurrentElement(BufferBuilder:378)
    at net.minecraft.client.render.BufferVertexConsumer.vertex(BufferVertexConsumer:18)
    at net.minecraft.client.render.VertexConsumer.vertex(VertexConsumer:532)
    at polydungeons.client.ber.SolidEndPortalBlockEntityRenderer.renderFace(SolidEndPortalBlockEntityRenderer.java:88)
    at polydungeons.client.ber.SolidEndPortalBlockEntityRenderer.renderCube(SolidEndPortalBlockEntityRenderer.java:81)
    at polydungeons.client.ber.SolidEndPortalBlockEntityRenderer.render(SolidEndPortalBlockEntityRenderer.java:68)
    at polydungeons.client.ber.SolidEndPortalBlockEntityRenderer.render(SolidEndPortalBlockEntityRenderer.java:16)
    at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.render(BlockEntityRenderDispatcher:107)
    at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.method_23081(BlockEntityRenderDispatcher:96)
    at net.minecraft.class_824$$Lambda$3694/0000000000000000.run(Unknown Source)
    at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.runReported(BlockEntityRenderDispatcher:128)
    at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.render(BlockEntityRenderDispatcher:96)
    at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:302)
    at net.minecraft.client.render.WorldRenderer.handler$zzg000$onRenderTileEntities(WorldRenderer:3692)
    at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1245)
    at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:717)
    at net.minecraft.client.render.GameRenderer.render(GameRenderer:540)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:1021)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:654)
    at net.minecraft.client.MinecraftClient.handler$bko000$afterCrashHandled(MinecraftClient:12835)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:672)
    at net.minecraft.client.main.Main.main(Main:215)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:564)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:564)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Block Entity Details --
  Name: polydungeons:end_block // polydungeons.block.entity.DecorativeEndBlockEntity
  Block: Block{polydungeons:end_block}
  Block location: World: (1567,63,-329), Chunk: (at 15,3,7 in 97,-21; contains blocks 1552,0,-336 to 1567,255,-321), Region: (3,-1; contains chunks 96,-32 to 127,-1, blocks 1536,0,-512 to 2047,255,-1)
  Block: Block{polydungeons:end_block}
  Block location: World: (1567,63,-329), Chunk: (at 15,3,7 in 97,-21; contains blocks 1552,0,-336 to 1567,255,-321), Region: (3,-1; contains chunks 96,-32 to 127,-1, blocks 1536,0,-512 to 2047,255,-1)
  Block Entity NBT: {x:1567,y:63,z:-329,id:"polydungeons:end_block"}

-- Affected level --
  All players: 1 total; [class_746['armelin1'/12338879, l='ClientLevel', x=1534.14, y=71.50, z=-382.01]]
  Chunk stats: SodiumChunkCache: 483
  Level dimension: minecraft:overworld
  Level spawn location: World: (112,73,-64), Chunk: (at 0,4,0 in 7,-4; contains blocks 112,0,-64 to 127,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
  Level time: 5138263 game time, 6994205 day time
  Server brand: fabric
  Server type: Non-integrated multiplayer server

-- System Details --
  Minecraft Version: 1.16.1
  Minecraft Version ID: 1.16.1
  Operating System: Windows 7 (amd64) version 6.1
  Java Version: 14.0.2, AdoptOpenJDK
  Java VM Version: Eclipse OpenJ9 VM (JRE 14 Windows 7 amd64-64-Bit Compressed References 20200715_148 (JIT enabled, AOT enabled)
                   OpenJ9   - 34cf4c075
                   OMR      - 113e54219
                   JCL      - 1d231bd6a2 based on jdk-14.0.2+12), Eclipse OpenJ9
  Memory: 1109158392 bytes (1057 MB) / 2828075008 bytes (2697 MB) up to 3758096384 bytes (3584 MB)
  CPUs: 4
  JVM Flags: 30 total; -Xoptionsfile=C:\MARCELO\Allan\Programas\OpenJDK\OpenJ9\jdk-14.0.2+12\lib\options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse29 -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=50 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=256m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=20000 -XX:ParallelGCThreads=4 -XX:+UnlockExperimentalVMOptions -XX:+UseStringDeduplication -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx3584m
  Suspected Mods: Fabric Loader (fabricloader), Sodium (sodium), PolyDungeons (polydungeons)
```
sodium: Sodium 0.1.0
fabricloader: Fabric Loader 0.9.0+build.204

**Comment by amnotbananaama** [comment]
This would be better titled as "Incompatibility with PolyDungeons". It looks like that mod [expects](https://github.com/Earthcomputer/PolyDungeons/blob/5bfbcc12920a1e8077afc3630916471d52f07953/src/main/java/polydungeons/client/ber/SolidEndPortalBlockEntityRenderer.java) vanilla rendering code that Sodium overwrites.

**Comment by amnotbananaama** [comment]
Closing after [discussing](https://discordapp.com/channels/602796788608401408/602805971391217683/752278372251336764) with Earthcomputer. This is something that needs to be fixed in PolyDungeons. If anyone is able to submit a Pull Request there for it, feel free to do so.
