### ISSUE TITLE
1.20.2 sodium crash 

### ISSUE THREAD

**Issue by Nisar12421** [jellysquid3/Sodium#2101]
### Bug Description

1.20.2 sodium world and server crash plobrem 

### Reproduction Steps

1.20.2 block invisible plobrem 

### Log File

2023-10-05 11:05:23,965 main ERROR appender Console has no parameter that matches element Policies
[11:05:25] [main/INFO]: Loading Minecraft 1.20.2 with Fabric Loader 0.14.22
[11:05:26] [main/INFO]: Loading 61 mods:
	- fabric-api 0.89.3+1.20.2
	   |-- fabric-api-base 0.4.33+fce67b32a0
	   |-- fabric-api-lookup-api-v1 1.6.41+fce67b32a0
	   |-- fabric-biome-api-v1 13.0.12+d9a2869ba0
	   |-- fabric-block-api-v1 1.0.12+73761d2ea0
	   |-- fabric-block-view-api-v2 1.0.1+73761d2ea0
	   |-- fabric-blockrenderlayer-v1 1.1.43+f4b7e424a0
	   |-- fabric-client-tags-api-v1 1.1.4+86b12645a0
	   |-- fabric-command-api-v1 1.2.36+f71b366fa0
	   |-- fabric-command-api-v2 2.2.15+86b12645a0
	   |-- fabric-commands-v0 0.2.53+df3654b3a0
	   |-- fabric-containers-v0 0.1.72+df3654b3a0
	   |-- fabric-content-registries-v0 5.0.4+285022b3a0
	   |-- fabric-convention-tags-v1 1.5.7+f4b7e424a0
	   |-- fabric-crash-report-info-v1 0.2.20+f4b7e424a0
	   |-- fabric-data-generation-api-v1 13.1.2+d19c4129a0
	   |-- fabric-dimensions-v1 2.1.56+b1229956a0
	   |-- fabric-entity-events-v1 1.5.25+f4b7e424a0
	   |-- fabric-events-interaction-v0 0.6.9+daef22a2a0
	   |-- fabric-events-lifecycle-v0 0.2.68+df3654b3a0
	   |-- fabric-game-rule-api-v1 1.0.40+f4b7e424a0
	   |-- fabric-item-api-v1 2.1.32+43511215a0
	   |-- fabric-item-group-api-v1 4.0.13+f4b7e424a0
	   |-- fabric-key-binding-api-v1 1.0.38+f4b7e424a0
	   |-- fabric-keybindings-v0 0.2.36+df3654b3a0
	   |-- fabric-lifecycle-events-v1 2.2.26+3bafade3a0
	   |-- fabric-loot-api-v2 2.0.2+0ba8e9cea0
	   |-- fabric-message-api-v1 6.0.1+e982ae85a0
	   |-- fabric-mining-level-api-v1 2.1.54+f4b7e424a0
	   |-- fabric-model-loading-api-v1 1.0.5+f4b7e424a0
	   |-- fabric-models-v0 0.4.4+9386d8a7a0
	   |-- fabric-networking-api-v1 3.0.8+b18afef3a0
	   |-- fabric-object-builder-api-v1 12.1.1+b1b4f7b0a0
	   |-- fabric-particles-v1 1.1.4+f4b7e424a0
	   |-- fabric-recipe-api-v1 2.0.5+96509552a0
	   |-- fabric-registry-sync-v0 4.0.3+34a3e0e2a0
	   |-- fabric-renderer-api-v1 3.2.1+2034447ca0
	   |-- fabric-renderer-indigo 1.5.1+2034447ca0
	   |-- fabric-renderer-registries-v1 3.2.48+df3654b3a0
	   |-- fabric-rendering-data-attachment-v1 0.3.39+73761d2ea0
	   |-- fabric-rendering-fluids-v1 3
.0.30+f4b7e424a0
	   |-- fabric-rendering-v0 1.1.51+df3654b3a0
	   |-- fabric-rendering-v1 3.0.10+86b12645a0
	   |-- fabric-resource-conditions-api-v1 2.3.9+43511215a0
	   |-- fabric-resource-loader-v0 0.11.11+86b12645a0
	   |-- fabric-screen-api-v1 2.0.11+0ba8e9cea0
	   |-- fabric-screen-handler-api-v1 1.3.38+86b12645a0
	   |-- fabric-sound-api-v1 1.0.14+f4b7e424a0
	   |-- fabric-transfer-api-v1 3.3.8+109a65e5a0
	   \-- fabric-transitive-access-wideners-v1 5.0.3+fce67b32a0
	- fabricloader 0.14.22
	- java 17
	- lithium 0.12.0
	- minecraft 1.20.2
	- modmenu 8.0.0
	- reeses-sodium-options 1.6.5+mc1.20.2-build.96
	- sodium 0.5.3
	- sodium-extra 0.5.2+mc1.20.2-build.113
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- starlight 1.1.2+fabric.bdaeb21
[11:05:27] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[11:05:28] [main/INFO]: Compatibility level set to JAVA_16
[11:05:28] [main/INFO]: Compatibility level set to JAVA_17
[11:05:30] [main/INFO]: Loaded configuration file for Lithium: 125 options available, 0 override(s) found
[11:05:30] [main/INFO]: Loaded configuration file for Sodium: 41 options available, 0 override(s) found
[11:05:30] [main/INFO]: Loaded configuration file for Sodium Extra: 33 options available, 0 override(s) found
[11:05:41] [main/INFO]: Searching for graphics cards...
[11:05:42] [main/WARN]: No graphics cards were found. Either you have no hardware devices supporting 3D acceleration, or something has gone terribly wrong!
[11:05:42] [main/WARN]: Unable to determine desktop session type because the environment variable XDG_SESSION_TYPE is not set! Your user session may not be configured correctly.
[11:05:48] [main/WARN]: Did not find udev library in operating system. Some features may not work.
[11:05:48] [main/WARN]: File not found or not readable: /proc/stat
[11:05:49] [main/WARN]: Failed to get system info for Microarchitecture
java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because "this.cpuVendor" is null
	at oshi.hardware.CentralProcessor$ProcessorIdentifier.queryMicroarchitecture(CentralProcessor.java:825) ~[oshi-core-6.4.5.jar:?]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.5.jar:?]
	at oshi.hardware.CentralProcessor$ProcessorIdentifier.getMicroarchitecture(CentralProcessor.java:816) ~[oshi-core-6.4.5.jar:?]
	at net.minecraft.class_6396.method_37123(class_6396.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37130(class_6396.java:128) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37146(class_6396.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37121(class_6396.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37128(class_6396.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37143(class_6396.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37121(class_6396.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.<init>(class_6396.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:274) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:167) ~[fabric-loader-0.14.22-1.20.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
[11:06:57] [Datafixer Bootstrap/INFO]: 192 Datafixer optimizations took 3010 milliseconds
--------- beginning of system

INFO: Initialized TensorFlow Lite runtime.

### Crash Report

Crash 1.20.2 sodium

**Comment by TheUserCreated** [comment]
Sodium does not work with pojav. There is no workaround and this is not a bug.

**Comment by Nisar12421** [comment]
Pojavlauncher 1.20.1 me sodium crash nhai horaha hai my 4gb ram mobile mera
100 fps me game chalta hai magar sodium pojavlauncher 1.20.2 me crash
horaha hai

**Comment by TheUserCreated** [comment]
It doesn't matter if it worked for you previously. Read the warning on the title screen or the warnings from the pojav team. Sodium does not provide support for pojav due to the complete lack of acceptable openGL drivers on mobile devices, among other things.

**Comment by Nisar12421** [comment]
Thanks for the tip!
