### ISSUE TITLE
Sodium is crashing my Curseforge fabric 1.20.1 modpack

### ISSUE THREAD

**Issue by WodanW** [jellysquid3/Sodium#2110]
### Bug Description

Every time i try to launch my modpack with sodium im getting this error code: "The game crashed whilst initializing game
Error: java.lang.RuntimeException: Mixin transformation of me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer failed'' Does anyone know how I can solve this? the crash code is -1.

### Reproduction Steps

I have a fabric modpack with 59 mods and im trying to get sodium on it because i want better performance.

### Log File

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Mixin transformation of me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer failed

### Crash Report

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 2023-10-08 15:44:05
Description: Initializing game

java.lang.RuntimeException: Mixin transformation of me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.minecraft.class_761.handler$chi000$sodium$init(class_761.java:5468)
	at net.minecraft.class_761.<init>(class_761.java:307)
	at net.minecraft.class_310.<init>(class_310.java:583)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 11 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector renderShipChunkBlockEntity(Lnet/minecraft/class_824;Lnet/minecraft/class_2586;FLnet/minecraft/class_4587;Lnet/minecraft/class_4597;Lnet/minecraft/class_4587;Lnet/minecraft/class_4599;Lit/unimi/dsi/fastutil/longs/Long2ObjectMap;Lnet/minecraft/class_4184;F)V in valkyrienskies-common.mixins.json:mod_compat.sodium.MixinSodiumWorldRenderer from mod valkyrienskies failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap valkyrienskies-1201-common-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.minecraft.class_761.handler$chi000$sodium$init(class_761.java:5468)
	at net.minecraft.class_761.<init>(class_761.java:307)
	at net.minecraft.class_310.<init>(class_310.java:583)

-- Initialization --

**Comment by Poopooracoocoo** [comment]
Please upload a latest.log. It's in your logs folder. It'll have more information about the crash such as the versions of your mods. And for future reference, the Discord server is the best place for support.

But before you go any further, if you're using Sodium with Valkyrien Skies on Minecraft 1.20.1, make sure you're using Sodium 0.4.10, Indium 1.0.21, and Fabric API 0.88.1. You need to get Sodium (and Iris) from Modrinth. If you want Iris, use Iris 1.6.4.

Valkyrien Skies is currently incompatible with Sodium 0.5.x. https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/556

**Comment by WodanW** [comment]
IT WORKT!! thanks you so much ive spent like 3 hours trying to fix sodium/optifabric
