### ISSUE TITLE
There's no correct version of Sodium for 1.20.1 for at least two mods, and Fabric itself suggests a version that doesn't exist

### ISSUE THREAD

**Issue by Mugman2000** [jellysquid3/Sodium#2124]
### Bug Description

When I put 0.5.3 in my mods, Sodium says it needs 1.20.2, despite 0.5.3 claiming compatability with 1.20.1 and not 1.20.2.
When I put 0.5.2 in my mods, two dependents break: Indium and Nvidium.

### Reproduction Steps

First scenario:
Install Sodium 0.5.3, Indium 1.0.27 and/or Nvidium 0.2.0-beta, and Fabric API 0.90.0

Second scenario:
Install Sodium 0.5.2, Indium 1.0.27 and/or Nvidium 0.2.0-beta, and Fabric API 0.90.0

### Log File

With 0.5.3:

[16:47:21] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.23
[16:47:21] [main/WARN]: Mod resolution failed
[16:47:21] [main/INFO]: Immediate reason: [HARD_DEP indium 1.0.27+mc1.20.1 {depends sodium @ [0.5.3]}, HARD_DEP_INCOMPATIBLE_PRESELECTED sodium 0.5.3 {depends minecraft @ [1.20.2]}, ROOT_FORCELOAD_SINGLE indium 1.0.27+mc1.20.1]
[16:47:21] [main/INFO]: Reason: [HARD_DEP sodium 0.5.3 {depends minecraft @ [1.20.2]}]
[16:47:21] [main/INFO]: Fix: add [], remove [], replace [[sodium 0.5.3] -> add:sodium 0.5.3 ([[0.5.3,0.5.3]])]
[16:47:21] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Sodium' (sodium) 0.5.3 with version 0.5.3 that is compatible with:
		 - minecraft 1.20.1
More details:
	 - Mod 'Sodium' (sodium) 0.5.3 requires version 1.20.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:194) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.23.jar:?]

With 0.5.2:
[16:53:57] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.23
[16:53:58] [main/WARN]: Mod resolution failed
[16:53:58] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE indium 1.0.27+mc1.20.1 {depends sodium @ [0.5.3]}, ROOT_FORCELOAD_SINGLE indium 1.0.27+mc1.20.1]
[16:53:58] [main/INFO]: Reason: [HARD_DEP indium 1.0.27+mc1.20.1 {depends sodium @ [0.5.3]}, HARD_DEP nvidium 0.2.0-beta {depends sodium @ [=0.5.3]}]
[16:53:58] [main/INFO]: Fix: add [], remove [], replace [[sodium 0.5.2] -> add:sodium 0.5.3 ([[0.5.3,0.5.3]])]
[16:53:58] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Sodium' (sodium) 0.5.2 with version 0.5.3.
More details:
	 - Mod 'Indium' (indium) 1.0.27+mc1.20.1 requires version 0.5.3 of mod 'Sodium' (sodium), but only the wrong version is present: 0.5.2!
	 - Mod 'Nvidium' (nvidium) 0.2.0-beta requires version 0.5.3 of mod 'Sodium' (sodium), but only the wrong version is present: 0.5.2!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:194) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.23.jar:?]

### Crash Report

For some reason, I haven't generated a crash report in 41 days, even though it crashed several times today... possibly because Fabric is preventing it from even loading? Also, F3+C won't do anything.

**Comment by Lolothepro** [comment]
You're using Sodium 0.5.3 for Minecraft 1.20.2, instead of Sodium 0.5.3 for Minecraft 1.20.1...

**Comment by Poopooracoocoo** [comment]
>Second scenario:
Install Sodium 0.5.2, Indium 1.0.27 and/or Nvidium 0.2.0-beta, and Fabric API 0.90.0

For Sodium 0.5.2, you need to use Indium 1.0.25 and Fabric API 0.88.1 and Nvidium 0.1.16-alpha

**Comment by Mugman2000** [comment]
> You're using Sodium 0.5.3 for Minecraft 1.20.2, instead of Sodium 0.5.3 for Minecraft 1.20.1...

That's the thing, I can't find a .1 version, the 0.5.3 I found claimed to be for .1 but then needs .2

**Comment by Mugman2000** [comment]
Wait, I found it now.
I couldn't find it earlier...
Odd.

**Comment by Poopooracoocoo** [comment]
Click on the Versions tab on the Modrinth page to view all versions. It's not in the sidebar for some reason
