### ISSUE TITLE
Mixin transformation of me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.FluidRenderer failed

### ISSUE THREAD

**Issue by uieqwhak** [jellysquid3/Sodium#2144]
### Bug Description

Whenever I open/create a world, the game crashes. I tried removing many of the downloaded mods but with no success. I also tried checking other solutions on github but also with no success. Yesterday when I played minecraft 1.20.2 with only optimization mods it worked fine, and after I downloaded the rest of the mods this started happening, so maybe one of these mods caused the issue? I downloaded the latest version of every mod (as of 10-12 hours ago).

### Reproduction Steps

version: 1.20.1
mods:
[mods.txt](https://github.com/CaffeineMC/sodium-fabric/files/13195706/mods.txt)
(Uploaded as file because body was too long)

### Log File

[log.txt](https://github.com/CaffeineMC/sodium-fabric/files/13195701/log.txt)
(Uploaded as file because body was too long)

### Crash Report

[crash.txt](https://github.com/CaffeineMC/sodium-fabric/files/13195703/crash.txt)
(Uploaded as file because body was too long)

**Comment by AlsoSylv** [comment]
Try removing the bedrock waters mod

**Comment by uieqwhak** [comment]
I removed the mod and it opens the world, but it crashes after a few seconds!
Log:
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2023-10-28 15:08:18
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'void net.minecraft.class_1735.method_53512(net.minecraft.class_1799)'
	at net.minecraft.class_3244.handler$eao000$stackable$onCreativeInventoryAction(class_3244.java:4480)
	at net.minecraft.class_3244.method_12070(class_3244.java:1772)
	at net.minecraft.class_2873.method_12480(class_2873.java:18)
	at net.minecraft.class_2873.method_11054(class_2873.java:7)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
	at net.minecraft.class_1255.method_18857(class_1255.java:139)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --

Crash report:
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2023-10-28 15:08:18
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'void net.minecraft.class_1735.method_53512(net.minecraft.class_1799)'
	at net.minecraft.class_3244.handler$eao000$stackable$onCreativeInventoryAction(class_3244.java:4480)
	at net.minecraft.class_3244.method_12070(class_3244.java:1772)
	at net.minecraft.class_2873.method_12480(class_2873.java:18)
	at net.minecraft.class_2873.method_11054(class_2873.java:7)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
	at net.minecraft.class_1255.method_18857(class_1255.java:139)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --

**Comment by jellysquid3** [comment]
TLauncher is not supported. Buy the game.
