### ISSUE TITLE
minecraft crashing after new mods

### ISSUE THREAD

**Issue by captainpewpew** [jellysquid3/Sodium#2172]
### Reproduction Steps

crashes after moving around a bit in game

### Log File

.

### Crash Report

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2023-11-19 17:39:00
Description: Unexpected error

java.lang.NoClassDefFoundError: net/caffeinemc/mods/sodium/api/vertex/buffer/VertexBufferWriter
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.diebuddies.physics.DummyMultiBufferSource.lambda$getBuffer$0(DummyMultiBufferSource.java:24)
	at java.base/java.util.Map.computeIfAbsent(Map.java:1054)
	at net.diebuddies.physics.DummyMultiBufferSource.getBuffer(DummyMultiBufferSource.java:24)
	at net.minecraft.class_922.method_4054(class_922.java:138)
	at net.minecraft.class_927.method_4072(class_927.java:45)
	at net.minecraft.class_959.method_4140(class_959.java:47)
	at net.minecraft.class_959.method_3936(class_959.java:15)
	at net.diebuddies.physics.PhysicsMod.blockifyEntity(PhysicsMod.java:746)
	at net.minecraft.class_1309.handler$ddd000$physicsmod$onDeath(class_1309.java:13650)
	at net.minecraft.class_1309.method_6078(class_1309.java)
	at net.minecraft.class_1309.method_5711(class_1309.java:1801)
	at net.minecraft.class_1308.method_5711(class_1308.java:345)
	at net.minecraft.class_634.method_11148(class_634.java:1067)
	at net.minecraft.class_2663.method_11471(class_2663.java:33)
	at net.minecraft.class_2663.method_11054(class_2663.java:11)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1175)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.caffeinemc.mods.sodium.api.vertex.buffer.VertexBufferWriter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 34 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.diebuddies.physics.DummyMultiBufferSource.lambda$getBuffer$0(DummyMultiBufferSource.java:24)
	at java.base/java.util.Map.computeIfAbsent(Map.java:1054)
	at net.diebuddies.physics.DummyMultiBufferSource.getBuffer(DummyMultiBufferSource.java:24)
	at net.minecraft.class_922.method_4054(class_922.java:138)
	at net.minecraft.class_927.method_4072(class_927.java:45)
	at net.minecraft.class_959.method_4140(class_959.java:47)
	at net.minecraft.class_959.method_3936(class_959.java:15)
	at net.diebuddies.physics.PhysicsMod.blockifyEntity(PhysicsMod.java:746)
	at net.minecraft.class_1309.handler$ddd000$physicsmod$onDeath(class_1309.java:13650)
	at net.minecraft.class_1309.method_6078(class_1309.java)
	at net.minecraft.class_1309.method_5711(class_1309.java:1801)
	at net.minecraft.class_1308.method_5711(class_1308.java:345)
	at net.minecraft.class_634.method_11148(class_634.java:1067)
	at net.minecraft.class_2663.method_11471(class_2663.java:33)
	at net.minecraft.class_2663.method_11054(class_2663.java:11)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)

-- Affected level --
Details:
	All players: 1 total; [class_746['CaptainPewPew'/291, l='ClientLevel', x=57.83, y=66.00, z=-163.86]]
	Chunk stats: 1024, 201
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,101,-144), Section: (at 0,5,0 in -2,6,-9; chunk contains blocks -32,-64,-144 to -17,319,-129), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 3794 game time, 3794 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/FreshAnimations_v1.8.1.zip, itemswapper:classic, visualoverhaul:rounddiscs, essential

-- System Details --
Details:
	Minecraft Version: 1.20
	Minecraft Version ID: 1.20
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1171916368 bytes (1117 MiB) / 3858759680 bytes (3680 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 12
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Intel(R) Arc(TM) A750 Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x56a1
	Graphics card #0 versionInfo: DriverVersion=31.0.101.4887
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.60
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.60
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 43958.98
	Virtual memory used (MB): 36849.97
	Swap memory total (MB): 11271.91
	Swap memory used (MB): 114.21
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		ambientsounds: AmbientSounds 5.2.22
		architectury: Architectury 9.1.12
		balm-fabric: Balm 7.1.4
		bclib: BCLib 3.0.13
			wunderlib: WunderLib 1.1.5
		bettercombat: Better Combat 1.8.3+1.20.1
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0
		betterdeserttemples: YUNG's Better Desert Temples 1.20-Fabric-3.0.3
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.3
		betterend: Better End 4.0.10
		betterf3: BetterF3 7.0.2
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.8+e3d6ed2577
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.5
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
		betternether: Better Nether 9.0.9
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.20-Fabric-3.0.3
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		betterwitchhuts: YUNG's Better Witch Huts 1.20-Fabric-3.0.3
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		comforts: Comforts 6.3.4+1.20.1
			cardinal-components-base: Cardinal Components API (base) 5.2.1
			cardinal-components-entity: Cardinal Components API (entities) 5.2.1
			spectrelib: SpectreLib 0.13.14+1.20.1
				com_electronwill_night-config_core: core 3.6.5
				com_electronwill_night-config_toml: toml 3.6.5
		connectedglass: Connected Glass 1.1.7
		continuity: Continuity 3.0.0-beta.2+1.20
		controlling: Controlling For Fabric 12.0.2
		creativecore: CreativeCore 2.11.5
			net_minecraftforge_eventbus: eventbus 6.0.3
		ctov: ChoiceTheorem's Overhauled Village 3.3.5b
		cupboard: cupboard 1.20.1-2.1
		dashloader: DashLoader 5.0.0-beta.2+1.20.0
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_notalpha_taski: Taski 2.1.0
			dev_quantumfusion_hyphen: Hyphen 0.4.0-rc.3
		dehydration: Dehydration 1.3.4
		dragonfight: Dragonfight Mod 1.20.1-4.1
		easyshulkerboxes: Easy Shulker Boxes 7.0.0
			iteminteractionscore: Item Interactions Core 7.0.0
		eatinganimationid: Eating Animation 1.9.4+1.20
		elementa: Elementa 614
		endrem: End Remastered 5.2.2
		essential: Essential 14565+deploy-staging+g7d1e613e0b
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.1
		extra_details: Panda's Extra Details 0.2+1.20-1.20.1-beta
		fabric-api: Fabric API 0.83.0+1.20
			fabric-api-base: Fabric API Base 0.4.29+b04edc7a27
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c927
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b27
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d127
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.39+b3afc78b27
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.20+b3afc78b27
			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f27
			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b27
			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b327
			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b327
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.7+b3afc78b27
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b27
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe27
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.10+b3afc78b27
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b27
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b27
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b27
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b327
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a27
			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b27
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.7+b3afc78b27
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da27
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b327
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b27
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.37+b3afc78b27
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.41+9e7660c627
			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b27
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.47+b3afc78b27
			fabric-models-v0: Fabric Models (v0) 0.3.35+b3afc78b27
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b27
			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b327
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.0.6+b3afc78b27
			fabric-particles-v1: Fabric Particles (v1) 1.0.28+b3afc78b27
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b27
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b27
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.0.1+b3afc78b27
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.3.1+b3afc78b27
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.44+df3654b327
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.33+b3afc78b27
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.26+b3afc78b27
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.47+df3654b327
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.6+b3afc78b27
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.4+b3afc78b27
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.6+b3afc78b27
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.27+b3afc78b27
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b27
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.2+b3afc78b27
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.2.0+b3afc78b27
		fabric-language-kotlin: Fabric Language Kotlin 1.10.10+kotlin.1.9.10
		fabricloader: Fabric Loader 0.14.24
		fallingtree: FallingTree 4.0.1
		farmersdelight: Farmer's Delight 1.20.1-1.4.2
		firstperson: FirstpersonModel 2.2.3
		geckolib: Geckolib 4.2.2
			com_eliotlash_mclib_mclib: mclib 20
		gildedarmor: Gilded Armor 1.8.0+fabric-1.20.1
		immersive_paintings: Immersive Paintings 0.6.3+1.20
		indium: Indium 1.0.18+mc1.20
		invmove: InvMove 0.8.4
		iris: Iris 1.6.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemswapper: ItemSwapper 0.5.3-mc1.20.1
		jade: Jade 11.6.2
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.8
			journeymap-api-fabric: JourneyMap API 1.20-1.9-fabric-SNAPSHOT
		lambdynlights: LambDynamicLights 2.3.2+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
			spruceui: SpruceUI 5.0.0+1.20
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.11.2
		mcwfurnitures: Macaw's Furniture 3.2.0b
		minecraft: Minecraft 1.20
		modmenu: Mod Menu 7.0.1
		mousewheelie: Mouse Wheelie 1.11.1+mc1.20-pre2
			amecsapi: Amecs API 1.4.0+mc1.20-pre1
			coat: Coat 1.0.0-beta.20+mc1.20-pre1
			tweed4_annotated: tweed4_annotated 1.3.1+mc1.20-pre1
			tweed4_base: tweed4_base 1.7.1+mc1.20-pre1
			tweed4_data: tweed4_data 1.2.1+mc1.20-pre1
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc1.20-pre1
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc1.20-pre1
			tweed4_tailor_lang_json_descriptions: tweed4_tailor_lang_json_descriptions 1.1.0+mc1.20-pre1
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.4+mc1.20-pre1
		mr_dungeons_andtaverns: Dungeons and Taverns 3.0.3
		org_jetbrains_annotations: annotations 13.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.10
		org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.22.0
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
		org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.0
		physicsmod: Physics Mod 3.0.9
		player-animator: Player Animator 1.0.2-rc1+1.20
		puzzleslib: Puzzles Lib 7.0.2
		realisticsleep: Realistic Sleep 1.9.1+mc1.20.x
		resourcefulconfig: Resourcefulconfig 2.1.0
		searchables: Searchables 1.0.2
		showmeyourskin: Show Me Your Skin! 1.6.11+1.20
			cicada: CICADA 0.4.0
		smallships: Small Ships 2.0.0-a2.3.2
			forgeconfigapiport: Forge Config API Port 7.0.0
		sodium: Sodium 0.4.10+build.27
		sound_physics_remastered: Sound Physics Remastered 1.20-1.1.1
		spyglass_astronomy: Spyglass Astronomy 1.0.8-mc1.20.1
		starlight: Starlight 1.1.2+fabric.dbc156f
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.10+c
		terralith: Terralith 2.4.8
		travelersbackpack: Traveler's Backpack 1.20-9.0.2
		travelerstitles: Traveler's Titles 1.20-Fabric-4.0.1
		universalcraft: UniversalCraft 318
		vigilance: Vigilance 295
		visuality: Visuality 0.7.1+1.20
		visualoverhaul: VisualOverhaul 5.0.1
			midnightlib: MidnightLib 1.4.1
		visualworkbench: Visual Workbench 7.0.0
		voicechat: Simple Voice Chat 1.20-2.4.9
		waystones: Waystones 14.0.2
		xaerominimap: Xaero's Minimap 23.8.4
		xaeroworldmap: Xaero's World Map 1.36.0
		yungsapi: YUNG's API 1.20-Fabric-4.0.2
			org_javassist_javassist: javassist 3.29.2-GA
	Loaded Shaderpack: ComplementaryReimagined_r5.0.1.zip
		Profile: Custom (+4 options changed by user)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.24-1.20
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Intel(R) Arc(TM) A750 Graphics GL version 3.2.0 - Build 31.0.101.4887, Intel
	Window size: 1920x1009
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1280, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_ENUM in (null): (ID: 897695363) non-integer <format> 28 has been provided.' x 1
id=1280, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_ENUM in (null): (ID: 173538523) Generic error' x 1
id=1280, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_ENUM in (null): (ID: 897695363) non-integer <format> 28 has been provided.' x 1
id=1280, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_ENUM in (null): (ID: 173538523) Generic error' x 1
id=1280, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_ENUM in (null): (ID: 897695363) non-integer <format> 28 has been provided.' x 1
id=1280, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_ENUM in (null): (ID: 173538523) Generic error' x 1
id=1280, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_ENUM in (null): (ID: 897695363) non-integer <format> 28 has been provided.' x 1
id=1280, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_ENUM in (null): (ID: 173538523) Generic error' x 1
id=1280, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_ENUM in (null): (ID: 897695363) non-integer <format> 28 has been provided.' x 1
id=1280, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_ENUM in (null): (ID: 173538523) Generic error' x 1
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, file/FreshAnimations_v1.8.1.zip (incompatible), itemswapper:classic
	Current Language: en_us
	CPU: 16x Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['CaptainPewPew'/291, l='ServerLevel[my own world]', x=57.83, y=66.00, z=-163.86]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental

**Comment by pajicadvance** [comment]
The crash is caused by Physics Mod, it's not related to Sodium. You're either using an incompatible version or there is a problem with the mod.

**Comment by captainpewpew** [comment]
thank you
