### ISSUE TITLE
Sodium 0.5.4 makes Indium Invalid and get Error message

### ISSUE THREAD

**Issue by T3chWarri0r** [jellysquid3/Sodium#2202]
### Reproduction Steps

Have installed latest updates but Indium seams not up to date 

### Log File

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Sodium' (sodium) 0.5.4 with version 0.5.4 that is compatible with:
		 - indium, any version
	 - Replace mod 'Indium' (indium) 1.0.27+mc1.20.1 with any version that is compatible with:
		 - sodium, version 0.5.4
More details:
	 - Mod 'Indium' (indium) 1.0.27+mc1.20.1 requires version 0.5.3 of mod 'Sodium' (sodium), but only the wrong version is present: 0.5.4!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:194)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Crash Report

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Sodium' (sodium) 0.5.4 with version 0.5.4 that is compatible with:
		 - indium, any version
	 - Replace mod 'Indium' (indium) 1.0.27+mc1.20.1 with any version that is compatible with:
		 - sodium, version 0.5.4
More details:
	 - Mod 'Indium' (indium) 1.0.27+mc1.20.1 requires version 0.5.3 of mod 'Sodium' (sodium), but only the wrong version is present: 0.5.4!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:194)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by pajicadvance** [comment]
You need to wait for Indium to release an update to support Sodium 0.5.4. Until then you can stick with 0.5.3.
