### ISSUE TITLE
LWJGL detects a memory leak in Sodium, is this normal?

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#2204]
```
[LWJGL] 864 bytes leaked, thread 1 (Render thread), address: 0x7F1C91782000
	at me.jellysquid.mods.sodium.client.render.immediate.model.EntityRenderer.<clinit>(EntityRenderer.java:41)
	at net.minecraft.class_630.handler$zch000$sodium$onRender(class_630.java:595)
	at net.minecraft.class_630.method_22699(class_630.java)
	at net.minecraft.class_4592.method_22949(class_4592.java:62)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at net.minecraft.class_4592.method_2828(class_4592.java:62)
	at net.minecraft.class_922.method_4054(class_922.java:139)
	at net.minecraft.class_927.method_4072(class_927.java:45)
	at net.minecraft.class_927.method_3936(class_927.java:18)
	at net.minecraft.class_898.method_3954(class_898.java:146)
	at net.minecraft.class_761.method_22977(class_761.java:1348)
	at net.minecraft.class_761.method_22710(class_761.java:1098)
	at net.minecraft.class_757.method_3188(class_757.java:1098)
	at net.minecraft.class_757.method_3192(class_757.java:866)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

When I tested douira's PR, I noticed this, it also happens with normal Sodium
Log file:
https://mclo.gs/0GyAV7W

**Comment by Moulberry** [comment]
Yes, this is normal. As you can see in the trace, the 'leak' is occuring inside `<clinit>` i.e. a static initializer.
The memory in question is a scratch buffer that lives for the lifetime of the program
