### ISSUE TITLE
Cant get into a local world or a server to play.

### ISSUE THREAD

**Issue by Shiroiame-Kusu** [jellysquid3/Sodium#2280]
### Bug Description

The game will stuck at "joining the world"
I may not able to upload a screenshot because my client was running at fullscreen mode and it frozen.

### Reproduction Steps

Use sodium 0.5.6 + Iris 1.6.15
then it will happen.

### Log File

[2024-01-28-4.log](https://github.com/CaffeineMC/sodium-fabric/files/14074828/2024-01-28-4.log)
```
[Render thread/ERROR]: Error executing task on Client
net.minecraft.class_148: Main thread packet handler
	at net.minecraft.class_2600.method_11072(class_2600.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1283) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.scheduleRebuild(int, int, int, boolean)" because "this.renderSectionManager" is null
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.scheduleRebuildForChunk(SodiumWorldRenderer.java:461) ~[sodium-fabric-0.5.6+mc1.20.3.jar:?]
	at net.minecraft.class_761.method_3295(class_761.java:15306) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_8571(class_761.java:2454) ~[client-intermediary.jar:?]
	at net.minecraft.class_631.method_12247(class_631.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_3568.clientUpdateLight(class_3568.java:2224) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.redirect$edn000$starlight$loadLightDataHook(class_634.java:20504) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_2870(class_634.java:2208) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_38543(class_634.java:2128) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.handler$edn000$starlight$postChunkLoadHook(class_634.java:20557) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11128(class_634.java:740) ~[client-intermediary.jar:?]
	at net.minecraft.class_2672.method_11528(class_2672.java:45) ~[client-intermediary.jar:?]
	at net.minecraft.class_2672.method_11054(class_2672.java:12) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:24) ~[client-intermediary.jar:?]
	... 10 more
```
### Crash Report

No crash report, the game didnt crash, just stuck and frozen.

**Comment by jellysquid3** [comment]
Cheat clients are not supported.
