### ISSUE TITLE
Fingerprint created with force_disable_donation_prompts: true

### ISSUE THREAD

**Issue by Madis0** [jellysquid3/Sodium#2288]
### Bug Description

Sodium creates a user fingerprint even if `force_disable_donation_prompts` is set to `true`. This is unnecessary, because if the donation prompts are disabled, the fingerprint file is technically unused, but right now still created.

### Reproduction Steps

1. Install Minecraft 1.20.4 and Fabric
2. Install Sodium 0.5.7
3. Run once
4. Edit Sodium config to adjust `force_disable_donation_prompts`, delete `sodium-fingerprint.json`
5. Run Sodium again
6. `sodium-fingerprint.json` is recreated, despite it being irrelevant

### Log File

```
[19:24:54] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.6
[19:24:54] [main/INFO]: Loading 10 mods:
	- fabricloader 0.15.6
	   \-- mixinextras 0.3.2
	- java 17
	- minecraft 1.20.4
	- sodium 0.5.7+mc1.20.3
	   |-- fabric-api-base 0.4.34+f31bf8813b
	   |-- fabric-block-view-api-v2 1.0.2+73761d2e3b
	   |-- fabric-rendering-data-attachment-v1 0.3.40+73761d2e3b
	   |-- fabric-rendering-fluids-v1 3.0.31+f4b7e4243b
	   \-- fabric-resource-loader-v0 0.11.14+f31bf8813b
[19:24:55] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/madis/.local/share/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[19:24:55] [main/INFO]: Compatibility level set to JAVA_17
[19:24:55] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 0 override(s) found
[19:24:55] [main/INFO]: Searching for graphics cards...
[19:24:55] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=INTEL, name=Iris Plus Graphics G7, version=unknown]
[19:24:55] [main/WARN]: Sodium has applied one or more workarounds to prevent crashes or other issues on your system: [NO_ERROR_CONTEXT_UNSUPPORTED]
[19:24:55] [main/WARN]: This is not necessarily an issue, but it may result in certain features or optimizations being disabled. You can sometimes fix these issues by upgrading your graphics driver.
[19:24:56] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[19:24:59] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 142 milliseconds
[19:25:01] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[19:25:01] [Render thread/INFO]: Setting user: robotkoer
[19:25:01] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[19:25:01] [Render thread/INFO]: OpenGL Vendor: Intel
[19:25:01] [Render thread/INFO]: OpenGL Renderer: Mesa Intel(R) Iris(R) Plus Graphics (ICL GT2)
[19:25:01] [Render thread/INFO]: OpenGL Version: 4.6 (Core Profile) Mesa 23.3.3-manjaro1.1
[19:25:02] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric (fabric-api-base, fabric-block-view-api-v2, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-resource-loader-v0, fabricloader, sodium)
[19:25:02] [Worker-Main-3/INFO]: Found unifont_all_no_pua-15.1.04.hex, loading
[19:25:02] [Worker-Main-7/WARN]: File minecraft:sounds/mob/wolf/armor_equip1.ogg does not exist, cannot add it to event minecraft:entity.wolf.armor_equip
[19:25:02] [Worker-Main-7/WARN]: File minecraft:sounds/mob/wolf/armor_equip1.ogg does not exist, cannot add it to event minecraft:entity.wolf.armor_equip
[19:25:02] [Worker-Main-7/WARN]: File minecraft:sounds/mob/wolf/armor_equip2.ogg does not exist, cannot add it to event minecraft:entity.wolf.armor_equip
[19:25:02] [Worker-Main-7/WARN]: File minecraft:sounds/mob/wolf/armor_equip2.ogg does not exist, cannot add it to event minecraft:entity.wolf.armor_equip
[19:25:02] [Worker-Main-7/WARN]: File minecraft:sounds/mob/wolf/armor_unequip1.ogg does not exist, cannot add it to event minecraft:entity.wolf.armor_unequip
[19:25:02] [Worker-Main-7/WARN]: File minecraft:sounds/mob/wolf/armor_unequip2.ogg does not exist, cannot add it to event minecraft:entity.wolf.armor_unequip
[19:25:05] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[19:25:05] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[19:25:05] [Render thread/INFO]: OpenAL initialized on device Indbygget lyd Analog stereo
[19:25:05] [Render thread/INFO]: Sound engine started
[19:25:05] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[19:25:05] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[19:25:05] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[19:25:05] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[19:25:05] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[19:25:05] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[19:25:05] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[19:25:05] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[19:25:05] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[19:25:05] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[19:25:05] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[19:25:05] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[19:25:05] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[19:25:05] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas
```

### Crash Report

```
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 2024-01-29 19:28:55
Description: Manually triggered debug crash

java.lang.Throwable: Manually triggered debug crash
	at net.minecraft.class_309.method_1474(class_309.java:520)
	at net.minecraft.class_310.method_1574(class_310.java:2064)
	at net.minecraft.class_310.method_1523(class_310.java:1289)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_309.method_1474(class_309.java:520)

-- Manual crash details --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.class_309.method_1474(class_309.java:520)
	at net.minecraft.class_310.method_1574(class_310.java:2064)
	at net.minecraft.class_310.method_1523(class_310.java:1289)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Uptime --
Details:
	JVM uptime: 238.175s
	Wall uptime: 231.108s
	High-res time: 230.710s
	Client ticks: 4026 ticks / 201.300s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2564)
	at net.minecraft.class_310.method_54580(class_310.java:995)
	at net.minecraft.class_310.method_1514(class_310.java:908)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Affected level --
Details:
	All players: 1 total; [class_746['robotkoer'/141, l='ClientLevel', x=26.50, y=64.00, z=-121.50]]
	Chunk stats: 1024, 565
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,66,-128), Section: (at 0,2,0 in 1,4,-8; chunk contains blocks 16,-64,-128 to 31,319,-113), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 280 game time, 280 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 128

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Linux (amd64) version 6.1.71-1-MANJARO
	Java Version: 17.0.9, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 433642216 bytes (413 MiB) / 1241513984 bytes (1184 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
	Identifier: Intel64 Family 6 Model 126 Stepping 5
	Microarchitecture: Ice Lake (Client)
	Frequency (GHz): 1.30
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Iris Plus Graphics G7
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x8a52
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 12006.81
	Virtual memory used (MB): 6746.41
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 645.89
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	Launched Version: 1.20.4
	Launcher name: PrismLauncher
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: Mesa Intel(R) Iris(R) Plus Graphics (ICL GT2) GL version 4.6 (Core Profile) Mesa 23.3.3-manjaro1.1, Intel
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: fabric
	Current Language: en_us
	Locale: en_EE
	CPU: 8x Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['robotkoer'/141, l='ServerLevel[New World]', x=26.50, y=64.00, z=-121.50]]
	Data Packs: vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
```

**Comment by jellysquid3** [comment]
This is not a bug. The fingerprint is always captured regardless of configuration, by design, and it can be used afterwards.
