### ISSUE TITLE
no sodium 5.8 for 1.20.2???? 

### ISSUE THREAD

**Issue by Allaark** [jellysquid3/Sodium#2384]
### Bug Description

There is no instance of Sodium version 0.5.8 for minecraft version 1.20.2, despite several other mods only for 1.20.2 explicitly declaring a need for sodium 0.5.8.

### Reproduction Steps

1. go to the [modpage for Sodium](https://modrinth.com/mod/sodium)
2. attempt to locate instance of version 0.5.8 of Sodium for Minecraft 1.20.2
3. find no such thing
![No Sodium](https://github.com/CaffeineMC/sodium-fabric/assets/92659523/67b871b0-9c8a-4679-8fe0-ee2f76abf347)

### Log File

[20:53:24] [main/INFO]: Loading Minecraft 1.20.2 with Fabric Loader 0.15.6
[20:53:24] [main/WARN]: Warnings were found!
 - Mod 'BetterF3' (betterf3) 8.0.3 recommends version 8.0.0 or later of modmenu, which is missing!
	 - You should install version 8.0.0 or later of modmenu for the optimal experience.
 - Mod 'Clear Despawn' (cleardespawn) 1.1.15 recommends any version of modmenu, which is missing!
	 - You should install any version of modmenu for the optimal experience.
 - Mod 'ClickThrough' (clickthrough) 1.20.2-fabric0.89.1-0.4.1 recommends any version of modmenu, which is missing!
	 - You should install any version of modmenu for the optimal experience.
 - Mod 'GBfabrictools' (gbfabrictools) 1.4+1.20 recommends any version of modmenu, which is missing!
	 - You should install any version of modmenu for the optimal experience.
[20:53:24] [main/INFO]: Loading 102 mods:
	- appleskin 2.5.1+mc1.20.2
	- badpackets 0.5.6
	- betterf3 8.0.3
	- blur 3.1.1
	   |-- midnightlib 1.5.0
	   \-- satin 1.14.0
	- cleardespawn 1.1.15
	- clickthrough 1.20.2-fabric0.89.1-0.4.1
	   |-- crowdin-translate 1.4+1.19.3
	   \-- gbfabrictools 1.4+1.20
	- cloth-config 12.0.119
	   \-- cloth-basic-math 0.6.1
	- distanthorizons 2.0.1-a
	   |-- fabric-events-interaction-v0 0.6.10+b1792f7da0
	   \-- fabric-rendering-v1 3.0.11+b1792f7da0
	- eatinganimationid 1.20+1.9.5
	- emi 1.1.3+1.20.2+fabric
	- emi_loot 0.6.5+1.20.1
	- fabric-api 0.91.6+1.20.2
	   |-- fabric-api-lookup-api-v1 1.6.43+b1792f7da0
	   |-- fabric-biome-api-v1 13.0.14+b1792f7da0
	   |-- fabric-block-api-v1 1.0.12+73761d2ea0
	   |-- fabric-blockrenderlayer-v1 1.1.43+f4b7e424a0
	   |-- fabric-client-tags-api-v1 1.1.4+86b12645a0
	   |-- fabric-command-api-v1 1.2.37+f71b366fa0
	   |-- fabric-command-api-v2 2.2.16+b1792f7da0
	   |-- fabric-commands-v0 0.2.54+df3654b3a0
	   |-- fabric-containers-v0 0.1.81+df3654b3a0
	   |-- fabric-content-registries-v0 5.0.6+b1792f7da0
	   |-- fabric-convention-tags-v1 1.5.8+b1792f7da0
	   |-- fabric-crash-report-info-v1 0.2.20+f4b7e424a0
	   |-- fabric-data-generation-api-v1 13.1.11+b1792f7da0
	   |-- fabric-dimensions-v1 2.1.57+b1792f7da0
	   |-- fabric-entity-events-v1 1.5.26+b1792f7da0
	   |-- fabric-events-lifecycle-v0 0.2.70+df3654b3a0
	   |-- fabric-game-rule-api-v1 1.0.42+a44e16a6a0
	   |-- fabric-item-api-v1 2.1.33+b1792f7da0
	   |-- fabric-item-group-api-v1 4.0.15+e3d2bf3fa0
	   |-- fabric-key-binding-api-v1 1.0.38+f4b7e424a0
	   |-- fabric-keybindings-v0 0.2.36+df3654b3a0
	   |-- fabric-lifecycle-events-v1 2.2.28+c8b10480a0
	   |-- fabric-loot-api-v2 2.1.1+3ba460fba0
	   |-- fabric-message-api-v1 6.0.2+e3d2bf3fa0
	   |-- fabric-mining-level-api-v1 2.1.56+f4b7e424a0
	   |-- fabric-model-loading-api-v1 1.0.6+b1792f7da0
	   |-- fabric-models-v0 0.4.5+9386d8a7a0
	   |-- fabric-networking-api-v1 3.1.5+f4be560ba0
	   |-- fabric-object-builder-api-v1 12.1.2+2ff98d3ba0
	   |-- fabric-particles-v1 1.1.4+f4b7e424a0
	   |-- fabric-recipe-api-v1 2.0.14+52b3ebe5a0
	   |-- fabric-registry-sync-v0 4.0.12+b1792f7da0
	   |-- fabric-renderer-api-v1 3.2.1+2034447ca0
	   |-- fabric-renderer-indigo 1.5.1+2034447ca0
	   |-- fabric-renderer-registries-v1 3.2.49+df3654b3a0
	   |-- fabric-rendering-v0 1.1.52+df3654b3a0
	   |-- fabric-resource-conditions-api-v1 2.3.11+239dafd8a0
	   |-- fabric-screen-api-v1 2.0.12+b1792f7da0
	   |-- fabric-screen-handler-api-v1 1.3.47+b1792f7da0
	   |-- fabric-sound-api-v1 1.0.14+f4b7e424a0
	   |-- fabric-transfer-api-v1 3.3.13+4944b5a5a0
	   \-- fabric-transitive-access-wideners-v1 5.0.3+fce67b32a0
	- fabric-language-kotlin 1.10.19+kotlin.1.9.23
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.23
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.6
	   \-- mixinextras 0.3.2
	- indium 1.0.30+mc1.20.4
	- java 17
	- minecraft 1.20.2
	- mru 0.4.0+1.20.2
	- music_control 1.7+1.20.2
	   \-- libgui 9.0.0+1.20.2
	        |-- jankson 6.0.0+j1.2.3
	        |    \-- blue_endless_jankson 1.2.3
	        \-- libninepatch 1.2.0
	- sodium 0.5.8+mc1.20.4
	   |-- fabric-api-base 0.4.36+78d798af4f
	   |-- fabric-block-view-api-v2 1.0.4+78d798af4f
	   |-- fabric-rendering-data-attachment-v1 0.3.42+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.0.33+78d798af4f
	   \-- fabric-resource-loader-v0 0.11.17+707e4d1b4f
	- sounds 0.6.0+1.20.2
	   \-- yet_another_config_lib_v3 3.3.0-beta.1+1.20.2
	        |-- com_twelvemonkeys_common_common-image 3.10.0
	        |-- com_twelvemonkeys_common_common-io 3.10.0
	        |-- com_twelvemonkeys_common_common-lang 3.10.0
	        |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	        |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	        |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	        |-- org_quiltmc_parsers_gson 0.2.1
	        \-- org_quiltmc_parsers_json 0.2.1
	- stendhal 1.4.1-1.20.2
	   \-- libgui 9.0.0+1.20.2
	        |-- jankson 6.0.0+j1.2.3
	        |    \-- blue_endless_jankson 1.2.3
	        \-- libninepatch 1.2.0
	- wthit 9.5.0
[20:53:25] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/com.modrinth.theseus/meta/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[20:53:25] [main/INFO]: Compatibility level set to JAVA_17
[20:53:25] [main/WARN]: Reference map 'de-guntram-mcmod-fabrictools-refmap.json' for mixins.de-guntram-mcmod-fabrictools.json could not be read. If this is a development environment you can ignore this message
[20:53:25] [main/WARN]: Reference map 'mru-refmap.json' for mru.mixins.json could not be read. If this is a development environment you can ignore this message
[20:53:25] [main/WARN]: [Satin] Sodium is present, custom block renders may not work
[20:53:25] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 0 override(s) found
[20:53:25] [main/WARN]: Error loading class: mezz/jei/library/load/PluginCaller (java.lang.ClassNotFoundException: mezz/jei/library/load/PluginCaller)
[20:53:26] [main/WARN]: Error loading class: net/minecraft/class_8819 (java.lang.ClassNotFoundException: net/minecraft/class_8819)
[20:53:26] [main/WARN]: @Mixin target net.minecraft.class_8819 was not found sodium.mixins.json:core.gui.WorldLoadingStateMixin from mod sodium
[20:53:26] [main/WARN]: Error loading class: org/jetbrains/annotations/ApiStatus$Internal (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$Internal)
[20:53:26] [main/INFO]: Searching for graphics cards...
[20:53:26] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[20:53:26] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=AMD, name=Radeon RX 570 Series, version=DriverVersion=31.0.14051.5006]
[20:53:27] [main/WARN]: Invalid registry value type detected for PerfOS counters. Should be REG_DWORD. Ignoring: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PerfOS\Performance\Disable Performance Counters.
[20:53:31] [Datafixer Bootstrap/INFO]: 192 Datafixer optimizations took 143 milliseconds
[20:53:33] [main/ERROR]: Mixin apply for mod emi_loot failed emi_loot.mixins.json:LootPoolEntryAccessor from mod emi_loot -> net.minecraft.class_79: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching field_988:[Lnet/minecraft/class_5341; in net/minecraft/class_79 for emi_loot.mixins.json:LootPoolEntryAccessor from mod emi_loot->@Accessor[FIELD_GETTER]::getConditions()[Lnet/minecraft/class_5341; [INJECT Applicator Phase -> emi_loot.mixins.json:LootPoolEntryAccessor from mod emi_loot -> Apply Accessors ->  -> Locate -> emi_loot.mixins.json:LootPoolEntryAccessor from mod emi_loot->@Accessor[FIELD_GETTER]::getConditions()[Lnet/minecraft/class_5341;]
org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching field_988:[Lnet/minecraft/class_5341; in net/minecraft/class_79 for emi_loot.mixins.json:LootPoolEntryAccessor from mod emi_loot->@Accessor[FIELD_GETTER]::getConditions()[Lnet/minecraft/class_5341; [INJECT Applicator Phase -> emi_loot.mixins.json:LootPoolEntryAccessor from mod emi_loot -> Apply Accessors ->  -> Locate -> emi_loot.mixins.json:LootPoolEntryAccessor from mod emi_loot->@Accessor[FIELD_GETTER]::getConditions()[Lnet/minecraft/class_5341;]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:519) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:502) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:476) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1411) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1071) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.class_75.<clinit>(class_75.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47515(class_7923.java:150) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47485(class_7923.java:219) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47482(class_7923.java:234) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(Unknown Source) ~[?:?]
	at net.minecraft.class_7923.method_47487(class_7923.java:232) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.redirect$zko000$fabric-registry-sync-v0$initialize(class_2966.java:565) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:169) ~[1.20.2-0.15.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
[20:53:33] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_79 failed
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_79 failed
	at net.minecraft.class_75.<clinit>(class_75.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47515(class_7923.java:150) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47485(class_7923.java:219) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47482(class_7923.java:234) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(Unknown Source) ~[?:?]
	at net.minecraft.class_7923.method_47487(class_7923.java:232) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.redirect$zko000$fabric-registry-sync-v0$initialize(class_2966.java:565) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:169) ~[1.20.2-0.15.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_79 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.class_75.<clinit>(class_75.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47515(class_7923.java:150) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47485(class_7923.java:219) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47482(class_7923.java:234) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(Unknown Source) ~[?:?]
	at net.minecraft.class_7923.method_47487(class_7923.java:232) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.redirect$zko000$fabric-registry-sync-v0$initialize(class_2966.java:565) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:169) ~[1.20.2-0.15.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.class_75.<clinit>(class_75.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47515(class_7923.java:150) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47485(class_7923.java:219) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47482(class_7923.java:234) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(Unknown Source) ~[?:?]
	at net.minecraft.class_7923.method_47487(class_7923.java:232) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.redirect$zko000$fabric-registry-sync-v0$initialize(class_2966.java:565) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:169) ~[1.20.2-0.15.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [emi_loot.mixins.json:LootPoolEntryAccessor from mod emi_loot] from phase [DEFAULT] in config [emi_loot.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.class_75.<clinit>(class_75.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47515(class_7923.java:150) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47485(class_7923.java:219) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47482(class_7923.java:234) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(Unknown Source) ~[?:?]
	at net.minecraft.class_7923.method_47487(class_7923.java:232) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.redirect$zko000$fabric-registry-sync-v0$initialize(class_2966.java:565) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:169) ~[1.20.2-0.15.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching field_988:[Lnet/minecraft/class_5341; in net/minecraft/class_79 for emi_loot.mixins.json:LootPoolEntryAccessor from mod emi_loot->@Accessor[FIELD_GETTER]::getConditions()[Lnet/minecraft/class_5341; [INJECT Applicator Phase -> emi_loot.mixins.json:LootPoolEntryAccessor from mod emi_loot -> Apply Accessors ->  -> Locate -> emi_loot.mixins.json:LootPoolEntryAccessor from mod emi_loot->@Accessor[FIELD_GETTER]::getConditions()[Lnet/minecraft/class_5341;]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:519) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:502) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:476) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1411) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1071) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.class_75.<clinit>(class_75.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47515(class_7923.java:150) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47485(class_7923.java:219) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47482(class_7923.java:234) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(Unknown Source) ~[?:?]
	at net.minecraft.class_7923.method_47487(class_7923.java:232) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.redirect$zko000$fabric-registry-sync-v0$initialize(class_2966.java:565) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:169) ~[1.20.2-0.15.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	... 2 more

### Crash Report

[crash-2024-03-19_20.18.43-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14659118/crash-2024-03-19_20.18.43-client.txt)

**Comment by jellysquid3** [comment]
There is no version of Sodium 0.5.8 for Minecraft 1.20.2. If you use the [search tool](https://modrinth.com/mod/sodium/versions?l=fabric&g=1.20.2&c=release) on Modrinth then you'll see versions 0.5.3, 0.5.4, and 0.5.5 are available, though. If other mods are falsely claiming to depend on Sodium 0.5.8 for Minecraft 1.20.2, that's a bug with the other mod.

```
[main/ERROR]: Mixin apply for mod emi_loot failed emi_loot.mixins.json:LootPoolEntryAccessor from mod emi_loot...
```

However, your crash still doesn't seem to have anything to do with Sodium. You have other mods (EMI) which are failing to apply mixins, probably because they aren't designed for the version of Minecraft you are using. Though it's impossible to tell what's really going on here, because the crash log you have uploaded does not seem to be related to the log file (they both mention a completely different set of mods).
