### ISSUE TITLE
Invalid Config Path causing Crashes when Loading

### ISSUE THREAD

**Issue by Universal-Flare** [jellysquid3/Sodium#2390]
### Bug Description

Loading Minecraft causes freezing and leads to a Crash when Loading a World
**ERROR WHILE MINECRAFT IS LOADING :-** 
`[11:41:21] [main/WARN]: Error loading class: net/caffeinemc/sodium/config/user/UserConfigCategories (java.lang.ClassNotFoundException: net/caffeinemc/sodium/config/user/UserConfigCategories)
[11:41:21] [main/WARN]: Error loading class: net/caffeinemc/sodium/config/user/UserConfigCategories (java.lang.ClassNotFoundException: net/caffeinemc/sodium/config/user/UserConfigCategories)
[11:41:22] [main/WARN]: Error loading class: org/jetbrains/annotations/ApiStatus$Internal (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$Internal)
[11:41:22] [main/WARN]: Error loading class: org/jetbrains/annotations/ApiStatus$Internal (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$Internal)`

**ERROR WHILE WORLD IS LOADING :-** 
`[11:44:03] [Render thread/ERROR]: Unreported exception thrown!
java.lang.RuntimeException: Shader compilation failed, see log for details
	at me.jellysquid.mods.sodium.client.gl.shader.GlShader.<init>(GlShader.java:34) ~[sodium-fabric-0.5.8+mc1.20.1.jar:?]
	at me.jellysquid.mods.sodium.client.gl.shader.ShaderLoader.loadShader(ShaderLoader.java:22) ~[sodium-fabric-0.5.8+mc1.20.1.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.createShader(ShaderChunkRenderer.java:48) ~[sodium-fabric-0.5.8+mc1.20.1.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.compileProgram(ShaderChunkRenderer.java:36) ~[sodium-fabric-0.5.8+mc1.20.1.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java:72) ~[sodium-fabric-0.5.8+mc1.20.1.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.DefaultChunkRenderer.render(DefaultChunkRenderer.java:48) ~[sodium-fabric-0.5.8+mc1.20.1.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:217) ~[sodium-fabric-0.5.8+mc1.20.1.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:226) ~[sodium-fabric-0.5.8+mc1.20.1.jar:?]
	at net.minecraft.class_761.method_3251(class_761.java:14515) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1253) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:880) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]`

**LOG AFTER CRASH :-** 
`java.lang.RuntimeException: Shader compilation failed, see log for details
	at me.jellysquid.mods.sodium.client.gl.shader.GlShader.<init>(GlShader.java:34)
	at me.jellysquid.mods.sodium.client.gl.shader.ShaderLoader.loadShader(ShaderLoader.java:22)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.createShader(ShaderChunkRenderer.java:48)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.compileProgram(ShaderChunkRenderer.java:36)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java:72)
	at me.jellysquid.mods.sodium.client.render.chunk.DefaultChunkRenderer.render(DefaultChunkRenderer.java:48)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:217)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:226)
	at net.minecraft.class_761.method_3251(class_761.java:14515)
	at net.minecraft.class_761.method_22710(class_761.java:1253)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)`

**EXIT CODE =** -1073740791

### Reproduction Steps

NO CLUE

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14753745/latest.log)

### Crash Report

[crash-2024-03-26_11.44.22-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14753715/crash-2024-03-26_11.44.22-client.txt)

**Comment by yamayaki1** [comment]
This is not a bug caused by Sodium. The mod **blendium** is incompatible with newer versions of this mod. See this issue made by the mod author: https://github.com/Steveplays28/blendium/issues/19
