### ISSUE TITLE
Sodium is not compatible with Minecraft 1.20.6 while listed as supported

### ISSUE THREAD

**Issue by alexitx** [jellysquid3/Sodium#2529]
### Bug Description

Sodium 0.5.8 is not compatible with Minecraft 1.20.6 while listed as supporting 1.20.5-1.20.6

### Reproduction Steps

1. Install Fabric 0.15.11 on Minecraft 1.20.6
2. Download Sodium 0.5.8 and Fabric API 0.99.4
3. Launch the game

### Log File

```
[22:13:09] [main/WARN]: Mod resolution failed
[22:13:09] [main/INFO]: Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED sodium 0.5.8+mc1.20.5 {depends minecraft @ [1.20.5]}, ROOT_FORCELOAD_SINGLE sodium 0.5.8+mc1.20.5]
[22:13:09] [main/INFO]: Reason: [HARD_DEP sodium 0.5.8+mc1.20.5 {depends minecraft @ [1.20.5]}]
[22:13:09] [main/INFO]: Fix: add [], remove [], replace [[minecraft 1.20.6] -> add:minecraft 1.20.5 ([[1.20.5,1.20.5]])]
[22:13:09] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace 'Minecraft' (minecraft) 1.20.6 with version 1.20.5.
More details:
	 - Mod 'Sodium' (sodium) 0.5.8+mc1.20.5 requires version 1.20.5 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.6!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

### Crash Report

N/A

**Comment by Lolothepro** [comment]
Please use the Modrinth build

**Comment by alexitx** [comment]
I don't use Modrinth. On your CurseForge page it's incorrectly listed as compatible with 1.20.6 and since this is latest version of Sodium it's confusing:
![unknown](https://github.com/CaffeineMC/sodium-fabric/assets/26458119/3da4b19b-274b-425e-ab27-fc1a56fc345b)

Is full support for 1.20.6 going to be out soon on all platforms?

**Comment by douira** [comment]
It's listed wrongly on curseforge, you can download the correct build [here](https://modrinth.com/mod/sodium/version/mc1.20.6-0.5.8).

**Comment by alexitx** [comment]
Thanks, though both of these versions share the same name (0.5.8 for 1.20.5–1.20.6) and there's no GitHub tag for 1.20.6 either, so I assume it's not fully released?

**Comment by douira** [comment]
the name of the jar is distinct, one is 1.20.5 and the other is 1.20.6

**Comment by alexitx** [comment]
I see. Is it going to be uploaded to CurseForge any time soon? It's easier for me to download all mods from there.

**Comment by jellysquid3** [comment]
I've asked @IMS212 a few times about it, but they've insisted there's not a problem. No idea what's going on. But there's been enough reports that it's obvious something is wrong.

**Comment by IMS212** [comment]
I’ve uploaded a new file; it should be fixed now.
