### ISSUE TITLE
Game crashes if GPU model name contains special characters

### ISSUE THREAD

**Issue by Criperto** [jellysquid3/Sodium#2545]
### Bug Description

When I try to start Minecraft with Sodium and Iris, I get an error saying that Sodium doesn't work.

### Reproduction Steps

1: Place the mods in the mods folder.
2: Start Minecraft with the Fabric installation.
3: It doesn't start and an error appears.

### Log File

[13:30:07] [main/INFO]: Loading Minecraft 1.21 with Fabric Loader 0.15.11
[13:30:08] [main/INFO]: Loading 57 mods:
	- fabric-api 0.100.1+1.21
	   |-- fabric-api-base 0.4.42+6573ed8c90
	   |-- fabric-api-lookup-api-v1 1.6.65+b559734490
	   |-- fabric-biome-api-v1 13.0.28+6fc22b9990
	   |-- fabric-block-api-v1 1.0.22+0af3f5a790
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8c90
	   |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a790
	   |-- fabric-client-tags-api-v1 1.1.15+6573ed8c90
	   |-- fabric-command-api-v1 1.2.48+f71b366f90
	   |-- fabric-command-api-v2 2.2.27+6a6dfa1990
	   |-- fabric-commands-v0 0.2.65+df3654b390
	   |-- fabric-content-registries-v0 8.0.11+b559734490
	   |-- fabric-convention-tags-v1 2.0.12+7f945d5b90
	   |-- fabric-convention-tags-v2 2.2.1+d153f34490
	   |-- fabric-crash-report-info-v1 0.2.29+0af3f5a790
	   |-- fabric-data-attachment-api-v1 1.1.22+6a6dfa1990
	   |-- fabric-data-generation-api-v1 20.2.6+16c4ae2590
	   |-- fabric-dimensions-v1 4.0.0+6fc22b9990
	   |-- fabric-entity-events-v1 1.6.12+6fc22b9990
	   |-- fabric-events-interaction-v0 0.7.10+e633f88390
	   |-- fabric-game-rule-api-v1 1.0.52+6573ed8c90
	   |-- fabric-item-api-v1 11.0.0+afdfc92190
	   |-- fabric-item-group-api-v1 4.1.0+00ab0a6390
	   |-- fabric-key-binding-api-v1 1.0.47+0af3f5a790
	   |-- fabric-keybindings-v0 0.2.45+df3654b390
	   |-- fabric-lifecycle-events-v1 2.3.9+98a7dbbb90
	   |-- fabric-loot-api-v2 3.0.9+6573ed8c90
	   |-- fabric-message-api-v1 6.0.13+6573ed8c90
	   |-- fabric-model-loading-api-v1 2.0.0+fe474d6b90
	   |-- fabric-networking-api-v1 4.1.0+686dcdce90
	   |-- fabric-object-builder-api-v1 15.1.10+d132107690
	   |-- fabric-particles-v1 4.0.2+6573ed8c90
	   |-- fabric-recipe-api-v1 5.0.8+6573ed8c90
	   |-- fabric-registry-sync-v0 5.0.21+b9828ba390
	   |-- fabric-renderer-api-v1 3.2.16+fe474d6b90
	   |-- fabric-renderer-indigo 1.6.3+cc9f121a90
	   |-- fabric-renderer-registries-v1 3.2.66+df3654b390
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2e90
	   |-- fabric-rendering-fluids-v1 3.1.6+b559734490
	   |-- fabric-rendering-v0 1.1.69+df3654b390
	   |-- fabric-rendering-v1 5.0.3+d132107690
	   |-- fabric-resource-conditions-api-v1 4.2.1+d153f34490
	   |-- fabric-resource-loader-v0 1.1.3+b559734490
	   |-- fabric-screen-api-v1 2.0.24+b559734490
	   |-- fabric-screen-handler-api-v1 1.3.78+b559734490
	   |-- fabric-sound-api-v1 1.0.23+6573ed8c90
	   |-- fabric-transfer-api-v1 5.1.12+b559734490
	   \-- fabric-transitive-access-wideners-v1 6.0.12+6573ed8c90
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- iris 1.7.1+mc1.21
	   |-- fabric-api-base 0.4.42+6573ed8c90
	   |-- fabric-key-binding-api-v1 1.0.47+0af3f5a790
	   |-- io_github_douira_glsl-transformer 2.0.1
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.13.1
	- java 21
	- minecraft 1.21
	- sodium 0.5.9+mc1.21
	   |-- fabric-api-base 0.4.42+6573ed8c90
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8c90
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2e90
	   |-- fabric-rendering-fluids-v1 3.1.6+b559734490
	   \-- fabric-resource-loader-v0 1.1.3+b559734490
[13:30:10] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/PC/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[13:30:14] [main/INFO]: Compatibility level set to JAVA_17
[13:30:15] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 3 override(s) found
[13:30:16] [main/WARN]: Force-disabling mixin 'features.render.entity.CuboidMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[13:30:16] [main/WARN]: Force-disabling mixin 'features.render.entity.ModelPartMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[13:30:16] [main/WARN]: Force-disabling mixin 'features.render.entity.cull.EntityRendererMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[13:30:16] [main/WARN]: Force-disabling mixin 'features.render.entity.shadows.EntityRenderDispatcherMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[13:30:16] [main/WARN]: Force-disabling mixin 'features.render.gui.font.GlyphRendererMixin' as rule 'mixin.features.render.gui.font' (added by mods [iris]) disables it and children
[13:30:16] [main/WARN]: Force-disabling mixin 'features.render.world.sky.BackgroundRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[13:30:16] [main/WARN]: Force-disabling mixin 'features.render.world.sky.ClientWorldMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[13:30:16] [main/WARN]: Force-disabling mixin 'features.render.world.sky.WorldRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[13:30:16] [main/INFO]: Searching for graphics cards...
[13:30:17] [main/INFO]: Found graphics adapter: AdapterInfo{vendor=AMD, description='AMD 15D8:C9', adapterType=0x0000232B, openglIcdFilePath='C:\WINDOWS\System32\DriverStore\FileRepository\u0400376.inf_amd64_fdce69582fa3a6b8\B400781\atig6pxx.dll', openglIcdVersion=31.0.21912.14}
[13:30:17] [main/ERROR]: A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.15.11.jar:?]
	... 2 more
Caused by: java.lang.IllegalArgumentException: NTFS ADS separator (':') in file name is forbidden.
	at org.apache.commons.io.FilenameUtils.indexOfExtension(FilenameUtils.java:955) ~[commons-io-2.15.1.jar:?]
	at org.apache.commons.io.FilenameUtils.removeExtension(FilenameUtils.java:1427) ~[commons-io-2.15.1.jar:?]
	at me.jellysquid.mods.sodium.client.platform.windows.api.d3dkmt.D3DKMT.getOpenGlIcdName(D3DKMT.java:210) ~[sodium-fabric-0.5.9+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.platform.windows.api.d3dkmt.D3DKMT$WDDMAdapterInfo.getOpenGlIcdName(D3DKMT.java:199) ~[sodium-fabric-0.5.9+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.compatibility.checks.PreLaunchChecks.findIntelDriverMatchingBug899(PreLaunchChecks.java:83) ~[sodium-fabric-0.5.9+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.compatibility.checks.PreLaunchChecks.onGameInit(PreLaunchChecks.java:24) ~[sodium-fabric-0.5.9+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.SodiumPreLaunch.onPreLaunch(SodiumPreLaunch.java:12) ~[sodium-fabric-0.5.9+mc1.21.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.15.11.jar:?]
	... 2 more

### Crash Report

A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	... 2 more
Caused by: java.lang.IllegalArgumentException: NTFS ADS separator (':') in file name is forbidden.
	at org.apache.commons.io.FilenameUtils.indexOfExtension(FilenameUtils.java:955)
	at org.apache.commons.io.FilenameUtils.removeExtension(FilenameUtils.java:1427)
	at me.jellysquid.mods.sodium.client.platform.windows.api.d3dkmt.D3DKMT.getOpenGlIcdName(D3DKMT.java:210)
	at me.jellysquid.mods.sodium.client.platform.windows.api.d3dkmt.D3DKMT$WDDMAdapterInfo.getOpenGlIcdName(D3DKMT.java:199)
	at me.jellysquid.mods.sodium.client.compatibility.checks.PreLaunchChecks.findIntelDriverMatchingBug899(PreLaunchChecks.java:83)
	at me.jellysquid.mods.sodium.client.compatibility.checks.PreLaunchChecks.onGameInit(PreLaunchChecks.java:24)
	at me.jellysquid.mods.sodium.client.SodiumPreLaunch.onPreLaunch(SodiumPreLaunch.java:12)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 3 more

**Comment by Lolothepro** [comment]
`Caused by: java.lang.IllegalArgumentException: NTFS ADS separator (':') in file name is forbidden.`
HOW

**Comment by jellysquid3** [comment]
Probably caused by [this code](https://github.com/CaffeineMC/sodium-fabric/blob/dev/src/main/java/net/caffeinemc/mods/sodium/client/platform/windows/api/d3dkmt/D3DKMT.java#L199) using the incorrect variable (`name` instead of `openglIcdFileName`)...

**Comment by AlexPewMaster** [comment]
Can confirm that this is an issue on Windows. Just downloaded the latest Fabulously Optimized alpha version and got this error. Here are the logs: https://mclo.gs/QBkYVx8

**Comment by jellysquid3** [comment]
We have a patch for the problem and others report that it works fine. A release will be published with the patch in the upcoming days.
