### ISSUE TITLE
Game crashes at startup with GetFileVersionInfoSizeW failed, error=127

### ISSUE THREAD

**Issue by Prezriw** [jellysquid3/Sodium#2550]
### Bug Description

When I start minecraft, sodium crashes with the following error.

A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	... 2 more
Caused by: java.lang.RuntimeException: GetFileVersionInfoSizeW failed, error=127
	at me.jellysquid.mods.sodium.client.platform.windows.api.version.Version.getModuleFileVersion(Version.java:63)
	at me.jellysquid.mods.sodium.client.platform.windows.api.d3dkmt.D3DKMT.queryDriverVersion(D3DKMT.java:127)
	at me.jellysquid.mods.sodium.client.platform.windows.api.d3dkmt.D3DKMT.getAdapterInfo(D3DKMT.java:95)
	at me.jellysquid.mods.sodium.client.platform.windows.api.d3dkmt.D3DKMT.queryAdapters(D3DKMT.java:58)
	at me.jellysquid.mods.sodium.client.platform.windows.api.d3dkmt.D3DKMT.findGraphicsAdapters(D3DKMT.java:44)
	at me.jellysquid.mods.sodium.client.compatibility.environment.probe.GraphicsAdapterProbe.findAdapters$Windows(GraphicsAdapterProbe.java:48)
	at me.jellysquid.mods.sodium.client.compatibility.environment.probe.GraphicsAdapterProbe.findAdapters(GraphicsAdapterProbe.java:25)
	at me.jellysquid.mods.sodium.client.SodiumPreLaunch.onPreLaunch(SodiumPreLaunch.java:11)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 3 more

### Reproduction Steps

I Start Mincraft through Modrinth App. with fabric loader 0.15.11, and only 2 mods, Fabric API 0.100.1+1.21 and Sodium MC1.21-0.5.7

### Log File

[latest.log](https://github.com/user-attachments/files/15865512/latest.log)

### Crash Report

no crash report generated

**Comment by jellysquid3** [comment]
Can you please provide information on what operating system and hardware/drivers you're using? There's nothing here to diagnose the issue. Error 127 is `ERROR_PROC_NOT_FOUND`  which really shouldn't happen for the `GetFileVersionInfoSizeW` function, since that's available from Windows 2000 onward.

**Comment by Prezriw** [comment]
Hi Jelly,

I have windows 10 Pro 64 bit build 19045 on a Gigabyte P85-D3 Mainboard, i3-4160 CPU, 32GB Memory, Nvidia Geforce GTX 1650 with driver 555.99.

I hope this help

**Comment by jellysquid3** [comment]
Can you see if [this build](https://nightly.link/CaffeineMC/sodium-fabric/suites/9551220247/artifacts/1609353425) fixes the problem? If not, please attach a new log file.

**Comment by kerrschtein** [comment]
that seems to fix it for me!

**Comment by Prezriw** [comment]
[MODERATOR EDIT: Uploaded log file to GitHub Gist.]

Log file: https://gist.github.com/jellysquid3/e62befe7bfa471074294c18d7675f0f3

**Comment by jellysquid3** [comment]
It seems to load the version information for the NVIDIA driver without issue, but the Intel driver (ig75icd64.dll) fails. What's more troubling is that we don't get a full path to the driver file, which is probably why querying the version information does not work.

So I guess we'd have to follow DLL search paths to see _where_ the Intel driver is being loaded from...

**Comment by jellysquid3** [comment]
@Prezriw I've written a workaround to deal with the Intel graphics drivers being weird. Please try [this build](https://nightly.link/CaffeineMC/sodium-fabric/suites/9551926777/artifacts/1609547185) and upload a log file if it does not work.

**Comment by Prezriw** [comment]
[latest.log](https://github.com/user-attachments/files/15886667/latest.log)

**Comment by jellysquid3** [comment]
Not sure. Seems that it can't find the OpenGL ICD in `%SYSTEMROOT%/System32` either, or my code is wrong. I'll need to look at it more closely once I have access to my regular computer again.

**Comment by Prezriw** [comment]
thank you very much

**Comment by Strong03** [comment]
also having the same issue with sodium and fabric not loading properly would love a fix for this as nothing has worked yet
Thanks in advance!

**Comment by blunderbust** [comment]
Ive also had this issue, using AMD 7900 xt gpu using latest amd drivers.

**Comment by chirrupted** [comment]
also having this issue. RTX 3050 Ti with latest drivers

**Comment by jellysquid3** [comment]
Please, make absolute certain the _exact_ error you're seeing is:

`Caused by: java.lang.RuntimeException: GetFileVersionInfoSizeW failed, error=127`

If you are getting this error, see [this comment](https://github.com/CaffeineMC/sodium-fabric/issues/2550#issuecomment-2173937094) and run the build which is attached. Then, upload your log file (as an attachment) so that we can look into what's going on.

**Comment by blunderbust** [comment]
I went back to verify, and no I do not have this exact error. I had started to follow this issue when it was more generic as I was having immediate crashes when using sodium 5.10, and saw gpu lines in the log.  here is my log (just running 5.10, not special build):

[latest.log](https://github.com/user-attachments/files/15949856/latest.log)

If this is unrelated I can start a separate issue.

**Comment by jellysquid3** [comment]
@blunderbust Your issue is unrelated. You have the wrong versions of LWJGL installed. See #2561.

**Comment by blunderbust** [comment]
yes, correcting my version of LWJGL fixed it. I apologize for cluttering up this issue.  Thanks for the help!

**Comment by ZedDevStuff** [comment]
So i have no idea if it was related or not but i changed my LWJGL version to 3.3.3 and it started correctly. I noticed a message before the crash talking about an unsupported jni version saying it could cause crashes, so i updated LWJGL and it worked. I updated my instance from 1.20.1 so it might not be a problem to anyone else but if you can update LWJGL, try that

**Comment by Prezriw** [comment]
I have disabled my intel video card in my bios, and sodium is working with ver. mc1.21-059

so it seems that the problem might be with the Intel video.

Thank you Jelly.

**Comment by douira** [comment]
Is this still current?
