### ISSUE TITLE
Errorcode=-1

### ISSUE THREAD

**Issue by baesjasa** [jellysquid3/Sodium#2566]
### Bug Description

i want to use iris shader so i was downloading sodium (windows 11)

### Reproduction Steps

windows 11, mc 1.21, sodium pack

### Log File

not writing this for some reason

### Crash Report

java.lang.NoSuchMethodError: 'me.jellysquid.mods.sodium.client.render.vertex.buffer.SodiumBufferBuilder me.jellysquid.mods.sodium.client.render.vertex.buffer.ExtendedBufferBuilder.sodium$getDelegate()'
	at traben.entity_texture_features.compat.SodiumGetBufferInjector$Impl.accept(SodiumGetBufferInjector.java:42)
	at traben.entity_texture_features.compat.SodiumGetBufferInjector$Impl.accept(SodiumGetBufferInjector.java:34)
	at traben.entity_texture_features.compat.SodiumGetBufferInjector.inject(SodiumGetBufferInjector.java:23)
	at net.minecraft.class_4597$class_4598.handler$zdg000$entity_texture_features$etf$injectIntoGetBufferReturn(class_4597.java:536)
	at net.minecraft.class_4597$class_4598.getBuffer(class_4597.java:64)
	at net.minecraft.class_332.method_48196(class_332.java:218)
	at net.minecraft.class_332.method_51737(class_332.java:199)
	at net.minecraft.class_332.method_25294(class_332.java:195)
	at net.minecraft.class_425.method_18103(class_425.java:167)
	at net.minecraft.class_425.method_25394(class_425.java:139)
	at net.minecraft.class_757.method_3192(class_757.java:902)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by jellysquid3** [comment]
You did not read the issue template. This is not a support forum. You failed to install the mod correctly.
