### ISSUE TITLE
The game crashed whilst unexpected error

### ISSUE THREAD

**Issue by TinhoCarrara** [jellysquid3/Sodium#2576]
### Bug Description

game closes immediately at the end of world rendering.

### Reproduction Steps

Start any world and the game will close.

### Log File

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2024-06-26 04:26:23
Description: Unexpected error

java.lang.RuntimeException: Mixin transformation of me.jellysquid.mods.sodium.client.render.immediate.CloudRenderer failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.minecraft.class_761.method_3259(class_761.java:12199)
	at net.minecraft.class_761.method_22710(class_761.java:1294)
	at net.minecraft.class_757.method_3188(class_757.java:1093)
	at net.minecraft.class_757.method_3192(class_757.java:858)
	at net.minecraft.class_310.method_1523(class_310.java:1320)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 14 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.iris.compat.sodium.json:clouds.MixinCloudRenderer from mod iris] from phase [DEFAULT] in config [mixins.iris.compat.sodium.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 17 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on buildIrisVertexBuffer could not find any targets matching 'render(Lnet/minecraft/class_638;Lnet/minecraft/class_746;Lnet/minecraft/class_4587;Lorg/joml/Matrix4f;Lorg/joml/Matrix4f;FFDDD)V' in me.jellysquid.mods.sodium.client.render.immediate.CloudRenderer. No refMap loaded. [PREINJECT Applicator Phase -> mixins.iris.compat.sodium.json:clouds.MixinCloudRenderer from mod iris -> Prepare Injections ->  -> handler$cal000$iris$buildIrisVertexBuffer(Lnet/minecraft/class_638;Lnet/minecraft/class_746;Lnet/minecraft/class_4587;Lorg/joml/Matrix4f;Lorg/joml/Matrix4f;FFDDDLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:658)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:589)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:710)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.minecraft.class_761.method_3259(class_761.java:12199)
	at net.minecraft.class_761.method_22710(class_761.java:1294)
	at net.minecraft.class_757.method_3188(class_757.java:1093)

-- Uptime --
Details:
	JVM uptime: 31.227s
	Wall uptime: 18.167s
	High-res time: 13.833s
	Client ticks: 157 ticks / 7.850s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2548)
	at net.minecraft.class_310.method_54580(class_310.java:983)
	at net.minecraft.class_310.method_1514(class_310.java:911)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Erhoz'/914300, l='ClientLevel', x=-508.18, y=73.00, z=-394.52]]
	Chunk stats: 16384, 237
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,70,48), Section: (at 0,6,0 in -2,4,3; chunk contains blocks -32,-64,48 to -17,319,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 120698642 game time, 126593625 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
	Tracked entity count: 361

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, azurelib, backpacked, bakingmod, balm-fabric, boxlib, cardinal-components-base, cardinal-components-entity, catalogue, cloth-config, configured, controlify, cookingforblockheads, coordinatesdisplay, ctov, detailab, dispenser_configurator, distanthorizons, dynamiclights, elytra_trinket, elytratrims, emeraldapple, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, framework, gigeresque, indium, iris, jankson, lchunkloader, libertyvillagers, libgui, lithium, modmenu, more_gems, mostructures, omega-config, philipsruins, sandwichmod, shulkerboxtooltip, simple-armor-hud, skinlayers3d, sodium, sushimod, terralith, trinkets, yet_another_config_lib_v3

-- System Details --
Details:
	Minecraft Version: 1.20.6
	Minecraft Version ID: 1.20.6
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 442962752 bytes (422 MiB) / 905969664 bytes (864 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: Comet Lake
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 20
	Graphics card #0 name: NVIDIA GeForce RTX 3070
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MB): 8192.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.5599
	Graphics card #1 name: Microsoft Basic Display Adapter
	Graphics card #1 vendor: Microsoft
	Graphics card #1 VRAM (MB): 0.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 10.0.22621.1
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 16384.00
	Memory slot #2 clockSpeed (GHz): 3.20
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 16384.00
	Memory slot #3 clockSpeed (GHz): 3.20
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 75146.08
	Virtual memory used (MB): 22710.47
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		azurelib: AzureLib 2.2.6
		backpacked: Backpacked 3.0.0-beta.5
		bakingmod: Baking Mod 1.1.1
		balm-fabric: Balm 10.3.3
			kuma_api: KumaAPI 20.6.4
		boxlib: BoxLib 13.0.2
		catalogue: Catalogue 1.10.1
		cloth-config: Cloth Config v14 14.0.126
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.61
		configured: Configured 2.4.0
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		controlify: Controlify 2.0.0-beta.10+1.20.6
			dev_isxander_libsdl4j: libsdl4j 3.693c75e-36
			org_hid4java_hid4java: hid4java 0.7.0
			org_quiltmc_parsers_gson: gson 0.3.0
			org_quiltmc_parsers_json: json 0.3.0
		cookingforblockheads: Cooking for Blockheads 19.0.2
		coordinatesdisplay: CoordinatesDisplay 10.0.0
		ctov: ChoiceTheorem's Overhauled Village 3.4.4
		detailab: Detail Armor Bar 2.6.3+1.20.6-fabric
		dispenser_configurator: Dispenser Configurator 1.2.15
		distanthorizons: Distant Horizons 2.1.2-a
			fabric-api-base: Fabric API Base 0.4.40+80f8cf51ff
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.6+c5fc38b3ff
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.45+80f8cf51ff
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.4+c5fc38b3ff
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.21+7b70ea8aff
		dynamiclights: Dynamic Lights 1.8.2+mod
		elytra_trinket: Elytra Trinket 1.0.7
		elytratrims: Elytra Trims 3.2.0
			mixinsquared: MixinSquared 0.1.2-beta.4
		emeraldapple: Emerald Apple 1.0.5
		explorify: Explorify 1.5.0
		fabric-api: Fabric API 0.100.4+1.20.6
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.59+e9d2a72bb0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.25+be5d88beb0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.20+6dfe4c9bb0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.8+80f8cf51b0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.50+80f8cf51b0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.12+7f945d5bb0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.45+f71b366fb0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.24+80f8cf51b0
			fabric-commands-v0: Fabric Commands (v0) 0.2.62+df3654b3b0
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.6+b82b2392b0
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.7+7f945d5bb0
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.1.3+f4bfb622b0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.27+80f8cf51b0
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.17+2a2c66b6b0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 19.2.4+a5d5299db0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.68+94793913b0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.8+e9d2a72bb0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.50+80f8cf51b0
			fabric-item-api-v1: Fabric Item API (v1) 8.2.3+6e5bbc4ab0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.1+f4bfb622b0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.43+df3654b3b0
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.6+97f703dab0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.11+a7dc0e41b0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.12+80f8cf51b0
			fabric-models-v0: Fabric Models (v0) 0.4.11+9386d8a7b0
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.0+a916f7c5b0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.5+c5fc38b3b0
			fabric-particles-v1: Fabric Particles (v1) 4.0.0+c5fc38b3b0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.6+9c745bbbb0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.18+a916f7c5b0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.3.0+81dac6a1b0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.15+41791025b0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.62+df3654b3b0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.46+73761d2eb0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.3+2c869dedb0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.65+df3654b3b0
			fabric-rendering-v1: Fabric Rendering (v1) 4.2.5+850ef40bb0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.0+a5d5299db0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.1+f4bfb622b0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.75+8c7b71c2b0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.21+c5fc38b3b0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.7+7fc4b352b0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.10+74e2f560b0
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		framework: Framework 0.8.13
			org_javassist_javassist: javassist 3.29.2-GA
			org_reflections_reflections: reflections 0.10.2
		geckolib: GeckoLib 4 4.5.4
		gigeresque: Gigeresque 0.5.74
		indium: Indium 1.0.32+mc1.20.1
		inventorytotem: Inventory Totem 3.2
		iris: Iris 1.7.0+mc1.20.6
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 21
		lchunkloader: Literally Chunk Loader 2.0.6
			libgui: LibGui 10.0.0+1.20.6
				jankson: Jankson 7.0.0+j1.2.3
					blue_endless_jankson: jankson 1.2.3
				libninepatch: LibNinePatch 1.2.0
		libertyvillagers: Liberty's Villagers 1.0.15+fabric+1.20.6
		lithium: Lithium 0.12.3
		lithostitched: Lithostitched 1.1.7b
		minecraft: Minecraft 1.20.6
		modmenu: Mod Menu 10.0.0-beta.1
		more_gems: More Gems 1.6.29
			pugh_tools: Pugh Tools 1.7.18
		mostructures: Mo' Structures 1.4.6+1.20.6
			omega-config: OmegaConfig 1.4.3+1.20.6
		philipsruins: Philip`s Ruins 1.20.6
		sandwichmod: Sandwich Mod 2.1.0
		shulkerboxtooltip: Shulker Box Tooltip 4.1.0-alpha.1+1.20.6
		simple-armor-hud: Simple armor hud 1.20.6-1.4.3
		skinlayers3d: 3d-Skin-Layers 1.6.5
		smartbrainlib: SmartBrainLib 1.14.2
		sodium: Sodium 0.5.9+mc1.20.6
		sushimod: Sushi Mod 1.2.0
		terralith: Terralith 2.5.1
		trinkets: Trinkets 3.9.0
			cardinal-components-base: Cardinal Components API (base) 6.0.0-beta.3
			cardinal-components-entity: Cardinal Components API (entities) 6.0.0-beta.3
		yet_another_config_lib_v3: YetAnotherConfigLib 3.4.4+1.20.6-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
	Loaded Shaderpack: (off)
	Launched Version: iris-fabric-loader-0.15.11-1.20.6
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce RTX 3070/PCIe/SSE2 GL version 3.2.0 NVIDIA 555.99, NVIDIA Corporation
	Window size: 5120x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 25/25 chunks
	Resource Packs: vanilla, fabric, azurelib (incompatible), backpacked (incompatible), bakingmod, balm-fabric (incompatible), boxlib, cardinal-components-base, cardinal-components-entity, catalogue, cloth-config, configured, controlify, cookingforblockheads (incompatible), coordinatesdisplay, ctov (incompatible), detailab, dispenser_configurator, distanthorizons (incompatible), dynamiclights, elytra_trinket, elytratrims (incompatible), emeraldapple, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, framework, gigeresque, indium, iris, jankson, lchunkloader, libertyvillagers, libgui, lithium, modmenu, more_gems, mostructures, omega-config, philipsruins, sandwichmod, shulkerboxtooltip, simple-armor-hud, skinlayers3d, sodium, sushimod, terralith, trinkets, yet_another_config_lib_v3 (incompatible)
	Current Language: pt_br
	Locale: pt_BR
	CPU: 20x Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz

### Crash Report

The game crashed whilst unexpected error
Error: java.lang.RuntimeException: Mixin transformation of me.jellysquid.mods.sodium.client.render.immediate.CloudRenderer failed

**Comment by MeeniMc** [comment]
You need to remove the resource pack that has empty cloud assets. 
Refer to https://github.com/CaffeineMC/sodium-fabric/issues/2552

**Comment by jellysquid3** [comment]
@MeeniMc This is unrelated. The problem is incompatible mixins from Iris trying to patch the CloudRenderer class. 

Probably you have incompatible versions of Iris and Sodium.
