### ISSUE TITLE
 1.20.5 version "needs 1.20.6"

### ISSUE THREAD

**Issue by MoonMoonShark** [jellysquid3/Sodium#2624]
### Bug Description

hey there! i know 1.20.5 was only out for like 3 days before 1.20.6 was released, so you may not even be supporting this anymore, but i'm running on a 1.20.5 server and trying to use sodium, but the 1.20.5 version throws an error and crashes during startup when i try to launch minecraft.

**Specs**
Minecraft: 1.20.5
Launcher: Fabric 0.16.0
Sodium: sodium-fabric-0.5.11+mc1.20.6

i appreciate all of your hard work! thank you so much for everything!

### Reproduction Steps

1. install latest version of fabric
2. add latest version of sodium to mods folder
3. start minecraft
4. receive error

### Log File

[14:50:13] [main/INFO]: Loading Minecraft 1.20.5 with Fabric Loader 0.16.0
[14:50:13] [main/WARN]: Mod resolution failed
[14:50:13] [main/INFO]: Immediate reason: [HARD_DEP chunksfadein 1.0.0-1.20.3 {depends sodium @ [>=0.5.0]}, HARD_DEP_INCOMPATIBLE_PRESELECTED sodium 0.5.11+mc1.20.6 {depends minecraft @ [1.20.6]}, ROOT_FORCELOAD_SINGLE chunksfadein 1.0.0-1.20.3]
[14:50:13] [main/INFO]: Reason: [HARD_DEP sodium 0.5.11+mc1.20.6 {depends minecraft @ [1.20.6]}]
[14:50:13] [main/INFO]: Fix: add [], remove [reeses-sodium-options 1.7.3+mc1.20.6], replace [[sodium 0.5.11+mc1.20.6] -> add:sodium 0.5.0 ([[0.5.0,∞)])]
[14:50:14] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Sodium' (sodium) 0.5.11+mc1.20.6 with version 0.5.0 or later that is compatible with:
		 - minecraft 1.20.5
More details:
	 - Mod 'Sodium' (sodium) 0.5.11+mc1.20.6 requires version 1.20.6 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.5!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.0.jar:?]

### Crash Report

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Sodium' (sodium) 0.5.11+mc1.20.6 with version 0.5.0 or later that is compatible with:
		 - minecraft 1.20.5
**More details:**
	 - Mod 'Sodium' (sodium) 0.5.11+mc1.20.6 requires version 1.20.6 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.5!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Felix14-v2** [comment]
Why do you use 1.20.5 instead of 1.20.6?
The version metadata on the Modrinth page is not correct though.
![Screenshot_20240725-223037](https://github.com/user-attachments/assets/a454da8c-2615-4bdd-a026-4835251cf17b)

**Comment by jellysquid3** [comment]
Yes, it looks like Modrinth had the wrong information. I've gone ahead and fixed that.

**Comment by MoonMoonShark** [comment]
thank you!

@Felix14-v2 it's a friend's server.

**Comment by Felix14-v2** [comment]
> @Felix14-v2 it's a friend's server.

You can use [ViaFabricPlus](https://modrinth.com/mod/ViaFabricPlus) to play on it from 1.20.6 or newer.
