### ISSUE TITLE
Weird crash

### ISSUE THREAD

**Issue by Eldersson1** [jellysquid3/Sodium#2636]
### Reproduction Steps

Join a server or a world

### Log File

	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1039) ~[client-intermediary.jar:?]
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51) ~[fabric-renderer-api-v1-3.4.0+c705a49cd1-2beb50691e4ea51.jar:?]
	at me.pepperbell.continuity.client.model.EmissiveBakedModel.emitBlockQuads(EmissiveBakedModel.java:64) ~[continuity-3.0.0-beta.5+1.21.jar:?]
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51) ~[fabric-renderer-api-v1-3.4.0+c705a49cd1-2beb50691e4ea51.jar:?]
	at me.pepperbell.continuity.client.model.CtmBakedModel.emitBlockQuads(CtmBakedModel.java:53) ~[continuity-3.0.0-beta.5+1.21.jar:?]
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51) ~[fabric-renderer-api-v1-3.4.0+c705a49cd1-2beb50691e4ea51.jar:?]
	at me.pepperbell.continuity.client.model.EmissiveBakedModel.emitBlockQuads(EmissiveBakedModel.java:72) ~[continuity-3.0.0-beta.5+1.21.jar:?]
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131) ~[indium-1.0.34+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$dei000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:543) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	... 4 more
[10:35:36] [Render thread/ERROR]:
 Reported exception thrown!
net.minecraft.class_148: Tessellating block in world - Indium Renderer
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.fillCrashInfo(ChunkBuilderMeshingTask.java:168) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:132) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'void net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(net.minecraft.class_1087, net.minecraft.class_2680, java.util.function.Supplier, net.fabricmc.fabric.api.renderer.v1.render.RenderContext, net.fabricmc.fabric.api.renderer.v1.mesh.QuadEmitter)'
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1039) ~[client-intermediary.jar:?]
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51) ~[fabric-renderer-api-v1-3.4.0+c705a49cd1-2beb50691e4ea51.jar:?]
	at me.pepperbell.continuity.client.model.EmissiveBakedModel.emitBlockQuads(EmissiveBakedModel.java:64) ~[continuity-3.0.0-beta.5+1.21.jar:?]
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51) ~[fabric-renderer-api-v1-3.4.0+c705a49cd1-2beb50691e4ea51.jar:?]
	at me.pepperbell.continuity.client.model.CtmBakedModel.emitBlockQuads(CtmBakedModel.java:53) ~[continuity-3.0.0-beta.5+1.21.jar:?]
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51) ~[fabric-renderer-api-v1-3.4.0+c705a49cd1-2beb50691e4ea51.jar:?]
	at me.pepperbell.continuity.client.model.EmissiveBakedModel.emitBlockQuads(EmissiveBakedModel.java:72) ~[continuity-3.0.0-beta.5+1.21.jar:?]
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131) ~[indium-1.0.34+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$dei000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:543) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	... 4 more

### Crash Report

???

**Comment by mrdhobbs** [comment]
I am also affected by this bug today. Freshly updated Arch Linux system, running Nvidia GPU on Wayland.

Full report: [latest.log](https://github.com/user-attachments/files/16493813/latest.log)

**Comment by pajicadvance** [comment]
https://github.com/comp500/Indium/issues/324

Downgrade Fabric API to the previous version to work around the crash for now.

**Comment by Eldersson1** [comment]
> [comp500/Indium#324](https://github.com/comp500/Indium/issues/324)
> 
> Downgrade Fabric API to the previous version to work around the crash for now.

It worked
