### ISSUE TITLE
Sodium for MC 1.16.5 keeps making Minecraft crash on loading EVEN IF NO other mods installed(except Fabric API)

### ISSUE THREAD

**Issue by IAmREGE** [jellysquid3/Sodium#2657]
### Bug Description

Sodium 0.2.0+build.4 for MC1.16.5 (which is the last version for MC1.16.5 could be found on Modrinth) keeps making Minecraft crash on loading EVEN IF NO other mods installed(except Fabric API).

### Reproduction Steps

Put only this mod(Sodium) and Fabric API to `mods` directory and launch the game. The game crashes as soon as the game window appears, before the loading progress bar appears.

### Log File

```
[15:52:41] [main/INFO]: Loading Minecraft 1.16.5 with Fabric Loader 0.16.0
[15:52:41] [main/INFO]: Loading 50 mods:
        - fabric 0.42.0+1.16
           |-- fabric-api-base 0.4.0+3cc0f0907d
           |-- fabric-api-lookup-api-v1 1.3.1+3cc0f0907d
           |-- fabric-biome-api-v1 3.1.13+3cc0f0907d
           |-- fabric-blockrenderlayer-v1 1.1.6+3cc0f0907d
           |-- fabric-command-api-v1 1.1.3+3cc0f0907d
           |-- fabric-commands-v0 0.2.3+3cc0f0907d
           |-- fabric-containers-v0 0.1.12+3cc0f0907d
           |-- fabric-content-registries-v0 0.2.5+3cc0f0907d
           |-- fabric-crash-report-info-v1 0.1.4+3cc0f0907d
           |-- fabric-dimensions-v1 2.0.8+3cc0f0907d
           |-- fabric-entity-events-v1 1.2.4+3cc0f0907d
           |-- fabric-events-interaction-v0 0.4.5+3cc0f0907d
           |-- fabric-events-lifecycle-v0 0.2.2+3cc0f0907d
           |-- fabric-game-rule-api-v1 1.0.7+3cc0f0907d
           |-- fabric-item-api-v1 1.2.2+3cc0f0907d
           |-- fabric-item-groups-v0 0.3.1+3cc0f0907d
           |-- fabric-key-binding-api-v1 1.0.5+3cc0f0907d
           |-- fabric-keybindings-v0 0.2.2+3cc0f0907d
           |-- fabric-lifecycle-events-v1 1.2.2+3cc0f0907d
           |-- fabric-loot-tables-v1 1.0.3+3cc0f0907d
           |-- fabric-mining-levels-v0 0.1.4+3cc0f0907d
           |-- fabric-models-v0 0.3.1+3cc0f0907d
           |-- fabric-networking-api-v1 1.0.5+3cc0f0907d
           |-- fabric-networking-blockentity-v0 0.2.9+3cc0f0907d
           |-- fabric-networking-v0 0.3.3+3cc0f0907d
           |-- fabric-object-builder-api-v1 1.9.6+3cc0f0907d
           |-- fabric-object-builders-v0 0.7.3+3cc0f0907d
           |-- fabric-particles-v1 0.2.5+3cc0f0907d
           |-- fabric-registry-sync-v0 0.7.6+3cc0f0907d
           |-- fabric-renderer-api-v1 0.4.5+3cc0f0907d
           |-- fabric-renderer-indigo 0.4.5+3cc0f0907d
           |-- fabric-renderer-registries-v1 2.3.1+3cc0f0907d
           |-- fabric-rendering-data-attachment-v1 0.1.6+3cc0f0907d
           |-- fabric-rendering-fluids-v1 0.1.15+3cc0f0907d
           |-- fabric-rendering-v0 1.1.3+3cc0f0907d
           |-- fabric-rendering-v1 1.6.1+3cc0f0907d
           |-- fabric-resource-loader-v0 0.4.8+3cc0f0907d
           |-- fabric-screen-api-v1 1.0.1+3cc0f0907d
           |-- fabric-screen-handler-api-v1 1.1.6+3cc0f0907d
           |-- fabric-structure-api-v1 1.1.12+3cc0f0907d
           |-- fabric-tag-extensions-v0 1.1.2+3cc0f0907d
           |-- fabric-textures-v0 1.0.7+3cc0f0907d
           |-- fabric-tool-attribute-api-v1 1.2.8+3cc0f0907d
           \-- fabric-transfer-api-v1 1.5.0+3cc0f0907d
        - fabricloader 0.16.0
           \-- mixinextras 0.4.0
        - java 22
        - minecraft 1.16.5
        - sodium 0.2.0+build.4
[15:52:42] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/run/media/rege/369f6f52-dd24-4876-9793-638017e825e8/.minecraft/libraries/net/fabricmc/sponge-mixin/0.15.0+mixin.0.8.7/sponge-mixin-0.15.0+mixin.0.8.7.jar Service=Knot/Fabric Env=CLIENT
[15:52:43] [main/INFO]: Loaded configuration file for Sodium: 24 options available, 0 override(s) found
[15:52:45] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.0).
[15:53:08] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:53:13] [main/INFO]: Setting user: NewWranPlateu
[15:53:58] [main/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[15:54:02] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[15:54:05] [main/INFO]: [STDERR]: [LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers.
[15:54:10] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/gl/device/RenderDevice (java.lang.RuntimeException: Failed to load class file for 'me.jellysquid.mods.sodium.client.gl.device.RenderDevice'!)
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2024/8/11 15:54
Description: Initializing game

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_761 failed
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at net.minecraft.class_310.<init>(class_310.java:541)
        at net.minecraft.client.main.Main.main(Main.java:177)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
        ... 9 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for sodium.mixins.json:features.chunk_rendering.MixinWorldRenderer from mod sodium during activity: [Transform -> Method onWorldChanged(Lnet/minecraft/class_638;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> INVOKESTATIC -> me/jellysquid/mods/sodium/client/gl/device/RenderDevice::enterManagedCode:()V]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313)
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:203)
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437)
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
        ... 12 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: me.jellysquid.mods.sodium.client.gl.device.RenderDevice
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:791)
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:777)
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:743)
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307)
        ... 18 more
Caused by: java.lang.ClassNotFoundException: me.jellysquid.mods.sodium.client.gl.device.RenderDevice
        ... 22 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at net.minecraft.class_310.<init>(class_310.java:541)

-- Initialization --
Details:
Stacktrace:
        at net.minecraft.client.main.Main.main(Main.java:177)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
        Minecraft Version: 1.16.5
        Minecraft Version ID: 1.16.5
        Operating System: Linux (amd64) version 6.9.10-arch1-1
        Java Version: 22.0.2, Arch Linux
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Arch Linux
        Memory: 387768928 bytes (369 MB) / 1073741824 bytes (1024 MB) up to 1610612736 bytes (1536 MB)
        CPUs: 2
        JVM Flags: 10 total; -Xmx1536m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods
        Fabric Mods: 
                fabric: Fabric API 0.42.0+1.16
                fabric-api-base: Fabric API Base 0.4.0+3cc0f0907d
                fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+3cc0f0907d
                fabric-biome-api-v1: Fabric Biome API (v1) 3.1.13+3cc0f0907d
                fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+3cc0f0907d
                fabric-command-api-v1: Fabric Command API (v1) 1.1.3+3cc0f0907d
                fabric-commands-v0: Fabric Commands (v0) 0.2.3+3cc0f0907d
                fabric-containers-v0: Fabric Containers (v0) 0.1.12+3cc0f0907d
                fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.5+3cc0f0907d
                fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.4+3cc0f0907d
                fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.8+3cc0f0907d
                fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.4+3cc0f0907d
                fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.5+3cc0f0907d
                fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+3cc0f0907d
                fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+3cc0f0907d
                fabric-item-api-v1: Fabric Item API (v1) 1.2.2+3cc0f0907d
                fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+3cc0f0907d
                fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+3cc0f0907d
                fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+3cc0f0907d
                fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.2+3cc0f0907d
                fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.3+3cc0f0907d
                fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.4+3cc0f0907d
                fabric-models-v0: Fabric Models (v0) 0.3.1+3cc0f0907d
                fabric-networking-api-v1: Fabric Networking API (v1) 1.0.5+3cc0f0907d
                fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.9+3cc0f0907d
                fabric-networking-v0: Fabric Networking (v0) 0.3.3+3cc0f0907d
                fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.6+3cc0f0907d
                fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+3cc0f0907d
                fabric-particles-v1: Fabric Particles (v1) 0.2.5+3cc0f0907d
                fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.6+3cc0f0907d
                fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+3cc0f0907d
                fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.5+3cc0f0907d
                fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.1+3cc0f0907d
                fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+3cc0f0907d
                fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.15+3cc0f0907d
                fabric-rendering-v0: Fabric Rendering (v0) 1.1.3+3cc0f0907d
                fabric-rendering-v1: Fabric Rendering (v1) 1.6.1+3cc0f0907d
                fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+3cc0f0907d
                fabric-screen-api-v1: Fabric Screen API (v1) 1.0.1+3cc0f0907d
                fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.6+3cc0f0907d
                fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+3cc0f0907d
                fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.2+3cc0f0907d
                fabric-textures-v0: Fabric Textures (v0) 1.0.7+3cc0f0907d
                fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.8+3cc0f0907d
                fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.0+3cc0f0907d
                fabricloader: Fabric Loader 0.16.0
                java: OpenJDK 64-Bit Server VM 22
                minecraft: Minecraft 1.16.5
                mixinextras: MixinExtras 0.4.0
                sodium: Sodium 0.2.0+build.4
        Launched Version: 1.16.5
        Backend library: LWJGL version 3.2.2 build 10
        Backend API: AMD Radeon R2 Graphics (radeonsi, stoney, LLVM 18.1.8, DRM 3.57, 6.9.10-arch1-1) GL version 4.5 (Compatibility Profile) Mesa 24.1.5-arch1.1, AMD
        GL Caps: Using framebuffer using OpenGL 3.0
        Using VBOs: Yes
        Is Modded: Definitely; Client brand changed to 'fabric'
        Type: Client (map_client.txt)
        CPU: 2x AMD E2-9010 RADEON R2, 4 COMPUTE CORES 2C+2G
#@!@# Game crashed! Crash report saved to: #@!@# /DELETED/.minecraft/versions/1.16.5/crash-reports/crash-2024-08-11_15.54.10-client.txt
```

### Crash Report

```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2024/8/11 15:54
Description: Initializing game

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_761 failed
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at net.minecraft.class_310.<init>(class_310.java:541)
        at net.minecraft.client.main.Main.main(Main.java:177)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
        ... 9 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for sodium.mixins.json:features.chunk_rendering.MixinWorldRenderer from mod sodium during activity: [Transform -> Method onWorldChanged(Lnet/minecraft/class_638;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> INVOKESTATIC -> me/jellysquid/mods/sodium/client/gl/device/RenderDevice::enterManagedCode:()V]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313)
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:203)
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437)
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
        ... 12 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: me.jellysquid.mods.sodium.client.gl.device.RenderDevice
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:791)
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:777)
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:743)
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307)
        ... 18 more
Caused by: java.lang.ClassNotFoundException: me.jellysquid.mods.sodium.client.gl.device.RenderDevice
        ... 22 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at net.minecraft.class_310.<init>(class_310.java:541)

-- Initialization --
Details:
Stacktrace:
        at net.minecraft.client.main.Main.main(Main.java:177)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
        Minecraft Version: 1.16.5
        Minecraft Version ID: 1.16.5
        Operating System: Linux (amd64) version 6.9.10-arch1-1
        Java Version: 22.0.2, Arch Linux
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Arch Linux
        Memory: 387768928 bytes (369 MB) / 1073741824 bytes (1024 MB) up to 1610612736 bytes (1536 MB)
        CPUs: 2
        JVM Flags: 10 total; -Xmx1536m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods
        Fabric Mods: 
                fabric: Fabric API 0.42.0+1.16
                fabric-api-base: Fabric API Base 0.4.0+3cc0f0907d
                fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+3cc0f0907d
                fabric-biome-api-v1: Fabric Biome API (v1) 3.1.13+3cc0f0907d
                fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+3cc0f0907d
                fabric-command-api-v1: Fabric Command API (v1) 1.1.3+3cc0f0907d
                fabric-commands-v0: Fabric Commands (v0) 0.2.3+3cc0f0907d
                fabric-containers-v0: Fabric Containers (v0) 0.1.12+3cc0f0907d
                fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.5+3cc0f0907d
                fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.4+3cc0f0907d
                fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.8+3cc0f0907d
                fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.4+3cc0f0907d
                fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.5+3cc0f0907d
                fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+3cc0f0907d
                fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+3cc0f0907d
                fabric-item-api-v1: Fabric Item API (v1) 1.2.2+3cc0f0907d
                fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+3cc0f0907d
                fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+3cc0f0907d
                fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+3cc0f0907d
                fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.2+3cc0f0907d
                fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.3+3cc0f0907d
                fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.4+3cc0f0907d
                fabric-models-v0: Fabric Models (v0) 0.3.1+3cc0f0907d
                fabric-networking-api-v1: Fabric Networking API (v1) 1.0.5+3cc0f0907d
                fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.9+3cc0f0907d
                fabric-networking-v0: Fabric Networking (v0) 0.3.3+3cc0f0907d
                fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.6+3cc0f0907d
                fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+3cc0f0907d
                fabric-particles-v1: Fabric Particles (v1) 0.2.5+3cc0f0907d
                fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.6+3cc0f0907d
                fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+3cc0f0907d
                fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.5+3cc0f0907d
                fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.1+3cc0f0907d
                fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+3cc0f0907d
                fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.15+3cc0f0907d
                fabric-rendering-v0: Fabric Rendering (v0) 1.1.3+3cc0f0907d
                fabric-rendering-v1: Fabric Rendering (v1) 1.6.1+3cc0f0907d
                fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+3cc0f0907d
                fabric-screen-api-v1: Fabric Screen API (v1) 1.0.1+3cc0f0907d
                fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.6+3cc0f0907d
                fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+3cc0f0907d
                fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.2+3cc0f0907d
                fabric-textures-v0: Fabric Textures (v0) 1.0.7+3cc0f0907d
                fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.8+3cc0f0907d
                fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.0+3cc0f0907d
                fabricloader: Fabric Loader 0.16.0
                java: OpenJDK 64-Bit Server VM 22
                minecraft: Minecraft 1.16.5
                mixinextras: MixinExtras 0.4.0
                sodium: Sodium 0.2.0+build.4
        Launched Version: 1.16.5
        Backend library: LWJGL version 3.2.2 build 10
        Backend API: AMD Radeon R2 Graphics (radeonsi, stoney, LLVM 18.1.8, DRM 3.57, 6.9.10-arch1-1) GL version 4.5 (Compatibility Profile) Mesa 24.1.5-arch1.1, AMD
        GL Caps: Using framebuffer using OpenGL 3.0
        Using VBOs: Yes
        Is Modded: Definitely; Client brand changed to 'fabric'
        Type: Client (map_client.txt)
        CPU: 2x AMD E2-9010 RADEON R2, 4 COMPUTE CORES 2C+2G
```

**Comment by jellysquid3** [comment]
`Caused by: java.lang.ClassNotFoundException: me.jellysquid.mods.sodium.client.gl.device.RenderDevice`

This looks like the JAR file you downloaded is corrupted. Delete it, and download it again [from Modrinth.](https://modrinth.com/mod/sodium/versions?l=fabric&g=1.16.5)

**Comment by IAmREGE** [comment]
My bad. :(
