### ISSUE TITLE
1.21 when I try creating a World it crashes

### ISSUE THREAD

**Issue by editon96** [jellysquid3/Sodium#2669]
### Bug Description

When I try creating a World it crashes and nothing happen, you stay in the Loading Tarrain screen.

I try go to a lower Indium an Sodium version like the newest in 1.21 but it happen there also.
I try to delete, Nvideum, CM2, Bobby and other chunk changing Mods but it still happen.

### Reproduction Steps

I dont now why that happen...

### Log File

https://mclo.gs/K182Gx2

### Crash Report

`[15/08/2024 12:44:30 PM] [Render thread/INFO] New Xaero hud session initialized!
[15/08/2024 12:44:30 PM] [Server thread/INFO] **MINECRAFTUSERNAME** joined the game
[15/08/2024 12:44:31 PM] [Server thread/INFO] Async chunk loading for player **MINECRAFTUSERNAME** completed
[15/08/2024 12:44:31 PM] [Render thread/INFO] New world map session initialized!
[15/08/2024 12:44:31 PM] [Render thread/INFO] Reloading pipeline on dimension change: minecraft:overworld => minecraft:overworld
[15/08/2024 12:44:31 PM] [Render thread/INFO] Destroying pipeline minecraft:overworld
[15/08/2024 12:44:31 PM] [Render thread/INFO] Creating pipeline for dimension minecraft:overworld
[15/08/2024 12:44:31 PM] [Render thread/INFO] Started 10 worker threads
[15/08/2024 12:44:32 PM] [Render thread/INFO] [ChatLog.restore] Restored 0 messages and 0 history messages from '**USERSDIR**\instances\CookingStation\logs\chatlog.json' into Minecraft!
[15/08/2024 12:44:32 PM] [Render thread/INFO] [voicechat] Sending secret request to the server
[15/08/2024 12:44:32 PM] [Server thread/INFO] [voicechat] Received secret request of **MINECRAFTUSERNAME** (18)
[15/08/2024 12:44:32 PM] [Server thread/INFO] [voicechat] Sent secret to **MINECRAFTUSERNAME**
[15/08/2024 12:44:32 PM] [Render thread/INFO] Initializing sound physics for voice chat audio
[15/08/2024 12:44:32 PM] [Render thread/INFO] Initializing Sound Physics
[15/08/2024 12:44:32 PM] [Render thread/INFO] EFX Extension recognized
[15/08/2024 12:44:32 PM] [Render thread/INFO] Max auxiliary sends: 2
[15/08/2024 12:44:32 PM] [Render thread/INFO] Aux slot 1 created
[15/08/2024 12:44:32 PM] [Render thread/INFO] Aux slot 2 created
[15/08/2024 12:44:32 PM] [Render thread/INFO] Aux slot 3 created
[15/08/2024 12:44:32 PM] [Render thread/INFO] Aux slot 4 created
[15/08/2024 12:44:32 PM] [Render thread/INFO] EFX ready
[15/08/2024 12:44:33 PM] [Render thread/INFO] [Inventory Profiles Next] Loaded 0 external GUI hints
[15/08/2024 12:44:33 PM] [Render thread/INFO] [Inventory Profiles Next] Loaded 797 build-in GUI hints
[15/08/2024 12:44:33 PM] [Render thread/INFO] [Inventory Profiles Next] Effective GUI hints after merge: 797
[15/08/2024 12:44:33 PM] [Render thread/INFO] [Client] The server has 'betterstats' installed.
[15/08/2024 12:44:33 PM] [Render thread/INFO] Loaded 3 advancements
[15/08/2024 12:44:33 PM] [Render thread/INFO] Minimap updated server level id: -1585109500 for world ResourceKey[minecraft:dimension / minecraft:overworld]
[15/08/2024 12:44:33 PM] [Render thread/INFO] [voicechat] Received secret
[15/08/2024 12:44:33 PM] [Render thread/INFO] [voicechat] Connecting to voice chat server: 'IP'
[15/08/2024 12:44:33 PM] [VoiceChatAuthenticationThread/INFO] [voicechat] Trying to authenticate voice chat connection
[15/08/2024 12:44:33 PM] [VoiceChatPacketProcessingThread/INFO] [voicechat] Successfully authenticated player XXX
[15/08/2024 12:44:33 PM] [Render thread/INFO] [CHAT] [12:44:33] [Simple Voice Chat] Press V to set up
[15/08/2024 12:44:33 PM] [VoiceChatConnectionThread/INFO] [voicechat] Server acknowledged authentication
[15/08/2024 12:44:34 PM] [Render thread/INFO] Reloading entity icon resources...
[15/08/2024 12:44:34 PM] [Render thread/INFO] Reloaded entity icon resources!
[15/08/2024 12:44:34 PM] [VoiceChatAuthenticationThread/INFO] [voicechat] Trying to validate voice chat connection
[15/08/2024 12:44:34 PM] [VoiceChatPacketProcessingThread/INFO] [voicechat] Successfully validated connection of player XXX
[15/08/2024 12:44:34 PM] [Render thread/WARN] Time from main menu to in-game was 9.946515 seconds
[15/08/2024 12:44:34 PM] [Render thread/WARN] Total time to load game and open world was 66.186516 seconds
[15/08/2024 12:44:34 PM] [VoiceChatPacketProcessingThread/INFO] [voicechat] Player **MINECRAFTUSERNAME** (175079d1-5f26-4ab4-ae90-bd088b03d90f) successfully connected to voice chat
[15/08/2024 12:44:34 PM] [VoiceChatConnectionThread/INFO] [voicechat] Server acknowledged connection check
[15/08/2024 12:44:35 PM] [MicrophoneThread/ERROR] [voicechat] Voicechat sound manager ALC error: de.maxhenkel.voicechat.voice.client.microphone.ALMicrophone.tryOpenMic[131] Invalid value
[15/08/2024 12:44:35 PM] [MicrophoneThread/WARN] [voicechat] Failed to open microphone '', falling back to default microphone
[15/08/2024 12:44:35 PM] [MicrophoneThread/ERROR] [voicechat] Voicechat sound manager ALC error: de.maxhenkel.voicechat.voice.client.microphone.ALMicrophone.tryOpenMic[131] Invalid value
[15/08/2024 12:44:35 PM] [MicrophoneThread/ERROR] [voicechat] Voicechat sound manager ALC error: de.maxhenkel.voicechat.voice.client.microphone.ALMicrophone.tryOpenMic[131] Invalid value
[15/08/2024 12:44:35 PM] 	at de.maxhenkel.voicechat.voice.client.microphone.ALMicrophone.tryOpenMic(ALMicrophone.java:132)
[15/08/2024 12:44:35 PM] 	at de.maxhenkel.voicechat.voice.client.microphone.ALMicrophone.openMic(ALMicrophone.java:123)
[15/08/2024 12:44:35 PM] 	at de.maxhenkel.voicechat.voice.client.microphone.ALMicrophone.open(ALMicrophone.java:33)
[15/08/2024 12:44:35 PM] 	at de.maxhenkel.voicechat.voice.client.microphone.MicrophoneManager.createALMicrophone(MicrophoneManager.java:39)
[15/08/2024 12:44:35 PM] 	at de.maxhenkel.voicechat.voice.client.microphone.MicrophoneManager.createMicrophone(MicrophoneManager.java:20)
[15/08/2024 12:44:35 PM] 	at de.maxhenkel.voicechat.voice.client.MicThread.getMic(MicThread.java:147)
[15/08/2024 12:44:35 PM] 	at de.maxhenkel.voicechat.voice.client.MicThread.run(MicThread.java:68)
[15/08/2024 12:44:35 PM] [MicrophoneThread/WARN] [voicechat] Failed to use OpenAL microphone implementation
[15/08/2024 12:44:35 PM] [MicrophoneThread/WARN] [voicechat] Falling back to Java microphone implementation
[15/08/2024 12:44:35 PM] [MicrophoneThread/WARN] [voicechat] Failed to open microphone '', falling back to default microphone
[15/08/2024 12:44:35 PM] 	at de.maxhenkel.voicechat.voice.client.microphone.JavaxMicrophone.open(JavaxMicrophone.java:46)
[15/08/2024 12:44:35 PM] 	at de.maxhenkel.voicechat.voice.client.microphone.MicrophoneManager.createJavaMicrophone(MicrophoneManager.java:33)
[15/08/2024 12:44:35 PM] 	at de.maxhenkel.voicechat.voice.client.microphone.MicrophoneManager.createMicrophone(MicrophoneManager.java:24)
[15/08/2024 12:44:35 PM] 	at de.maxhenkel.voicechat.voice.client.MicThread.getMic(MicThread.java:147)
[15/08/2024 12:44:35 PM] 	at de.maxhenkel.voicechat.voice.client.MicThread.run(MicThread.java:68)
[15/08/2024 12:44:35 PM] [MicrophoneThread/ERROR] [voicechat] Failed to start microphone thread
[15/08/2024 12:44:35 PM] [MicrophoneThread/INFO] [CHAT] [12:44:35] [Simple Voice Chat] Microphone unavailable
[15/08/2024 12:44:35 PM] 	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.fillCrashInfo(ChunkBuilderMeshingTask.java:168)
[15/08/2024 12:44:35 PM] 	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:132)
[15/08/2024 12:44:35 PM] 	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
[15/08/2024 12:44:35 PM] 	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
[15/08/2024 12:44:35 PM] 	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
[15/08/2024 12:44:35 PM] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[15/08/2024 12:44:35 PM] Caused by: java.lang.NoSuchMethodError: 'void net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(net.minecraft.class_1087, net.minecraft.class_2680, java.util.function.Supplier, net.fabricmc.fabric.api.renderer.v1.render.RenderContext, net.fabricmc.fabric.api.renderer.v1.mesh.QuadEmitter)'
[15/08/2024 12:44:35 PM] 	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1039)
[15/08/2024 12:44:35 PM] 	at net.minecraft.class_1097.emitBlockQuads(class_1097.java:574)
[15/08/2024 12:44:35 PM] 	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
[15/08/2024 12:44:35 PM] 	at me.pepperbell.continuity.client.model.CtmBakedModel.emitBlockQuads(CtmBakedModel.java:53)
[15/08/2024 12:44:35 PM] 	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131)
[15/08/2024 12:44:35 PM] 	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$dag000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:543)
[15/08/2024 12:44:35 PM] 	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103)
[15/08/2024 12:44:35 PM] 	... 4 more
[15/08/2024 12:44:35 PM] [Chunk Render Task Executor #0/ERROR] Chunk build failed
[15/08/2024 12:44:35 PM] 	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.fillCrashInfo(ChunkBuilderMeshingTask.java:168)
[15/08/2024 12:44:35 PM] 	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:132)
[15/08/2024 12:44:35 PM] 	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
[15/08/2024 12:44:35 PM] 	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
[15/08/2024 12:44:35 PM] 	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
[15/08/2024 12:44:35 PM] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[15/08/2024 12:44:35 PM] Caused by: java.lang.NoSuchMethodError: 'void net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(net.minecraft.class_1087, net.minecraft.class_2680, java.util.function.Supplier, net.fabricmc.fabric.api.renderer.v1.render.RenderContext, net.fabricmc.fabric.api.renderer.v1.mesh.QuadEmitter)'
[15/08/2024 12:44:35 PM] 	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1039)
[15/08/2024 12:44:35 PM] 	at net.minecraft.class_1097.emitBlockQuads(class_1097.java:574)
[15/08/2024 12:44:35 PM] 	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
[15/08/2024 12:44:35 PM] 	at me.pepperbell.continuity.client.model.CtmBakedModel.emitBlockQuads(CtmBakedModel.java:53)
[15/08/2024 12:44:35 PM] 	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131)
[15/08/2024 12:44:35 PM] 	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$dag000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:543)
[15/08/2024 12:44:35 PM] 	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103)
[15/08/2024 12:44:35 PM] 	... 4 more
[15/08/2024 12:44:35 PM] [Render thread/FATAL] Reported exception thrown!
[15/08/2024 12:44:36 PM] [Server thread/INFO] Stopping server
[15/08/2024 12:44:36 PM] [Server thread/INFO] Saving players
[15/08/2024 12:44:36 PM] [Server thread/INFO] Saving worlds
[15/08/2024 12:44:37 PM] [Server thread/INFO] Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[15/08/2024 12:44:39 PM] [Server thread/INFO] Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[15/08/2024 12:44:39 PM] [Server thread/INFO] Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[15/08/2024 12:44:39 PM] [Server thread/INFO] ThreadedAnvilChunkStorage (New World): All chunks are saved
[15/08/2024 12:44:39 PM] [Server thread/INFO] ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[15/08/2024 12:44:39 PM] [Server thread/INFO] ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[15/08/2024 12:44:39 PM] [Server thread/INFO] ThreadedAnvilChunkStorage: All dimensions are saved`

**Comment by editon96** [comment]
Also with entering an Multiplayer Server...

But It looks like there Indium is fault for that, I test and check all again, If i now why I let you now.
Error Link:
https://mclo.gs/Nk3mzzz

**Comment by Lolothepro** [comment]
update Indium

**Comment by editon96** [comment]
I did it a minite ago and now all works,
Multiplayer and Singleplayer works now thanks.

**Comment by Usuwd7dyah** [comment]
Its so good

**Comment by Warrobot10** [comment]
If your issue is fixed, feel free to close it.
