### ISSUE TITLE
sodium 0.6.0-beta.1 for Fabric does not work with more culling

### ISSUE THREAD

**Issue by Dom23575** [jellysquid3/Sodium#2716]
### Bug Description

previous version of sodium i was able to play with the more culling mod but now i cant. Every time i try to log into a world or server my game always crashes,

### Reproduction Steps

Just try joining any world or server with sodium version 0.6.0-beta.1 for Fabric with more culling mod.

### Log File

[latest.log](https://github.com/user-attachments/files/16738293/latest.log)

### Crash Report

[crash-2024-08-24_19.10.58-client.txt](https://github.com/user-attachments/files/16738292/crash-2024-08-24_19.10.58-client.txt)

**Comment by Lolothepro** [comment]
This bug is caused by More Culling, which uses Mixin in Sodium. However, Sodium's main class has changed, causing it to crash.
```
Caused by: java.lang.NoClassDefFoundError: me/jellysquid/mods/sodium/client/SodiumClientMod
	at ca.fxco.moreculling.utils.CullingUtils.areLeavesOpaque(CullingUtils.java:92) ~[moreculling-1.21-0.26.0.jar:?]
	at net.minecraft.class_2397.method_9522(class_2397.java:2037) ~[client-intermediary.jar:?]
```
