### ISSUE TITLE
Problem with launching minecraft 1.21.1 with sodium

### ISSUE THREAD

**Issue by Prark00** [jellysquid3/Sodium#2731]
### Bug Description

When launching minecraft with sodium and fabric api gives the following error:
A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium' at 'net.caffeinemc.mods.sodium.fabric.SodiumPreLaunch'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium' at 'net.caffeinemc.mods.sodium.fabric.SodiumPreLaunch'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	... 5 more
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\?????\AppData\Local\Temp\jna-1007792265\jna6873146617604809216.dll: Can't find dependent libraries
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2025)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1041)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:1011)
	at com.sun.jna.Native.<clinit>(Native.java:221)
	at com.sun.jna.Structure.setAlignType(Structure.java:291)
	at com.sun.jna.Structure.<init>(Structure.java:208)
	at com.sun.jna.Structure.<init>(Structure.java:204)
	at com.sun.jna.Structure.<init>(Structure.java:191)
	at com.sun.jna.Structure.<init>(Structure.java:183)
	at com.sun.jna.platform.win32.WinNT$OSVERSIONINFOEX.<init>(WinNT.java:1980)
	at com.sun.jna.platform.win32.VersionHelpers.IsWindowsVersionOrGreater(VersionHelpers.java:59)
	at com.sun.jna.platform.win32.VersionHelpers.IsWindowsVistaOrGreater(VersionHelpers.java:127)
	at net.caffeinemc.mods.sodium.client.platform.windows.api.d3dkmt.D3DKMT.<clinit>(D3DKMT.java:28)
	at net.caffeinemc.mods.sodium.client.compatibility.environment.probe.GraphicsAdapterProbe.findAdapters$Windows(GraphicsAdapterProbe.java:56)
	at net.caffeinemc.mods.sodium.client.compatibility.environment.probe.GraphicsAdapterProbe.findAdapters(GraphicsAdapterProbe.java:29)
	at net.caffeinemc.mods.sodium.fabric.SodiumPreLaunch.onPreLaunch(SodiumPreLaunch.java:12)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 6 more

### Reproduction Steps

I've launched minecraft with sodium and Fabric api on version 1.21.1  

### Log File

[18:38:19] [main/INFO]: Loading Minecraft 1.21.1 with Fabric Loader 0.16.3
[18:38:19] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[18:38:20] [main/INFO]: Loading 54 mods:
	- fabric-api 0.103.0+1.21.1
	   |-- fabric-api-base 0.4.42+6573ed8c19
	   |-- fabric-api-lookup-api-v1 1.6.68+b559734419
	   |-- fabric-biome-api-v1 13.0.29+5bd9f1bc19
	   |-- fabric-block-api-v1 1.0.22+0af3f5a719
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8c19
	   |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a719
	   |-- fabric-client-tags-api-v1 1.1.15+6573ed8c19
	   |-- fabric-command-api-v1 1.2.49+f71b366f19
	   |-- fabric-command-api-v2 2.2.28+6ced4dd919
	   |-- fabric-commands-v0 0.2.66+df3654b319
	   |-- fabric-content-registries-v0 8.0.16+b559734419
	   |-- fabric-convention-tags-v1 2.0.21+7f945d5b19
	   |-- fabric-convention-tags-v2 2.6.1+9b16164119
	   |-- fabric-crash-report-info-v1 0.2.29+0af3f5a719
	   |-- fabric-data-attachment-api-v1 1.1.28+1daea21519
	   |-- fabric-data-generation-api-v1 20.2.18+16c4ae2519
	   |-- fabric-dimensions-v1 4.0.0+6fc22b9919
	   |-- fabric-entity-events-v1 1.7.0+2122d82819
	   |-- fabric-events-interaction-v0 0.7.12+ba9dae0619
	   |-- fabric-game-rule-api-v1 1.0.53+6ced4dd919
	   |-- fabric-item-api-v1 11.0.0+afdfc92119
	   |-- fabric-item-group-api-v1 4.1.5+3fc0e55219
	   |-- fabric-key-binding-api-v1 1.0.47+0af3f5a719
	   |-- fabric-keybindings-v0 0.2.45+df3654b319
	   |-- fabric-lifecycle-events-v1 2.3.12+6c1df36019
	   |-- fabric-loot-api-v2 3.0.14+3f89f5a519
	   |-- fabric-loot-api-v3 1.0.2+3f89f5a519
	   |-- fabric-message-api-v1 6.0.13+6573ed8c19
	   |-- fabric-model-loading-api-v1 2.0.0+fe474d6b19
	   |-- fabric-networking-api-v1 4.2.2+60c3209b19
	   |-- fabric-object-builder-api-v1 15.2.0+40875a9319
	   |-- fabric-particles-v1 4.0.2+6573ed8c19
	   |-- fabric-recipe-api-v1 5.0.12+6508971219
	   |-- fabric-registry-sync-v0 5.1.2+60c3209b19
	   |-- fabric-renderer-api-v1 3.4.0+c705a49c19
	   |-- fabric-renderer-indigo 1.7.0+c705a49c19
	   |-- fabric-renderer-registries-v1 3.2.68+df3654b319
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2e19
	   |-- fabric-rendering-fluids-v1 3.1.6+1daea21519
	   |-- fabric-rendering-v0 1.1.71+df3654b319
	   |-- fabric-rendering-v1 5.0.5+df16efd019
	   |-- fabric-resource-conditions-api-v1 4.3.0+8dc279b119
	   |-- fabric-resource-loader-v0 1.3.0+5659912919
	   |-- fabric-screen-api-v1 2.0.25+8b68f1c719
	   |-- fabric-screen-handler-api-v1 1.3.86+b559734419
	   |-- fabric-sound-api-v1 1.0.23+6573ed8c19
	   |-- fabric-transfer-api-v1 5.1.17+1db1cc1f19
	   \-- fabric-transitive-access-wideners-v1 6.1.0+1daea21519
	- fabricloader 0.16.3
	   \-- mixinextras 0.4.1
	- java 21
	- minecraft 1.21.1
	- sodium 0.6.0-beta.1+mc1.21
[18:38:20] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/C:/Users/%d0%9f%d1%80%d0%b0%d1%80%d0%ba/AppData/Roaming/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.15.2+mixin.0.8.7/sponge-mixin-0.15.2+mixin.0.8.7.jar Service=Knot/Fabric Env=CLIENT
[18:38:20] [main/INFO]: Compatibility level set to JAVA_17
[18:38:20] [main/INFO]: Compatibility level set to JAVA_21
[18:38:20] [main/INFO]: Loaded configuration file for Sodium: 43 options available, 0 override(s) found
[18:38:21] [main/INFO]: Searching for graphics cards...
[18:38:21] [main/ERROR]: A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium' at 'net.caffeinemc.mods.sodium.fabric.SodiumPreLaunch'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.3.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium' at 'net.caffeinemc.mods.sodium.fabric.SodiumPreLaunch'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.16.3.jar:?]
	... 5 more
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\?????\AppData\Local\Temp\jna-1007792265\jna12441862116981247989.dll: Can't find dependent libraries
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331) ~[?:?]
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197) ~[?:?]
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139) ~[?:?]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418) ~[?:?]
	at java.base/java.lang.Runtime.load0(Runtime.java:852) ~[?:?]
	at java.base/java.lang.System.load(System.java:2025) ~[?:?]
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1041) ~[jna-5.14.0.jar:?]
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:1011) ~[jna-5.14.0.jar:?]
	at com.sun.jna.Native.<clinit>(Native.java:221) ~[jna-5.14.0.jar:?]
	at com.sun.jna.Structure.setAlignType(Structure.java:291) ~[jna-5.14.0.jar:?]
	at com.sun.jna.Structure.<init>(Structure.java:208) ~[jna-5.14.0.jar:?]
	at com.sun.jna.Structure.<init>(Structure.java:204) ~[jna-5.14.0.jar:?]
	at com.sun.jna.Structure.<init>(Structure.java:191) ~[jna-5.14.0.jar:?]
	at com.sun.jna.Structure.<init>(Structure.java:183) ~[jna-5.14.0.jar:?]
	at com.sun.jna.platform.win32.WinNT$OSVERSIONINFOEX.<init>(WinNT.java:1980) ~[jna-platform-5.14.0.jar:?]
	at com.sun.jna.platform.win32.VersionHelpers.IsWindowsVersionOrGreater(VersionHelpers.java:59) ~[jna-platform-5.14.0.jar:?]
	at com.sun.jna.platform.win32.VersionHelpers.IsWindowsVistaOrGreater(VersionHelpers.java:127) ~[jna-platform-5.14.0.jar:?]
	at net.caffeinemc.mods.sodium.client.platform.windows.api.d3dkmt.D3DKMT.<clinit>(D3DKMT.java:28) ~[sodium-fabric-0.6.0-beta.1+mc1.21.jar:?]
	at net.caffeinemc.mods.sodium.client.compatibility.environment.probe.GraphicsAdapterProbe.findAdapters$Windows(GraphicsAdapterProbe.java:56) ~[sodium-fabric-0.6.0-beta.1+mc1.21.jar:?]
	at net.caffeinemc.mods.sodium.client.compatibility.environment.probe.GraphicsAdapterProbe.findAdapters(GraphicsAdapterProbe.java:29) ~[sodium-fabric-0.6.0-beta.1+mc1.21.jar:?]
	at net.caffeinemc.mods.sodium.fabric.SodiumPreLaunch.onPreLaunch(SodiumPreLaunch.java:12) ~[sodium-fabric-0.6.0-beta.1+mc1.21.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.16.3.jar:?]
	... 5 more

### Crash Report

No crash report

**Comment by McLem0nPlay** [comment]
Не еби мозги, играй в ваниллу.
Заебали эти долбаебы, много фпс им надо. Пошел нахуй 👿

**Comment by ironswordX** [comment]
I had an issue using sodium on 1.21.1 with both fabric and quilt, and they would just freeze a little while after I entered the server list

**Comment by jellysquid3** [comment]
Your launcher's configuration appears to be broken, as certain files are not present. Please try creating a new instance for Minecraft 1.21 in Prism Launcher, and make sure you are not playing in offline mode.

**Comment by Prark00** [comment]
> Your launcher's configuration appears to be broken, as certain files are not present. Please try creating a new instance for Minecraft 1.21 in Prism Launcher, and make sure you are not playing in offline mode.

I did what you asked, nothing changed.
Plus I tried on the official launcher there is the same error.

**Comment by jellysquid3** [comment]
I do not know why the issue is happening, but it is not a problem with Sodium, and there doesn't seem to be anything we can do about it. Minecraft uses the JNA library for other things and if that doesn't work either, the game will crash even without Sodium installed.

Most likely your system is missing dynamic libraries or there is a problem with the dynamic linker.

**Comment by Banananananananannananana** [comment]
(A mod crashed on startup!)
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium' at 'net.caffeinemc.mods.sodium.fabric.SodiumPreLaunch'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:158)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:66)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium' at 'net.caffeinemc.mods.sodium.fabric.SodiumPreLaunch'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$0(FabricLoaderImpl.java:409)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:407)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:156)
	... 2 more
Caused by: java.lang.UnsatisfiedLinkError: Failed to locate library: lwjgl.dll
	at knot//org.lwjgl.system.Library.loadSystem(Library.java:174)
	at knot//org.lwjgl.system.Library.loadSystem(Library.java:64)
	at knot//org.lwjgl.system.Library.<clinit>(Library.java:52)
	at knot//org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:100)
	at knot//org.lwjgl.system.Pointer$Default.<clinit>(Pointer.java:67)
	at knot//org.lwjgl.system.APIUtil.apiCreateLibrary(APIUtil.java:126)
	at knot//net.caffeinemc.mods.sodium.client.platform.windows.api.Gdi32.<clinit>(Gdi32.java:11)
	at knot//net.caffeinemc.mods.sodium.client.platform.windows.api.d3dkmt.D3DKMT.findGraphicsAdapters(D3DKMT.java:28)
	at knot//net.caffeinemc.mods.sodium.client.compatibility.environment.probe.GraphicsAdapterProbe.findAdapters$Windows(GraphicsAdapterProbe.java:63)
	at knot//net.caffeinemc.mods.sodium.client.compatibility.environment.probe.GraphicsAdapterProbe.findAdapters(GraphicsAdapterProbe.java:36)
	at knot//net.caffeinemc.mods.sodium.fabric.SodiumPreLaunch.onPreLaunch(SodiumPreLaunch.java:12)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:405)
	... 3 more

**Comment by douira** [comment]
This is not a support forum. Please come to [our discord server](https://jellysquid.me/discord) to receive help.
