### ISSUE TITLE
Sodium 1.20.4 keeps crashing my game and i dont know how to fix it

### ISSUE THREAD

**Issue by Willweasly** [jellysquid3/Sodium#2733]
### Bug Description

im able to run minecraft without sodium but whenever i try to it crashes with error code 1

### Reproduction Steps

I downloaded sodium 1.20.4 and put it in my mods folder with architectury, cloth config, fabric api, ForgeConfigAPIPort, immersivemc, iris, physics mod, vivecraft, and vrapi. if I take sodium out of the folder it works perfectly fine but when i put it in it crashes everytime.

### Log File

[16:39:46] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.3
[16:39:46] [main/WARN]: Mod resolution failed
[16:39:46] [main/INFO]: Immediate reason: [HARD_DEP iris 1.7.2+mc1.20.4 {depends sodium @ [0.5.8 || 0.5.11]}, HARD_DEP_INCOMPATIBLE_PRESELECTED sodium 0.5.11+mc1.20.6 {depends minecraft @ [1.20.6]}, ROOT_FORCELOAD_SINGLE iris 1.7.2+mc1.20.4]
[16:39:46] [main/INFO]: Reason: [HARD_DEP sodium 0.5.11+mc1.20.6 {depends minecraft @ [1.20.6]}]
[16:39:46] [main/INFO]: Fix: add [], remove [], replace [[sodium 0.5.11+mc1.20.6] -> add:sodium 0.5.11 ([[0.5.8,0.5.8], [0.5.11,0.5.11]])]
[16:39:46] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Sodium' (sodium) 0.5.11+mc1.20.6 with version 0.5.8 or version 0.5.11 that is compatible with:
		 - minecraft 1.20.4
More details:
	 - Mod 'Sodium' (sodium) 0.5.11+mc1.20.6 requires version 1.20.6 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]

### Crash Report

RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium'!
    <html>at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)<br>at 
    net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)<br>at 
    net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)<br>at 
    net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)<br>at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) 
   <br>at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)</html>
<html>UnsupportedClassVersionError: me/jellysquid/mods/sodium/client/compatibility/workarounds/Workarounds has been compiled<br>by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes<br>class file versions up to 61.0</html>
    <html>at java.base/java.lang.ClassLoader.defineClass1(Native Method)<br>at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)<br>at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)<br>at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160)<br>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)<br>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)<br>at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)<br>at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)<br>at me.jellysquid.mods.sodium.client.SodiumPreLaunch.onPreLaunch(SodiumPreLaunch.java:13)<br>at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)<br>... 3 more</html>

**Comment by 777Naity** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by Willweasly** [comment]
dont download this its a virus

**Comment by pajicadvance** [comment]
You're trying to use a version of Sodium that's not compatible with 1.20.4, the latest Sodium version for that MC version is 0.5.8.

**Comment by Willweasly** [comment]
i thought it was for mc1.20.4 but it was file version 0.5.8

**Comment by Willweasly** [comment]
![Screenshot (147)](https://github.com/user-attachments/assets/380dccbd-75b1-4b60-bde7-e17aed249b9c)
these are all the mods i have installed

**Comment by pajicadvance** [comment]
The log you posted is saying you are using 0.5.11 so I don't know what's going on.

**Comment by Willweasly** [comment]
what about this log???

**Comment by Willweasly** [comment]
[17:05:19] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.3
[17:05:19] [main/INFO]: Loading 74 mods:
	- architectury 11.1.17
	- cloth-config 13.0.121
	   \-- cloth-basic-math 0.6.1
	- fabric-api 0.97.2+1.20.4
	   |-- fabric-api-base 0.4.37+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.50+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.17+78d798af4f
	   |-- fabric-block-api-v1 1.0.17+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.5+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.47+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.8+78d798af4f
	   |-- fabric-command-api-v1 1.2.42+f71b366f4f
	   |-- fabric-command-api-v2 2.2.21+78d798af4f
	   |-- fabric-commands-v0 0.2.59+df3654b34f
	   |-- fabric-containers-v0 0.1.88+df3654b34f
	   |-- fabric-content-registries-v0 5.0.16+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.11+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.24+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.1.5+b90db5744f
	   |-- fabric-data-generation-api-v1 13.2.6+5c0133444f
	   |-- fabric-dimensions-v1 2.1.63+6605d1a84f
	   |-- fabric-entity-events-v1 1.6.2+09fc25014f
	   |-- fabric-events-interaction-v0 0.7.2+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.75+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.47+78d798af4f
	   |-- fabric-item-api-v1 2.3.0+bcdd12964f
	   |-- fabric-item-group-api-v1 4.0.27+ee30b13a4f
	   |-- fabric-key-binding-api-v1 1.0.42+78d798af4f
	   |-- fabric-keybindings-v0 0.2.40+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.3.1+a67ffb5d4f
	   |-- fabric-loot-api-v2 2.1.10+78d798af4f
	   |-- fabric-message-api-v1 6.0.6+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.66+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.9+78d798af4f
	   |-- fabric-models-v0 0.4.8+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.9+6abb6a4b4f
	   |-- fabric-object-builder-api-v1 13.1.0+dba1195c4f
	   |-- fabric-particles-v1 1.1.8+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.22+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.21+ee30b13a4f
	   |-- fabric-renderer-api-v1 3.2.5+78d798af4f
	   |-- fabric-renderer-indigo 1.5.6+d331d3144f
	   |-- fabric-renderer-registries-v1 3.2.54+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.43+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.1.2+e761c6694f
	   |-- fabric-rendering-v0 1.1.57+df3654b34f
	   |-- fabric-rendering-v1 3.2.1+6fd945a04f
	   |-- fabric-resource-conditions-api-v1 2.3.15+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.21+ee30b13a4f
	   |-- fabric-screen-api-v1 2.0.18+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.57+78d798af4f
	   |-- fabric-sound-api-v1 1.0.18+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.12+90f2d7b14f
	   \-- fabric-transitive-access-wideners-v1 5.0.15+78d798af4f
	- fabricloader 0.15.3
	   \-- mixinextras 0.3.2
	- forgeconfigapiport 20.4.3
	   |-- com_electronwill_night-config_core 3.6.6
	   \-- com_electronwill_night-config_toml 3.6.6
	- immersivemc 1.5.0-beta1
	- iris 1.7.2+mc1.20.4
	   |-- io_github_douira_glsl-transformer 2.0.1
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.13.1
	- java 17
	- minecraft 1.20.4
	- physicsmod 3.0.14
	- sodium 0.5.8+mc1.20.4
	- vivecraft 1.20.4-1.1.11
	   |-- com_electronwill_night-config_core 3.6.6
	   |-- com_electronwill_night-config_toml 3.6.6
	   |-- org_lwjgl_lwjgl-openvr 3.3.2
	   |-- org_lwjgl_lwjgl-openvr_natives-linux 3.3.2
	   |-- org_lwjgl_lwjgl-openvr_natives-macos 3.3.2
	   \-- org_lwjgl_lwjgl-openvr_natives-windows 3.3.2
	- vrapi 3.0.9
[17:05:20] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/William/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[17:05:20] [main/INFO]: Compatibility level set to JAVA_16
[17:05:20] [main/INFO]: Compatibility level set to JAVA_17
[17:05:20] [main/WARN]: Reference map 'ForgeConfigAPIPort-Common-refmap.json' for forgeconfigapiport.common.mixins.json could not be read. If this is a development environment you can ignore this message
[17:05:20] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 3 override(s) found
[17:05:21] [main/WARN]: Error loading class: org/vivecraft/gameplay/trackers/BackpackTracker (java.lang.ClassNotFoundException: org/vivecraft/gameplay/trackers/BackpackTracker)
[17:05:21] [main/WARN]: Error loading class: org/vivecraft/render/VivecraftItemRendering (java.lang.ClassNotFoundException: org/vivecraft/render/VivecraftItemRendering)
[17:05:21] [main/WARN]: @Mixin target org.vivecraft.render.VivecraftItemRendering was not found mixins.immersivemc.json:throw_render_helpers.vivecraft.VivecraftItemRenderingMixin from mod immersivemc
[17:05:21] [main/WARN]: Error loading class: software/bernie/geckolib/renderer/GeoRenderer (java.lang.ClassNotFoundException: software/bernie/geckolib/renderer/GeoRenderer)
[17:05:21] [main/WARN]: Error loading class: net/optifine/shaders/Shaders (java.lang.ClassNotFoundException: net/optifine/shaders/Shaders)
[17:05:21] [main/WARN]: Error loading class: net/optifine/shaders/ShadersCompatibility (java.lang.ClassNotFoundException: net/optifine/shaders/ShadersCompatibility)
[17:05:21] [main/WARN]: Error loading class: net/optifine/shaders/Programs (java.lang.ClassNotFoundException: net/optifine/shaders/Programs)
[17:05:21] [main/WARN]: Error loading class: org/valkyrienskies/core/impl/game/ships/ShipObjectClient (java.lang.ClassNotFoundException: org/valkyrienskies/core/impl/game/ships/ShipObjectClient)
[17:05:21] [main/WARN]: Error loading class: net/optifine/util/BlockUtils (java.lang.ClassNotFoundException: net/optifine/util/BlockUtils)
[17:05:21] [main/WARN]: Error loading class: ca/spottedleaf/starlight/common/light/StarLightEngine (java.lang.ClassNotFoundException: ca/spottedleaf/starlight/common/light/StarLightEngine)
[17:05:21] [main/WARN]: Error loading class: link/infra/indium/renderer/render/TerrainRenderContext (java.lang.ClassNotFoundException: link/infra/indium/renderer/render/TerrainRenderContext)
[17:05:21] [main/WARN]: Force-disabling mixin 'features.render.entity.CuboidMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[17:05:21] [main/WARN]: Force-disabling mixin 'features.render.entity.ModelPartMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[17:05:21] [main/WARN]: Force-disabling mixin 'features.render.entity.cull.EntityRendererMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[17:05:21] [main/WARN]: Force-disabling mixin 'features.render.entity.shadows.EntityRenderDispatcherMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[17:05:21] [main/WARN]: Force-disabling mixin 'features.render.gui.font.GlyphRendererMixin' as rule 'mixin.features.render.gui.font' (added by mods [iris]) disables it and children
[17:05:21] [main/WARN]: Force-disabling mixin 'features.render.world.sky.BackgroundRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[17:05:21] [main/WARN]: Force-disabling mixin 'features.render.world.sky.ClientWorldMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[17:05:21] [main/WARN]: Force-disabling mixin 'features.render.world.sky.WorldRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[17:05:21] [main/INFO]: Vivecraft: applying 'dynamicfps' fixes
[17:05:21] [main/INFO]: Vivecraft: applying 'sodium' fixes
[17:05:21] [main/INFO]: Vivecraft: applying 'sodium' fixes
[17:05:21] [main/INFO]: Vivecraft: applying 'iris' fixes
[17:05:21] [main/INFO]: Vivecraft: skipping mixin 'org.vivecraft.mod_compat_vr.iris.mixin.irisshaders.IrisChunkProgramOverridesMixin'
[17:05:21] [main/INFO]: Vivecraft: skipping mixin 'org.vivecraft.mod_compat_vr.iris.mixin.irisshaders.IrisChunkProgramOverridesMixinSodium_0_6'
[17:05:21] [main/INFO]: Vivecraft: applying 'modmenu' fixes
[17:05:21] [main/INFO]: Vivecraft: applying 'physicsmod' fixes
[17:05:21] [main/WARN]: Error loading class: org/vivecraft/gameplay/trackers/BackpackTracker (java.lang.ClassNotFoundException: org/vivecraft/gameplay/trackers/BackpackTracker)
[17:05:21] [main/WARN]: Error loading class: org/vivecraft/gameplay/trackers/BackpackTracker (java.lang.ClassNotFoundException: org/vivecraft/gameplay/trackers/BackpackTracker)
[17:05:22] [main/INFO]: Searching for graphics cards...
[17:05:22] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=NVIDIA, name=NVIDIA GeForce GTX 1070 Ti, version=DriverVersion=32.0.15.6094]
[17:05:22] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[17:05:22] [main/ERROR]: A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.15.3.jar:?]
	... 2 more
Caused by: java.lang.UnsupportedClassVersionError: me/jellysquid/mods/sodium/client/compatibility/workarounds/Workarounds has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at me.jellysquid.mods.sodium.client.SodiumPreLaunch.onPreLaunch(SodiumPreLaunch.java:13) ~[sodium-fabric-0.5.8+mc1.20.4%20(1).jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.15.3.jar:?]
	... 2 more

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by douira** [comment]
@Willweasly The GitHub Issue tracker is not intended for support requests. We can help you with your problem on [our discord server.](https://jellysquid.me/discord) Please make a new support request there.

**Comment by Willweasly** [comment]
i still would like some help on how to fix this please

**Comment by MeeniMc** [comment]
follow the link above to the discord, you'll receive help there.

**Comment by Willweasly** [comment]
ok thank you
