### ISSUE TITLE
Colourless potions,splash,etc

### ISSUE THREAD

**Issue by Jayplayz7209** [jellysquid3/Sodium#2795]
### Bug Description

Whenever I apply sodium mod and load up the game the potion colours always go transparent leaving the potion bottle only looking like a empty potion.

### Reproduction Steps

Just put sodium mod,sodium extra and reeses sodium options mod in the mods folder and run minecraft.

### Log File

[2024-09-28-1.log.gz](https://github.com/user-attachments/files/17264592/2024-09-28-1.log.gz)

### Crash Report

<html>
<body>

[06:20:19] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.16.5
--
2 | [06:20:19] [main/WARN]: Mod resolution failed
3 | [06:20:19] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE sodium-extra 0.5.4 mc1.20.1-build.115 {depends fabric-api @ [*]}, ROOT_FORCELOAD_SINGLE sodium-extra 0.5.4 mc1.20.1-build.115]
4 | [06:20:19] [main/INFO]: Reason: [HARD_DEP sodium-extra 0.5.4 mc1.20.1-build.115 {depends fabric-api @ [*]}]
5 | [06:20:19] [main/INFO]: Fix: add [add:fabric-api 1 ([(-?,?)])], remove [], replace []
6 | [06:20:20] [main/ERROR]: Incompatible mods found!
7 | net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
8 | A potential solution has been determined, this may resolve your problem:
9 | - Install fabric-api, any version.
10 | More details:
11 | - Mod 'Sodium Extra' (sodium-extra) 0.5.4 mc1.20.1-build.115 requires any version of fabric-api, which is missing!
12 | at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.5.jar:?]
13 | at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.5.jar:?]
14 | at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.5.jar:?]
15 | at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.16.5.jar:?]
16 | at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.5.jar:?]

</body>
</html>[06:20:19] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.16.5
[06:[2](https://mclo.gs/JMCGdnH#L2)0:19] [main/WARN]: Mod resolution failed
[06:20:19] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE sodium-extra 0.5.4 mc1.20.1-build.115 {depends fabric-api @ [*]}, ROOT_FORCELOAD_SINGLE sodium-extra 0.5.4 mc1.20.1-build.115]
[06:20:19] [main/INFO]: Reason: [HARD_DEP sodium-extra 0.5.4 mc1.20.1-build.115 {depends fabric-api @ [*]}]
[06:20:19] [main/INFO]: Fix: add [add:fabric-api 1 ([(-?,?)])], remove [], replace []
[06:20:20] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Install fabric-api, any version.
More details:
	 - Mod 'Sodium Extra' (sodium-extra) 0.5.4 mc1.20.1-build.115 requires any version of fabric-api, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:2[3](https://mclo.gs/JMCGdnH#L3)) ~[fabric-loader-0.16.5.jar:?]

**Comment by Poopooracoocoo** [comment]
That log doesn't have Sodium and that crash report is just the dependency resolver window. 

If you're having issues locating the right log and crash report, I suggest deleting the `logs` and `crash-reports` folders and then reproducing the issue, and then crashing the game (by holding F3+C).
