### ISSUE TITLE
@Mixin target me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages was not found seamless-fabric.mixins.json:SodiumGameOptionPagesMixin from mod seamless

### ISSUE THREAD

**Issue by Shadowblitz16** [jellysquid3/Sodium#2799]
### Bug Description

I am getting this warning
```
[main/WARN]: @Mixin target me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages was not found seamless-fabric.mixins.json:SodiumGameOptionPagesMixin from mod seamless
```

It would be nice if `me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages` was included for the mod seamless or the warning muted if it has 100% zero effect on gameplay.

If this is an issue with seamless let me know I will close this and report it there.

### Reproduction Steps

- download mods 
- launch minecraft
- see logs

### Log File

https://mclo.gs/p21AsCm

### Crash Report

```
[14:01:11] [Render thread/INFO]: [System] [CHAT] [Debug]: F3 + C is held down. This will crash the game unless released.
[14:01:12] [Render thread/INFO]: [System] [CHAT] [Debug]: Crashing in 8...
[14:01:13] [Render thread/INFO]: [System] [CHAT] [Debug]: Crashing in 7...
[14:01:14] [Render thread/INFO]: [System] [CHAT] [Debug]: Crashing in 6...
[14:01:15] [Render thread/INFO]: [System] [CHAT] [Debug]: Crashing in 5...
[14:01:16] [Render thread/INFO]: [System] [CHAT] [Debug]: Crashing in 4...
[14:01:17] [Render thread/INFO]: [System] [CHAT] [Debug]: Crashing in 3...
[14:01:18] [Render thread/INFO]: [System] [CHAT] [Debug]: Crashing in 2...
[14:01:19] [Render thread/INFO]: [System] [CHAT] [Debug]: Crashing in 1...
[14:01:20] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Manually triggered debug crash
	at net.minecraft.class_309.method_1474(class_309.java:531) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:2009) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1246) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.5.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.lang.Throwable: Manually triggered debug crash
	at net.minecraft.class_309.method_1474(class_309.java:528) ~[client-intermediary.jar:?]
	... 10 more
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 2024-10-05 14:01:20
Description: Manually triggered debug crash

java.lang.Throwable: Manually triggered debug crash
	at net.minecraft.class_309.method_1474(class_309.java:528)
	at net.minecraft.class_310.method_1574(class_310.java:2009)
	at net.minecraft.class_310.method_1523(class_310.java:1246)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_309.method_1474(class_309.java:528)

-- Manual crash details --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.class_309.method_1474(class_309.java:528)
	at net.minecraft.class_310.method_1574(class_310.java:2009)
	at net.minecraft.class_310.method_1523(class_310.java:1246)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Uptime --
Details:
	JVM uptime: 52.453s
	Wall uptime: 45.164s
	High-res time: 39.907s
	Client ticks: 718 ticks / 35.900s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:902)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, balm-fabric, caffeineconfig, cloth-config, conditional-mixin, connectedglass, cratedelight, distanthorizons, dynamic_fps, enhancedblockentities, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, farmersdelight, forgeconfigapiport, fpsreducer, handcrafted, krypton, lithium, mine-spawners, mm, modmenu, moonlight, moreculling, moredelight, notenoughanimations, oceansdelight, placeholder-api, plasmovoice, porting_lib_accessors, porting_lib_asm, porting_lib_attributes, porting_lib_base, porting_lib_blocks, porting_lib_common, porting_lib_conditions, porting_lib_config, porting_lib_core, porting_lib_entity, porting_lib_extensions, porting_lib_fluids, porting_lib_gametest, porting_lib_gui_utils, porting_lib_item_abilities, porting_lib_lazy_registration, porting_lib_level_events, porting_lib_loot, porting_lib_mixin_extensions, porting_lib_recipe_book_categories, porting_lib_tags, porting_lib_transfer, rechiseled, seamless, sodium, sodium-extra, stoneworks, storagedelight, supermartijn642corelib, waystones, xaerominimap, xaeroworldmap, xanders-sodium-options, yet_another_config_lib_v3, seamless:default_seamless, moonlight:mods_dynamic_assets

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Linux (amd64) version 6.10.9-1-liquorix-amd64
	Java Version: 21.0.4, Ubuntu
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Ubuntu
	Memory: 981286664 bytes (935 MiB) / 2334130176 bytes (2226 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5700G with Radeon Graphics
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 4.67
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Cezanne [Radeon Vega Series / Radeon Vega Mobile Series]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MiB): 258.00
	Graphics card #0 deviceId: 0x1638
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MiB): 9637.98
	Virtual memory used (MiB): 12844.86
	Swap memory total (MiB): 1956.00
	Swap memory used (MiB): 1682.01
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 681661.88, total: 935363.19
	Space in storage for workdir (MiB): available: 681661.88, total: 935363.19
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	Fabric Mods: 
		architectury: Architectury 13.0.6
		balm-fabric: Balm 21.0.19
			kuma_api: KumaAPI 21.0.5-SNAPSHOT
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		connectedglass: Connected Glass 1.1.12
		continents: Continents 1.1.5
		cratedelight: Crate Delight 24.9.3-1.21-fabric
		distanthorizons: Distant Horizons 2.2.1-a
		dynamic_fps: Dynamic FPS 3.7.3
			net_lostluma_battery: battery 1.1.0
		enhancedblockentities: Enhanced Block Entities 0.10.2+1.21
		entityculling: EntityCulling 1.7.0
		fabric-api: Fabric API 0.105.0+1.21.1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bc19
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.23+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.8.0+9d22c5fd19
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.28+1daea21519
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.20+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.0+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.5+3fc0e55219
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df36019
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.3+60c3209b19
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+5659912919
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.87+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.3.0+d831205f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabricloader: Fabric Loader 0.16.5
			mixinextras: MixinExtras 0.4.1
		farmersdelight: Farmer's Delight 1.21-2.1.9+refabricated
			mm: Manningham Mills 2.3
			porting_lib_base: Porting Lib Base 3.1.0-beta+fdrf.1+1.21
				porting_lib_accessors: Porting Lib Accessors 3.1.0-beta+fdrf.1+1.21
				porting_lib_asm: Porting Lib ASM 3.1.0-beta+fdrf.1+1.21
				porting_lib_attributes: Porting Lib Attributes 3.1.0-beta+fdrf.1+1.21
				porting_lib_common: Porting Lib Common 3.1.0-beta+fdrf.1+1.21
				porting_lib_entity: Porting Lib Entity 3.1.0-beta+fdrf.1+1.21
				porting_lib_extensions: Porting Lib Extensions 3.1.0-beta+fdrf.1+1.21
				porting_lib_fluids: Porting Lib Fluids 3.1.0-beta+fdrf.1+1.21
				porting_lib_gui_utils: Porting Lib Gui Utils 3.1.0-beta+fdrf.1+1.21
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 3.1.0-beta+fdrf.1+1.21
				porting_lib_tags: Porting Lib Tags 3.0
				porting_lib_transfer: Porting Lib Transfer 3.1.0-beta+fdrf.1+1.21
			porting_lib_config: Porting Lib Config 3.1.0-beta+fdrf.1+1.21
			porting_lib_item_abilities: Porting Lib Item Abilities 3.1.0-beta+fdrf.1+1.21
				porting_lib_blocks: Porting Lib Blocks 3.1.0-beta+fdrf.1+1.21
				porting_lib_core: Porting Lib Core 3.1.0-beta+fdrf.1+1.21
				porting_lib_gametest: Porting Lib GameTest 3.1.0-beta+fdrf.1+1.21
				porting_lib_level_events: Porting Lib Level Events 3.1.0-beta+fdrf.1+1.21
			porting_lib_lazy_registration: Porting Lib Lazy Register 3.1.0-beta+fdrf.1+1.21
			porting_lib_loot: Porting Lib Loot 3.1.0-beta+fdrf.1+1.21
				porting_lib_conditions: Porting Lib Conditions 3.1.0-beta+fdrf.1+1.21
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 3.1.0-beta+fdrf.1+1.21
		forgeconfigapiport: Forge Config API Port 21.1.1
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
		fpsreducer: FPS Reducer 1.21-2.9
		fusion: Fusion 1.1.1
		handcrafted: Handcrafted 4.0.2
		java: OpenJDK 64-Bit Server VM 21
		krypton: Krypton 0.2.8
			com_velocitypowered_velocity-native: velocity-native 3.3.0-SNAPSHOT
		lithium: Lithium 0.13.1
		mine-spawners: Minespawners 1.4.2
		minecraft: Minecraft 1.21.1
		modmenu: Mod Menu 11.0.2
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a790
		moonlight: Moonlight Lib 1.21-2.14.20
		moreculling: More Culling 1.0.0-beta.2
			conditional-mixin: conditional mixin 0.6.3
			mixinsquared: MixinSquared 0.2.0
		moredelight: More Delight 24.9.27-1.21-fabric
		notenoughanimations: NotEnoughAnimations 1.7.6
		nullscape: Nullscape 1.2.7
		oceansdelight: Ocean's Delight fdrf-fabric-1.0.2-1.21
		placeholder-api: Placeholder API 2.4.1+1.21
		plasmovoice: Plasmo Voice 2.1.0
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
		puzzleslib: Puzzles Lib 21.1.17
		rechiseled: Rechiseled 1.1.6+b
		resourcefullib: Resourceful Lib 3.0.10
			com_teamresourceful_bytecodecs: bytecodecs 1.1.2
			com_teamresourceful_yabn: yabn 1.0.3
		seamless: Seamless 2.3.0
		sodium: Sodium 0.6.0-beta.2+mc1.21.1
		sodium-extra: Sodium Extra 0.6.0-beta.3+mc1.21.1
		stoneworks: Stoneworks 21.1.0
		storagedelight: Storage Delight 24.9.11-1.21-fabric
		structory: Structory 1.3.5
		structory_towers: Structory: Towers 1.0.7
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.17+c
		terralith: Terralith 2.5.5
		waystones: Waystones 21.1.4
		xaerominimap: Xaero's Minimap 24.5.0
		xaeroworldmap: Xaero's World Map 1.39.0
		xanders-sodium-options: Xander's Sodium Options 2.0.0+1.21.1
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Launched Version: 1.21.1
	Launcher name: PrismLauncher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: AMD Radeon Graphics (radeonsi, renoir, LLVM 17.0.6, DRM 3.57, 6.10.9-1-liquorix-amd64) GL version 4.6 (Core Profile) Mesa 24.0.9-0ubuntu0.1, AMD
	Window size: 854x480
	GFLW Platform: x11
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fast
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, fabric, balm-fabric (incompatible), caffeineconfig, cloth-config, conditional-mixin, connectedglass, cratedelight, distanthorizons (incompatible), dynamic_fps, enhancedblockentities, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, farmersdelight, forgeconfigapiport, fpsreducer, handcrafted, krypton, lithium, mine-spawners, mm, modmenu, moonlight, moreculling, moredelight, notenoughanimations, oceansdelight, placeholder-api, plasmovoice, porting_lib_accessors, porting_lib_asm, porting_lib_attributes, porting_lib_base, porting_lib_blocks, porting_lib_common, porting_lib_conditions, porting_lib_config, porting_lib_core, porting_lib_entity, porting_lib_extensions, porting_lib_fluids, porting_lib_gametest, porting_lib_gui_utils, porting_lib_item_abilities, porting_lib_lazy_registration, porting_lib_level_events, porting_lib_loot, porting_lib_mixin_extensions, porting_lib_recipe_book_categories, porting_lib_tags, porting_lib_transfer, rechiseled, seamless, sodium, sodium-extra, stoneworks, storagedelight, supermartijn642corelib, waystones (incompatible), xaerominimap (incompatible), xaeroworldmap (incompatible), xanders-sodium-options, yet_another_config_lib_v3 (incompatible), seamless:default_seamless, moonlight:mods_dynamic_assets
	Current Language: en_us
	Locale: en_US
	System encoding: UTF-8
	File encoding: UTF-8
	CPU: 16x AMD Ryzen 7 5700G with Radeon Graphics
#@!@# Game crashed! Crash report saved to: #@!@# /home/shadowblitz16/.local/share/PrismLauncher/instances/Test/.minecraft/crash-reports/crash-2024-10-05_14.01.20-client.txt
Process exited with code 255.
```

**Comment by douira** [comment]
The mod seamless needs to be updated to work with sodium 0.6 beta 2.
