### ISSUE TITLE
macOS: Fullscreen resolution "unsupported" on 1.21.3

### ISSUE THREAD

**Issue by Proton0** [jellysquid3/Sodium#2831]
### Bug Description

I wanted to reduce my fullscreen resolution due to macOS having retina displays causing my M1 air to lag (especially with shaders) but i noticed that it said that its unavailable and is only supported on Windows

![Minecraft 1.21.3](https://github.com/user-attachments/assets/5191c452-9f87-4073-a174-73591453f8db)

but on other versions (1.21.0) it allows me to change the fullscreen resolution
![Minecraft 1.21.0](https://github.com/user-attachments/assets/10a0e042-49da-42f3-ab2f-de3c279073db)

I launched Minecraft 1.21.3 without Sodium and the fullscreen resolution slider works and is supported
![Minecraft 1.21.3 without sodium](https://github.com/user-attachments/assets/03e92d61-c1ee-41c7-8870-cb8143d87a7e)

My Minecraft version is 1.21.3 and sodium version is 0.6.0-beta.3-fabric and my macOS Version is macOS Seqouia (15.0.1 build 24A348)

### Reproduction Steps

1. Play on Minecraft 1.21.3 on macOS
2. Check fullscreen resolution (should say unsupported)

### Log File

[11:12:51] [main/INFO]: Loading Minecraft 1.21.3 with Fabric Loader 0.16.7
[11:12:51] [main/INFO]: Loading 11 mods:
	- fabricloader 0.16.7
	   \-- mixinextras 0.4.1
	- java 21
	- minecraft 1.21.3
	- sodium 0.6.0-beta.3+mc1.21.2
	   |-- fabric-api-base 0.4.48+c47b9d431a
	   |-- fabric-block-view-api-v2 1.0.16+c47b9d431a
	   |-- fabric-renderer-api-v1 4.0.3+c47b9d431a
	   |-- fabric-rendering-data-attachment-v1 0.3.54+73761d2e1a
	   |-- fabric-rendering-fluids-v1 3.1.13+c47b9d431a
	   \-- fabric-resource-loader-v0 3.0.5+c47b9d431a
[11:12:51] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/Users/proton/Library/Application%20Support/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.15.3+mixin.0.8.7/sponge-mixin-0.15.3+mixin.0.8.7.jar Service=Knot/Fabric Env=CLIENT
[11:12:51] [main/INFO]: Compatibility level set to JAVA_21
[11:12:51] [main/INFO]: Loaded configuration file for Sodium: 43 options available, 0 override(s) found
[11:12:51] [main/WARN]: Reference map 'sodium.refmap.json' for sodium.mixins.json could not be read. If this is a development environment you can ignore this message
[11:12:51] [main/WARN]: Reference map 'sodium-fabric.refmap.json' for sodium-fabric.mixins.json could not be read. If this is a development environment you can ignore this message
[11:12:51] [main/INFO]: Searching for graphics cards...
[11:12:53] [Datafixer Bootstrap/INFO]: 237 Datafixer optimizations took 334 milliseconds
[11:12:54] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).
[11:12:58] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[11:12:58] [Render thread/INFO]: Setting user: Proton0
[11:12:58] [Render thread/INFO]: Backend library: LWJGL version 3.3.3-snapshot
[11:12:59] [Render thread/INFO]: OpenGL Vendor: Apple
[11:12:59] [Render thread/INFO]: OpenGL Renderer: Apple M1
[11:12:59] [Render thread/INFO]: OpenGL Version: 4.1 Metal - 89.3
[11:13:00] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric, fabric-api-base, fabric-block-view-api-v2, fabric-renderer-api-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-resource-loader-v0, fabricloader, sodium
[11:13:00] [Worker-Main-4/INFO]: Found unifont_all_no_pua-15.1.05.hex, loading
[11:13:01] [Worker-Main-1/INFO]: Found unifont_jp_patch-15.1.05.hex, loading
[11:13:02] [Render thread/WARN]: Missing sound for event: minecraft:block.spawner.fall
[11:13:02] [Render thread/INFO]: OpenAL initialized on device MacBook Air Speakers
[11:13:02] [Render thread/INFO]: Sound engine started
[11:13:02] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[11:13:02] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[11:13:02] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[11:13:02] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[11:13:02] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[11:13:02] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[11:13:02] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[11:13:02] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[11:13:02] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[11:13:02] [Render thread/INFO]: Created: 64x64x0 minecraft:textures/atlas/map_decorations.png-atlas
[11:13:02] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[11:13:02] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/paintings.png-atlas
[11:13:02] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[11:13:02] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas
[11:13:41] [Render thread/INFO]: Loaded 1337 recipes
[11:13:41] [Render thread/INFO]: Loaded 1448 advancements
[11:13:41] [Server thread/INFO]: Starting integrated minecraft server version 1.21.3
[11:13:41] [Server thread/INFO]: Generating keypair
[11:13:42] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[11:13:44] [Render thread/INFO]: Preparing spawn area: 0%
[11:13:44] [Render thread/INFO]: Preparing spawn area: 0%
[11:13:44] [Render thread/INFO]: Preparing spawn area: 0%
[11:13:44] [Render thread/INFO]: Preparing spawn area: 0%
[11:13:44] [Render thread/INFO]: Preparing spawn area: 0%
[11:13:44] [Render thread/INFO]: Time elapsed: 2450 ms
[11:13:44] [Server thread/INFO]: Changing view distance to 12, from 10
[11:13:44] [Server thread/INFO]: Changing simulation distance to 12, from 0
[11:13:45] [Server thread/INFO]: Proton0[local:E:c324536a] logged in with entity id 72 at (-531.4749829179203, 80.0, -28.30000001192093)
[11:13:45] [Server thread/INFO]: Proton0 joined the game
[11:13:45] [Render thread/INFO]: Started 2 worker threads
[11:13:45] [Render thread/INFO]: Loaded 2 advancements
[11:13:46] [Server thread/INFO]: Saving and pausing game...
[11:13:46] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[11:13:46] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[11:13:46] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[11:13:46] [Server thread/INFO]: Saving and pausing game...
[11:13:46] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[11:13:46] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[11:13:46] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[11:13:50] [Render thread/INFO]: Flushed changes to Minecraft configuration
[11:14:36] [Render thread/INFO]: [System] [CHAT] [Debug]: Copied location to clipboard
[11:14:37] [Render thread/INFO]: [System] [CHAT] [Debug]: F3 + C is held down. This will crash the game unless released.
[11:14:38] [Render thread/INFO]: [System] [CHAT] [Debug]: Crashing in 8...
[11:14:39] [Render thread/INFO]: [System] [CHAT] [Debug]: Crashing in 7...
[11:14:40] [Render thread/INFO]: [System] [CHAT] [Debug]: Crashing in 6...
[11:14:41] [Render thread/INFO]: [System] [CHAT] [Debug]: Crashing in 5...
[11:14:42] [Render thread/INFO]: [System] [CHAT] [Debug]: Crashing in 4...
[11:14:43] [Render thread/INFO]: [System] [CHAT] [Debug]: Crashing in 3...
[11:14:44] [Render thread/INFO]: [System] [CHAT] [Debug]: Crashing in 2...
[11:14:45] [Render thread/INFO]: [System] [CHAT] [Debug]: Crashing in 1...
[11:14:47] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Manually triggered debug crash
	at knot/net.minecraft.class_309.method_1474(class_309.java:559) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1574(class_310.java:1946) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1313) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:933) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:265) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.7.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.lang.Throwable: Manually triggered debug crash
	at knot/net.minecraft.class_309.method_1474(class_309.java:556) ~[client-intermediary.jar:?]
	... 10 more
[11:14:47] [Server thread/INFO]: Stopping server
[11:14:47] [Server thread/INFO]: Saving players
[11:14:47] [Server thread/INFO]: Saving worlds
[11:14:48] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[11:14:48] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[11:14:48] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[11:14:48] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World): All chunks are saved
[11:14:48] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[11:14:48] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[11:14:48] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[11:14:48] [Render thread/INFO]: Stopping worker threads

### Crash Report

---- Minecraft Crash Report ----
// There are four lights!

Time: 2024-10-24 11:14:48
Description: Manually triggered debug crash

java.lang.Throwable: Manually triggered debug crash
	at knot//net.minecraft.class_309.method_1474(class_309.java:556)
	at knot//net.minecraft.class_310.method_1574(class_310.java:1946)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1313)
	at knot//net.minecraft.class_310.method_1514(class_310.java:933)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//net.minecraft.class_309.method_1474(class_309.java:556)

-- Manual crash details --
Details:
	Modules: 
Stacktrace:
	at knot//net.minecraft.class_309.method_1474(class_309.java:556)
	at knot//net.minecraft.class_310.method_1574(class_310.java:1946)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1313)
	at knot//net.minecraft.class_310.method_1514(class_310.java:933)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Uptime --
Details:
	JVM uptime: 117.428s
	Wall uptime: 109.667s
	High-res time: 108.768s
	Client ticks: 2047 ticks / 102.350s
Stacktrace:
	at knot//net.minecraft.class_310.method_1587(class_310.java:2443)
	at knot//net.minecraft.class_310.method_54580(class_310.java:1002)
	at knot//net.minecraft.class_310.method_1514(class_310.java:954)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Affected level --
Details:
	All players: 1 total; [class_746['Proton0'/72, l='ClientLevel', x=-531.47, y=80.00, z=-28.30]]
	Chunk stats: 961, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (-528,80,-32), Section: (at 0,0,0 in -33,5,-2; chunk contains blocks -528,-64,-32 to -513,319,-17), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,-64,-512 to -513,319,-1)
	Level time: 2877 game time, 2877 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 171

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, fabric-api-base, fabric-block-view-api-v2, fabric-renderer-api-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-resource-loader-v0, fabricloader, sodium

-- System Details --
Details:
	Minecraft Version: 1.21.3
	Minecraft Version ID: 1.21.3
	Operating System: Mac OS X (aarch64) version 15.0.1
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 58152456 bytes (55 MiB) / 878706688 bytes (838 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: ARM64 SoC: Firestorm + Icestorm
	Frequency (GHz): 3.20
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M1
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MiB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MiB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MiB): 8192.00
	Virtual memory used (MiB): 5840.86
	Swap memory total (MiB): 0.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 124153.56, total: 233752.44
	Space in storage for workdir (MiB): available: 124153.56, total: 233752.44
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	Launched Version: 1.21.3
	Launcher name: PrismLauncher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Apple M1 GL version 4.1 Metal - 89.3, Apple
	Window size: 1650x1050
	GFLW Platform: cocoa
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	GPU Warnings: version: Metal
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, fabric, fabric-api-base, fabric-block-view-api-v2, fabric-renderer-api-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-resource-loader-v0, fabricloader, sodium
	Current Language: en_us
	Locale: en_PH
	System encoding: UTF-8
	File encoding: UTF-8
	CPU: 8x Apple M1
	Server Running: true
	Player Count: 1 / 8; [class_3222['Proton0'/72, l='ServerLevel[New World]', x=-531.47, y=80.00, z=-28.30]]
	Active Data Packs: vanilla, fabric
	Available Data Packs: fabric, minecart_improvements, redstone_experiments, trade_rebalance, vanilla, winter_drop
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -2764318682352290268
	Suppressed Exceptions: ~~NONE~~

**Comment by douira** [comment]
It was specifically only enabled on windows because on the other platforms it's kinda broken. We can look into re-enabling it on macOS if it's actually necessary, even though the behavior is quite janky. For the time being, if you want a native solution I recommend that you go into your System Settings and change the display resolution to a lower value that's marked as "low resolution" (otherwise it's just fractional scaling). This also lets you use the regular fullscreen mode (not fullscreen in Minecraft, just using the green macOS fullscreen button) and avoids weird behavior when switching applications. Alternatively you could use one of the Resolution Control mods to render at a lower resolution and then upscale the image, however it seems like none of them are updated for current versions as far as I can tell.

**Comment by Proton0** [comment]
Oh, maybe like an option to enable changing fullscreen resolution because it isnt janky for my system and probably others?

**Comment by JGtHb** [comment]
Another workaround for anyone waiting on the above PR: 

Open the video settings page and then press [control] + [shift] + [p]. This will open the legacy video settings and allow you to change the fullscreen resolution on macOS. This worked well on multiple devices, both at the main menu and in-world.

**Comment by Nek-12** [comment]
I can confirm that on my Mac M1 changing the resolution works flawlessly and is crucial for squeezing more fps out of my instance when running on a 4k monitor.

**Comment by Subilan** [comment]
Can confirm Mac M2 Pro works well with fullscreen resolution set in cmd+shift+p vanilla menu
