### ISSUE TITLE
Exception Loading Entity NBT Error Spam

### ISSUE THREAD

**Issue by Archy-X** [jellysquid3/Sodium#289]
### Expected Behavior
There should be no errors.

### Actual Behavior
Logs are spammed with the same error thousands of times

### Reproduction Steps
1. Log onto a server, the one I was on was Paper 1.12.2 with Viaversion
2. Stand near a mob spawner, specifically I was standing near an Iron Golem Spawner, may also be caused by zombie_pigman as it was in the logs a few times.
3. Look in logs for errors

### Attachments
`[20:34:21] [main/WARN]: Skipping Entity with id minecraft:zombie_pigman
[20:34:21] [main/WARN]: Exception loading entity: 
net.minecraft.class_148: Loading entity NBT
	at net.minecraft.class_1297.method_5651(class_1297.java:1645) ~[intermediary-fabric-loader-0.9.2+build.206-1.16.1.jar:?]
	at net.minecraft.class_1299.method_17839(class_1299.java:468) ~[intermediary-fabric-loader-0.9.2+build.206-1.16.1.jar:?]
	at net.minecraft.class_1299$$Lambda$3502/1297726039.accept(Unknown Source) ~[?:?]
	at net.minecraft.class_156.method_17974(class_156.java:401) ~[intermediary-fabric-loader-0.9.2+build.206-1.16.1.jar:?]
	at net.minecraft.class_1299.method_5892(class_1299.java:467) ~[intermediary-fabric-loader-0.9.2+build.206-1.16.1.jar:?]
	at net.minecraft.class_1299.method_17848(class_1299.java:530) [intermediary-fabric-loader-0.9.2+build.206-1.16.1.jar:?]
	at net.minecraft.class_1299.method_17842(class_1299.java:511) [intermediary-fabric-loader-0.9.2+build.206-1.16.1.jar:?]
	at net.minecraft.class_1917.method_8283(class_1917.java:256) [intermediary-fabric-loader-0.9.2+build.206-1.16.1.jar:?]
	at net.minecraft.class_839.method_3589(class_839.java:22) [intermediary-fabric-loader-0.9.2+build.206-1.16.1.jar:?]
	at net.minecraft.class_839.method_3569(class_839.java:12) [intermediary-fabric-loader-0.9.2+build.206-1.16.1.jar:?]
	at net.minecraft.class_824.method_23079(class_824.java:107) [intermediary-fabric-loader-0.9.2+build.206-1.16.1.jar:?]
	at net.minecraft.class_824.method_23081(class_824.java:96) [intermediary-fabric-loader-0.9.2+build.206-1.16.1.jar:?]
	at net.minecraft.class_824$$Lambda$3489/1478363267.run(Unknown Source) [intermediary-fabric-loader-0.9.2+build.206-1.16.1.jar:?]
	at net.minecraft.class_824.method_3554(class_824.java:128) [intermediary-fabric-loader-0.9.2+build.206-1.16.1.jar:?]
	at net.minecraft.class_824.method_3555(class_824.java:96) [intermediary-fabric-loader-0.9.2+build.206-1.16.1.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:302) [sodium-fabric-mc1.16.1-0.1.0.jar:?]
	at net.minecraft.class_761.handler$zck000$onRenderTileEntities(class_761.java:3192) [intermediary-fabric-loader-0.9.2+build.206-1.16.1.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1245) [intermediary-fabric-loader-0.9.2+build.206-1.16.1.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:717) [intermediary-fabric-loader-0.9.2+build.206-1.16.1.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:540) [intermediary-fabric-loader-0.9.2+build.206-1.16.1.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1021) [intermediary-fabric-loader-0.9.2+build.206-1.16.1.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:654) [intermediary-fabric-loader-0.9.2+build.206-1.16.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-fabric-loader-0.9.2+build.206-1.16.1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.2+build.206.jar:?]
Caused by: java.lang.ClassCastException: net.minecraft.class_638 cannot be cast to net.minecraft.class_3218
	at net.minecraft.class_1439.method_5749(class_1439.java:170) ~[intermediary-fabric-loader-0.9.2+build.206-1.16.1.jar:?]
	at net.minecraft.class_1297.method_5651(class_1297.java:1636) ~[intermediary-fabric-loader-0.9.2+build.206-1.16.1.jar:?]
	... 29 more
`

### System Information

- Java Version: 1.8.0_251-b08
- CPU: Intel Core i5-8400
- GPU: NVIDIA GeForce RTX 2060

**Comment by amnotbananaama** [comment]
I can reproduce this (and other people are reporting this) without Sodium installed, just on a Vanilla client. For example PaperMC/Paper/issues/1069 

ViaVersion should not be sending the entity ID `minecraft:zombie_pigman` to a 1.16.x client, as it no longer exists in 1.16.x. This is something that I believe needs to be fixed by the server you are on.

**Comment by amnotbananaama** [comment]
As an alternative, you could look into using [multiconnect](https://github.com/Earthcomputer/multiconnect) on your client, which actually takes the time to handle incompatibilities between versions. This *may* fix your issue
