### ISSUE TITLE
Crash on Snapdragon X Elite

### ISSUE THREAD

**Issue by asdfghjkl403622** [jellysquid3/Sodium#2927]
### Reproduction Steps

attempt to launch an instance with sodium on a snapdragon x elite laptop

### Log File

https://mclo.gs/ZpgNxhl

### Crash Report

A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium' at 'me.jellysquid.mods.sodium.client.SodiumPreLaunch'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium' at 'me.jellysquid.mods.sodium.client.SodiumPreLaunch'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	... 5 more
Caused by: java.lang.NullPointerException: Cannot invoke "String.matches(String)" because "driverName" is null
	at knot//me.jellysquid.mods.sodium.client.compatibility.checks.PreLaunchChecks.findIntelDriverMatchingBug899(PreLaunchChecks.java:123)
	at knot//me.jellysquid.mods.sodium.client.compatibility.checks.PreLaunchChecks.onGameInit(PreLaunchChecks.java:60)
	at knot//me.jellysquid.mods.sodium.client.SodiumPreLaunch.onPreLaunch(SodiumPreLaunch.java:13)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 6 more

I can't generate a crash report because the game crashes before I get to the main menu, and there is nothing in th ecrash report directory.

**Comment by asdfghjkl403622** [comment]
sodium works on 1.21.4 but not on 1.20.1

**Comment by jellysquid3** [comment]
Sodium 0.5 has a bug with detecting certain OpenGL drivers since they don't provide a driver name. This was fixed in Sodium 0.6 but we haven't backported the changes yet.

**Comment by douira** [comment]
Is this a duplicate of https://github.com/CaffeineMC/sodium/issues/2591?

**Comment by jellysquid3** [comment]
This is a duplicate, but it was kept open because we needed a backport to Sodium 0.5.x. Since this has been done in Sodium 0.5.12, we can close it.
