### ISSUE TITLE
Crash while rendering moving block entities [0.6.4]

### ISSUE THREAD

**Issue by litetex** [jellysquid3/Sodium#2940]
### Bug Description

Just updated to 1.21.3-0.6.4 (from 1.21.3-0.6.3)  and immediately ran into an error:

```
Description: Rendering Block Entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1920.method_24852(net.minecraft.class_2350, boolean)" because "level" is null
	at knot//net.caffeinemc.mods.sodium.client.model.light.smooth.SmoothLightPipeline.<init>(SmoothLightPipeline.java:75)
	at knot//net.caffeinemc.mods.sodium.client.model.light.LightPipelineProvider.<init>(LightPipelineProvider.java:13)
	at knot//net.caffeinemc.mods.sodium.client.render.frapi.render.NonTerrainBlockRenderContext.<init>(NonTerrainBlockRenderContext.java:56)
...

-- Block Entity Details --
Details:
	Name: minecraft:piston // net.minecraft.class_2669
	Block: Block{minecraft:moving_piston}[facing=up,type=sticky]
	Block location: World: (-587,71,-514), Section: (at 5,7,14 in -37,4,-33; chunk contains blocks -592,-64,-528 to -577,319,-513), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,-64,-1024 to -513,319,-513)
	Block: Block{minecraft:moving_piston}[facing=up,type=sticky]
	Block location: World: (-587,71,-514), Section: (at 5,7,14 in -37,4,-33; chunk contains blocks -592,-64,-528 to -577,319,-513), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,-64,-1024 to -513,319,-513)
Stacktrace:
	at knot//net.minecraft.class_824.method_3554(class_824.java:104)
	at knot//net.minecraft.class_824.method_3555(class_824.java:79)
	at knot//net.caffeinemc.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntity(SodiumWorldRenderer.java:422)
	at knot//net.caffeinemc.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:357)
	at knot//net.caffeinemc.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:318)
	at knot//net.minecraft.class_761.method_62208(class_761.java:11262)
	at knot//net.minecraft.class_761.method_62214(class_761.java:651)
	at knot//net.minecraft.class_9909.method_61910(class_9909.java:67)
	at knot//net.minecraft.class_761.method_22710(class_761.java:556)
	at knot//net.minecraft.class_757.method_3188(class_757.java:731)
	at knot//net.minecraft.class_757.method_3192(class_757.java:491)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1352)
	at knot//net.minecraft.class_310.method_1514(class_310.java:933)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

### Reproduction Steps

Piston/Observer moves

### Log File

[latest.log](https://github.com/user-attachments/files/18171527/latest.log)

### Crash Report

[crash-2024-12-17_22.03.57-client.txt](https://github.com/user-attachments/files/18171480/crash-2024-12-17_22.03.57-client.txt)
[crash-2024-12-17_22.07.12-client.txt](https://github.com/user-attachments/files/18171481/crash-2024-12-17_22.07.12-client.txt)

**Comment by jellysquid3** [comment]
Ouch! That's a rather severe bug.

**Comment by jellysquid3** [comment]
Fixed with https://github.com/CaffeineMC/sodium/commit/0d4ab847519dfa7be84c562d6fe4e24761c96e7d.

**Comment by suerion** [comment]
@jellysquid3 

https://mclo.gs/awCqc13 

had the same crash on Fabric 1.21.1  after Using an Amboss(Anvil xD)

**Comment by litetex** [comment]
Holy cow that was a fast fix 😄

**Comment by jellysquid3** [comment]
Sodium 0.6.5 has been published and fixes this problem. I've archived the release for Sodium 0.6.4 since it was very recent and was mostly unusable due to this bug.
