### ISSUE TITLE
BetterGrassify does not work with Sodium on 1.21.4

### ISSUE THREAD

**Issue by chrrybmb64** [jellysquid3/Sodium#2948]
### Bug Description

See: https://github.com/UltimatChamp/BetterGrassify/issues/42

BetterGrassify works flawlessly without Sodium on 1.21.4, but when Sodium is installed alongside it, grass looks like vanilla. The dev of BetterGrassify believes this is an issue on Sodium's end.

>  I don't think there are any significant changes in the mod in 1.21.4, except for using Fabric's Model Loading API instead of a mixin into vanilla directly (which shouldn't affect Sodium). Sodium's FRAPI's emitBlockQuads implementation might be broken. You should report to them instead.

### Reproduction Steps

Open a world on 1.21.4 with BetterGrassify 1.4.1 installed, and see that the mod works. Then install Sodium 0.6.5, open the same world again, and see that grass blocks now look like vanilla.

### Log File

https://mclo.gs/G2HD5Q4

### Crash Report

<details>
<summary>Crash Report</summary>

```
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 2024-12-21 20:08:06
Description: Manually triggered debug crash

java.lang.Throwable: Manually triggered debug crash
	at knot//net.minecraft.class_309.method_1474(class_309.java:556)
	at knot//net.minecraft.class_310.method_1574(class_310.java:1937)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1302)
	at knot//net.minecraft.class_310.method_1514(class_310.java:922)
	at knot//net.minecraft.client.main.Main.main(Main.java:267)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//net.minecraft.class_309.method_1474(class_309.java:556)

-- Manual crash details --
Details:
	Modules: 
Stacktrace:
	at knot//net.minecraft.class_309.method_1474(class_309.java:556)
	at knot//net.minecraft.class_310.method_1574(class_310.java:1937)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1302)
	at knot//net.minecraft.class_310.method_1514(class_310.java:922)
	at knot//net.minecraft.client.main.Main.main(Main.java:267)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Uptime --
Details:
	JVM uptime: 23.762s
	Wall uptime: 18.919s
	High-res time: 18.507s
	Client ticks: 360 ticks / 18.000s
Stacktrace:
	at knot//net.minecraft.class_310.method_1587(class_310.java:2371)
	at knot//net.minecraft.class_310.method_54580(class_310.java:991)
	at knot//net.minecraft.class_310.method_1514(class_310.java:943)
	at knot//net.minecraft.client.main.Main.main(Main.java:267)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, bettergrass, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-tag-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, modmenu, placeholder-api, reeses-sodium-options, sodium, sodium-extra

-- System Details --
Details:
	Minecraft Version: 1.21.4
	Minecraft Version ID: 1.21.4
	Operating System: Linux (amd64) version 6.12.4-arch1-1
	Java Version: 21.0.5, Arch Linux
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Arch Linux
	Memory: 68435456 bytes (65 MiB) / 536870912 bytes (512 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5700X3D 8-Core Processor
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Navi 32 [Radeon RX 7700 XT / 7800 XT]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MiB): 258.00
	Graphics card #0 deviceId: 0x747e
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MiB): 16009.30
	Virtual memory used (MiB): 12390.21
	Swap memory total (MiB): 0.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 15967.40, total: 16009.30
	Space in storage for workdir (MiB): available: 344747.13, total: 936784.31
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	Fabric Mods: 
		bettergrass: BetterGrassify 1.4.1+fabric.1.21.4
			blue_endless_jankson: jankson 1.2.3
		fabric-api: Fabric API 0.112.2+1.21.4
			fabric-api-base: Fabric API Base 0.4.54+b47eab6b04
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.86+b1caf1e904
			fabric-biome-api-v1: Fabric Biome API (v1) 15.0.5+b1caf1e904
			fabric-block-api-v1: Fabric Block API (v1) 1.0.31+7feeb73304
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.19+7feeb73304
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 2.0.8+7feeb73304
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.29+20ea1e2304
			fabric-command-api-v1: Fabric Command API (v1) 1.2.62+f71b366f04
			fabric-command-api-v2: Fabric Command API (v2) 2.2.41+e496eb1504
			fabric-commands-v0: Fabric Commands (v0) 0.2.79+df3654b304
			fabric-content-registries-v0: Fabric Content Registries (v0) 9.1.14+7feeb73304
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.9+7f945d5b04
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.9+3d1fb53904
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.3.6+7feeb73304
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.4.6+9aea556b04
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 22.2.2+20ea1e2304
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.10+7feeb73304
			fabric-entity-events-v1: Fabric Entity Events (v1) 2.0.12+60fccc7604
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 4.0.2+a4eebcf004
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.62+7feeb73304
			fabric-item-api-v1: Fabric Item API (v1) 11.1.14+203e6b2304
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.23+7feeb73304
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.56+7feeb73304
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.54+df3654b304
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.4+bf2a60eb04
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.33+3f89f5a504
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.21+203e6b2304
			fabric-message-api-v1: Fabric Message API (v1) 6.0.25+7feeb73304
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 4.1.1+7b6b225304
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.9+cc0fa2fe04
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 18.0.8+d70d2c0604
			fabric-particles-v1: Fabric Particles (v1) 4.0.14+7feeb73304
			fabric-recipe-api-v1: Fabric Recipe API (v1) 8.0.5+b1caf1e904
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 6.1.2+3d1fb53904
			fabric-renderer-api-v1: Fabric Renderer API (v1) 5.0.2+84404cdd04
			fabric-renderer-indigo: Fabric Renderer - Indigo 2.0.2+84404cdd04
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.57+73761d2e04
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.19+7feeb73304
			fabric-rendering-v1: Fabric Rendering (v1) 10.1.2+b874120c04
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 5.0.13+203e6b2304
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 3.0.11+b1caf1e904
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.38+7feeb73304
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.109+7feeb73304
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.32+7feeb73304
			fabric-tag-api-v1: Fabric Tag API (v1) 1.0.2+20ea1e2304
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.8+b1caf1e904
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.3.2+56e78b9b04
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.21.4
		modmenu: Mod Menu 13.0.0-beta.1
			placeholder-api: Placeholder API 2.5.1+1.21.3
		no-telemetry: No Telemetry 1.8.0
		reeses-sodium-options: Reese's Sodium Options 1.8.1+mc1.21.4
		sodium: Sodium 0.6.5+mc1.21.4
		sodium-extra: Sodium Extra 0.6.1+mc1.21.4
	Launched Version: 1.21.4
	Launcher name: PrismLauncher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: zink Vulkan 1.3(AMD Radeon RX 7800 XT (RADV NAVI32) (MESA_RADV)) GL version 4.6 (Core Profile) Mesa 24.3.1-arch1.3, Mesa
	Window size: 1920x1080
	GFLW Platform: x11
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 16/16 chunks
	Resource Packs: vanilla, fabric, bettergrass, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-tag-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, modmenu, placeholder-api, reeses-sodium-options, sodium, sodium-extra
	Current Language: en_us
	Locale: en_US
	System encoding: ANSI_X3.4-1968
	File encoding: UTF-8
	CPU: 16x AMD Ryzen 7 5700X3D 8-Core Processor
```

</details>

**Comment by chrrybmb64** [comment]
This bug was fixed with commit [a40937b](https://github.com/CaffeineMC/sodium/commit/a40937b)
