### ISSUE TITLE
Game crashes whenever a piston activates (1.21.4, Sodium 0.6.x)

### ISSUE THREAD

**Issue by Shadow74742** [jellysquid3/Sodium#2957]
### Bug Description

My game crashes whenever a piston is activated, and i know that indium is the solution but indium doesn't support sodium 0.6.x beacuse it already has support for Fabric Rendering API, but the game still crashes. I'm on version 1.21.4

### Reproduction Steps

I joined a singleplayer world and activated a piston

### Log File

[latest.log](https://github.com/user-attachments/files/18270599/latest.log)

### Crash Report

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2024-12-29 19:46:22
Description: Unexpected error

java.lang.IllegalStateException: Pose stack not empty
	at knot//net.minecraft.class_761.method_22979(class_761.java:978)
	at knot//net.minecraft.class_761.method_62214(class_761.java:644)
	at knot//net.minecraft.class_9909.method_61910(class_9909.java:67)
	at knot//net.minecraft.class_761.method_22710(class_761.java:552)
	at knot//net.minecraft.class_757.method_3188(class_757.java:733)
	at knot//net.minecraft.class_757.method_3192(class_757.java:493)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1341)
	at knot//net.minecraft.class_310.method_1514(class_310.java:922)
	at knot//net.minecraft.client.main.Main.main(Main.java:267)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//net.minecraft.class_761.method_22979(class_761.java:978)
	at knot//net.minecraft.class_761.method_62214(class_761.java:644)
	at knot//net.minecraft.class_9909.method_61910(class_9909.java:67)
	at knot//net.minecraft.class_761.method_22710(class_761.java:552)
	at knot//net.minecraft.class_757.method_3188(class_757.java:733)

-- Uptime --
Details:
	JVM uptime: 680.501s
	Wall uptime: 660.636s
	High-res time: 657.391s
	Client ticks: 12492 ticks / 624.600s
Stacktrace:
	at knot//net.minecraft.class_310.method_1587(class_310.java:2371)
	at knot//net.minecraft.class_310.method_54580(class_310.java:991)
	at knot//net.minecraft.class_310.method_1514(class_310.java:946)
	at knot//net.minecraft.client.main.Main.main(Main.java:267)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16)

-- Affected level --
Details:
	All players: 2 total; [class_746['Shadow74742'/51246, l='ClientLevel', x=0.37, y=72.00, z=32.55], class_745['SweetJJ'/51240, l='ClientLevel', x=21.41, y=76.12, z=-19.32]]
	Chunk stats: 18225, 156
	Level dimension: minecraft:overworld
	Level spawn location: World: (-24,71,58), Section: (at 8,7,10 in -2,4,3; chunk contains blocks -32,0,48 to -17,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 24225631 game time, 26000 day time
	Server brand: CheatBungee <- Spigot
	Server type: Non-integrated multiplayer server
	Tracked entity count: 36

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, betterf3, cloth-config, collisionfix, dynamic_fps, dynamiclights, entity_model_features, entity_texture_features, entityculling, essential, essential-container, essential-loader, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, feather, freecam, freelook, iris, lithium, modmenu, notenoughanimations, placeholder-api, skinlayers3d, sodium, sound_physics_remastered, voicechat, wildfire_gender, yet_another_config_lib_v3, black_icons, file/no-fishing-bobber.zip, file/Not game changing textures + pink.zip, Essential Assets, essential

-- System Details --
Details:
	Minecraft Version: 1.21.4
	Minecraft Version ID: 1.21.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 1721118296 bytes (1641 MiB) / 3489660928 bytes (3328 MiB) up to 7214202880 bytes (6880 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics 630
	Graphics card #0 vendor: Intel Corporation
	Graphics card #0 VRAM (MiB): 1024.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 27.20.100.8729
	Graphics card #1 name: NVIDIA GeForce GTX 1050
	Graphics card #1 vendor: NVIDIA
	Graphics card #1 VRAM (MiB): 3072.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 32.0.15.6636
	Memory slot #0 capacity (MiB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 19327.11
	Virtual memory used (MiB): 12776.70
	Swap memory total (MiB): 11264.00
	Swap memory used (MiB): 3015.80
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 315241.97, total: 975109.44
	Space in storage for workdir (MiB): available: 315241.97, total: 975109.44
	JVM Flags: 14 total; -Xmx6853M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:ErrorFile=feather/java_error.log -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		betterf3: BetterF3 13.0.0
		cloth-config: Cloth Config v17 17.0.144
			cloth-basic-math: cloth-basic-math 0.6.1
		collisionfix: CollisionFix 1.0.1
		dynamic_fps: Dynamic FPS 3.7.7
			net_lostluma_battery: battery 1.3.0
		dynamiclights: Dynamic Lights 1.8.5+mod
		elementa: Elementa 670
		entity_model_features: Entity Model Features 2.4.1
		entity_texture_features: Entity Texture Features 6.2.9
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.7.2
		essential: Essential 1.3.5.5
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.3
		fabric-api: Fabric API 0.110.5+1.21.4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.83+7feeb73382
			fabric-biome-api-v1: Fabric Biome API (v1) 15.0.3+f12498d082
			fabric-block-api-v1: Fabric Block API (v1) 1.0.30+7feeb73382
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 2.0.6+7feeb73382
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.26+7feeb73382
			fabric-command-api-v1: Fabric Command API (v1) 1.2.60+f71b366f82
			fabric-command-api-v2: Fabric Command API (v2) 2.2.39+e496eb1582
			fabric-commands-v0: Fabric Commands (v0) 0.2.77+df3654b382
			fabric-content-registries-v0: Fabric Content Registries (v0) 9.1.11+7feeb73382
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.5+7f945d5b82
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.5+15afce7982
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.3.5+7feeb73382
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.4.2+9aea556b82
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 22.1.1+5bea021682
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.9+7feeb73382
			fabric-entity-events-v1: Fabric Entity Events (v1) 2.0.10+60fccc7682
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 4.0.0+a4eebcf082
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.61+7feeb73382
			fabric-item-api-v1: Fabric Item API (v1) 11.1.11+203e6b2382
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.20+7feeb73382
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.55+7feeb73382
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.53+df3654b382
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.2+bf2a60eb82
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.30+3f89f5a582
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.18+203e6b2382
			fabric-message-api-v1: Fabric Message API (v1) 6.0.23+7feeb73382
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 4.0.1+84404cdd82
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.7+cc0fa2fe82
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 18.0.4+6383078582
			fabric-particles-v1: Fabric Particles (v1) 4.0.12+7feeb73382
			fabric-recipe-api-v1: Fabric Recipe API (v1) 8.0.2+203e6b2382
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 6.0.0+cc0fa2fe82
			fabric-renderer-indigo: Fabric Renderer - Indigo 2.0.0+84404cdd82
			fabric-rendering-v1: Fabric Rendering (v1) 10.0.0+6a293bdb82
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 5.0.12+203e6b2382
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.36+7feeb73382
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.105+7feeb73382
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.31+7feeb73382
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.5+1885ad7482
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.3.1+56e78b9b82
		fabric-language-kotlin: Fabric Language Kotlin 1.10.19+kotlin.1.9.23
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		feather: Feather Client release/e71b24c3
		freecam: Freecam 1.3.2+mc1.21.4
		freelook: Freelook 1.2.5
		iris: Iris 1.8.5+mc1.21.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		lithium: Lithium 0.14.3+mc1.21.4
		minecraft: Minecraft 1.21.4
		modmenu: Mod Menu 13.0.0-beta.1
		mr_tnt_timer: TNT Timer 3.0
		notenoughanimations: NotEnoughAnimations 1.9.0
		org_jetbrains_annotations: annotations 23.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.23
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.23
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.23
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.23
		org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.2
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.0
		org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		placeholder-api: Placeholder API 2.5.1+1.21.3
		skinlayers3d: 3d-Skin-Layers 1.7.4
		sodium: Sodium 0.6.6+mc1.21.4
			fabric-api-base: Fabric API Base 0.4.54+b47eab6b04
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.19+7feeb73304
			fabric-renderer-api-v1: Fabric Renderer API (v1) 5.0.2+84404cdd04
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.57+73761d2e04
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.19+7feeb73304
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 3.0.11+b1caf1e904
		sound_physics_remastered: Sound Physics Remastered 1.21.4-1.4.8
		universalcraft: UniversalCraft 365
		vigilance: Vigilance 306
		voicechat: Simple Voice Chat 1.21.4-2.5.27
		wildfire_gender: Wildfire's Female Gender Mod 4.3.3+1.21.4
		yet_another_config_lib_v3: YetAnotherConfigLib 3.6.2+1.21.4-fabric
			com_twelvemonkeys_common_common-image: common-image 3.12.0
			com_twelvemonkeys_common_common-io: common-io 3.12.0
			com_twelvemonkeys_common_common-lang: common-lang 3.12.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.12.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.12.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.12.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Loaded Shaderpack: (off)
	Launched Version: 1.21.4-feather
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce GTX 1050/PCIe/SSE2 GL version 3.2.0 NVIDIA 566.36, NVIDIA Corporation
	Window size: 1680x1050
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'Feather Fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 20/20 chunks
	Resource Packs: vanilla, fabric, betterf3, cloth-config, collisionfix, dynamic_fps, dynamiclights, entity_model_features, entity_texture_features, entityculling, essential (incompatible), essential-container, essential-loader, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, feather (incompatible), freecam, freelook, iris, lithium, modmenu, notenoughanimations, placeholder-api, skinlayers3d, sodium, sound_physics_remastered, voicechat, wildfire_gender, yet_another_config_lib_v3 (incompatible), black_icons, file/no-fishing-bobber.zip (incompatible), file/Not game changing textures + pink.zip
	Current Language: en_us
	Locale: hu_HU
	System encoding: Cp1250
	File encoding: UTF-8
	CPU: 8x Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz

**Comment by Timolino456** [comment]
This is very likely a Feather Client issue, as I can't see any other mods that are incompatible (as far as I know) or being mentioned for another reason in the crash log, but this:

> at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16)

which seems to be part of Feather.

Feather Client is not supported and has caused problems in the past. If this persists with only Sodium enabled, you should probably contact the Feather devs about this.

**Comment by douira** [comment]
I'm closing this as looks to be an issue with feather client. If you need support, please come to our discord server and make a support request.
