### ISSUE TITLE
Crash just after loading mojang screen

### ISSUE THREAD

**Issue by St0RM53** [jellysquid3/Sodium#504]
### Reproduction Steps

1) Launch Minecraft 1.16.4 with fabric-loader-0.11.1-1.16.4 and sodium-fabric-mc1.16.4-0.1.1

2) Upon finishing loading the mojang screen just as a few frames of the menu are rendered game crashes before even showing the menu buttons even

### Crash Report File

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 1/29/21 11:19 PM
Description: Rendering screen

java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at net.minecraft.class_287.method_1341(class_287.java:1536)
	at net.minecraft.class_1921.method_23012(class_1921.java:596)
	at net.minecraft.class_4597$class_4598.method_22994(class_4597.java:86)
	at net.minecraft.class_4597$class_4598.method_24213(class_4597.java:65)
	at net.minecraft.class_4597$class_4598$$Lambda$3087/386002713.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.minecraft.class_4597$class_4598.method_22993(class_4597.java:62)
	at net.minecraft.class_327.method_27520(class_327.java:109)
	at net.minecraft.class_327.method_1720(class_327.java:58)
	at net.minecraft.class_332.method_25300(class_332.java:114)
	at net.minecraft.class_442.method_25394(class_442.java:260)
	at net.minecraft.class_757.method_3192(class_757.java:616)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_287.method_1341(class_287.java:1536)
	at net.minecraft.class_1921.method_23012(class_1921.java:596)
	at net.minecraft.class_4597$class_4598.method_22994(class_4597.java:86)
	at net.minecraft.class_4597$class_4598.method_24213(class_4597.java:65)
	at net.minecraft.class_4597$class_4598$$Lambda$3087/386002713.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.minecraft.class_4597$class_4598.method_22993(class_4597.java:62)
	at net.minecraft.class_327.method_27520(class_327.java:109)
	at net.minecraft.class_327.method_1720(class_327.java:58)
	at net.minecraft.class_332.method_25300(class_332.java:114)
	at net.minecraft.class_442.method_25394(class_442.java:260)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_442
	Mouse location: Scaled: (356, 226). Absolute: (1427.000000, 907.000000)
	Screen size: Scaled: (640, 360). Absolute: (2560, 1440). Scale factor of 4.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:616)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1361001736 bytes (1297 MB) / 1879048192 bytes (1792 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 32
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.11.1-1.16.4
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon RX 5700 XT GL version 4.6.14758 Compatibility Profile Context 21.1.1 27.20.14527.2002, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 32x AMD Ryzen 9 3950X 16-Core Processor 

### Additional Information

Just compiled sodium this morning; i'm unfamiliar with minecraft, maybe i'm using wrong loader version!?
edit: updating java now, maybe that's the issue? edit2: no still crash

**Comment by Kroppeb** [comment]
If you compile with Java 9+, you must use a Java 9+ runtime.
see #16

**Comment by St0RM53** [comment]
> 
> 
> If you compile with Java 9+, you must use a Java 9+ runtime.
> see #16

ok thanks i'll try this now..weird java only updates to 8 and not 9

**Comment by St0RM53** [comment]
ok re-compiled with OpenJDK 8 and it works
