### ISSUE TITLE
Cannot build from source.

### ISSUE THREAD

**Issue by K0-RR** [jellysquid3/Sodium#580]
Downloaded the source (the latest commit is 2fb1d28aa61680170e44a138c296f3b5534314e0) and tried to build it.

> ./gradlew build
Exception in thread "main" java.lang.RuntimeException: Could not load wrapper properties from '/home/k0rr/Downloads/SODIUM/sodium-fabric-1.16.x-next/gradle/wrapper/gradle-wrapper.properties'.
        at org.gradle.wrapper.WrapperExecutor.<init>(WrapperExecutor.java:61)
        at org.gradle.wrapper.WrapperExecutor.forWrapperPropertiesFile(WrapperExecutor.java:45)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:62)
Caused by: java.io.FileNotFoundException: /home/k0rr/Downloads/SODIUM/sodium-fabric-1.16.x-next/gradle/wrapper/gradle-wrapper.properties (Is a directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at org.gradle.wrapper.WrapperExecutor.loadProperties(WrapperExecutor.java:84)
        at org.gradle.wrapper.WrapperExecutor.<init>(WrapperExecutor.java:53)
        ... 2 more

**Comment by K0-RR** [comment]
Don't know why but
![image](https://user-images.githubusercontent.com/43277609/111065824-fdfe8a00-84bb-11eb-9595-41fdca68158f.png)

Tried deleting and unzipping it again and nothing

**Comment by altrisi** [comment]
Seems like Java is complaining about `gradle-wrapper.properties` being a directory.

Try cloning/downloading it again or, if you just want a build from the latest commit, you can instead use the build provided by Github Actions for that commit (which isn't failing, suggesting it to be an issue with your setup).

For support it would be better to join the discord instead of the issue tracker though.

**Comment by LucilleTea** [comment]
This seems like a problem with your environment rather than the mod itself. You can get [a build of the latest commit from Github Actions](https://github.com/CaffeineMC/sodium-fabric/actions/runs/645274334) - which did build successfully.

**Comment by K0-RR** [comment]
Seems like it's something wrong with PeaZip.
