### ISSUE TITLE
Crash loop

### ISSUE THREAD

**Issue by Boobies** [jellysquid3/Sodium#619]
I got this while flying around in spectator mode on the End island. Now I'm on a crash loop and will have to disable Sodium to get out of it.

```
[09:54:41] [main/FATAL]: Unreported exception thrown!
java.lang.ArrayIndexOutOfBoundsException: -1
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkRenderColumn.getRender(ChunkRenderColumn.java:33) ~[sodium-fabric-mc1.16.4-0.1.1-SNAPSHOT.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkRenderManager.getRender(ChunkRenderManager.java:236) ~[sodium-fabric-mc1.16.4-0.1.1-SNAPSHOT.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkRenderManager.isChunkVisible(ChunkRenderManager.java:385) ~[sodium-fabric-mc1.16.4-0.1.1-SNAPSHOT.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.isEntityVisible(SodiumWorldRenderer.java:388) ~[sodium-fabric-mc1.16.4-0.1.1-SNAPSHOT.jar:?]
	at net.minecraft.class_897.handler$zzk000$preShouldRender(class_897.java:537) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_897.method_3933(class_897.java:58) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_898.method_3950(class_898.java:247) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1188) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:727) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:546) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1048) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.5-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by DragonEggBedrockBreaking** [comment]
Make sure you are on the latest commit of sodium.

**Comment by LucilleTea** [comment]
You are using an outdated snapshot build of sodium, please confirm it happens on the latest. There are instructions on how to get it in the readme if you need.

**Comment by Boobies** [comment]
It does not. I just did a build and it looks to me like this is the same as #611.
