### ISSUE TITLE
Game crash : internal server error

### ISSUE THREAD

**Issue by HazeG** [jellysquid3/Sodium#704]
Having some issues that seem to be caused by sodium when rendering the nether.

[16:33:54] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /77.54.159.154:59801
net.minecraft.crash.ReportedException: Ticking player
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:467) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:endergetic.mixins.json:ServerPlayerEntityMixin,pl:mixin:A}
        at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_server_entity_interact,xf:fml:astralsorcery:allow_entity_interaction,pl:mixin:A}
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291] {}
Caused by: java.lang.ClassCastException: net.minecraft.village.PointOfInterestManager cannot be cast to me.jellysquid.mods.lithium.common.world.interests.PointOfInterestDataExtended
        at net.minecraft.world.Teleporter.func_242957_a(Teleporter.java:539) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium.mixins.json:ai.poi.fast_portals.PortalForcerMixin,pl:mixin:A}
        at net.minecraft.entity.Entity.func_241830_a(Entity.java:2214) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:add_custom_entity_collision,pl:mixin:APP:spiderstpo.mixins.json:EntityMixin,pl:mixin:APP:abnormals_core.mixins.json:EntityMixin,pl:mixin:APP:extraboats.mixins.json:EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.collisions.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.fast_suffocation_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.stream_entity_collisions_lazily.EntityMixin,pl:mixin:APP:endergetic.mixins.json:EntityMixin,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.ServerPlayerEntity.func_241830_a(ServerPlayerEntity.java:702) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:endergetic.mixins.json:ServerPlayerEntityMixin,pl:mixin:A}
        at net.minecraft.entity.Entity.func_241829_a(Entity.java:2179) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:add_custom_entity_collision,pl:mixin:APP:spiderstpo.mixins.json:EntityMixin,pl:mixin:APP:abnormals_core.mixins.json:EntityMixin,pl:mixin:APP:extraboats.mixins.json:EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.collisions.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.fast_suffocation_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.stream_entity_collisions_lazily.EntityMixin,pl:mixin:APP:endergetic.mixins.json:EntityMixin,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.ServerPlayerEntity.func_241829_a(ServerPlayerEntity.java:612) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:endergetic.mixins.json:ServerPlayerEntityMixin,pl:mixin:A}
        at net.minecraftforge.common.util.ITeleporter.getPortalInfo(ITeleporter.java:84) ~[forge:?] {re:classloading,re:mixin}
        at net.minecraft.entity.player.ServerPlayerEntity.changeDimension(ServerPlayerEntity.java:645) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:endergetic.mixins.json:ServerPlayerEntityMixin,pl:mixin:A}
        at net.minecraft.entity.Entity.func_241206_a_(Entity.java:2120) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:add_custom_entity_collision,pl:mixin:APP:spiderstpo.mixins.json:EntityMixin,pl:mixin:APP:abnormals_core.mixins.json:EntityMixin,pl:mixin:APP:extraboats.mixins.json:EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.collisions.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.fast_suffocation_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.stream_entity_collisions_lazily.EntityMixin,pl:mixin:APP:endergetic.mixins.json:EntityMixin,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.Entity.func_213284_aV(Entity.java:1779) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:add_custom_entity_collision,pl:mixin:APP:spiderstpo.mixins.json:EntityMixin,pl:mixin:APP:abnormals_core.mixins.json:EntityMixin,pl:mixin:APP:extraboats.mixins.json:EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.collisions.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.fast_suffocation_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.stream_entity_collisions_lazily.EntityMixin,pl:mixin:APP:endergetic.mixins.json:EntityMixin,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.Entity.func_70030_z(Entity.java:403) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:add_custom_entity_collision,pl:mixin:APP:spiderstpo.mixins.json:EntityMixin,pl:mixin:APP:abnormals_core.mixins.json:EntityMixin,pl:mixin:APP:extraboats.mixins.json:EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.collisions.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.fast_suffocation_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.stream_entity_collisions_lazily.EntityMixin,pl:mixin:APP:endergetic.mixins.json:EntityMixin,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.LivingEntity.func_70030_z(LivingEntity.java:295) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:set_player_field,xf:fml:placebo:placeboshieldblock,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,xf:fml:astralsorcery:water_movement_slowdown_prevention,pl:mixin:APP:sodium.mixins.json:entity.block_cache.LivingEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:LivingEntityMixin,pl:mixin:APP:sodium.mixins.json:alloc.enum_values.LivingEntityMixin,pl:mixin:APP:supplementaries.mixins.json:LivingEntityMixin,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:charm.mixins.json:LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.Entity.func_70071_h_(Entity.java:387) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:add_custom_entity_collision,pl:mixin:APP:spiderstpo.mixins.json:EntityMixin,pl:mixin:APP:abnormals_core.mixins.json:EntityMixin,pl:mixin:APP:extraboats.mixins.json:EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.collisions.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.fast_suffocation_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.stream_entity_collisions_lazily.EntityMixin,pl:mixin:APP:endergetic.mixins.json:EntityMixin,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2113) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:set_player_field,xf:fml:placebo:placeboshieldblock,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,xf:fml:astralsorcery:water_movement_slowdown_prevention,pl:mixin:APP:sodium.mixins.json:entity.block_cache.LivingEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:LivingEntityMixin,pl:mixin:APP:sodium.mixins.json:alloc.enum_values.LivingEntityMixin,pl:mixin:APP:supplementaries.mixins.json:LivingEntityMixin,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:charm.mixins.json:LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:endergetic.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:accessor.PlayerEntityAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:endergetic.mixins.json:ServerPlayerEntityMixin,pl:mixin:A}
        ... 9 more
        
        
       Not sure if its anything i can fix or the creator would need to fix, nether works just fine without the mod but fps drops 50%

**Comment by amnotbananaama** [comment]
You appear to be using an unofficial version of Sodium, on a Forge client. This is not made by us and we have no input or insight whatsoever. Our mod only supports the Fabric modloader. You'll need to seek support from wherever you found it
