### ISSUE TITLE
sodium-fabric-mc1.17-0.3.0+unknown-dev.jar crashes on launch.

### ISSUE THREAD

**Issue by moo-sek-freak** [jellysquid3/Sodium#743]
### Version

mc1.17-0.3.0+unknown-dev 

### Reproduction Steps

1. Launch game using unknown-dev.jar. (Game launches normally using unknown.jar)

### Crash Report File

Starting the game with only the Sodium mod loaded gives this:
```
[18:40:51] [main/INFO]: Loading for game Minecraft 1.17.1
[18:40:51] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Errors were found!
 - Mod 'Sodium' (sodium) requires version 0.1 or later of mod fabric-rendering-data-attachment-v1, which is missing!
	 - You must install version 0.1 or later of fabric-rendering-data-attachment-v1.
 - Mod 'Sodium' (sodium) requires version 0.1 or later of mod fabric-rendering-fluids-v1, which is missing!
	 - You must install version 0.1 or later of fabric-rendering-fluids-v1.
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:342) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```
And with Fabric API: (This is the whole log file, launcher gives exit code -1.)
```
[18:43:01] [main/INFO]: Loading for game Minecraft 1.17.1
[18:43:01] [main/INFO]: [FabricLoader] Loading 48 mods:
	- fabric@0.36.1+1.17
	- fabric-api-base@0.3.0+a02b446313
	- fabric-api-lookup-api-v1@1.2.0+2b5c62d013
	- fabric-biome-api-v1@3.1.11+c345aea813
	- fabric-blockrenderlayer-v1@1.1.5+a02b446313
	- fabric-command-api-v1@1.1.2+6cefd57713
	- fabric-commands-v0@0.2.2+92519afa13
	- fabric-containers-v0@0.1.12+a02b446313
	- fabric-content-registries-v0@0.2.2+a02b446313
	- fabric-crash-report-info-v1@0.1.5+be9da31013
	- fabric-dimensions-v1@2.0.11+6cefd57713
	- fabric-entity-events-v1@1.1.0+a02b446313
	- fabric-events-interaction-v0@0.4.9+a722d8c013
	- fabric-events-lifecycle-v0@0.2.1+92519afa13
	- fabric-game-rule-api-v1@1.0.7+6cefd57713
	- fabric-item-api-v1@1.2.4+a02b446313
	- fabric-item-groups-v0@0.2.10+b7ab612113
	- fabric-key-binding-api-v1@1.0.4+a02b446313
	- fabric-keybindings-v0@0.2.2+36b77c3e13
	- fabric-lifecycle-events-v1@1.4.4+a02b446313
	- fabric-loot-tables-v1@1.0.4+a02b446313
	- fabric-mining-levels-v0@0.1.3+92519afa13
	- fabric-models-v0@0.3.0+a02b446313
	- fabric-networking-api-v1@1.0.12+6cefd57713
	- fabric-networking-blockentity-v0@0.2.11+a02b446313
	- fabric-networking-v0@0.3.2+92519afa13
	- fabric-object-builder-api-v1@1.10.9+b7ab612113
	- fabric-object-builders-v0@0.7.3+a02b446313
	- fabric-particles-v1@0.2.4+a02b446313
	- fabric-registry-sync-v0@0.7.10+e2961fee13
	- fabric-renderer-api-v1@0.4.4+5f02c96913
	- fabric-renderer-indigo@0.4.8+a02b446313
	- fabric-renderer-registries-v1@3.2.0+a02b446313
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446313
	- fabric-rendering-fluids-v1@0.1.13+a02b446313
	- fabric-rendering-v0@1.1.2+92519afa13
	- fabric-rendering-v1@1.6.0+a02b446313
	- fabric-resource-loader-v0@0.4.7+b7ab612113
	- fabric-screen-api-v1@1.0.4+155f865c13
	- fabric-screen-handler-api-v1@1.1.8+a02b446313
	- fabric-structure-api-v1@1.1.12+6cefd57713
	- fabric-tag-extensions-v0@1.1.4+a02b446313
	- fabric-textures-v0@1.0.6+a02b446313
	- fabric-tool-attribute-api-v1@1.2.12+b7ab612113
	- fabricloader@0.11.6
	- java@16
	- minecraft@1.17.1
	- sodium@0.3.0+unknown
```

**Comment by LucilleTea** [comment]
the -dev suffix indicates that it is for use in a development environment, it will never work in a regular minecraft launcher.

**Comment by moo-sek-freak** [comment]
how _do_ you use the dev version then?

**Comment by silversquirl** [comment]
Normally you don't. Use the non-suffixed jar instead
