### ISSUE TITLE
Exit Code 0

### ISSUE THREAD

**Issue by BallerTroy07** [jellysquid3/Sodium#783]
### Version information

mc.1.17.1

### Reproduction Steps

1. Run Mc Java
2. Game crash

### Crash Report file

A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: iris requires {minecraft @ [1.17 || 1.17-rc.2]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:198)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832)
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:195)
	... 5 more

### Additional information

It launched before the Iris shaders, now it's not

**Comment by Leo40Git** [comment]
This is a problem with Iris, not Sodium. Report this to Iris.

**Comment by BallerTroy07** [comment]
> This is a problem with Iris, not Sodium. Report this to Iris.

thanks so much for letting me know!!
