### ISSUE TITLE
Crash after opening World to LAN

### ISSUE THREAD

**Issue by JmbFountain** [jellysquid3/Sodium#786]
### Version information

mc1.17-0.3.0+IRIS1-rev.7491e3a.jar

### Reproduction Steps

create/join a Singleplayer world
open to LAN
have a second player join
wait a few seconds, the game will begin to lag and eventually crash

### Crash Report file

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 19/07/2021, 20:52
Description: Rendering entity in world

java.lang.OutOfMemoryError: Cannot reserve 2098688 bytes of direct buffer memory (allocated: 2147256619, limit: 2147483648)
	at java.base/java.nio.Bits.reserveMemory(Bits.java:178)
	at java.base/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:121)
	at java.base/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:330)
	at net.minecraft.class_311.method_1596(class_311.java:17)
	at net.minecraft.class_287.ensureBufferCapacity(class_287.java:559)
	at me.jellysquid.mods.sodium.client.model.vertex.buffer.VertexBufferWriter.ensureCapacity(VertexBufferWriter.java:30)
	at net.minecraft.class_630.method_22702(class_630.java:541)
	at net.minecraft.class_630.method_22699(class_630.java:92)
	at net.minecraft.class_630.method_22699(class_630.java:95)
	at net.minecraft.class_630.method_22699(class_630.java:95)
	at net.minecraft.class_5597.method_2828(class_5597.java:23)
	at net.minecraft.class_922.method_4054(class_922.java:134)
	at net.minecraft.class_927.method_4072(class_927.java:45)
	at net.minecraft.class_927.method_3936(class_927.java:18)
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_761.method_22977(class_761.java:1483)
	at net.minecraft.class_761.method_22710(class_761.java:1231)
	at net.minecraft.class_757.method_3188(class_757.java:1001)
	at net.minecraft.class_757.method_3192(class_757.java:806)
	at net.minecraft.class_310.method_1523(class_310.java:1114)
	at net.minecraft.class_310.method_1514(class_310.java:730)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.nio.Bits.reserveMemory(Bits.java:178)
	at java.base/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:121)
	at java.base/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:330)
	at net.minecraft.class_311.method_1596(class_311.java:17)
	at net.minecraft.class_287.ensureBufferCapacity(class_287.java:559)
	at me.jellysquid.mods.sodium.client.model.vertex.buffer.VertexBufferWriter.ensureCapacity(VertexBufferWriter.java:30)
	at net.minecraft.class_630.method_22702(class_630.java:541)
	at net.minecraft.class_630.method_22699(class_630.java:92)
	at net.minecraft.class_630.method_22699(class_630.java:95)
	at net.minecraft.class_630.method_22699(class_630.java:95)
	at net.minecraft.class_5597.method_2828(class_5597.java:23)
	at net.minecraft.class_922.method_4054(class_922.java:134)
	at net.minecraft.class_927.method_4072(class_927.java:45)
	at net.minecraft.class_927.method_3936(class_927.java:18)

-- Entity being rendered --
Details:
	Entity Type: minecraft:bat (net.minecraft.class_1420)
	Entity ID: 18671
	Entity Name: Bat
	Entity's Exact location: 28.97, 23.69, -151.50
	Entity's Block location: World: (28,23,-152), Section: (at 12,7,8 in 1,1,-10; chunk contains blocks 16,0,-160 to 31,255,-145), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.06, 0.00, -0.09
	Entity's Passengers: []
	Entity's Vehicle: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_879@1805f0c5
	Location: 14.58,-41.95,51.46 - World: (14,-42,51), Section: (at 14,6,3 in 0,-3,3; chunk contains blocks 0,0,48 to 15,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: -42.862553
	Delta: 0.7200561
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_761.method_22977(class_761.java:1483)
	at net.minecraft.class_761.method_22710(class_761.java:1231)
	at net.minecraft.class_757.method_3188(class_757.java:1001)

-- Affected level --
Details:
	All players: 2 total; [class_746['Kashjar'/17393, l='ClientLevel', x=14.34, y=64.00, z=-203.01], class_745['ragnar_the_red11'/18595, l='ClientLevel', x=10.32, y=65.00, z=-200.39]]
	Chunk stats: 16384, 4825
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,64,-192), Section: (at 0,0,0 in 1,4,-12; chunk contains blocks 16,0,-192 to 31,255,-177), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 57390 game time, 46184 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:749)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 871436248 bytes (831 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3,19
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x1f02
	Graphics card #0 versionInfo: DriverVersion=27.21.14.6589
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 2,67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 2,67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 28142,24
	Virtual memory used (MB): 24808,35
	Swap memory total (MB): 11838,91
	Swap memory used (MB): 196,59
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: iris-fabric-loader-0.11.5-1.17
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2070/PCIe/SSE2 GL version 3.2.0 NVIDIA 465.89, NVIDIA Corporation
	Window size: 2560x1377
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
	Player Count: 2 / 8; [class_3222['Kashjar'/17393, l='ServerLevel[SchwippSchwapp]', x=14.34, y=64.00, z=-203.01], class_3222['ragnar_the_red11'/18595, l='ServerLevel[SchwippSchwapp]', x=10.32, y=65.00, z=-200.38]]
	Data Packs: vanilla

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 19/07/2021, 20:57
Description: Rendering entity in world

java.lang.OutOfMemoryError: Cannot reserve 2098688 bytes of direct buffer memory (allocated: 2147483068, limit: 2147483648)
	at java.base/java.nio.Bits.reserveMemory(Bits.java:178)
	at java.base/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:121)
	at java.base/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:330)
	at net.minecraft.class_311.method_1596(class_311.java:17)
	at net.minecraft.class_287.ensureBufferCapacity(class_287.java:559)
	at me.jellysquid.mods.sodium.client.model.vertex.buffer.VertexBufferWriter.ensureCapacity(VertexBufferWriter.java:30)
	at net.minecraft.class_630.method_22702(class_630.java:541)
	at net.minecraft.class_630.method_22699(class_630.java:92)
	at net.minecraft.class_4592.method_22947(class_4592.java:63)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)
	at net.minecraft.class_4592.method_2828(class_4592.java:63)
	at net.minecraft.class_922.method_4054(class_922.java:134)
	at net.minecraft.class_927.method_4072(class_927.java:45)
	at net.minecraft.class_927.method_3936(class_927.java:18)
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_761.method_22977(class_761.java:1483)
	at net.minecraft.class_761.method_22710(class_761.java:1231)
	at net.minecraft.class_757.method_3188(class_757.java:1001)
	at net.minecraft.class_757.method_3192(class_757.java:806)
	at net.minecraft.class_310.method_1523(class_310.java:1114)
	at net.minecraft.class_310.method_1514(class_310.java:730)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.nio.Bits.reserveMemory(Bits.java:178)
	at java.base/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:121)
	at java.base/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:330)
	at net.minecraft.class_311.method_1596(class_311.java:17)
	at net.minecraft.class_287.ensureBufferCapacity(class_287.java:559)
	at me.jellysquid.mods.sodium.client.model.vertex.buffer.VertexBufferWriter.ensureCapacity(VertexBufferWriter.java:30)
	at net.minecraft.class_630.method_22702(class_630.java:541)
	at net.minecraft.class_630.method_22699(class_630.java:92)
	at net.minecraft.class_4592.method_22947(class_4592.java:63)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)
	at net.minecraft.class_4592.method_2828(class_4592.java:63)
	at net.minecraft.class_922.method_4054(class_922.java:134)
	at net.minecraft.class_927.method_4072(class_927.java:45)
	at net.minecraft.class_927.method_3936(class_927.java:18)

-- Entity being rendered --
Details:
	Entity Type: minecraft:sheep (net.minecraft.class_1472)
	Entity ID: 32
	Entity Name: Sheep
	Entity's Exact location: -19.19, 78.00, -252.82
	Entity's Block location: World: (-20,78,-253), Section: (at 12,14,3 in -2,4,-16; chunk contains blocks -32,0,-256 to -17,255,-241), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_941@1518c435
	Location: -29.54,12.38,-52.48 - World: (-30,12,-53), Section: (at 2,12,11 in -2,0,-4; chunk contains blocks -32,0,-64 to -17,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Rotation: 43.59375
	Delta: 0.34005356
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_761.method_22977(class_761.java:1483)
	at net.minecraft.class_761.method_22710(class_761.java:1231)
	at net.minecraft.class_757.method_3188(class_757.java:1001)

-- Affected level --
Details:
	All players: 2 total; [class_746['Kashjar'/101, l='ClientLevel', x=10.35, y=64.00, z=-200.34], class_745['ragnar_the_red11'/740, l='ClientLevel', x=12.48, y=64.00, z=-201.28]]
	Chunk stats: 16384, 4032
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,64,-192), Section: (at 0,0,0 in 1,4,-12; chunk contains blocks 16,0,-192 to 31,255,-177), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 61745 game time, 50539 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:749)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1231739360 bytes (1174 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3,19
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x1f02
	Graphics card #0 versionInfo: DriverVersion=27.21.14.6589
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 2,67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 2,67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 26066,28
	Virtual memory used (MB): 23241,96
	Swap memory total (MB): 9762,95
	Swap memory used (MB): 186,59
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: iris-fabric-loader-0.11.5-1.17
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2070/PCIe/SSE2 GL version 3.2.0 NVIDIA 465.89, NVIDIA Corporation
	Window size: 2560x1377
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
	Player Count: 2 / 8; [class_3222['Kashjar'/101, l='ServerLevel[SchwippSchwapp]', x=10.35, y=64.00, z=-200.34], class_3222['ragnar_the_red11'/740, l='ServerLevel[SchwippSchwapp]', x=12.68, y=64.00, z=-201.76]]
	Data Packs: vanilla

### Additional information

I also had IRIS shaders installed, however they weren't used at that time. 

if needed, I can try to recreate the crash on Linux.

**Comment by LucilleTea** [comment]
Iris use their own version of Sodium, please try to reproduce the issue with vanilla Sodium. If this isn't possible the issue report should be sent to Iris.

**Comment by JmbFountain** [comment]
I tried again without IRIS, it only produced massive lagspikes. I'd guess it's a problem with the IRIS port to 1.17
