### ISSUE TITLE
Visual texture corruption

### ISSUE THREAD

**Issue by miike3459** [jellysquid3/Sodium#802]
- Sodium version: `0.3.0+build.5`
- Fabric version: `0.11.6` (MultiMC)

Occasionally, with Sodium installed, I receive a visual glitch that causes the apparent unloading of most Minecraft textures, showing pink and black instead:

![2021-07-27_14 10 03](https://user-images.githubusercontent.com/54710811/127206949-8215801c-2b2e-440a-bfcf-d11dee3e167c.png)

The expected behavior is that this does not happen. I cannot narrow down the exact cause, but I did receive an error in logs:

```
[14:08:27] [Render thread/WARN]: Failed to load texture: minecraft:textures/atlas/blocks.png
java.io.FileNotFoundException: minecraft:textures/atlas/blocks.png
	at net.minecraft.class_3294.method_14486(class_3294.java:67) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_3304.method_14486(class_3304.java:62) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1049$class_4006.method_18156(class_1049.java:81) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1049.method_18153(class_1049.java:57) ~[intermediary-minecraft-1.17.1-client.jar:?]
        ... (similar lines)
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-minecraft-1.17.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by jellysquid3** [comment]
Please upload a complete client log file. The snippet does not contain enough information to diagnose the problem.

**Comment by miike3459** [comment]
Is there a way I can get you this log privately? Since it is an all-day log, there is some private information inside that I should not share publicly.

**Comment by amnotbananaama** [comment]
The easiest way to share this privately would most likely be through Direct Messages on [Discord](https://caffeinemc.net/discord). You can message Jelly, or any of the other staff and we will make sure it's kept private

**Comment by jellysquid3** [comment]
I do not believe this issue is caused by Sodium or that we can do anything about it. It appears that resource pack reloading is failing, something we don't touch in any capacity.
