### ISSUE TITLE
Crash 1.17.1

### ISSUE THREAD

**Issue by nonmems** [jellysquid3/Sodium#919]
### Version information

sodium-fabric-mc1.17.1-0.3.2+build.7

### Reproduction Steps

When you go to the graphics settings menu, it crashes.

### Crash Report file

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 25.09.2021, 14:01
Description: mouseClicked event handler

java.lang.IllegalArgumentException: The maximum value must be greater than the minimum value
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:158)
	at me.jellysquid.mods.sodium.client.gui.options.control.SliderControl.<init>(SliderControl.java:18)
	at me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages.mddb323a$lambda$general$0$3(SodiumGameOptionPages.java:537)
	at me.jellysquid.mods.sodium.client.gui.options.OptionImpl.<init>(OptionImpl.java:48)
	at me.jellysquid.mods.sodium.client.gui.options.OptionImpl$Builder.build(OptionImpl.java:200)
	at me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages.handler$zjm000$general(SodiumGameOptionPages.java:556)
	at me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages.general(SodiumGameOptionPages.java:30)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.SodiumVideoOptionsScreen.<init>(SodiumVideoOptionsScreen.java:50)
	at net.minecraft.class_429.handler$zlo001$open(class_429.java:524)
	at net.minecraft.class_429.method_19828(class_429.java)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:121)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:490)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:172)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1137)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:158)
	at me.jellysquid.mods.sodium.client.gui.options.control.SliderControl.<init>(SliderControl.java:18)
	at me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages.mddb323a$lambda$general$0$3(SodiumGameOptionPages.java:537)
	at me.jellysquid.mods.sodium.client.gui.options.OptionImpl.<init>(OptionImpl.java:48)
	at me.jellysquid.mods.sodium.client.gui.options.OptionImpl$Builder.build(OptionImpl.java:200)
	at me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages.handler$zjm000$general(SodiumGameOptionPages.java:556)
	at me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages.general(SodiumGameOptionPages.java:30)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.SodiumVideoOptionsScreen.<init>(SodiumVideoOptionsScreen.java:50)
	at net.minecraft.class_429.handler$zlo001$open(class_429.java:524)
	at net.minecraft.class_429.method_19828(class_429.java)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:121)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_429
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:490)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:172)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:747)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 684332416 bytes (652 MiB) / 1979711488 bytes (1888 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 58 Stepping 9
	Microarchitecture: Ivy Bridge (Client)
	Frequency (GHz): 2,59
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GT 720M
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048,00
	Graphics card #0 deviceId: 0x1140
	Graphics card #0 versionInfo: DriverVersion=23.21.13.8873
	Graphics card #1 name: Intel(R) HD Graphics 4000
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 2112,00
	Graphics card #1 deviceId: 0x0166
	Graphics card #1 versionInfo: DriverVersion=10.18.10.4358
	Memory slot #0 capacity (MB): 4096,00
	Memory slot #0 clockSpeed (GHz): 1,60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096,00
	Memory slot #1 clockSpeed (GHz): 1,60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 15908,10
	Virtual memory used (MB): 11969,94
	Swap memory total (MB): 7830,46
	Swap memory used (MB): 1068,03
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		atomic: dungeon master 1.0.0
		baritone: Baritone 1.7.0
		clientcommands: Client Commands 2.5.3
		clientcommands-scripting: Clientcommands Scripting 1.1.1
		com_github_hube12_seed: SEED master-SNAPSHOT
		fabric: Fabric API 0.38.2+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+2f75c6ce18
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.12+3fe74aa118
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.4+2e8bd82f18
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+2e8bd82f18
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.7.0+2e8bd82f18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.0+3fe74aa118
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.1.2+8195aec118
		fabricloader: Fabric Loader 0.11.7
		ferritecore: FerriteCore 3.0.1
		hydrogen: Hydrogen 0.3
		java: OpenJDK 64-Bit Server VM 16
		lithium: Lithium 0.7.3-SNAPSHOT
		meteor-client: Meteor Client 0.4.6-1265
		meteor-rejects: Meteor Rejects 0.0.4
		minecraft: Minecraft 1.17.1
		modmenu: Mod Menu 2.0.2
		multiconnect-api: MultiConnect API 1.4
		org_yaml_snakeyaml: snakeyaml 1.29
		reeses-sodium-options: Reese's Sodium Options 1.1.2
		shulkerdupe: Shulker dupe mod 1.0.0
		sodium: Sodium 0.3.0+build.5
		sodium-extra: Sodium Extra 0.3.3
		viafabric: ViaFabric 0.4.3+203-main
		viafabric-mc117: ViaFabric for 1.17 0.4.3+203-main
		viaversion: ViaVersion 4.0.1
		xaerominimap: Xaero's Minimap 21.12.5.1
		xaeroworldmap: Xaero's World Map 1.14.5.2
	Launched Version: fabric-loader-0.11.7-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GT 720M/PCIe/SSE2 GL version 3.2.0 NVIDIA 388.73, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz

-- Meteor Client --
Version: 0.4.6
Dev Build: 1265

[Combat]:
Auto Totem (auto-totem)

[Player]:
Portals (portals)

[Render]:
Better Tooltips (better-tooltips)
Block Selection (block-selection)
Break Indicators (break-indicators)
Esp (esp)
Fullbright (fullbright)
HUD (HUD)
Item Physics (item-physics)
Logout Spots (logout-spots)
Nametags (nametags)
No Render (no-render)
Storage Esp (storage-esp)
Tracers (tracers)
Trajectories (trajectories)

[World]:
Enderman Look (enderman-look)

[Misc]:
Auto Reconnect (auto-reconnect)
Better Chat (better-chat)
Better Tab (better-tab)
Vanilla Spoof (vanilla-spoof)

[Rejects]:
Skeleton Esp (skeleton-esp)

**Comment by ShadowMasterGo** [comment]
what all mods you used? try using sodium alone

**Comment by amnotbananaama** [comment]
1. This is a support issue, not something related to the issue tracker.
2. We do not provide support for hacked clients, especially when their usage is attempted to be concealed. 
3. Your issue is not caused by Sodium.
