### ISSUE TITLE
Game can't start

### ISSUE THREAD

**Issue by iHemoX3** [jellysquid3/Sodium#943]
### Version information

sodium-extra-mc1.17.1-0.3.5

### Reproduction Steps

Game doesn't launch and Fabric loader says this 
![image](https://user-images.githubusercontent.com/92804812/137936093-26a6f144-4758-4e48-848a-e584a455b1f4.png)
Here is my mod folder if I missed anything in the installation process: 
![image](https://user-images.githubusercontent.com/92804812/137937115-bafa5b05-6d99-4579-a833-2869c556532b.png)

### Crash Report file

[17:26:42] [main/INFO]: Loading for game Minecraft 1.17.1
[17:26:45] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: sodium-extra requires {fabric @ [*]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:198) ~[fabric-loader-0.11.7.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832) ~[fabric-loader-0.11.7.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195) ~[fabric-loader-0.11.7.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185) [fabric-loader-0.11.7.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132) [fabric-loader-0.11.7.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.7.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:195) ~[fabric-loader-0.11.7.jar:?]
	... 5 more

**Comment by iHemoX3** [comment]
Yes I realized optifabric conflicts with sodium, although i have removed right now, the problem still occurs, I will be playing without the sodium extra mod since that's what causing the issue, tho I'd like to get the extra frames from it, so please look into this

**Comment by jellysquid3** [comment]
This isn't an issue with our mod. Sodium Extra is telling you it needs [Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api), which you haven't installed. Fabric Loader is the mod loader (what you have installed), but the Fabric API (which some mods also need) isn't installed with Fabric Loader.
